#include "identity_fusion_replay.h"

#include "../../src/common/system_d3d11.h"
#include "../../src/d3d11/weapon_motion.h"
#include <windows.h>
#include <d3d11.h>
#include <d3d11shader.h>
#include <d3d11sdklayers.h>
#include <d3dcompiler.h>
#include <wrl/client.h>
#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

using Microsoft::WRL::ComPtr;

namespace identity_fusion_replay { namespace {

constexpr uint32_t kMaxFrames=4,kMaxShaders=5,kMaxGeometry=64,kMaxResources=16,kMaxDraws=64;
constexpr uint32_t kMaxVertices=131072,kMaxBlob=16*1024*1024,kMaxFile=256*1024*1024;
constexpr uint64_t kFamilies[kMaxShaders]={
    0x7B0DC42D383F694Cull,0x8B589D25B2A0ADDCull,0x114AF608F86D9ED8ull,
    0xAACFDCF2FB9AD809ull,0x174E8D76363BE337ull};

void require(bool value,const char* what){if(!value)throw std::runtime_error(what);}
void hr(HRESULT value,const char* what){if(FAILED(value)){char text[192]{};std::snprintf(text,sizeof(text),"%s (HRESULT %08X)",what,unsigned(value));throw std::runtime_error(text);}}

struct Cursor {
    const std::vector<unsigned char>& bytes;size_t at=0;
    uint32_t u32(){require(at+4<=bytes.size(),"truncated fixture u32");uint32_t v=0;std::memcpy(&v,bytes.data()+at,4);at+=4;return v;}
    uint64_t u64(){require(at+8<=bytes.size(),"truncated fixture u64");uint64_t v=0;std::memcpy(&v,bytes.data()+at,8);at+=8;return v;}
    std::vector<unsigned char> blob(uint32_t cap=kMaxBlob){const uint32_t n=u32();require(n<=cap&&at+n<=bytes.size(),"invalid fixture blob");std::vector<unsigned char> out(n);if(n)std::memcpy(out.data(),bytes.data()+at,n);at+=n;return out;}
    std::string text(){auto b=blob(63);require(!b.empty()&&std::find(b.begin(),b.end(),0)==b.end(),"invalid fixture semantic");return std::string(b.begin(),b.end());}
};

struct Layout {std::string semantic;uint32_t index=0,format=0,slot=0,offset=0,classification=0,step=0;};
struct Shader {
    uint64_t hash=0;std::vector<unsigned char> code;uint32_t cb1=0,cb2=0;
    ComPtr<ID3D11VertexShader> vs;ComPtr<ID3D11GeometryShader> capture;
};
struct Resource {uint32_t stride=0;std::vector<unsigned char> data;ComPtr<ID3D11Buffer> buffer;ComPtr<ID3D11ShaderResourceView> view;};
struct Geometry {
    uint32_t shader=0,count=0,stride=0;std::vector<Layout> layout;
    std::vector<unsigned char> vertices,indices;ComPtr<ID3D11Buffer> vb,ib;ComPtr<ID3D11InputLayout> input;
};
struct Draw {
    uint32_t geometry=0,pool=0,bones=0,original=0;std::array<unsigned char,8> instance{};
    std::vector<unsigned char> cb1,cb2;ComPtr<ID3D11Buffer> instanceBuffer,cb1Buffer,cb2Buffer;
};
struct Frame {uint32_t number=0;std::vector<Draw> draws;};
struct Fixture {uint32_t width=0,height=0;std::vector<Shader> shaders;std::vector<Resource> resources;std::vector<Geometry> geometry;std::vector<Frame> frames;};

std::vector<unsigned char> loadFile(const std::filesystem::path& path){
    std::ifstream in(path,std::ios::binary|std::ios::ate);require(bool(in),"open replay fixture");const auto end=in.tellg();require(end>=0&&uint64_t(end)<=kMaxFile,"replay fixture exceeds 256 MiB");std::vector<unsigned char> bytes(static_cast<size_t>(end));in.seekg(0);if(!bytes.empty())in.read(reinterpret_cast<char*>(bytes.data()),std::streamsize(bytes.size()));require(bool(in)||bytes.empty(),"read replay fixture");return bytes;
}

Fixture parseBytes(const std::vector<unsigned char>& bytes){
    Cursor c{bytes};require(bytes.size()>=36&&!std::memcmp(bytes.data(),"EDVRIFR1",8),"not an EDVRIFR1 fixture");c.at=8;
    const uint32_t version=c.u32(),width=c.u32(),height=c.u32(),nf=c.u32(),ns=c.u32(),ng=c.u32(),nr=c.u32();
    require(version==1&&width==5120&&height==2880,"unsupported replay fixture version or dimensions");require(nf==2&&ns&&ns<=kMaxShaders&&ng&&ng<=kMaxGeometry&&nr&&nr<=kMaxResources,"invalid replay fixture table counts");
    Fixture f;f.width=width;f.height=height;f.shaders.resize(ns);f.geometry.resize(ng);f.resources.resize(nr);f.frames.resize(nf);
    for(auto& s:f.shaders){s.hash=c.u64();s.code=c.blob(65536);require(!s.code.empty(),"empty replay vertex shader");}
    for(auto& r:f.resources){r.stride=c.u32();require(r.stride==336||r.stride==48,"invalid replay structured-resource stride");r.data=c.blob();require(!r.data.empty()&&r.data.size()%r.stride==0,"invalid replay structured-resource data");}
    for(auto& g:f.geometry){g.shader=c.u32();g.count=c.u32();g.stride=c.u32();const uint32_t nl=c.u32();require(g.shader<ns&&g.count&&g.count%3==0&&g.count<=kMaxVertices&&g.stride&&g.stride<=256&&nl&&nl<=32,"invalid replay geometry header");g.layout.resize(nl);for(auto& e:g.layout){e.semantic=c.text();e.index=c.u32();e.format=c.u32();e.slot=c.u32();e.offset=c.u32();e.classification=c.u32();e.step=c.u32();require(e.slot<2&&e.classification<=1,"invalid replay input element");}g.vertices=c.blob();g.indices=c.blob();require(!g.vertices.empty()&&g.vertices.size()%g.stride==0&&g.indices.size()==uint64_t(g.count)*4,"invalid replay geometry payload");for(uint32_t i=0;i<g.count;++i){uint32_t index=0;std::memcpy(&index,g.indices.data()+size_t(i)*4,4);require(uint64_t(index)*g.stride<g.vertices.size(),"rebased replay index outside vertex payload");}}
    for(auto& frame:f.frames){frame.number=c.u32();const uint32_t nd=c.u32();require(nd&&nd<=kMaxDraws,"invalid replay frame draw count");frame.draws.resize(nd);for(auto& d:frame.draws){d.geometry=c.u32();d.pool=c.u32();d.bones=c.u32();d.original=c.u32();require(d.geometry<ng&&d.pool<nr&&d.bones<nr&&f.resources[d.pool].stride==336&&f.resources[d.bones].stride==48,"invalid replay draw reference");require(c.at+d.instance.size()<=bytes.size(),"truncated replay instance");std::memcpy(d.instance.data(),bytes.data()+c.at,d.instance.size());c.at+=d.instance.size();d.cb1=c.blob(65536);d.cb2=c.blob(65536);require(!d.cb1.empty()&&!d.cb2.empty()&&d.cb1.size()%16==0&&d.cb2.size()%16==0,"invalid replay constant buffers");}}
    require(c.at==bytes.size(),"trailing replay fixture data");require(f.frames[0].number+1==f.frames[1].number,"replay frames are not adjacent");
    for(const auto& frame:f.frames){uint64_t positionBytes=0;for(const auto& draw:frame.draws)positionBytes+=uint64_t(f.geometry[draw.geometry].count)*32;require(positionBytes<=32*1024*1024,"replay frame exceeds production position allocation bound");}
    std::array<bool,kMaxShaders> family{};for(const auto& s:f.shaders){const auto it=std::find(std::begin(kFamilies),std::end(kFamilies),s.hash);require(it!=std::end(kFamilies),"unexpected replay shader family");const size_t n=size_t(it-std::begin(kFamilies));require(!family[n],"duplicate replay shader family");family[n]=true;}
    return f;
}
Fixture parse(const std::filesystem::path& path){return parseBytes(loadFile(path));}

struct Device {
    ComPtr<ID3D11Device> dev;ComPtr<ID3D11DeviceContext> ctx;ComPtr<ID3D11InfoQueue> info;bool debug=false;
    explicit Device(bool wantDebug=true){auto create=edvr::systemD3D11CreateDevice();require(create!=nullptr,"System32 D3D11CreateDevice unavailable");D3D_FEATURE_LEVEL level{};HRESULT h=create(nullptr,D3D_DRIVER_TYPE_HARDWARE,nullptr,wantDebug?D3D11_CREATE_DEVICE_DEBUG:0,nullptr,0,D3D11_SDK_VERSION,&dev,&level,&ctx);if(h==DXGI_ERROR_SDK_COMPONENT_MISSING&&wantDebug)h=create(nullptr,D3D_DRIVER_TYPE_HARDWARE,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&dev,&level,&ctx);hr(h,"create replay hardware device");debug=wantDebug&&SUCCEEDED(dev.As(&info));}
};

ComPtr<ID3DBlob> compile(const char* source,const char* profile){ComPtr<ID3DBlob> code,errors;const HRESULT h=D3DCompile(source,std::strlen(source),"identity_fusion_replay",nullptr,nullptr,"main",profile,D3DCOMPILE_ENABLE_STRICTNESS|D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&code,&errors);if(FAILED(h)&&errors)std::fwrite(errors->GetBufferPointer(),1,errors->GetBufferSize(),stderr);hr(h,"compile replay shader");return code;}
ComPtr<ID3D11Buffer> buffer(ID3D11Device* dev,const void* data,uint32_t bytes,uint32_t bind,uint32_t stride=0){require(bytes>0,"zero-size replay buffer");D3D11_BUFFER_DESC d{};d.ByteWidth=bytes;d.BindFlags=bind;d.StructureByteStride=stride;d.MiscFlags=stride?D3D11_RESOURCE_MISC_BUFFER_STRUCTURED:0;D3D11_SUBRESOURCE_DATA initial{};initial.pSysMem=data;ComPtr<ID3D11Buffer> out;hr(dev->CreateBuffer(&d,data?&initial:nullptr,&out),"create replay buffer");return out;}
ComPtr<ID3D11ShaderResourceView> srv(ID3D11Device* dev,ID3D11Buffer* b,const D3D11_SHADER_RESOURCE_VIEW_DESC* desc=nullptr){ComPtr<ID3D11ShaderResourceView> out;hr(dev->CreateShaderResourceView(b,desc,&out),"create replay SRV");return out;}

const char* kFusionGs=R"HLSL(
Buffer<uint> Index:register(t0);struct Instance{uint4 row[21];};StructuredBuffer<Instance> Pool:register(t1);
struct V{float4 position:SV_Position;};struct P{float4 position:SV_Position;};struct I{uint4 identity:IDENTITY;};
[maxvertexcount(2)]void main(point V v[1],uint primitive:SV_PrimitiveID,inout PointStream<P> positions,inout PointStream<I> identities){P p;p.position=v[0].position;positions.Append(p);if(primitive==0){uint n,stride;Pool.GetDimensions(n,stride);uint id=Index[0];I i;i.identity=id<n?uint4(Pool[id].row[0].x,Pool[id].row[1].w,1,0):0;identities.Append(i);}}
)HLSL";

void reflect(Shader& shader){
    ComPtr<ID3D11ShaderReflection> r;hr(D3DReflect(shader.code.data(),shader.code.size(),IID_ID3D11ShaderReflection,&r),"reflect replay VS");D3D11_SHADER_DESC sd{};hr(r->GetDesc(&sd),"read replay VS reflection");bool position=false;
    for(UINT i=0;i<sd.InputParameters;++i){D3D11_SIGNATURE_PARAMETER_DESC p{};hr(r->GetInputParameterDesc(i,&p),"read replay VS input");require(p.SystemValueType!=D3D_NAME_VERTEX_ID&&p.SystemValueType!=D3D_NAME_INSTANCE_ID,"replay VS reads rebased vertex/instance system ID");}
    for(UINT i=0;i<sd.OutputParameters;++i){D3D11_SIGNATURE_PARAMETER_DESC p{};hr(r->GetOutputParameterDesc(i,&p),"read replay VS output");if(!_stricmp(p.SemanticName,"SV_POSITION")){require(!position&&p.Mask==15&&p.ComponentType==D3D_REGISTER_COMPONENT_FLOAT32,"invalid replay SV_POSITION output");position=true;}}
    require(position,"replay VS has no SV_POSITION output");
    // Elite's retained blobs are stripped (ISGN/OSGN/SHEX, no RDEF), so
    // reflection cannot enumerate resources. Validate the declaration tokens
    // in Microsoft's own disassembly instead of silently assuming bindings.
    ComPtr<ID3DBlob> assembly;hr(D3DDisassemble(shader.code.data(),shader.code.size(),0,nullptr,&assembly),"disassemble replay VS");const std::string text(static_cast<const char*>(assembly->GetBufferPointer()),assembly->GetBufferSize());std::istringstream lines(text);std::string line;unsigned cb1=0,cb2=0,t33=0,t38=0;
    while(std::getline(lines,line)){
        const auto cb=line.find("dcl_constantbuffer");if(cb!=std::string::npos){const auto name=line.find("CB",cb),open=line.find('[',name),close=line.find(']',open);require(name!=std::string::npos&&open!=std::string::npos&&close!=std::string::npos,"malformed replay constant-buffer declaration");const unsigned slot=unsigned(std::stoul(line.substr(name+2,open-name-2))),registers=unsigned(std::stoul(line.substr(open+1,close-open-1)));require(slot==1||slot==2,"replay VS declares unsupported constant buffer");unsigned& target=slot==1?cb1:cb2;require(!target&&registers,"duplicate/empty replay constant buffer");target=registers;continue;}
        const auto structured=line.find("dcl_resource_structured");if(structured!=std::string::npos){const auto name=line.find('t',structured+23),comma=line.find(',',name);require(name!=std::string::npos&&comma!=std::string::npos,"malformed replay structured-resource declaration");const unsigned slot=unsigned(std::stoul(line.substr(name+1,comma-name-1))),stride=unsigned(std::stoul(line.substr(comma+1)));require((slot==33&&stride==336)||(slot==38&&stride==48),"replay VS declares unsupported structured resource");unsigned& target=slot==33?t33:t38;require(!target,"duplicate replay structured resource");target=stride;continue;}
        require(line.find("dcl_resource")==std::string::npos&&line.find("dcl_sampler")==std::string::npos&&line.find("dcl_uav")==std::string::npos,"replay VS declares an uncaptured resource");
    }
    const unsigned expectedCb2=shader.hash==0xAACFDCF2FB9AD809ull?6u:(shader.hash==0x174E8D76363BE337ull?7u:10u);
    require(cb1==276&&cb2==expectedCb2&&t33==336&&t38==48,"replay VS declaration contract is incomplete");shader.cb1=cb1*16;shader.cb2=cb2*16;
}

void createGpu(Fixture& f,Device& d,ComPtr<ID3D11GeometryShader>& fused,ComPtr<ID3D11ComputeShader>& identify){
    auto gs=compile(kFusionGs,"gs_5_0"),cs=compile(edvr::kWeaponIdentityCs,"cs_5_0");D3D11_SO_DECLARATION_ENTRY fd[2]={{0,"SV_POSITION",0,0,4,0},{1,"IDENTITY",0,0,4,1}};UINT fs[2]={16,16};hr(d.dev->CreateGeometryShaderWithStreamOutput(gs->GetBufferPointer(),gs->GetBufferSize(),fd,2,fs,2,D3D11_SO_NO_RASTERIZED_STREAM,nullptr,&fused),"create replay fused GS");hr(d.dev->CreateComputeShader(cs->GetBufferPointer(),cs->GetBufferSize(),nullptr,&identify),"create replay identity CS");
    for(auto& s:f.shaders){reflect(s);hr(d.dev->CreateVertexShader(s.code.data(),s.code.size(),nullptr,&s.vs),"create captured VS");D3D11_SO_DECLARATION_ENTRY e{0,"SV_POSITION",0,0,4,0};UINT stride=16;hr(d.dev->CreateGeometryShaderWithStreamOutput(s.code.data(),s.code.size(),&e,1,&stride,1,D3D11_SO_NO_RASTERIZED_STREAM,nullptr,&s.capture),"create captured no-program SO shader");}
    for(auto& r:f.resources){r.buffer=buffer(d.dev.Get(),r.data.data(),uint32_t(r.data.size()),D3D11_BIND_SHADER_RESOURCE,r.stride);r.view=srv(d.dev.Get(),r.buffer.Get());}
    for(auto& g:f.geometry){g.vb=buffer(d.dev.Get(),g.vertices.data(),uint32_t(g.vertices.size()),D3D11_BIND_VERTEX_BUFFER);g.ib=buffer(d.dev.Get(),g.indices.data(),uint32_t(g.indices.size()),D3D11_BIND_INDEX_BUFFER);std::vector<D3D11_INPUT_ELEMENT_DESC> desc(g.layout.size());for(size_t i=0;i<g.layout.size();++i){const auto&e=g.layout[i];desc[i]={e.semantic.c_str(),e.index,DXGI_FORMAT(e.format),e.slot,e.offset,D3D11_INPUT_CLASSIFICATION(e.classification),e.step};}const auto&s=f.shaders[g.shader];hr(d.dev->CreateInputLayout(desc.data(),UINT(desc.size()),s.code.data(),s.code.size(),&g.input),"create captured input layout");}
    for(auto& frame:f.frames)for(auto& draw:frame.draws){const auto&s=f.shaders[f.geometry[draw.geometry].shader];require(draw.cb1.size()>=s.cb1&&draw.cb2.size()>=s.cb2,"captured constant buffer is smaller than reflected VS requirement");draw.instanceBuffer=buffer(d.dev.Get(),draw.instance.data(),uint32_t(draw.instance.size()),D3D11_BIND_VERTEX_BUFFER);draw.cb1Buffer=buffer(d.dev.Get(),draw.cb1.data(),uint32_t(draw.cb1.size()),D3D11_BIND_CONSTANT_BUFFER);draw.cb2Buffer=buffer(d.dev.Get(),draw.cb2.data(),uint32_t(draw.cb2.size()),D3D11_BIND_CONSTANT_BUFFER);}
}

std::vector<unsigned char> readback(Device& d,ID3D11Buffer* source,uint32_t bytes){D3D11_BUFFER_DESC bd{};source->GetDesc(&bd);bd.Usage=D3D11_USAGE_STAGING;bd.BindFlags=0;bd.CPUAccessFlags=D3D11_CPU_ACCESS_READ;bd.MiscFlags=0;bd.StructureByteStride=0;ComPtr<ID3D11Buffer> stage;hr(d.dev->CreateBuffer(&bd,nullptr,&stage),"create replay staging buffer");d.ctx->CopyResource(stage.Get(),source);D3D11_MAPPED_SUBRESOURCE map{};hr(d.ctx->Map(stage.Get(),0,D3D11_MAP_READ,0,&map),"map replay staging buffer");std::vector<unsigned char> out(bytes);std::memcpy(out.data(),map.pData,bytes);d.ctx->Unmap(stage.Get(),0);return out;}

struct Pair {ComPtr<ID3D11Buffer> baselinePosition,baselineIdentity,fusedPosition,fusedIdentity;ComPtr<ID3D11ShaderResourceView> baselinePositionView,baselineIdentityView,fusedPositionView,fusedIdentityView;ComPtr<ID3D11UnorderedAccessView> baselineUav;};
Pair outputs(Device& d,uint32_t count){Pair p;D3D11_SHADER_RESOURCE_VIEW_DESC position{};position.Format=DXGI_FORMAT_R32G32B32A32_FLOAT;position.ViewDimension=D3D11_SRV_DIMENSION_BUFFER;position.Buffer.NumElements=count;p.baselinePosition=buffer(d.dev.Get(),nullptr,count*16,D3D11_BIND_STREAM_OUTPUT|D3D11_BIND_SHADER_RESOURCE);p.baselinePositionView=srv(d.dev.Get(),p.baselinePosition.Get(),&position);p.fusedPosition=buffer(d.dev.Get(),nullptr,count*16,D3D11_BIND_STREAM_OUTPUT|D3D11_BIND_SHADER_RESOURCE);p.fusedPositionView=srv(d.dev.Get(),p.fusedPosition.Get(),&position);p.baselineIdentity=buffer(d.dev.Get(),nullptr,16,D3D11_BIND_UNORDERED_ACCESS|D3D11_BIND_SHADER_RESOURCE,16);hr(d.dev->CreateUnorderedAccessView(p.baselineIdentity.Get(),nullptr,&p.baselineUav),"create replay identity UAV");p.baselineIdentityView=srv(d.dev.Get(),p.baselineIdentity.Get());p.fusedIdentity=buffer(d.dev.Get(),nullptr,16,D3D11_BIND_STREAM_OUTPUT|D3D11_BIND_SHADER_RESOURCE);D3D11_SHADER_RESOURCE_VIEW_DESC identity{};identity.Format=DXGI_FORMAT_R32G32B32A32_UINT;identity.ViewDimension=D3D11_SRV_DIMENSION_BUFFER;identity.Buffer.NumElements=1;p.fusedIdentityView=srv(d.dev.Get(),p.fusedIdentity.Get(),&identity);return p;}

void bindDraw(Device& d,const Fixture& f,const Draw& draw){const auto&g=f.geometry[draw.geometry];const auto&s=f.shaders[g.shader];d.ctx->IASetInputLayout(g.input.Get());ID3D11Buffer* vb[2]={draw.instanceBuffer.Get(),g.vb.Get()};UINT strides[2]={8,g.stride},offsets[2]{};d.ctx->IASetVertexBuffers(0,2,vb,strides,offsets);d.ctx->IASetIndexBuffer(g.ib.Get(),DXGI_FORMAT_R32_UINT,0);d.ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_POINTLIST);d.ctx->VSSetShader(s.vs.Get(),nullptr,0);ID3D11Buffer* cb[2]={draw.cb1Buffer.Get(),draw.cb2Buffer.Get()};d.ctx->VSSetConstantBuffers(1,2,cb);ID3D11ShaderResourceView* pool=f.resources[draw.pool].view.Get();ID3D11ShaderResourceView* bones=f.resources[draw.bones].view.Get();d.ctx->VSSetShaderResources(33,1,&pool);d.ctx->VSSetShaderResources(38,1,&bones);}

void identifyBaseline(Device& d,ID3D11ComputeShader* shader,ID3D11Buffer* instance,ID3D11ShaderResourceView* pool,ID3D11UnorderedAccessView* output,ID3D11Buffer* index,ID3D11ShaderResourceView* indexView){D3D11_BOX box{0,0,0,4,1,1};d.ctx->CopySubresourceRegion(index,0,0,0,0,instance,0,&box);ID3D11ShaderResourceView* in[2]={indexView,pool};d.ctx->CSSetShaderResources(0,2,in);d.ctx->CSSetUnorderedAccessViews(0,1,&output,nullptr);d.ctx->CSSetShader(shader,nullptr,0);d.ctx->Dispatch(1,1,1);ID3D11ShaderResourceView* none[2]{};ID3D11UnorderedAccessView* noUav=nullptr;d.ctx->CSSetShaderResources(0,2,none);d.ctx->CSSetUnorderedAccessViews(0,1,&noUav,nullptr);d.ctx->CSSetShader(nullptr,nullptr,0);}

void captureBaseline(Device& d,const Fixture& f,const Draw& draw,ID3D11Buffer* position){bindDraw(d,f,draw);const auto&s=f.shaders[f.geometry[draw.geometry].shader];d.ctx->GSSetShader(s.capture.Get(),nullptr,0);UINT zero=0;d.ctx->SOSetTargets(1,&position,&zero);d.ctx->DrawIndexedInstanced(f.geometry[draw.geometry].count,1,0,0,0);d.ctx->SOSetTargets(0,nullptr,nullptr);d.ctx->GSSetShader(nullptr,nullptr,0);}
void captureFused(Device& d,const Fixture& f,const Draw& draw,ID3D11GeometryShader* shader,ID3D11Buffer* position,ID3D11Buffer* identity,ID3D11Buffer* index,ID3D11ShaderResourceView* indexView){bindDraw(d,f,draw);D3D11_BOX box{0,0,0,4,1,1};d.ctx->CopySubresourceRegion(index,0,0,0,0,draw.instanceBuffer.Get(),0,&box);ID3D11ShaderResourceView* in[2]={indexView,f.resources[draw.pool].view.Get()};d.ctx->GSSetShaderResources(0,2,in);d.ctx->GSSetShader(shader,nullptr,0);ID3D11Buffer* out[2]={position,identity};UINT zero[2]{};d.ctx->SOSetTargets(2,out,zero);d.ctx->DrawIndexedInstanced(f.geometry[draw.geometry].count,1,0,0,0);d.ctx->SOSetTargets(0,nullptr,nullptr);ID3D11ShaderResourceView* none[2]{};d.ctx->GSSetShaderResources(0,2,none);d.ctx->GSSetShader(nullptr,nullptr,0);}

void debugClean(Device& d){if(!d.info)return;for(UINT64 i=0;i<d.info->GetNumStoredMessagesAllowedByRetrievalFilter();++i){SIZE_T n=0;d.info->GetMessage(i,nullptr,&n);std::vector<unsigned char> bytes(n);auto*m=reinterpret_cast<D3D11_MESSAGE*>(bytes.data());hr(d.info->GetMessage(i,m,&n),"read replay debug message");if(m->Severity<=D3D11_MESSAGE_SEVERITY_WARNING){std::fprintf(stderr,"D3D replay: %s\n",m->pDescription);require(false,"replay debug layer warning/error");}}}

using Captures=std::vector<std::vector<Pair>>;
Captures sourceGate(Fixture& f,Device& d,ID3D11GeometryShader* fused,ID3D11ComputeShader* identify,bool verify){
    D3D11_BUFFER_DESC id{};id.ByteWidth=16;id.BindFlags=D3D11_BIND_SHADER_RESOURCE;auto index=buffer(d.dev.Get(),nullptr,16,D3D11_BIND_SHADER_RESOURCE);D3D11_SHADER_RESOURCE_VIEW_DESC view{};view.Format=DXGI_FORMAT_R32_UINT;view.ViewDimension=D3D11_SRV_DIMENSION_BUFFER;view.Buffer.NumElements=4;auto indexView=srv(d.dev.Get(),index.Get(),&view);
    Captures captured(f.frames.size());uint64_t draws=0,vertices=0;for(size_t fi=0;fi<f.frames.size();++fi){const auto& frame=f.frames[fi];captured[fi].reserve(frame.draws.size());for(const auto& draw:frame.draws){const auto&g=f.geometry[draw.geometry];auto out=outputs(d,g.count);identifyBaseline(d,identify,draw.instanceBuffer.Get(),f.resources[draw.pool].view.Get(),out.baselineUav.Get(),index.Get(),indexView.Get());captureBaseline(d,f,draw,out.baselinePosition.Get());captureFused(d,f,draw,fused,out.fusedPosition.Get(),out.fusedIdentity.Get(),index.Get(),indexView.Get());if(verify){const auto bp=readback(d,out.baselinePosition.Get(),g.count*16),fp=readback(d,out.fusedPosition.Get(),g.count*16),bi=readback(d,out.baselineIdentity.Get(),16),fiBytes=readback(d,out.fusedIdentity.Get(),16);require(bp==fp,"captured VS positions differ between no-program SO and fused GS");require(bi==fiBytes,"captured identity differs between compute and fused GS");}captured[fi].push_back(std::move(out));++draws;vertices+=g.count;}}
    if(verify){debugClean(d);std::printf("replay source gate: frames=%zu draws=%llu indices=%llu exact_positions=yes exact_identity=yes families=%zu debug=%s\n",f.frames.size(),(unsigned long long)draws,(unsigned long long)vertices,f.shaders.size(),d.debug?"clean":"unavailable");}return captured;
}

std::string typedMotionSource(){std::string source=edvr::kWeaponMotionVs;const std::string from="StructuredBuffer<uint4>",to="Buffer<uint4>";size_t at=0;unsigned changed=0;while((at=source.find(from,at))!=std::string::npos){source.replace(at,from.size(),to);at+=to.size();++changed;}require(changed==5,"production motion shader identity declarations changed");return source;}

struct Raster {
    Device& d;uint32_t width=0,height=0;ComPtr<ID3D11Texture2D> depth,map;ComPtr<ID3D11DepthStencilView> dsv;ComPtr<ID3D11RenderTargetView> rtv;ComPtr<ID3D11DepthStencilState> writeDepth,readDepth;ComPtr<ID3D11RasterizerState> raster;ComPtr<ID3D11BlendState> blend;ComPtr<ID3D11VertexShader> structuredVs,typedVs;ComPtr<ID3D11PixelShader> ps;ComPtr<ID3D11Buffer> settings,sequential,index;ComPtr<ID3D11ShaderResourceView> indexView;
    Raster(Device& device,uint32_t w,uint32_t h):d(device),width(w),height(h){
        D3D11_TEXTURE2D_DESC td{};td.Width=w;td.Height=h;td.MipLevels=td.ArraySize=td.SampleDesc.Count=1;td.Format=DXGI_FORMAT_R32G8X24_TYPELESS;td.BindFlags=D3D11_BIND_DEPTH_STENCIL;hr(d.dev->CreateTexture2D(&td,nullptr,&depth),"create replay depth");D3D11_DEPTH_STENCIL_VIEW_DESC dv{};dv.Format=DXGI_FORMAT_D32_FLOAT_S8X24_UINT;dv.ViewDimension=D3D11_DSV_DIMENSION_TEXTURE2D;hr(d.dev->CreateDepthStencilView(depth.Get(),&dv,&dsv),"create replay DSV");td.Format=DXGI_FORMAT_R16G16B16A16_FLOAT;td.BindFlags=D3D11_BIND_RENDER_TARGET;hr(d.dev->CreateTexture2D(&td,nullptr,&map),"create replay motion map");hr(d.dev->CreateRenderTargetView(map.Get(),nullptr,&rtv),"create replay motion RTV");
        D3D11_DEPTH_STENCIL_DESC write{};write.DepthEnable=TRUE;write.DepthWriteMask=D3D11_DEPTH_WRITE_MASK_ALL;write.DepthFunc=D3D11_COMPARISON_GREATER_EQUAL;write.StencilEnable=TRUE;write.StencilWriteMask=255;write.FrontFace.StencilFunc=D3D11_COMPARISON_ALWAYS;write.FrontFace.StencilPassOp=D3D11_STENCIL_OP_REPLACE;write.FrontFace.StencilFailOp=write.FrontFace.StencilDepthFailOp=D3D11_STENCIL_OP_KEEP;write.BackFace=write.FrontFace;hr(d.dev->CreateDepthStencilState(&write,&writeDepth),"create replay depth-write state");D3D11_DEPTH_STENCIL_DESC read{};read.DepthEnable=TRUE;read.DepthWriteMask=D3D11_DEPTH_WRITE_MASK_ZERO;read.DepthFunc=D3D11_COMPARISON_EQUAL;read.StencilEnable=TRUE;read.StencilReadMask=16;read.FrontFace.StencilFunc=D3D11_COMPARISON_EQUAL;read.FrontFace.StencilPassOp=read.FrontFace.StencilFailOp=read.FrontFace.StencilDepthFailOp=D3D11_STENCIL_OP_KEEP;read.BackFace=read.FrontFace;hr(d.dev->CreateDepthStencilState(&read,&readDepth),"create replay depth-read state");
        D3D11_RASTERIZER_DESC rs{};rs.FillMode=D3D11_FILL_SOLID;rs.CullMode=D3D11_CULL_NONE;rs.DepthClipEnable=TRUE;hr(d.dev->CreateRasterizerState(&rs,&raster),"create replay rasterizer");D3D11_BLEND_DESC bd{};bd.RenderTarget[0].RenderTargetWriteMask=15;hr(d.dev->CreateBlendState(&bd,&blend),"create replay blend state");
        auto structured=compile(edvr::kWeaponMotionVs,"vs_5_0");const auto typedText=typedMotionSource();auto typed=compile(typedText.c_str(),"vs_5_0"),pixel=compile(edvr::kWeaponMotionPs,"ps_5_0");hr(d.dev->CreateVertexShader(structured->GetBufferPointer(),structured->GetBufferSize(),nullptr,&structuredVs),"create production structured motion VS");hr(d.dev->CreateVertexShader(typed->GetBufferPointer(),typed->GetBufferSize(),nullptr,&typedVs),"create typed motion VS");hr(d.dev->CreatePixelShader(pixel->GetBufferPointer(),pixel->GetBufferSize(),nullptr,&ps),"create production motion PS");
        settings=buffer(d.dev.Get(),nullptr,16,D3D11_BIND_CONSTANT_BUFFER);std::vector<uint32_t> ids(kMaxVertices);for(uint32_t i=0;i<kMaxVertices;++i)ids[i]=i;sequential=buffer(d.dev.Get(),ids.data(),uint32_t(ids.size()*4),D3D11_BIND_INDEX_BUFFER);index=buffer(d.dev.Get(),nullptr,16,D3D11_BIND_SHADER_RESOURCE);D3D11_SHADER_RESOURCE_VIEW_DESC iv{};iv.Format=DXGI_FORMAT_R32_UINT;iv.ViewDimension=D3D11_SRV_DIMENSION_BUFFER;iv.Buffer.NumElements=4;indexView=srv(d.dev.Get(),index.Get(),&iv);
    }
    void clear(){float zero[4]{};d.ctx->ClearRenderTargetView(rtv.Get(),zero);d.ctx->ClearDepthStencilView(dsv.Get(),D3D11_CLEAR_DEPTH|D3D11_CLEAR_STENCIL,0,0);D3D11_VIEWPORT vp{0,0,float(width),float(height),0,1};d.ctx->RSSetViewports(1,&vp);d.ctx->RSSetState(raster.Get());}
};

enum class ReplayPath {Baseline,Fused};

void depthDraw(Raster& r,const Fixture& f,const Draw& draw){bindDraw(r.d,f,draw);r.d.ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);r.d.ctx->GSSetShader(nullptr,nullptr,0);r.d.ctx->PSSetShader(nullptr,nullptr,0);r.d.ctx->OMSetRenderTargets(0,nullptr,r.dsv.Get());r.d.ctx->OMSetDepthStencilState(r.writeDepth.Get(),16);r.d.ctx->DrawIndexedInstanced(f.geometry[draw.geometry].count,1,0,0,0);}

std::vector<size_t> candidates(const Fixture& f,const Draw& draw){std::vector<size_t> out;for(size_t i=0;i<f.frames[0].draws.size();++i)if(f.frames[0].draws[i].geometry==draw.geometry){require(out.size()<4,"replay geometry has more than four prior occurrences");out.push_back(i);}return out;}

void motionDraw(Raster& r,const Fixture& f,const Captures& captured,size_t current,ReplayPath path){const auto&draw=f.frames[1].draws[current];const auto&g=f.geometry[draw.geometry];const auto old=candidates(f,draw);const auto&now=captured[1][current];ID3D11ShaderResourceView* views[10]{};views[0]=path==ReplayPath::Baseline?now.baselinePositionView.Get():now.fusedPositionView.Get();views[5]=path==ReplayPath::Baseline?now.baselineIdentityView.Get():now.fusedIdentityView.Get();for(size_t i=0;i<old.size();++i){const auto&p=captured[0][old[i]];views[1+i]=path==ReplayPath::Baseline?p.baselinePositionView.Get():p.fusedPositionView.Get();views[6+i]=path==ReplayPath::Baseline?p.baselineIdentityView.Get():p.fusedIdentityView.Get();}float settings[4]={float(r.width),float(r.height),float(old.size()),0};r.d.ctx->UpdateSubresource(r.settings.Get(),0,nullptr,settings,0,0);r.d.ctx->OMSetRenderTargets(1,r.rtv.GetAddressOf(),r.dsv.Get());r.d.ctx->OMSetDepthStencilState(r.readDepth.Get(),16);r.d.ctx->OMSetBlendState(r.blend.Get(),nullptr,~0u);r.d.ctx->VSSetShader(path==ReplayPath::Baseline?r.structuredVs.Get():r.typedVs.Get(),nullptr,0);r.d.ctx->VSSetShaderResources(0,10,views);r.d.ctx->VSSetConstantBuffers(0,1,r.settings.GetAddressOf());r.d.ctx->PSSetShader(r.ps.Get(),nullptr,0);r.d.ctx->PSSetConstantBuffers(0,1,r.settings.GetAddressOf());r.d.ctx->IASetInputLayout(nullptr);ID3D11Buffer* none[2]{};UINT strides[2]{},offsets[2]{};r.d.ctx->IASetVertexBuffers(0,2,none,strides,offsets);r.d.ctx->IASetIndexBuffer(r.sequential.Get(),DXGI_FORMAT_R32_UINT,0);r.d.ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);r.d.ctx->DrawIndexed(g.count,0,0);ID3D11ShaderResourceView* noViews[10]{};r.d.ctx->VSSetShaderResources(0,10,noViews);}

void produceCurrent(Raster& r,Fixture& f,Captures& captured,size_t current,ReplayPath path,ID3D11GeometryShader* fused,ID3D11ComputeShader* identify){auto&draw=f.frames[1].draws[current];auto&out=captured[1][current];if(path==ReplayPath::Baseline){identifyBaseline(r.d,identify,draw.instanceBuffer.Get(),f.resources[draw.pool].view.Get(),out.baselineUav.Get(),r.index.Get(),r.indexView.Get());captureBaseline(r.d,f,draw,out.baselinePosition.Get());}else captureFused(r.d,f,draw,fused,out.fusedPosition.Get(),out.fusedIdentity.Get(),r.index.Get(),r.indexView.Get());}

void rasterBatch(Raster& r,Fixture& f,Captures& captured,ReplayPath path,ID3D11GeometryShader* fused,ID3D11ComputeShader* identify){r.clear();for(size_t i=0;i<f.frames[1].draws.size();++i){depthDraw(r,f,f.frames[1].draws[i]);produceCurrent(r,f,captured,i,path,fused,identify);motionDraw(r,f,captured,i,path);}}

std::vector<unsigned char> readTexture(Raster& r){D3D11_TEXTURE2D_DESC td{};r.map->GetDesc(&td);td.Usage=D3D11_USAGE_STAGING;td.BindFlags=0;td.CPUAccessFlags=D3D11_CPU_ACCESS_READ;ComPtr<ID3D11Texture2D> stage;hr(r.d.dev->CreateTexture2D(&td,nullptr,&stage),"create replay map staging");r.d.ctx->CopyResource(stage.Get(),r.map.Get());D3D11_MAPPED_SUBRESOURCE map{};hr(r.d.ctx->Map(stage.Get(),0,D3D11_MAP_READ,0,&map),"map replay motion texture");const size_t row=size_t(r.width)*8;std::vector<unsigned char> out(row*r.height);for(uint32_t y=0;y<r.height;++y)std::memcpy(out.data()+size_t(y)*row,static_cast<const unsigned char*>(map.pData)+size_t(y)*map.RowPitch,row);r.d.ctx->Unmap(stage.Get(),0);return out;}

void rasterGate(Fixture& f,Device& d,Captures& captured,ID3D11GeometryShader* fused,ID3D11ComputeShader* identify){Raster r(d,f.width,f.height);rasterBatch(r,f,captured,ReplayPath::Baseline,fused,identify);auto baseline=readTexture(r);rasterBatch(r,f,captured,ReplayPath::Fused,fused,identify);auto typed=readTexture(r);require(baseline==typed,"full replay motion maps differ between baseline and typed fusion");uint64_t valid=0,rejected=0;for(size_t i=6;i<baseline.size();i+=8){uint16_t flag=0;std::memcpy(&flag,baseline.data()+i,2);valid+=flag==0x3c00;rejected+=flag==0x4000;}require(valid>0,"replay motion map has no valid correspondence pixels");debugClean(d);std::printf("replay raster gate: dimensions=%ux%u selected_mesh_depth=yes maps_exact=yes valid_pixels=%llu rejected_pixels=%llu\n",f.width,f.height,(unsigned long long)valid,(unsigned long long)rejected);}

ComPtr<ID3D11Query> query(ID3D11Device* dev,D3D11_QUERY type){D3D11_QUERY_DESC q{type,0};ComPtr<ID3D11Query> out;hr(dev->CreateQuery(&q,&out),"create replay timing query");return out;}
bool waitData(ID3D11DeviceContext* ctx,ID3D11Asynchronous* query,void* data,UINT size){const ULONGLONG until=GetTickCount64()+5000;ctx->Flush();HRESULT h=S_FALSE;while((h=ctx->GetData(query,data,size,D3D11_ASYNC_GETDATA_DONOTFLUSH))==S_FALSE&&GetTickCount64()<until)Sleep(0);return h==S_OK;}
struct Sample {unsigned round=0,order=0;ReplayPath path=ReplayPath::Baseline;double cpuMs=0,gpuMs=0;uint64_t ticks=0,frequency=0;bool ready=false,disjoint=false,valid=false;};
const char* pathName(ReplayPath path){return path==ReplayPath::Baseline?"baseline":"fused_typed_direct";}
Sample measure(Raster& r,Fixture& f,Captures& captured,ReplayPath path,ID3D11GeometryShader* fused,ID3D11ComputeShader* identify,unsigned round,unsigned order){auto dis=query(r.d.dev.Get(),D3D11_QUERY_TIMESTAMP_DISJOINT),firstQuery=query(r.d.dev.Get(),D3D11_QUERY_TIMESTAMP),lastQuery=query(r.d.dev.Get(),D3D11_QUERY_TIMESTAMP);D3D11_QUERY_DATA_TIMESTAMP_DISJOINT dj{};uint64_t first=0,last=0;LARGE_INTEGER qpf{},begin{},end{};QueryPerformanceFrequency(&qpf);r.d.ctx->Begin(dis.Get());r.d.ctx->End(firstQuery.Get());QueryPerformanceCounter(&begin);rasterBatch(r,f,captured,path,fused,identify);QueryPerformanceCounter(&end);r.d.ctx->End(lastQuery.Get());r.d.ctx->End(dis.Get());Sample s;s.round=round;s.order=order;s.path=path;s.cpuMs=double(end.QuadPart-begin.QuadPart)*1000.0/double(qpf.QuadPart);const bool rd=waitData(r.d.ctx.Get(),dis.Get(),&dj,sizeof(dj)),rf=waitData(r.d.ctx.Get(),firstQuery.Get(),&first,sizeof(first)),rl=waitData(r.d.ctx.Get(),lastQuery.Get(),&last,sizeof(last));s.ready=rd&&rf&&rl;s.disjoint=s.ready&&dj.Disjoint!=FALSE;s.frequency=s.ready?dj.Frequency:0;s.ticks=s.ready&&last>=first?last-first:0;s.valid=s.ready&&!s.disjoint&&s.frequency&&last>first;if(s.valid)s.gpuMs=double(s.ticks)*1000.0/double(s.frequency);return s;}
double median(std::vector<double> values){std::sort(values.begin(),values.end());return values.empty()?0.0:values[values.size()/2];}
std::string adapterName(ID3D11Device* dev){ComPtr<IDXGIDevice> dxgi;ComPtr<IDXGIAdapter> adapter;DXGI_ADAPTER_DESC desc{};if(FAILED(dev->QueryInterface(IID_PPV_ARGS(&dxgi)))||FAILED(dxgi->GetAdapter(&adapter))||FAILED(adapter->GetDesc(&desc)))return "unknown";char out[512]{};WideCharToMultiByte(CP_UTF8,0,desc.Description,-1,out,UINT(sizeof(out)),nullptr,nullptr);return out;}
std::string jsonEscape(const std::string& text){std::string out;for(char c:text){if(c=='"'||c=='\\')out.push_back('\\');if(static_cast<unsigned char>(c)>=0x20)out.push_back(c);}return out;}

void writeBenchmark(const std::filesystem::path& directory,const std::filesystem::path& fixture,const Fixture& f,const std::string& adapter,const std::vector<Sample>& samples,unsigned warmupBatches,double warmupWallMs,double warmupGpuMs){std::filesystem::create_directories(directory);std::vector<double> baseline,typed;unsigned unhealthy=0;for(const auto&s:samples)if(!s.valid)++unhealthy;else (s.path==ReplayPath::Baseline?baseline:typed).push_back(s.gpuMs);uint64_t indices=0;for(const auto&d:f.frames[1].draws)indices+=f.geometry[d.geometry].count;const auto json=directory/L"identity_fusion_replay_benchmark.json",csv=directory/L"identity_fusion_replay_benchmark.csv";std::ofstream j(json,std::ios::binary),c(csv,std::ios::binary);require(bool(j)&&bool(c),"open replay benchmark artifacts");j<<"{\n  \"schema\": 1,\n  \"scope\": {\"driver\":\"hardware\",\"debug\":false,\"vertex_shader\":\"captured original DXBC\",\"depth\":\"selected-mesh reconstructed per draw\",\"consumer\":\"immediate production motion raster; typed variant changes only identity Buffer declarations\",\"clears_inside_timing\":true,\"full_game_claim\":false},\n  \"fixture\": \""<<jsonEscape(fixture.string())<<"\",\n  \"adapter\": \""<<jsonEscape(adapter)<<"\",\n  \"width\": "<<f.width<<",\n  \"height\": "<<f.height<<",\n  \"frame_before\": "<<f.frames[0].number<<",\n  \"frame_now\": "<<f.frames[1].number<<",\n  \"draws\": "<<f.frames[1].draws.size()<<",\n  \"indices\": "<<indices<<",\n  \"families\": "<<f.shaders.size()<<",\n  \"warmup_batches\": "<<warmupBatches<<",\n  \"warmup_wall_ms\": "<<warmupWallMs<<",\n  \"warmup_gpu_ms\": "<<warmupGpuMs<<",\n  \"baseline_gpu_median_ms\": "<<median(baseline)<<",\n  \"fused_typed_direct_gpu_median_ms\": "<<median(typed)<<",\n  \"unhealthy_samples\": "<<unhealthy<<",\n  \"samples\": [\n";for(size_t i=0;i<samples.size();++i){const auto&s=samples[i];j<<"    {\"round\":"<<s.round<<",\"order\":"<<s.order<<",\"path\":\""<<pathName(s.path)<<"\",\"cpu_ms\":"<<s.cpuMs<<",\"gpu_ms\":"<<s.gpuMs<<",\"ticks\":"<<s.ticks<<",\"frequency\":"<<s.frequency<<",\"disjoint\":"<<(s.disjoint?"true":"false")<<",\"ready\":"<<(s.ready?"true":"false")<<",\"valid\":"<<(s.valid?"true":"false")<<"}"<<(i+1==samples.size()?"\n":",\n");}j<<"  ]\n}\n";c<<"round,order,path,cpu_ms,gpu_ms,ticks,frequency,disjoint,ready,valid\n";for(const auto&s:samples)c<<s.round<<','<<s.order<<','<<pathName(s.path)<<','<<s.cpuMs<<','<<s.gpuMs<<','<<s.ticks<<','<<s.frequency<<','<<(s.disjoint?1:0)<<','<<(s.ready?1:0)<<','<<(s.valid?1:0)<<'\n';j.close();c.close();require(bool(j)&&bool(c),"write replay benchmark artifacts");}

void benchmarkReplay(const std::filesystem::path& fixturePath,const std::filesystem::path* output){auto f=parse(fixturePath);Device d(false);ComPtr<ID3D11GeometryShader> fused;ComPtr<ID3D11ComputeShader> identify;createGpu(f,d,fused,identify);auto captured=sourceGate(f,d,fused.Get(),identify.Get(),false);Raster r(d,f.width,f.height);constexpr unsigned rounds=15,maxWarmup=10000;LARGE_INTEGER qpf{},start{},now{};QueryPerformanceFrequency(&qpf);QueryPerformanceCounter(&start);unsigned warmupBatches=0;double warmupWallMs=0,warmupGpuMs=0;do{const auto sample=measure(r,f,captured,(warmupBatches&1)?ReplayPath::Fused:ReplayPath::Baseline,fused.Get(),identify.Get(),0,warmupBatches&1);if(sample.valid)warmupGpuMs+=sample.gpuMs;++warmupBatches;QueryPerformanceCounter(&now);warmupWallMs=double(now.QuadPart-start.QuadPart)*1000.0/double(qpf.QuadPart);}while((warmupGpuMs<250.0||warmupWallMs<250.0)&&warmupBatches<maxWarmup);require(warmupGpuMs>=250.0&&warmupWallMs>=250.0,"replay benchmark warmup failed");std::vector<Sample> samples;samples.reserve(rounds*2);for(unsigned round=0;round<rounds;++round)for(unsigned order=0;order<2;++order)samples.push_back(measure(r,f,captured,((round+order)&1)?ReplayPath::Fused:ReplayPath::Baseline,fused.Get(),identify.Get(),round,order));std::vector<double> baseline,typed;unsigned unhealthy=0;for(const auto&s:samples)if(!s.valid)++unhealthy;else (s.path==ReplayPath::Baseline?baseline:typed).push_back(s.gpuMs);require(!unhealthy,"unhealthy replay timestamp/disjoint sample");uint64_t indices=0;for(const auto&draw:f.frames[1].draws)indices+=f.geometry[draw.geometry].count;const auto adapter=adapterName(d.dev.Get());std::printf("replay benchmark: adapter=%s dimensions=%ux%u draws=%zu indices=%llu families=%zu warmup_batches=%u warmup_wall_ms=%.3f warmup_gpu_ms=%.3f unhealthy=%u\n",adapter.c_str(),f.width,f.height,f.frames[1].draws.size(),(unsigned long long)indices,f.shaders.size(),warmupBatches,warmupWallMs,warmupGpuMs,unhealthy);std::printf("replay GPU median selected-depth+producer+immediate-raster: baseline %.6f ms, fused_typed_direct %.6f ms (descriptive only; no pass/fail threshold)\n",median(baseline),median(typed));if(output)writeBenchmark(*output,fixturePath,f,adapter,samples,warmupBatches,warmupWallMs,warmupGpuMs);}

void put32(std::vector<unsigned char>& out,uint32_t value){const auto at=out.size();out.resize(at+4);std::memcpy(out.data()+at,&value,4);}
void put64(std::vector<unsigned char>& out,uint64_t value){const auto at=out.size();out.resize(at+8);std::memcpy(out.data()+at,&value,8);}
void putBlob(std::vector<unsigned char>& out,const std::vector<unsigned char>& value){put32(out,uint32_t(value.size()));out.insert(out.end(),value.begin(),value.end());}
std::vector<unsigned char> parserFixture(bool badIndex=false){std::vector<unsigned char> out{'E','D','V','R','I','F','R','1'};for(uint32_t v:{1u,5120u,2880u,2u,1u,1u,2u})put32(out,v);put64(out,kFamilies[0]);putBlob(out,{1});put32(out,336);putBlob(out,std::vector<unsigned char>(336));put32(out,48);putBlob(out,std::vector<unsigned char>(48));put32(out,0);put32(out,3);put32(out,4);put32(out,1);putBlob(out,{'P','O','S','I','T','I','O','N'});for(uint32_t v:{0u,uint32_t(DXGI_FORMAT_R32_FLOAT),1u,0u,uint32_t(D3D11_INPUT_PER_VERTEX_DATA),0u})put32(out,v);putBlob(out,std::vector<unsigned char>(12));std::vector<unsigned char> indices(12);const uint32_t ids[3]={0,1,badIndex?3u:2u};std::memcpy(indices.data(),ids,sizeof(ids));putBlob(out,indices);for(uint32_t frame:{10u,11u}){put32(out,frame);put32(out,1);for(uint32_t v:{0u,0u,1u,7u})put32(out,v);out.insert(out.end(),8,0);putBlob(out,std::vector<unsigned char>(16));putBlob(out,std::vector<unsigned char>(16));}return out;}
bool rejected(const std::vector<unsigned char>& bytes){try{(void)parseBytes(bytes);return false;}catch(const std::exception&){return true;}}

} // namespace

bool run(const std::filesystem::path& fixture,bool benchmark,const std::filesystem::path* output){
    try{require(benchmark||output==nullptr,"replay output requires benchmark mode");auto f=parse(fixture);Device d;ComPtr<ID3D11GeometryShader> fused;ComPtr<ID3D11ComputeShader> identify;createGpu(f,d,fused,identify);if(d.info)d.info->ClearStoredMessages();auto captured=sourceGate(f,d,fused.Get(),identify.Get(),true);rasterGate(f,d,captured,fused.Get(),identify.Get());if(benchmark)benchmarkReplay(fixture,output);return true;}catch(const std::exception& e){std::fprintf(stderr,"identity fusion replay: %s\n",e.what());return false;}
}

bool selfTest(){try{const auto good=parserFixture();const auto parsed=parseBytes(good);require(parsed.frames.size()==2&&parsed.geometry.size()==1&&parsed.frames[1].number==11,"replay parser self-test fixture changed");auto truncated=good;truncated.pop_back();require(rejected(truncated),"replay parser accepts truncation");auto trailing=good;trailing.push_back(0);require(rejected(trailing),"replay parser accepts trailing bytes");require(rejected(parserFixture(true)),"replay parser accepts out-of-range rebased index");auto tooManyFrames=good;const uint32_t five=5;std::memcpy(tooManyFrames.data()+20,&five,4);require(rejected(tooManyFrames),"replay parser accepts frame cap violation");auto badMagic=good;badMagic[0]='X';require(rejected(badMagic),"replay parser accepts bad magic");std::printf("identity fusion replay parser: 6 checks passed\n");return true;}catch(const std::exception&e){std::fprintf(stderr,"identity fusion replay self-test: %s\n",e.what());return false;}}

}
