// The HLSL of the native runtime's stereo renderer (d3d11_stereo.cpp): the captured-eye blit that hands the game's eye texture to the OpenXR swapchain
// (one full-screen triangle; the bounds, clamp and sRGB encode of the capture), and the skybox that draws the six captured cube faces across the eye.
//
// COMPILED BY THE BUILD, never in the runtime. tools/temporal_shader_build compiles each of the four entry points below (--stereo-output) into
// build\gen\openxr_stereo_shader_bytecode.h, and D3D11Stereo::initialize creates the shaders from those bytes. Until 2026-10-01 the runtime carried these two
// strings and called D3DCompile on the render thread of the first VR_Init, which made d3dcompiler_47.dll a load-time import of the runtime DLL. The text
// is the text that was compiled then, byte for byte (the build tool's self-test holds both to the FNV-1a64 hash of the original), and the compile
// parameters are the old call's: source names "EDVR captured blit" and "EDVR skybox", entries "vs" and "ps", profiles vs_5_0 and ps_5_0, no macros,
// D3DCOMPILE_ENABLE_STRICTNESS and no second flag word. A change to the text or to any of that changes the generated bytes; the key in the generated
// header covers the text, the variant table and the compiler DLL, so the header is rebuilt, and the rig tools\openxr_stereo_test compiles the text again
// at test time and compares the embedded bytes.
#pragma once

namespace edvr::openxr {

inline constexpr char kStereoBlitHlsl[] = R"(
cbuffer Constants : register(b0) { float4 bounds; float4 clampUV; float encodeSRGB; float3 pad; };
Texture2D sourceTexture : register(t0); SamplerState linearSampler : register(s0);
struct O { float4 position:SV_POSITION; float2 uv:TEXCOORD; };
O vs(uint id:SV_VertexID) { O o; float2 p=float2((id<<1)&2,id&2); o.position=float4(p*float2(2,-2)+float2(-1,1),0,1); o.uv=p; return o; }
float3 srgb(float3 c) { return lerp(12.92*c,1.055*pow(max(c,0),1.0/2.4)-0.055,step(0.0031308,c)); }
float4 ps(O v):SV_TARGET { float2 uv=clamp(bounds.xy+v.uv*(bounds.zw-bounds.xy),clampUV.xy,clampUV.zw); float4 c=sourceTexture.Sample(linearSampler,uv); return float4(encodeSRGB>0.5?srgb(c.rgb):c.rgb,c.a); }
)";
inline constexpr char kStereoSkyboxHlsl[] = R"(
cbuffer C:register(b0) {
  row_major float3x4 orient;
  float4 tangents; // left, right, up, down
  float encode; float3 pad;
};
Texture2D f0:register(t0); Texture2D f1:register(t1);
Texture2D f2:register(t2); Texture2D f3:register(t3);
Texture2D f4:register(t4); Texture2D f5:register(t5);
SamplerState s:register(s0);
struct O { float4 p:SV_POSITION; float2 uv:TEXCOORD; };
O vs(uint id:SV_VertexID) {
  O o; float2 q=float2((id<<1)&2,id&2);
  o.p=float4(q*float2(2,-2)+float2(-1,1),0,1); o.uv=q; return o;
}
float3 enc(float3 c) {
  return lerp(12.92*c,1.055*pow(max(c,0),1.0/2.4)-0.055,step(0.0031308,c));
}
float4 ps(O o):SV_TARGET {
  float3 q=float3(lerp(tangents.x,tangents.y,o.uv.x),lerp(tangents.z,tangents.w,o.uv.y),-1);
  float3 r=mul(orient,float4(q,0)); float3 a=abs(r); int k;
  if(a.x>a.y && a.x>a.z) k=r.x>0?3:2;
  else if(a.y>a.z) k=r.y>0?4:5;
  else k=r.z>0?1:0;
  // Front/back/left/right/top/bottom, top-left image coordinates.
  float2 uv;
  if(k==0) uv=float2(.5+.5*r.x/(-r.z),.5-.5*r.y/(-r.z));
  else if(k==1) uv=float2(.5-.5*r.x/r.z,.5-.5*r.y/r.z);
  else if(k==2) uv=float2(.5-.5*r.z/(-r.x),.5-.5*r.y/(-r.x));
  else if(k==3) uv=float2(.5+.5*r.z/r.x,.5-.5*r.y/r.x);
  else if(k==4) uv=float2(.5+.5*r.x/r.y,.5-.5*r.z/r.y);
  else uv=float2(.5+.5*r.x/(-r.y),.5+.5*r.z/(-r.y));
  // SRVs decode Gamma/Auto before filtering. Each face clamps at its edge;
  // this path does not promise seamless cubemap filtering.
  float4 c=k==0?f0.Sample(s,uv):k==1?f1.Sample(s,uv):k==2?f2.Sample(s,uv):
           k==3?f3.Sample(s,uv):k==4?f4.Sample(s,uv):f5.Sample(s,uv);
  return float4(encode>0.5?enc(c.rgb):c.rgb,c.a);
}
)";

}  // namespace edvr::openxr
