#include "../../src/d3d11/eye_tonemap_snapshot.h"
#include <d3d11.h>
#include <d3dcompiler.h>
#include <wrl/client.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
#include <windows.h>
using Microsoft::WRL::ComPtr;
static void hr(HRESULT x,const char* s){if(FAILED(x)){std::printf("FAIL %s 0x%08lx\n",s,(unsigned long)x);std::exit(1);}}
static void check(bool x,const char* s){if(!x){std::printf("FAIL %s\n",s);std::exit(1);}}
static void waitGpu(ID3D11Device* d,ID3D11DeviceContext* c){ComPtr<ID3D11Query> q;D3D11_QUERY_DESC qd{D3D11_QUERY_EVENT,0};hr(d->CreateQuery(&qd,&q),"query");c->End(q.Get());c->Flush();const ULONGLONG until=GetTickCount64()+10000;for(;;){BOOL done=FALSE;HRESULT x=c->GetData(q.Get(),&done,sizeof(done),D3D11_ASYNC_GETDATA_DONOTFLUSH);if(x==S_OK&&done)break;if(x!=S_FALSE||GetTickCount64()>until)hr(x==S_FALSE?DXGI_ERROR_WAS_STILL_DRAWING:x,"query data");Sleep(1);}}
static ComPtr<ID3D11ShaderResourceView> srv2(ID3D11Device* d,ID3D11Resource* r,DXGI_FORMAT f){D3D11_SHADER_RESOURCE_VIEW_DESC v{};v.Format=f;v.ViewDimension=D3D11_SRV_DIMENSION_TEXTURE2D;v.Texture2D.MipLevels=1;ComPtr<ID3D11ShaderResourceView>x;hr(d->CreateShaderResourceView(r,&v,&x),"srv2");return x;}
int wmain(int argc,wchar_t** argv){
 if(argc!=2){std::puts("fixture path required");return 2;}
 ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>c;hr(D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,nullptr,&c),"WARP");
 // Exposure: distinct scalar rows.
 D3D11_TEXTURE2D_DESC ed{};ed.Width=4;ed.Height=4;ed.MipLevels=ed.ArraySize=1;ed.Format=DXGI_FORMAT_R32_FLOAT;ed.SampleDesc.Count=1;ed.BindFlags=D3D11_BIND_SHADER_RESOURCE;std::vector<float> ev(16);for(unsigned i=0;i<16;++i)ev[i]=10.f+float(i);D3D11_SUBRESOURCE_DATA ei{ev.data(),16,sizeof(float)*16};ComPtr<ID3D11Texture2D> exposure;hr(d->CreateTexture2D(&ed,&ei,&exposure),"exposure");auto ex=srv2(d.Get(),exposure.Get(),DXGI_FORMAT_R32_FLOAT);
 // LUT: four RGBA8 slices with independently identifiable values.
 D3D11_TEXTURE3D_DESC ld{};ld.Width=4;ld.Height=4;ld.Depth=4;ld.MipLevels=1;ld.Format=DXGI_FORMAT_R8G8B8A8_UNORM;ld.BindFlags=D3D11_BIND_SHADER_RESOURCE;std::vector<unsigned char> lv(4*4*4*4);for(unsigned z=0;z<4;++z)for(unsigned y=0;y<4;++y)for(unsigned x=0;x<4;++x){auto p=&lv[((z*4+y)*4+x)*4];p[0]=(unsigned char)(0x10+z);p[1]=(unsigned char)(0x20+y);p[2]=(unsigned char)(0x30+x);p[3]=0xE0;}D3D11_SUBRESOURCE_DATA li{lv.data(),16,64};ComPtr<ID3D11Texture3D>lut;hr(d->CreateTexture3D(&ld,&li,&lut),"lut");D3D11_SHADER_RESOURCE_VIEW_DESC lvd{};lvd.Format=DXGI_FORMAT_R8G8B8A8_UNORM;lvd.ViewDimension=D3D11_SRV_DIMENSION_TEXTURE3D;lvd.Texture3D.MipLevels=1;ComPtr<ID3D11ShaderResourceView>ls;hr(d->CreateShaderResourceView(lut.Get(),&lvd,&ls),"lut srv");
 // HDR input and separate typeless output. Both exceed the crop so origin is (2,3).
 D3D11_TEXTURE2D_DESC hd{};hd.Width=1404;hd.Height=1406;hd.MipLevels=hd.ArraySize=1;hd.Format=DXGI_FORMAT_R8G8B8A8_UNORM;hd.SampleDesc.Count=1;hd.BindFlags=D3D11_BIND_SHADER_RESOURCE;std::vector<unsigned char> hv(size_t(hd.Width)*hd.Height*4,0x41);D3D11_SUBRESOURCE_DATA hi{hv.data(),hd.Width*4,hd.Width*hd.Height*4};ComPtr<ID3D11Texture2D>hdr;hr(d->CreateTexture2D(&hd,&hi,&hdr),"hdr");auto hs=srv2(d.Get(),hdr.Get(),DXGI_FORMAT_R8G8B8A8_UNORM);
 D3D11_TEXTURE2D_DESC od=hd;od.Format=DXGI_FORMAT_R8G8B8A8_TYPELESS;od.BindFlags=D3D11_BIND_RENDER_TARGET|D3D11_BIND_SHADER_RESOURCE;ComPtr<ID3D11Texture2D>output;hr(d->CreateTexture2D(&od,nullptr,&output),"output");D3D11_RENDER_TARGET_VIEW_DESC rv{};rv.Format=DXGI_FORMAT_R8G8B8A8_UNORM;rv.ViewDimension=D3D11_RTV_DIMENSION_TEXTURE2D;ComPtr<ID3D11RenderTargetView>rt;hr(d->CreateRenderTargetView(output.Get(),&rv,&rt),"output rtv");
 // Real POSITION/TEXCOORD layout, 20-byte vertices, bound offset 20 and draw start 2.
 D3D11_INPUT_ELEMENT_DESC ie[]={{"POSITION",0,DXGI_FORMAT_R32G32B32_FLOAT,0,0,D3D11_INPUT_PER_VERTEX_DATA,0},{"TEXCOORD",0,DXGI_FORMAT_R32G32_FLOAT,0,12,D3D11_INPUT_PER_VERTEX_DATA,0}};ComPtr<ID3D11InputLayout>layout;
 const char* vsrc="struct V{float3 p:POSITION;float2 t:TEXCOORD;}; float4 main(V v):SV_Position{return float4(v.p,1);}";
 const char* psrc="float4 main():SV_Target{return float4(1,0,0,1);}";
 ComPtr<ID3DBlob> vbcode,pbcode,err;hr(D3DCompile(vsrc,strlen(vsrc),"fixture",nullptr,nullptr,"main","vs_5_0",0,0,&vbcode,&err),"compile VS");hr(D3DCompile(psrc,strlen(psrc),"fixture",nullptr,nullptr,"main","ps_5_0",0,0,&pbcode,&err),"compile PS");
 ComPtr<ID3D11VertexShader> vshader;ComPtr<ID3D11PixelShader> pshader;hr(d->CreateVertexShader(vbcode->GetBufferPointer(),vbcode->GetBufferSize(),nullptr,&vshader),"VS");hr(d->CreatePixelShader(pbcode->GetBufferPointer(),pbcode->GetBufferSize(),nullptr,&pshader),"PS");
 hr(d->CreateInputLayout(ie,2,vbcode->GetBufferPointer(),vbcode->GetBufferSize(),&layout),"layout");c->IASetInputLayout(layout.Get());c->VSSetShader(vshader.Get(),nullptr,0);c->PSSetShader(pshader.Get(),nullptr,0);edvr::EyeTonemapSnapshot::rememberLayout(layout.Get(),ie,2,edvr::EyeTonemapSnapshot::kVs);
 unsigned char shaderBytes[]={68,88,66,67,1,2,3,4};
 D3D11_BUFFER_DESC vbd{};vbd.ByteWidth=20*7;vbd.Usage=D3D11_USAGE_DEFAULT;vbd.BindFlags=D3D11_BIND_VERTEX_BUFFER;std::vector<unsigned char> vv(vbd.ByteWidth,0x51);ComPtr<ID3D11Buffer>vb;D3D11_SUBRESOURCE_DATA vi{vv.data(),0,0};hr(d->CreateBuffer(&vbd,&vi,&vb),"vb");
 D3D11_BUFFER_DESC cbd{};cbd.ByteWidth=256;cbd.Usage=D3D11_USAGE_DEFAULT;cbd.BindFlags=D3D11_BIND_CONSTANT_BUFFER;std::vector<unsigned char> cv(256);for(unsigned i=0;i<cv.size();++i)cv[i]=(unsigned char)(i^0xA5);D3D11_SUBRESOURCE_DATA ci{cv.data(),0,0};ComPtr<ID3D11Buffer>cb;hr(d->CreateBuffer(&cbd,&ci,&cb),"cb");
 // Bind all resources and explicit states without modifying them after capture.
 ID3D11RenderTargetView* r=rt.Get();c->OMSetRenderTargets(1,&r,nullptr);ID3D11ShaderResourceView* evs=ex.Get();c->VSSetShaderResources(0,1,&evs);ID3D11ShaderResourceView* ps[2]={ls.Get(),hs.Get()};c->PSSetShaderResources(0,1,&ps[0]);c->PSSetShaderResources(1,1,&ps[1]);ID3D11Buffer* cp=cb.Get();c->PSSetConstantBuffers(2,1,&cp);UINT stride=20,offset=20;ID3D11Buffer* vp=vb.Get();c->IASetVertexBuffers(0,1,&vp,&stride,&offset);c->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP);
 D3D11_SAMPLER_DESC sd{};sd.Filter=D3D11_FILTER_MIN_MAG_MIP_LINEAR;sd.AddressU=sd.AddressV=sd.AddressW=D3D11_TEXTURE_ADDRESS_CLAMP;ComPtr<ID3D11SamplerState>s0,s1,s2;sd.MipLODBias=0;hr(d->CreateSamplerState(&sd,&s0),"sampler0");sd.MipLODBias=1;hr(d->CreateSamplerState(&sd,&s1),"sampler1");sd.MipLODBias=-1;hr(d->CreateSamplerState(&sd,&s2),"sampler2");ID3D11SamplerState* vsamp=s0.Get();c->VSSetSamplers(0,1,&vsamp);ID3D11SamplerState* ps0=s1.Get();c->PSSetSamplers(0,1,&ps0);ID3D11SamplerState* ps1=s2.Get();c->PSSetSamplers(1,1,&ps1);
 D3D11_BLEND_DESC blend{};blend.RenderTarget[0].BlendEnable=FALSE;blend.RenderTarget[0].RenderTargetWriteMask=D3D11_COLOR_WRITE_ENABLE_ALL;ComPtr<ID3D11BlendState>bs;hr(d->CreateBlendState(&blend,&bs),"blend");FLOAT bf[4]={.1f,.2f,.3f,.4f};c->OMSetBlendState(bs.Get(),bf,0xA5A5A5A5);
 D3D11_DEPTH_STENCIL_DESC dd{};dd.DepthEnable=TRUE;dd.DepthFunc=D3D11_COMPARISON_GREATER;ComPtr<ID3D11DepthStencilState>ds;hr(d->CreateDepthStencilState(&dd,&ds),"depth");c->OMSetDepthStencilState(ds.Get(),7);D3D11_RASTERIZER_DESC rd{};rd.FillMode=D3D11_FILL_SOLID;rd.CullMode=D3D11_CULL_NONE;rd.ScissorEnable=TRUE;ComPtr<ID3D11RasterizerState>rs;hr(d->CreateRasterizerState(&rd,&rs),"raster");c->RSSetState(rs.Get());D3D11_VIEWPORT v{0,0,1404,1406,0,1};c->RSSetViewports(1,&v);D3D11_RECT sc{2,3,1402,1403};c->RSSetScissorRects(1,&sc);
 ComPtr<ID3D11InputLayout> ilBefore;ComPtr<ID3D11VertexShader> vsBefore;ComPtr<ID3D11PixelShader> psBefore;ComPtr<ID3D11Buffer> cbBefore;ComPtr<ID3D11ShaderResourceView> exBefore,lutBefore,hdrBefore;ComPtr<ID3D11SamplerState> sa0Before,sa1Before,sa2Before;ComPtr<ID3D11BlendState> blendBefore;ComPtr<ID3D11DepthStencilState> depthBefore;ComPtr<ID3D11RasterizerState> rastBefore;UINT stencilBefore=0,maskBefore=0;FLOAT factorsBefore[4]{};D3D11_VIEWPORT vpBefore{};D3D11_RECT scBefore{};c->IAGetInputLayout(&ilBefore);c->VSGetShader(&vsBefore,nullptr,nullptr);c->PSGetShader(&psBefore,nullptr,nullptr);c->PSGetConstantBuffers(2,1,&cbBefore);c->VSGetShaderResources(0,1,&exBefore);c->PSGetShaderResources(0,1,&lutBefore);c->PSGetShaderResources(1,1,&hdrBefore);c->VSGetSamplers(0,1,&sa0Before);c->PSGetSamplers(0,1,&sa1Before);c->PSGetSamplers(1,1,&sa2Before);c->OMGetBlendState(&blendBefore,factorsBefore,&maskBefore);c->OMGetDepthStencilState(&depthBefore,&stencilBefore);c->RSGetState(&rastBefore);UINT nvp=1,nsc=1;c->RSGetViewports(&nvp,&vpBefore);c->RSGetScissorRects(&nsc,&scBefore);
 auto rtBefore=rt.Get();auto vbBefore=vb.Get();edvr::EyeTonemapSnapshot::rememberShader(edvr::EyeTonemapSnapshot::kVs,shaderBytes,sizeof(shaderBytes));edvr::EyeTonemapSnapshot::rememberShader(edvr::EyeTonemapSnapshot::kPs,shaderBytes,sizeof(shaderBytes));edvr::EyeTonemapSnapshot snap;snap.capture(c.Get(),42,0,edvr::EyeTonemapSnapshot::kVs,edvr::EyeTonemapSnapshot::kPs,'N',3,2);check(snap.count()==1,"capture bounded");
 // Ensure queued capture copies complete, then rewrite every original input.
 waitGpu(d.Get(),c.Get());std::vector<unsigned char> ev2(64,0x7A);c->UpdateSubresource(exposure.Get(),0,nullptr,ev2.data(),16,64);std::vector<unsigned char> lv2(lv.size(),0xCC);c->UpdateSubresource(lut.Get(),0,nullptr,lv2.data(),16,64);std::vector<unsigned char> hv2(hv.size(),0xD2);c->UpdateSubresource(hdr.Get(),0,nullptr,hv2.data(),hd.Width*4,hd.Width*hd.Height*4);std::vector<unsigned char> cv2(256,0xEE);c->UpdateSubresource(cb.Get(),0,nullptr,cv2.data(),0,0);std::vector<unsigned char> vv2(vv.size(),0xF1);c->UpdateSubresource(vb.Get(),0,nullptr,vv2.data(),0,0);
 FLOAT clearA[4]={.2f,.3f,.4f,.5f};c->ClearRenderTargetView(rt.Get(),clearA);snap.end(c.Get());waitGpu(d.Get(),c.Get());FLOAT clearB[4]={.8f,.7f,.6f,.5f};c->ClearRenderTargetView(rt.Get(),clearB);snap.end(c.Get());
 // The fixture must preserve bindings across capture/end/write.
 ComPtr<ID3D11RenderTargetView>rtCheck; c->OMGetRenderTargets(1,&rtCheck,nullptr);check(rtCheck.Get()==rtBefore,"RTV binding changed");UINT so=0;ComPtr<ID3D11Buffer>vbCheck;c->IAGetVertexBuffers(0,1,&vbCheck,&stride,&so);check(vbCheck.Get()==vbBefore&&so==20,"VB binding changed");
 ComPtr<ID3D11InputLayout> ilAfter;ComPtr<ID3D11VertexShader> vsAfter;ComPtr<ID3D11PixelShader> psAfter;ComPtr<ID3D11Buffer> cbAfter;ComPtr<ID3D11ShaderResourceView> exAfter,lutAfter,hdrAfter;ComPtr<ID3D11SamplerState> sa0After,sa1After,sa2After;ComPtr<ID3D11BlendState> blendAfter;ComPtr<ID3D11DepthStencilState> depthAfter;ComPtr<ID3D11RasterizerState> rastAfter;UINT stencilAfter=0,maskAfter=0;FLOAT factorsAfter[4]{};D3D11_VIEWPORT vpAfter{};D3D11_RECT scAfter{};c->IAGetInputLayout(&ilAfter);c->VSGetShader(&vsAfter,nullptr,nullptr);c->PSGetShader(&psAfter,nullptr,nullptr);c->PSGetConstantBuffers(2,1,&cbAfter);c->VSGetShaderResources(0,1,&exAfter);c->PSGetShaderResources(0,1,&lutAfter);c->PSGetShaderResources(1,1,&hdrAfter);c->VSGetSamplers(0,1,&sa0After);c->PSGetSamplers(0,1,&sa1After);c->PSGetSamplers(1,1,&sa2After);c->OMGetBlendState(&blendAfter,factorsAfter,&maskAfter);c->OMGetDepthStencilState(&depthAfter,&stencilAfter);c->RSGetState(&rastAfter);UINT nvp2=1,nsc2=1;c->RSGetViewports(&nvp2,&vpAfter);c->RSGetScissorRects(&nsc2,&scAfter);check(ilAfter.Get()==ilBefore.Get()&&vsAfter.Get()==vsBefore.Get()&&psAfter.Get()==psBefore.Get()&&cbAfter.Get()==cbBefore.Get()&&exAfter.Get()==exBefore.Get()&&lutAfter.Get()==lutBefore.Get()&&hdrAfter.Get()==hdrBefore.Get(),"shader/resource state changed");check(sa0After.Get()==sa0Before.Get()&&sa1After.Get()==sa1Before.Get()&&sa2After.Get()==sa2Before.Get()&&blendAfter.Get()==blendBefore.Get()&&depthAfter.Get()==depthBefore.Get()&&rastAfter.Get()==rastBefore.Get(),"sampler/state pointers changed");check(stencilAfter==stencilBefore&&maskAfter==maskBefore&&memcmp(factorsAfter,factorsBefore,sizeof(factorsBefore))==0&&memcmp(&vpAfter,&vpBefore,sizeof(vpBefore))==0&&memcmp(&scAfter,&scBefore,sizeof(scBefore))==0,"state values changed");
 // A second eye in the same frame is accepted; a third and a later frame decline.
 uint32_t declinesBefore=snap.declined;snap.capture(c.Get(),43,99,edvr::EyeTonemapSnapshot::kVs,edvr::EyeTonemapSnapshot::kPs,'N',3,2);check(snap.count()==1&&snap.declined==declinesBefore,"first-frame guard");snap.capture(c.Get(),42,1,edvr::EyeTonemapSnapshot::kVs,edvr::EyeTonemapSnapshot::kPs,'N',3,2);snap.end(c.Get());snap.capture(c.Get(),42,2,edvr::EyeTonemapSnapshot::kVs,edvr::EyeTonemapSnapshot::kPs,'N',3,2);check(snap.count()==2,"draw cap");waitGpu(d.Get(),c.Get());check(snap.write(c.Get(),argv[1]),"write");
 // Pending output is explicitly recorded as a zero payload and failure.
 edvr::EyeTonemapSnapshot pending;pending.capture(c.Get(),55,0,edvr::EyeTonemapSnapshot::kVs,edvr::EyeTonemapSnapshot::kPs,'N',3,2);waitGpu(d.Get(),c.Get());wchar_t pendingPath[MAX_PATH];_snwprintf_s(pendingPath,MAX_PATH,_TRUNCATE,L"%s.pending",argv[1]);check(pending.write(c.Get(),pendingPath),"pending write");check(pending.failures>0,"pending failure");std::puts("GPU tonemap snapshot fixture passed");return 0;
}
