// The Full System Scanner's PANEL composite vertex shader,
// vh=A888D51024D9798E, dumped from the game 2026-08-25 and disassembled
// with fxc. See docs/fss-panel.md for the reading. Its position-only
// sibling (vh=B018D143700AB803, the depth prepass of the same quad)
// differs only in omitting every non-position output.
//
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// INSTANCEANDMODELDATAINDEX     0   xy          0     NONE    uint   x   
// PACKEDVERTEXDATAA        0   xyzw        1     NONE    uint   xyzw
// PACKEDVERTEXDATAB        0   xyzw        2     NONE    uint   x   
// PACKEDVERTEXDATAC        0   xyzw        3     NONE    uint   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 2   xyz         1     NONE   float   xyz 
// TEXCOORD                 4   xyz         2     NONE   float   xyz 
// TEXCOORD                 5   xyz         3     NONE   float   xyz 
// TEXCOORD                 6   xy          4     NONE   float   xy  
// SV_POSITION              0   xyzw        5      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[12], immediateIndexed
dcl_constantbuffer CB1[276], immediateIndexed
dcl_constantbuffer CB2[8], immediateIndexed
dcl_resource_structured t33, 336
dcl_resource_structured t38, 48
dcl_input v0.x
dcl_input v1.xyzw
dcl_input v2.x
dcl_input v3.xy
dcl_output o0.xyzw
dcl_output o1.xyz
dcl_output o2.xyz
dcl_output o3.xyz
dcl_output o4.xy
dcl_output_siv o5.xyzw, position
dcl_temps 9
ubfe r0.xyzw, l(7, 8, 8, 8), l(24, 8, 16, 8), v1.zwwz
ieq r1.x, r0.x, l(64)
if_nz r1.x
  and r1.xy, v1.xyxx, l(0x0000ffff, 0x0000ffff, 0, 0)
  ushr r1.zw, v1.xxxy, l(0, 0, 16, 16)
  utof r2.xyzw, r1.xyzw
  mul r1.x, r2.w, l(0.000244)
  exp r1.x, r1.x
  add r1.x, r1.x, l(-1.000000)
  mad r1.yzw, r2.xxzy, l(0.000000, 0.000031, 0.000031, 0.000031), l(0.000000, -1.000000, -1.000000, -1.000000)
  mul r1.xyz, r1.xxxx, r1.yzwy
else 
  ushr r2.xy, v1.zxzz, l(24, 21, 0, 0)
  iadd r0.x, -r0.x, l(20)
  ishl r0.x, l(1), r0.x
  iadd r0.x, r0.x, l(-1)
  itof r0.x, r0.x
  rcp r0.x, r0.x
  ishl r2.x, l(1), r2.x
  itof r2.x, r2.x
  and r2.z, v1.x, l(0x001fffff)
  bfi r2.w, l(10), l(11), v1.y, l(0)
  iadd r2.y, r2.w, r2.y
  ubfe r2.w, l(21), l(10), v1.y
  utof r3.xyz, r2.zywz
  mad r1.xyz, r3.xyzx, r0.xxxx, -r2.xxxx
endif 
and r2.xyz, v1.wzzw, l(255, 0x80000000, 255, 0)
utof r3.xy, r2.xzxx
utof r0.xyz, r0.ywzy
mov r3.zw, r0.xxxz
mad r2.xzw, r3.xxzw, l(0.007874, 0.000000, 0.007874, 0.007874), l(-1.000000, 0.000000, -1.000000, -1.000000)
ubfe r0.w, l(8), l(16), v1.z
utof r0.z, r0.w
mov r0.x, r3.y
mad r0.xyz, r0.xyzx, l(0.007874, 0.007874, 0.007874, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
mul r3.xyz, r2.zwxz, r0.zxyz
mad r3.xyz, r0.yzxy, r2.wxzw, -r3.xyzx
dp3 r4.x, r1.xyzx, r2.xzwx
dp3 r4.y, r1.xyzx, r3.xyzx
mad o0.xyzw, r4.xyxy, cb2[7].xyxy, cb2[6].xyzw
and r0.w, v2.x, l(0x0000ffff)
utof r3.x, r0.w
ushr r0.w, v2.x, l(16)
utof r3.y, r0.w
mad r3.xy, r3.xyxx, l(0.000031, 0.000031, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
mul o4.xy, r3.xyxx, l(16.000000, 16.000000, 0.000000, 0.000000)
ld_structured_indexable(structured_buffer, stride=336)(mixed,mixed,mixed,mixed) r3.xyzw, v0.x, l(0), t33.xyzw
if_nz r3.x
  mov r7.xy, v3.xyxx
  mov r4.xyzw, l(0,0,0,0)
  mov r5.xyzw, l(0,0,0,0)
  mov r6.xyzw, l(0,0,0,0)
  mov r0.w, l(4)
  loop 
    ine r7.z, r7.y, l(0)
    ult r7.w, l(0), r0.w
    and r7.z, r7.w, r7.z
    breakc_z r7.z
    and r7.zw, r7.xxxy, l(0, 0, 255, 255)
    iadd r7.z, r3.x, r7.z
    utof r7.w, r7.w
    mul r7.w, r7.w, l(0.003922)
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r8.xyzw, r7.z, l(0), t38.xyzw
    mad r4.xyzw, r8.xyzw, r7.wwww, r4.xyzw
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r8.xyzw, r7.z, l(16), t38.xyzw
    mad r5.xyzw, r8.xyzw, r7.wwww, r5.xyzw
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r8.xyzw, r7.z, l(32), t38.xyzw
    mad r6.xyzw, r8.xyzw, r7.wwww, r6.xyzw
    ushr r7.xy, r7.xyxx, l(8, 8, 0, 0)
    iadd r0.w, r0.w, l(-1)
  endloop 
  mov r1.w, l(1.000000)
  dp4 r7.x, r4.xyzw, r1.xyzw
  dp4 r7.y, r5.xyzw, r1.xyzw
  dp4 r7.z, r6.xyzw, r1.xyzw
  dp3 r8.x, r4.xyzx, r0.xyzx
  dp3 r8.y, r5.xyzx, r0.xyzx
  dp3 r8.z, r6.xyzx, r0.xyzx
  dp3 r4.x, r4.xyzx, r2.xzwx
  dp3 r4.y, r5.xyzx, r2.xzwx
  dp3 r4.z, r6.xyzx, r2.xzwx
  mov r1.xyz, r7.xyzx
  mov r0.xyz, r8.xyzx
  mov r2.xzw, r4.xxyz
endif 
ld_structured_indexable(structured_buffer, stride=336)(mixed,mixed,mixed,mixed) r4.xyz, v0.x, l(16), t33.xyzx
add r4.xyz, r4.xyzx, -cb1[275].xyzx
and r5.xy, r3.zwzz, l(0x0000ffff, 0x0000ffff, 0, 0)
ushr r3.xz, r3.zzwz, l(16, 0, 16, 0)
utof r5.xz, r5.xxyx
utof r5.yw, r3.xxxz
mad r5.xyzw, r5.xyzw, l(0.000031, 0.000031, 0.000031, 0.000031), l(-1.000000, -1.000000, -1.000000, -1.000000)
add r6.xyzw, r5.xyzw, r5.xyzw
mul r3.xzw, r1.yyzx, r5.zzxy
mad r3.xzw, r5.yyzx, r1.zzxy, -r3.xxzw
dp3 r0.w, r5.xyzx, r1.xyzx
mul r1.w, r5.w, r6.w
mad r1.xyz, r1.wwww, r1.xyzx, -r1.xyzx
mad r1.xyz, r0.wwww, r6.xyzx, r1.xyzx
mad r1.xyz, r3.xzwx, r6.wwww, r1.xyzx
mul r3.xzw, r0.xxyz, r5.yyzx
mad r3.xzw, r5.xxyz, r0.yyzx, -r3.xxzw
dp3 r0.w, r5.xyzx, r0.xyzx
mad r0.xyz, r1.wwww, r0.zxyz, -r0.zxyz
mad r0.xyz, r0.wwww, r6.zxyz, r0.xyzx
mad r0.xyz, r3.xzwx, r6.wwww, r0.xyzx
mul r3.xzw, r2.wwxz, r5.xxyz
mad r3.xzw, r5.zzxy, r2.xxzw, -r3.xxzw
dp3 r0.w, r5.xyzx, r2.xzwx
mad r2.xzw, r1.wwww, r2.zzwx, -r2.zzwx
mad r2.xzw, r0.wwww, r6.yyzx, r2.xxzw
mad r2.xzw, r3.xxzw, r6.wwww, r2.xxzw
mad r1.xyz, r1.xyzx, r3.yyyy, r4.xyzx
mov r1.w, l(1.000000)
dp4 o2.x, r1.xyzw, cb0[9].xyzw
dp4 o2.y, r1.xyzw, cb0[10].xyzw
dp4 o2.z, r1.xyzw, cb0[11].xyzw
dp4 o5.x, cb0[4].xyzw, r1.xyzw
dp4 o5.y, cb0[5].xyzw, r1.xyzw
dp4 o5.z, cb0[6].xyzw, r1.xyzw
dp4 o5.w, cb0[7].xyzw, r1.xyzw
dp3 o3.x, r2.wxzw, cb0[9].xyzx
dp3 o3.y, r2.wxzw, cb0[10].xyzx
dp3 o3.z, r2.wxzw, cb0[11].xyzx
mul r1.xyz, r0.xyzx, r2.xzwx
mad r0.xyz, r0.zxyz, r2.zwxz, -r1.xyzx
movc o1.xyz, r2.yyyy, -r0.xyzx, r0.xyzx
ret 
// Approximately 0 instruction slots used
