//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xyzw        0     NONE   float   xyzw
// TEXCOORD                 2   xyz         1     NONE   float   xyz 
// TEXCOORD                 4   xyz         2     NONE   float   xyz 
// TEXCOORD                 5   xyz         3     NONE   float   xyz 
// TEXCOORD                 6   xy          4     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB1[88], immediateIndexed
dcl_constantbuffer CB2[15], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_input_ps linear v0.xyzw
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xy
dcl_output o0.xyzw
dcl_temps 6
sample_indexable(texture2d)(float,float,float,float) r0.x, v0.xyxx, t0.yxzw, s0
mul r0.x, r0.x, cb2[5].w
sample_indexable(texture2d)(float,float,float,float) r0.y, v0.zwzz, t0.xyzw, s0
mul r0.y, r0.y, cb2[5].w
dp3 r0.z, v2.xyzx, v2.xyzx
rsq r0.z, r0.z
mul r1.xyz, r0.zzzz, v2.xyzx
dp3 r0.z, r1.xyzx, v3.xyzx
mul r2.x, r0.z, cb2[14].z
dp3 r0.z, r1.xyzx, v1.xyzx
mul r2.y, r0.z, cb2[14].z
sample_indexable(texture2d)(float,float,float,float) r1.xyzw, v4.xyxx, t1.xyzw, s1
mul r0.zw, r2.xxxy, cb2[11].zzzw
mad r0.zw, r0.zzzw, l(0.000000, 0.000000, 8.000000, 8.000000), v4.xxxy
mov r2.zw, r0.zzzw
mov r3.xyzw, l(0,0,0,0)
mov r4.x, l(0)
loop 
  ige r4.y, r4.x, l(8)
  breakc_nz r4.y
  sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r2.zwzz, t1.xyzw, s1
  add r5.xyzw, -r3.xyzw, r5.xyzw
  mad r3.xyzw, cb2[14].yyyy, r5.xyzw, r3.xyzw
  mad r2.zw, -r2.xxxy, cb2[11].zzzw, r2.zzzw
  iadd r4.x, r4.x, l(1)
endloop 
dp3 r0.z, r3.xyzx, l(0.308600, 0.609400, 0.082000, 0.000000)
add r2.xyz, -r3.xyzx, r0.zzzz
mad r3.xyz, cb2[14].xxxx, r2.xyzx, r3.xyzx
mul r2.xyzw, r3.xyzw, cb2[8].xyzw
mul r3.xyzw, r3.xyzw, cb2[9].xyzw
mul r3.xyzw, r0.yyyy, r3.xyzw
mad r0.xyzw, r2.xyzw, r0.xxxx, r3.xyzw
add r0.xyzw, r0.xyzw, r1.xyzw
mul r1.xyz, r0.xyzx, cb2[5].xxxx
mul r1.xyz, r1.xyzx, cb2[12].yzwy
log r1.xyz, r1.xyzx
mul r1.xyz, r1.xyzx, l(2.200000, 2.200000, 2.200000, 0.000000)
div r1.w, l(1.000000, 1.000000, 1.000000, 1.000000), cb2[4].w
mul r1.xyz, r1.xyzx, r1.wwww
exp r1.xyz, r1.xyzx
add r1.w, r0.w, l(-0.000010)
lt r1.w, r1.w, l(0.000000)
discard_nz r1.w
mul r2.xyz, r1.yyyy, cb1[86].xyzx
mad r1.xyw, r1.xxxx, cb1[85].xyxz, r2.xyxz
mad r0.xyz, r1.zzzz, cb1[87].xyzx, r1.xywx
lt r1.xyzw, r0.xyzw, l(0.019608, 0.019608, 0.019608, 0.019608)
and r1.xy, r1.zwzz, r1.xyxx
and r1.x, r1.y, r1.x
if_nz r1.x
  discard_nz l(-1)
endif 
mul o0.xyzw, r0.xyzw, cb2[12].xxxx
ret 
// Approximately 0 instruction slots used
