//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// TEXCOORD                 0   xy          1     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// SV_POSITION              0   xyzw        1      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[5], immediateIndexed
dcl_input v0.xyz
dcl_input v1.xy
dcl_output o0.xy
dcl_output_siv o1.xyzw, position
dcl_temps 2
mov o0.xy, v1.xyxx
mul r0.xy, v0.xyxx, cb2[0].xyxx
mul r1.xyzw, r0.yyyy, cb2[2].xyzw
mad r0.xyzw, r0.xxxx, cb2[1].xyzw, r1.xyzw
mad r0.xyzw, v0.zzzz, cb2[3].xyzw, r0.xyzw
add o1.xyzw, r0.xyzw, cb2[4].xyzw
ret 
// Approximately 0 instruction slots used
