// THE GAME'S AMORTIZED TILE RENDERER, READING THE SCENE DEPTH'S STENCIL.
// cs EB0245DE0BB23BB6, dumped 2026-09-07 from the Steam install and
// disassembled with fxc. Its larger sibling cs 5998146D464F5C0E (792 lines)
// is a different shader with IDENTICAL resource declarations and the
// IDENTICAL stencil sequence quoted below; reading one reads both.
//
// WHY THIS IS IN THE REPOSITORY
//
// docs/per-object-motion.md wants to stamp a per-mover tag into free bits of
// this exact stencil plane, and its Phase 0 question 1 was answered "bits 1
// and 6 are free" from the census's so= column. That column records a draw's
// DEPTH-STENCIL STATE -- and a compute shader has none. So the answer was a
// statement about DRAWS, and these two dispatches are a consumer it could not
// see. They were found by accident, chasing a stale dispatch hash.
//
// docs/fss-scanner.md already named them: the game's own GPU-driven amortized
// tile renderer, DispatchIndirect, one thread group per 16x16 tile, the thing
// that actually produces the FSS arrival content. What was not known is that
// it reads the stencil.
//
// WHAT IT DOES WITH THE STENCIL, and what that settles
//
// t4 is declared (uint,uint,uint,uint) -- the X32_G8X24_UINT view of the
// R32G8X24 scene depth, i.e. the stencil plane. The census confirms the
// binding: these dispatches sample the eye-sized scene depth through a
// view of format 22. The whole use is four instructions:
//
//     ld_indexable(texture2d)(uint,uint,uint,uint) r1.z, r1.xyzw, t4.xzyw
//     and  r1.z, r1.z, cb1[26].y
//     ieq  r1.z, r1.z, cb1[26].y
//     if_nz r1.z
//
// So the test is (stencil & M) == M -- "are all bits of M set" -- and M is
// cb1[26].y, a RUNTIME CONSTANT. **The bytecode therefore establishes the
// mechanism and NOT the mask.** Which bits these dispatches read cannot be
// read from any disassembly; it needs the value of cb1[26].y at dispatch
// time, which is float index 105 of that constant buffer.
//
// That is capturable with no new code: draw_census's cbWatchOnDispatch
// already does CSGetConstantBuffers(0, 2) and dumps both, so
// advanced.census_cb_watch = 5998146D464F5C0E and a census while the tile
// renderer runs will print it on a DCW line.
//
// UNTIL THEN, question 1's answer stands as "bits 1 and 6 are free of every
// DRAW", with this shader as the named, unmeasured exception. If M covers
// bit 1 or bit 6, a tag written there changes what this renderer does.
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Note: shader requires additional functionality:
//       Typed UAV Load Additional Formats
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[28], immediateIndexed
dcl_constantbuffer CB1[27], immediateIndexed
dcl_constantbuffer CB2[1], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_resource_raw t0
dcl_resource_raw t1
dcl_resource_structured t2, 8
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (uint,uint,uint,uint) t4
dcl_resource_structured t5, 4
dcl_resource_texturecubearray (float,float,float,float) t6
dcl_resource_buffer (float,float,float,float) t7
dcl_resource_texture2d (float,float,float,float) t8
dcl_resource_texture2d (float,float,float,float) t9
dcl_resource_texture2d (float,float,float,float) t10
dcl_resource_texture2d (float,float,float,float) t11
dcl_uav_typed_texture2d (float,float,float,float) u0
dcl_uav_typed_texture2d (float,float,float,float) u1
dcl_input vThreadGroupID.xy
dcl_input vThreadIDInGroup.xy
dcl_temps 15
dcl_thread_group 8, 8, 1
ushr r0.x, cb0[1].w, l(3)
imul null, r0.y, r0.x, r0.x
ishl r0.z, vThreadGroupID.x, l(7)
iadd r0.z, r0.z, vThreadGroupID.y
udiv r1.x, r2.x, r0.z, r0.y
iadd r0.y, cb0[1].w, l(-1)
iadd r0.yz, r0.yyyy, cb0[0].xxyx
udiv r0.yz, null, r0.yyzy, cb0[1].wwww
imul null, r0.w, r0.z, r0.y
uge r0.w, r1.x, r0.w
if_z r0.w
  ld_structured_indexable(structured_buffer, stride=8)(mixed,mixed,mixed,mixed) r0.yz, r1.x, l(0), t2.xxyx
endif 
udiv r1.x, r2.x, r2.x, r0.x
mov r2.y, r1.x
imad r0.xy, r0.yzyy, r0.xxxx, r2.xyxx
bfi r1.xy, l(29, 29, 0, 0), l(3, 3, 0, 0), r0.xyxx, vThreadIDInGroup.xyxx
ult r0.zw, r1.xxxy, cb0[0].xxxy
and r0.z, r0.w, r0.z
if_nz r0.z
  mov r1.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r0.z, r1.xyww, t3.yzxw
  lt r0.w, r0.z, l(9999999827968.000000)
  if_nz r0.w
    ishl r0.xy, r0.xyxx, l(3, 3, 0, 0)
    udiv r0.xy, null, r0.xyxx, cb0[1].wwww
    ld_indexable(texture2d)(float,float,float,float) r2.xyzw, r1.xyww, t10.xyzw
    mad r0.w, r2.w, l(255.000000), l(0.500000)
    ftou r0.w, r0.w
    ld_indexable(texture2d)(float,float,float,float) r3.xyz, r1.xyww, t9.xyzw
    mad r3.yz, r3.yyzy, l(0.000000, 4.000000, 4.000000, 0.000000), l(0.000000, -2.000000, -2.000000, 0.000000)
    dp2 r2.w, r3.yzyy, r3.yzyy
    mad r3.w, -r2.w, l(0.250000), l(1.000000)
    max r3.w, r3.w, l(0.000000)
    sqrt r3.w, r3.w
    mul r4.xy, r3.wwww, r3.yzyy
    mad r4.z, r2.w, l(0.500000), l(-1.000000)
    dp3 r2.w, r4.xyzx, r4.xyzx
    rsq r2.w, r2.w
    mul r3.yzw, r2.wwww, r4.xxyz
    ld_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.xyww, t11.yzxw
    and r2.w, r0.w, l(128)
    if_nz r2.w
      mov r5.xy, l(1.000000,1.000000,0,0)
    else 
      and r0.w, r0.w, l(64)
      if_nz r0.w
        mov r4.xy, r4.zzzz
      endif 
      add r0.w, -r4.w, l(1.000000)
      mad r5.xy, -r0.wwww, cb1[24].zwzz, l(1.000000, 1.000000, 0.000000, 0.000000)
    endif 
    log r0.w, r0.z
    mul r0.w, r0.w, cb0[0].z
    mad r0.w, r0.w, l(0.693147), cb0[0].w
    ftoi r0.w, r0.w
    iadd r2.w, cb0[1].z, l(-1)
    imax r0.w, r0.w, l(0)
    imin r0.w, r2.w, r0.w
    imad r0.x, cb0[1].x, r0.y, r0.x
    imul null, r0.y, cb0[1].y, cb0[1].x
    imad r0.x, r0.y, r0.w, r0.x
    utof r0.yw, r1.xxxy
    utof r5.zw, cb0[0].xxxy
    div r0.yw, r0.yyyw, r5.zzzw
    div r5.zw, l(0.000000, 0.000000, 0.500000, 0.500000), r5.zzzw
    add r6.xy, r0.ywyy, r5.zwzz
    mov r6.z, l(1.000000)
    dp3 r7.x, cb0[10].xywx, r6.xyzx
    dp3 r7.y, cb0[11].xywx, r6.xyzx
    dp3 r7.z, cb0[12].xywx, r6.xyzx
    mul r6.xyz, r0.zzzz, r7.xyzx
    imad r0.y, r0.x, l(2372), l(24)
    ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r0.yw, r0.y, t0.xxxy
    ld_indexable(texture2d)(uint,uint,uint,uint) r1.z, r1.xyzw, t4.xzyw
    and r1.z, r1.z, cb1[26].y
    ieq r1.z, r1.z, cb1[26].y
    if_nz r1.z
      umax r1.w, r0.y, l(1)
      iadd r1.w, r1.w, l(-1)
    else 
      mov r1.w, l(0)
    endif 
    ult r0.y, r1.w, r0.y
    if_nz r0.y
      ishl r0.y, r1.w, l(2)
      imad r0.y, r0.x, l(2372), r0.y
      iadd r0.y, r0.y, l(2084)
      ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r0.y, r0.y, t0.xxxx
      imad r1.w, l(96), r0.y, cb0[25].w
      iadd r8.xyz, r1.wwww, l(32, 48, 64, 0)
      ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r9.xyz, r8.x, t1.xyzx
      ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r8.xyw, r8.y, t1.xyxz
      ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r10.xyz, r8.z, t1.xyzx
      ishl r0.y, r0.y, l(5)
      iadd r0.y, r0.y, cb0[26].x
      iadd r0.y, r0.y, l(12)
      ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r5.zw, r0.y, t1.xxxy
      dp3 r9.x, r9.xyzx, r3.yzwy
      dp3 r9.y, r8.xywx, r3.yzwy
      dp3 r9.z, r10.xyzx, r3.yzwy
      udiv r0.y, null, r5.z, l(24)
      imul null, r1.w, r0.y, l(6)
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.w, r1.w, l(0), t5.xxxx
      imad r2.w, r0.y, l(6), l(1)
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r2.w, r2.w, l(0), t5.xxxx
      and r4.w, r1.w, l(0x0000ffff)
      ushr r1.w, r1.w, l(16)
      f16tof32 r8.x, r4.w
      f16tof32 r8.y, r1.w
      and r1.w, r2.w, l(0x0000ffff)
      ushr r2.w, r2.w, l(16)
      f16tof32 r8.z, r1.w
      f16tof32 r8.w, r2.w
      imad r10.xy, r0.yyyy, l(6, 6, 0, 0), l(2, 4, 0, 0)
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.y, r10.x, l(0), t5.xxxx
      iadd r10.xz, r10.xxyx, l(1, 0, 1, 0)
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.w, r10.x, l(0), t5.xxxx
      and r2.w, r0.y, l(0x0000ffff)
      ushr r0.y, r0.y, l(16)
      f16tof32 r11.x, r2.w
      f16tof32 r11.y, r0.y
      and r0.y, r1.w, l(0x0000ffff)
      ushr r1.w, r1.w, l(16)
      f16tof32 r11.z, r0.y
      f16tof32 r11.w, r1.w
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.y, r10.y, l(0), t5.xxxx
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.w, r10.z, l(0), t5.xxxx
      and r2.w, r0.y, l(0x0000ffff)
      ushr r0.y, r0.y, l(16)
      f16tof32 r10.x, r2.w
      f16tof32 r10.y, r0.y
      and r0.y, r1.w, l(0x0000ffff)
      ushr r1.w, r1.w, l(16)
      f16tof32 r10.z, r0.y
      f16tof32 r10.w, r1.w
      mov r9.w, l(1.000000)
      dp4 r8.x, r8.xyzw, r9.xyzw
      dp4 r8.y, r11.xyzw, r9.xyzw
      dp4 r8.z, r10.xyzw, r9.xyzw
      mul r8.xyz, r5.wwww, r8.xyzx
      mul r8.xyz, r8.xyzx, l(0.999990, 0.999990, 0.999990, 0.000000)
      mov r0.y, l(0.999990)
    else 
      mov r8.xyz, l(0,0,0,0)
      mov r0.y, l(0)
    endif 
    mul r8.xyz, r8.xyzx, cb1[26].wwww
    ine r1.w, cb2[0].x, l(0)
    ge r2.w, r0.y, l(0.001000)
    and r1.w, r1.w, r2.w
    if_nz r1.w
      imad r1.w, r0.x, l(2372), l(32)
      ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r1.w, r1.w, t0.xxxx
      mov r9.xyz, r8.xyzx
      mov r2.w, l(0)
      loop 
        uge r4.w, r2.w, r1.w
        breakc_nz r4.w
        ishl r4.w, r2.w, l(2)
        imad r4.w, r0.x, l(2372), r4.w
        iadd r4.w, r4.w, l(2340)
        ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r4.w, r4.w, t0.xxxx
        iadd r2.w, r2.w, l(1)
        ishl r5.z, r4.w, l(4)
        iadd r5.z, r5.z, cb0[26].w
        ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r10.xyzw, r5.z, t1.xyzw
        imad r4.w, l(48), r4.w, cb0[27].x
        ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r11.xyzw, r4.w, t1.xyzw
        iadd r5.zw, r4.wwww, l(0, 0, 16, 32)
        ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r12.xyzw, r5.z, t1.xyzw
        ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r4.w, r5.w, t1.xxxx
        mad r10.xyz, r7.xyzx, r0.zzzz, -r10.xyzx
        dp3 r5.z, r10.xyzx, r10.xyzx
        sqrt r5.z, r5.z
        div r10.xyz, r10.xyzx, r5.zzzz
        mul r13.xyz, r11.yzwy, r10.yzxy
        mad r13.xyz, r10.xyzx, r11.zwyz, -r13.xyzx
        dp3 r5.w, r13.xyzx, r13.xyzx
        rsq r5.w, r5.w
        mul r13.xyz, r5.wwww, r13.xyzx
        mul r14.xyz, r10.yzxy, r13.xyzx
        mad r13.xyz, r13.zxyz, r10.zxyz, -r14.xyzx
        dp3 r5.w, r13.xyzx, r13.xyzx
        rsq r5.w, r5.w
        mul r13.xyz, r5.wwww, r13.xyzx
        dp3 r5.w, r13.xyzx, r3.yzwy
        add r5.w, r5.w, l(1.000000)
        mad r5.w, r5.w, l(0.050000), l(-0.050000)
        dp3 r6.w, r10.xyzx, r11.yzwy
        add r5.w, r5.w, r6.w
        add r5.w, r5.w, l(1.000000)
        mul_sat r5.w, r5.w, l(0.500000)
        dp3 r6.w, r10.xyzx, r3.yzwy
        add r6.w, r6.w, l(1.000000)
        mul r6.w, r6.w, l(0.500000)
        add r7.w, -r4.w, r10.w
        mad r4.w, r7.w, l(0.500000), r4.w
        add r5.z, -r4.w, r5.z
        add r4.w, -r4.w, r10.w
        div_sat r4.w, r5.z, r4.w
        add r4.w, -r4.w, l(1.000000)
        mul r5.z, r5.w, l(63.000000)
        ftou r5.w, r5.z
        frc r5.z, r5.z
        ushr r7.w, r11.x, l(2)
        imad r5.w, r5.w, l(3), r7.w
        ld_indexable(buffer)(float,float,float,float) r10.x, r5.wwww, t7.xyzw
        iadd r11.xyzw, r5.wwww, l(3, 1, 2, 4)
        ld_indexable(buffer)(float,float,float,float) r10.y, r11.yyyy, t7.yxzw
        ld_indexable(buffer)(float,float,float,float) r10.z, r11.zzzz, t7.yzxw
        ld_indexable(buffer)(float,float,float,float) r11.x, r11.xxxx, t7.xyzw
        ld_indexable(buffer)(float,float,float,float) r11.y, r11.wwww, t7.yxzw
        iadd r5.w, r5.w, l(5)
        ld_indexable(buffer)(float,float,float,float) r11.z, r5.wwww, t7.yzxw
        add r11.xyz, -r10.xyzx, r11.xyzx
        mad r10.xyz, r5.zzzz, r11.xyzx, r10.xyzx
        mul r10.xyz, r6.wwww, r10.xyzx
        mul r10.xyz, r4.wwww, r10.xyzx
        mul r10.xyz, r12.wwww, r10.xyzx
        mul r10.xyz, r0.yyyy, r10.xyzx
        mul r10.xyz, r10.xyzx, r12.xyzx
        mad r9.xyz, r10.xyzx, l(0.318317, 0.318317, 0.318317, 0.000000), r9.xyzx
      endloop 
      mov r8.xyz, r9.xyzx
    endif 
    mul r7.xyz, r2.xyzx, r8.xyzx
    max r2.xyz, r2.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
    dp3 r0.y, r2.xyzx, r2.xyzx
    rsq r0.y, r0.y
    mul r2.xyz, r0.yyyy, r2.xyzx
    mul r2.xyz, r2.xyzx, cb0[21].wwww
    max r2.xyz, r2.xyzx, r7.xyzx
    max r7.xyz, r8.xyzx, cb0[21].wwww
    mul r7.xyz, r5.xxxx, r7.xyzx
    if_nz r1.z
      umax r0.y, r0.w, l(1)
      iadd r0.y, r0.y, l(-1)
    else 
      mov r0.y, l(0)
    endif 
    ult r0.z, r0.y, r0.w
    if_nz r0.z
      max r0.z, r3.x, l(0.050000)
      min r8.x, r0.z, l(1.000000)
      dp3 r0.z, r6.xyzx, r6.xyzx
      rsq r0.z, r0.z
      mul r6.xyz, r0.zzzz, r6.xyzx
      dp3 r0.z, r6.xyzx, r3.yzwy
      add r0.z, r0.z, r0.z
      mad r9.xyz, r3.yzwy, -r0.zzzz, r6.xyzx
      ishl r0.y, r0.y, l(2)
      imad r0.x, r0.x, l(2372), r0.y
      iadd r0.x, r0.x, l(2212)
      ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r0.x, r0.x, t0.xxxx
      imad r0.xy, l(160, 48, 0, 0), r0.xxxx, cb0[26].yzyy
      iadd r0.xzw, r0.xxxx, l(112, 0, 128, 144)
      ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r10.xyz, r0.x, t1.xyzx
      ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r11.xyz, r0.z, t1.xyzx
      ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r0.xzw, r0.w, t1.xxyz
      ld_raw_indexable(raw_buffer)(mixed,mixed,mixed,mixed) r1.zw, r0.y, t1.xxxy
      dp3 r10.x, r10.xyzx, r9.xyzx
      dp3 r10.y, r11.xyzx, r9.xyzx
      dp3 r10.z, r0.xzwx, r9.xyzx
      utof r10.w, r1.z
      dp3_sat r8.y, r3.yzwy, -r6.xyzx
      sample_l_indexable(texture2d)(float,float,float,float) r0.xy, r8.xyxx, t8.xyzw, s1, l(0.000000)
      mad r0.xyz, r4.zxyz, r0.xxxx, r0.yyyy
      sqrt r0.w, r8.x
      mul r0.w, r0.w, l(8.000000)
      min r0.w, r0.w, l(7.000000)
      sample_l_indexable(texturecubearray)(float,float,float,float) r3.xyz, r10.xyzw, t6.xyzw, s0, r0.w
      mul r0.xyz, r0.xyzx, r3.xyzx
      mul r0.xyz, r1.wwww, r0.xyzx
      mul r0.xyz, r0.xyzx, l(0.999990, 0.999990, 0.999990, 0.000000)
    else 
      mov r0.xyz, l(0,0,0,0)
    endif 
    mul r0.xyz, r0.xyzx, cb1[26].wwww
    mul r0.xyz, r5.yyyy, r0.xyzx
    mad r0.xyz, r2.xyzx, r5.xxxx, r0.xyzx
    mul r0.xyz, r0.xyzx, cb1[26].zzzz
    ld_uav_typed_indexable(texture2d)(float,float,float,float) r2.xyzw, r1.xyyy, u0.xyzw
    mov r0.w, l(1.000000)
    add r0.xyzw, r0.xyzw, r2.xyzw
    store_uav_typed u0.xyzw, r1.xyyy, r0.xyzw
    mul r0.xyz, r7.xyzx, cb1[26].zzzz
    ld_uav_typed_indexable(texture2d)(float,float,float,float) r2.xyzw, r1.xyyy, u1.xyzw
    mov r0.w, l(1.000000)
    add r0.xyzw, r0.xyzw, r2.xyzw
    store_uav_typed u1.xyzw, r1.xyyy, r0.xyzw
  endif 
endif 
ret 
// Approximately 0 instruction slots used
