//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 6   xyzw        0     NONE   float   xyzw
// TEXCOORD                 7   xyzw        1     NONE   float   xyzw
// TEXCOORD                 8   xyzw        2     NONE   float   xyzw
// TEXCOORD                10   x           3     NONE   float   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[3], immediateIndexed
dcl_input_ps linear v0.xyzw
dcl_input_ps linear v1.xyzw
dcl_input_ps linear v2.xyzw
dcl_input_ps linear v3.x
dcl_output o0.xyzw
dcl_temps 3
and r0.xyzw, cb2[2].xxxx, l(1, 128, 0x00010000, 0x00020000)
movc r1.xyzw, r0.xxxx, l(1.000000,1.000000,1.000000,1.000000), v2.xyzw
mad r1.xyzw, r1.xyzw, v0.xyzw, v1.xyzw
movc r0.x, r0.y, v3.x, l(1.000000)
mul r1.w, r0.x, r1.w
add r2.xyzw, r1.xyzw, l(-1.000000, -1.000000, -1.000000, -1.000000)
movc r0.x, r0.z, r1.w, l(1.000000)
mad r1.xyzw, r0.xxxx, r2.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
movc r0.x, r0.w, r1.w, l(1.000000)
mul r1.xyz, r0.xxxx, r1.xyzx
max o0.xyzw, r1.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
ret 
// Approximately 0 instruction slots used
