//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// COLOUR                   0   xyzw        1     NONE   float   xyzw
// COLOUR                   1   xyzw        2     NONE   float   x  w
// COLOUR                   2   xyzw        3     NONE   float   x  w
// TEXCOORD                 0   xy          4     NONE   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 6   xyzw        0     NONE   float   xyzw
// TEXCOORD                 7   xyzw        1     NONE   float   xyzw
// TEXCOORD                 8   xyzw        2     NONE   float   xyzw
// TEXCOORD                10   x           3     NONE   float   x   
// SV_POSITION              0   xyzw        4      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[3], immediateIndexed
dcl_resource_structured t0, 160
dcl_input v0.xyzw
dcl_input v1.xyzw
dcl_input v2.xw
dcl_input v3.xw
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.x
dcl_output_siv o4.xyzw, position
dcl_temps 3
and r0.xyzw, cb2[2].xxxx, l(0x00008000, 8192, 0x00004000, 2)
movc r0.z, r0.z, v2.x, l(0)
movc r0.z, r0.x, v3.x, r0.z
mad r0.z, r0.z, l(255.000000), l(0.100000)
ftoi r0.z, r0.z
ld_structured_indexable(structured_buffer, stride=160)(mixed,mixed,mixed,mixed) o0.xyzw, r0.z, l(64), t0.xyzw
ld_structured_indexable(structured_buffer, stride=160)(mixed,mixed,mixed,mixed) o1.xyzw, r0.z, l(80), t0.xyzw
and r1.x, cb2[2].x, l(4)
movc r2.xyzw, r0.wwww, cb2[0].xyzw, l(0,0,0,0)
movc o2.xyzw, r1.xxxx, v1.xyzw, r2.xyzw
movc r0.x, r0.x, v3.w, l(0)
movc o3.x, r0.y, v2.w, r0.x
ld_structured_indexable(structured_buffer, stride=160)(mixed,mixed,mixed,mixed) r1.xyzw, r0.z, l(0), t0.xyzw
dp4 o4.x, v0.xyzw, r1.xyzw
ld_structured_indexable(structured_buffer, stride=160)(mixed,mixed,mixed,mixed) r1.xyzw, r0.z, l(16), t0.xyzw
dp4 o4.y, v0.xyzw, r1.xyzw
ld_structured_indexable(structured_buffer, stride=160)(mixed,mixed,mixed,mixed) r1.xyzw, r0.z, l(32), t0.xyzw
ld_structured_indexable(structured_buffer, stride=160)(mixed,mixed,mixed,mixed) r0.xyzw, r0.z, l(48), t0.xyzw
dp4 o4.w, v0.xyzw, r0.xyzw
dp4 o4.z, v0.xyzw, r1.xyzw
ret 
// Approximately 0 instruction slots used
