#pragma once

// ABI census for Valve OpenVR v0.9.20.  Slots are zero-based within the
// named interface and include only the pure virtual methods in openvr.h.
// The declarations themselves live in openvr_v0_9_20.h; this table is a
// review-friendly inventory and deliberately does not provide generic thunks.

namespace edvr::openvr_abi {
struct Method { const char* interface_name; unsigned slot; const char* signature; };

inline constexpr Method kMethods[] = {
    {"IVRSystem_012",0,"void GetRecommendedRenderTargetSize(uint32_t*,uint32_t*)"},
    {"IVRSystem_012",1,"HmdMatrix44_t GetProjectionMatrix(EVREye,float,float,EGraphicsAPIConvention)"},
    {"IVRSystem_012",2,"void GetProjectionRaw(EVREye,float*,float*,float*,float*)"},
    {"IVRSystem_012",3,"DistortionCoordinates_t ComputeDistortion(EVREye,float,float)"},
    {"IVRSystem_012",4,"HmdMatrix34_t GetEyeToHeadTransform(EVREye)"},
    {"IVRSystem_012",5,"bool GetTimeSinceLastVsync(float*,uint64_t*)"},
    {"IVRSystem_012",6,"int32_t GetD3D9AdapterIndex()"},
    {"IVRSystem_012",7,"void GetDXGIOutputInfo(int32_t*)"},
    {"IVRSystem_012",8,"bool IsDisplayOnDesktop()"},
    {"IVRSystem_012",9,"bool SetDisplayVisibility(bool)"},
    {"IVRSystem_012",10,"void GetDeviceToAbsoluteTrackingPose(ETrackingUniverseOrigin,float,TrackedDevicePose_t*,uint32_t)"},
    {"IVRSystem_012",11,"void ResetSeatedZeroPose()"},
    {"IVRSystem_012",12,"HmdMatrix34_t GetSeatedZeroPoseToStandingAbsoluteTrackingPose()"},
    {"IVRSystem_012",13,"HmdMatrix34_t GetRawZeroPoseToStandingAbsoluteTrackingPose()"},
    {"IVRSystem_012",14,"uint32_t GetSortedTrackedDeviceIndicesOfClass(ETrackedDeviceClass,TrackedDeviceIndex_t*,uint32_t,TrackedDeviceIndex_t)"},
    {"IVRSystem_012",15,"EDeviceActivityLevel GetTrackedDeviceActivityLevel(TrackedDeviceIndex_t)"},
    {"IVRSystem_012",16,"void ApplyTransform(TrackedDevicePose_t*,const TrackedDevicePose_t*,const HmdMatrix34_t*)"},
    {"IVRSystem_012",17,"TrackedDeviceIndex_t GetTrackedDeviceIndexForControllerRole(ETrackedControllerRole)"},
    {"IVRSystem_012",18,"ETrackedControllerRole GetControllerRoleForTrackedDeviceIndex(TrackedDeviceIndex_t)"},
    {"IVRSystem_012",19,"ETrackedDeviceClass GetTrackedDeviceClass(TrackedDeviceIndex_t)"},
    {"IVRSystem_012",20,"bool IsTrackedDeviceConnected(TrackedDeviceIndex_t)"},
    {"IVRSystem_012",21,"bool GetBoolTrackedDeviceProperty(TrackedDeviceIndex_t,ETrackedDeviceProperty,ETrackedPropertyError*)"},
    {"IVRSystem_012",22,"float GetFloatTrackedDeviceProperty(TrackedDeviceIndex_t,ETrackedDeviceProperty,ETrackedPropertyError*)"},
    {"IVRSystem_012",23,"int32_t GetInt32TrackedDeviceProperty(TrackedDeviceIndex_t,ETrackedDeviceProperty,ETrackedPropertyError*)"},
    {"IVRSystem_012",24,"uint64_t GetUint64TrackedDeviceProperty(TrackedDeviceIndex_t,ETrackedDeviceProperty,ETrackedPropertyError*)"},
    {"IVRSystem_012",25,"HmdMatrix34_t GetMatrix34TrackedDeviceProperty(TrackedDeviceIndex_t,ETrackedDeviceProperty,ETrackedPropertyError*)"},
    {"IVRSystem_012",26,"uint32_t GetStringTrackedDeviceProperty(TrackedDeviceIndex_t,ETrackedDeviceProperty,char*,uint32_t,ETrackedPropertyError*)"},
    {"IVRSystem_012",27,"const char* GetPropErrorNameFromEnum(ETrackedPropertyError)"},
    {"IVRSystem_012",28,"bool PollNextEvent(VREvent_t*,uint32_t)"},
    {"IVRSystem_012",29,"bool PollNextEventWithPose(ETrackingUniverseOrigin,VREvent_t*,uint32_t,TrackedDevicePose_t*)"},
    {"IVRSystem_012",30,"const char* GetEventTypeNameFromEnum(EVREventType)"},
    {"IVRSystem_012",31,"HiddenAreaMesh_t GetHiddenAreaMesh(EVREye)"},
    {"IVRSystem_012",32,"bool GetControllerState(TrackedDeviceIndex_t,VRControllerState_t*)"},
    {"IVRSystem_012",33,"bool GetControllerStateWithPose(ETrackingUniverseOrigin,TrackedDeviceIndex_t,VRControllerState_t*,TrackedDevicePose_t*)"},
    {"IVRSystem_012",34,"void TriggerHapticPulse(TrackedDeviceIndex_t,uint32_t,unsigned short)"},
    {"IVRSystem_012",35,"const char* GetButtonIdNameFromEnum(EVRButtonId)"},
    {"IVRSystem_012",36,"const char* GetControllerAxisTypeNameFromEnum(EVRControllerAxisType)"},
    {"IVRSystem_012",37,"bool CaptureInputFocus()"},
    {"IVRSystem_012",38,"void ReleaseInputFocus()"},
    {"IVRSystem_012",39,"bool IsInputFocusCapturedByAnotherProcess()"},
    {"IVRSystem_012",40,"uint32_t DriverDebugRequest(TrackedDeviceIndex_t,const char*,char*,uint32_t)"},
    {"IVRSystem_012",41,"EVRFirmwareError PerformFirmwareUpdate(TrackedDeviceIndex_t)"},
    {"IVRSystem_012",42,"void AcknowledgeQuit_Exiting()"},
    {"IVRSystem_012",43,"void AcknowledgeQuit_UserPrompt()"},
    {"IVRCompositor_014",0,"void SetTrackingSpace(ETrackingUniverseOrigin)"},
    {"IVRCompositor_014",1,"ETrackingUniverseOrigin GetTrackingSpace()"},
    {"IVRCompositor_014",2,"EVRCompositorError WaitGetPoses(TrackedDevicePose_t*,uint32_t,TrackedDevicePose_t*,uint32_t)"},
    {"IVRCompositor_014",3,"EVRCompositorError GetLastPoses(TrackedDevicePose_t*,uint32_t,TrackedDevicePose_t*,uint32_t)"},
    {"IVRCompositor_014",4,"EVRCompositorError GetLastPoseForTrackedDeviceIndex(TrackedDeviceIndex_t,TrackedDevicePose_t*,TrackedDevicePose_t*)"},
    {"IVRCompositor_014",5,"EVRCompositorError Submit(EVREye,const Texture_t*,const VRTextureBounds_t*,EVRSubmitFlags)"},
    {"IVRCompositor_014",6,"void ClearLastSubmittedFrame()"},
    {"IVRCompositor_014",7,"void PostPresentHandoff()"},
    {"IVRCompositor_014",8,"bool GetFrameTiming(Compositor_FrameTiming*,uint32_t)"},
    {"IVRCompositor_014",9,"float GetFrameTimeRemaining()"},
    {"IVRCompositor_014",10,"void FadeToColor(float,float,float,float,float,bool)"},
    {"IVRCompositor_014",11,"void FadeGrid(float,bool)"},
    {"IVRCompositor_014",12,"EVRCompositorError SetSkyboxOverride(const Texture_t*,uint32_t)"},
    {"IVRCompositor_014",13,"void ClearSkyboxOverride()"},
    {"IVRCompositor_014",14,"void CompositorBringToFront()"},
    {"IVRCompositor_014",15,"void CompositorGoToBack()"},
    {"IVRCompositor_014",16,"void CompositorQuit()"},
    {"IVRCompositor_014",17,"bool IsFullscreen()"},
    {"IVRCompositor_014",18,"uint32_t GetCurrentSceneFocusProcess()"},
    {"IVRCompositor_014",19,"uint32_t GetLastFrameRenderer()"},
    {"IVRCompositor_014",20,"bool CanRenderScene()"},
    {"IVRCompositor_014",21,"void ShowMirrorWindow()"},
    {"IVRCompositor_014",22,"void HideMirrorWindow()"},
    {"IVRCompositor_014",23,"bool IsMirrorWindowVisible()"},
    {"IVRCompositor_014",24,"void CompositorDumpImages()"},
    {"IVRCompositor_014",25,"bool ShouldAppRenderWithLowResources()"},
    {"IVRCompositor_014",26,"void ForceInterleavedReprojectionOn(bool)"},
    {"IVRCompositor_014",27,"void ForceReconnectProcess()"},
    {"IVRCompositor_014",28,"void SuspendRendering(bool)"},
    {"IVRChaperone_003",0,"ChaperoneCalibrationState GetCalibrationState()"},
    {"IVRChaperone_003",1,"bool GetPlayAreaSize(float*,float*)"},
    {"IVRChaperone_003",2,"bool GetPlayAreaRect(HmdQuad_t*)"},
    {"IVRChaperone_003",3,"void ReloadInfo()"},
    {"IVRChaperone_003",4,"void SetSceneColor(HmdColor_t)"},
    {"IVRChaperone_003",5,"void GetBoundsColor(HmdColor_t*,int,float,HmdColor_t*)"},
    {"IVRChaperone_003",6,"bool AreBoundsVisible()"},
    {"IVRChaperone_003",7,"void ForceBoundsVisible(bool)"},
    {"IVRExtendedDisplay_001",0,"void GetWindowBounds(int32_t*,int32_t*,uint32_t*,uint32_t*)"},
    {"IVRExtendedDisplay_001",1,"void GetEyeOutputViewport(EVREye,uint32_t*,uint32_t*,uint32_t*)"},
    {"IVRExtendedDisplay_001",2,"void GetDXGIOutputInfo(int32_t*,int32_t*)"},
};
inline constexpr unsigned kMethodCount = sizeof(kMethods) / sizeof(kMethods[0]);
}
