#define NOMINMAX
#include <windows.h>
#include <d3d11.h>
#include <d3dcompiler.h>
#include <wrl/client.h>
#include <cstdio>
#include <cstring>
#include <stdexcept>
#include <cmath>
// The UI layer's depth-stencil seed (src/d3d11/ui_layer_seed.h) across the
// three depth formats, every stencil value class, a scale and a jitter, and
// the reuse of one seeder: the readback must be the nearest input texel.
#include "../../src/d3d11/ui_layer_seed.h"
#pragma comment(lib,"d3d11.lib")
#pragma comment(lib,"d3dcompiler.lib")
using Microsoft::WRL::ComPtr;
static ComPtr<ID3DBlob> compile(const char*s,const char*e,const char*p){ComPtr<ID3DBlob>b,x;HRESULT h=D3DCompile(s,strlen(s),"seed_test",nullptr,nullptr,e,p,0,0,&b,&x);if(FAILED(h))throw std::runtime_error(x?std::string((char*)x->GetBufferPointer(),x->GetBufferSize()):"shader compile");return b;}
static const char* kInitVS=R"(struct V{float4 p:SV_POSITION;};V main(uint i:SV_VertexID){float2 p=i==0?float2(-1,-1):(i==1?float2(-1,3):float2(3,-1));V v;v.p=float4(p,0,1);return v;})";
static const char* kInitPS=R"(float main(float4 p:SV_POSITION):SV_Depth{float2 q=p.xy/float2(7,5);return 0.1+0.8*(0.6*q.x+0.4*q.y);})";
static ComPtr<ID3D11Texture2D> makeTex(ID3D11Device*d,UINT w,UINT h,DXGI_FORMAT f,UINT bind,D3D11_USAGE u=D3D11_USAGE_DEFAULT,UINT cpu=0){D3D11_TEXTURE2D_DESC x{};x.Width=w;x.Height=h;x.MipLevels=x.ArraySize=1;x.Format=f;x.SampleDesc.Count=1;x.BindFlags=bind;x.Usage=u;x.CPUAccessFlags=cpu;ComPtr<ID3D11Texture2D>t;if(FAILED(d->CreateTexture2D(&x,nullptr,&t)))throw std::runtime_error("CreateTexture2D");return t;}
static ComPtr<ID3D11DepthStencilView> makeDSV(ID3D11Device*d,ID3D11Resource*r,DXGI_FORMAT f){D3D11_DEPTH_STENCIL_VIEW_DESC x{};x.Format=f;x.ViewDimension=D3D11_DSV_DIMENSION_TEXTURE2D;ComPtr<ID3D11DepthStencilView>v;if(FAILED(d->CreateDepthStencilView(r,&x,&v)))throw std::runtime_error("CreateDSV");return v;}
static ComPtr<ID3D11ShaderResourceView> makeSRV(ID3D11Device*d,ID3D11Resource*r,DXGI_FORMAT f){D3D11_SHADER_RESOURCE_VIEW_DESC x{};x.Format=f;x.ViewDimension=D3D11_SRV_DIMENSION_TEXTURE2D;x.Texture2D.MipLevels=1;ComPtr<ID3D11ShaderResourceView>v;if(FAILED(d->CreateShaderResourceView(r,&x,&v)))throw std::runtime_error("CreateSRV");return v;}
static void check(bool v,const char*s){if(!v)throw std::runtime_error(s);}
static void runCase(ID3D11Device*d,ID3D11DeviceContext*imm,DXGI_FORMAT dsvf,DXGI_FORMAT resourcef,DXGI_FORMAT depthSRVf,DXGI_FORMAT stencilSRVf,bool stencil,UINT ow,UINT oh){
 const UINT iw=7,ih=5;auto in=makeTex(d,iw,ih,resourcef,D3D11_BIND_DEPTH_STENCIL|D3D11_BIND_SHADER_RESOURCE);auto id=makeDSV(d,in.Get(),dsvf);auto ds=makeSRV(d,in.Get(),depthSRVf);ComPtr<ID3D11ShaderResourceView>ss;if(stencil)ss=makeSRV(d,in.Get(),stencilSRVf);
 auto vb=compile(kInitVS,"main","vs_5_0"),pb=compile(kInitPS,"main","ps_5_0");ComPtr<ID3D11VertexShader>vs;ComPtr<ID3D11PixelShader>ps;check(SUCCEEDED(d->CreateVertexShader(vb->GetBufferPointer(),vb->GetBufferSize(),nullptr,&vs)),"init VS");check(SUCCEEDED(d->CreatePixelShader(pb->GetBufferPointer(),pb->GetBufferSize(),nullptr,&ps)),"init PS");
 D3D11_DEPTH_STENCIL_DESC z{};z.DepthEnable=TRUE;z.DepthWriteMask=D3D11_DEPTH_WRITE_MASK_ALL;z.DepthFunc=D3D11_COMPARISON_ALWAYS;z.StencilEnable=stencil;z.StencilReadMask=255;z.StencilWriteMask=0;z.FrontFace={D3D11_STENCIL_OP_KEEP,D3D11_STENCIL_OP_KEEP,D3D11_STENCIL_OP_KEEP,D3D11_COMPARISON_ALWAYS};z.BackFace=z.FrontFace;ComPtr<ID3D11DepthStencilState>zs;check(SUCCEEDED(d->CreateDepthStencilState(&z,&zs)),"init state");
 D3D11_VIEWPORT iv{0,0,(float)iw,(float)ih,0,1};imm->RSSetViewports(1,&iv);imm->OMSetRenderTargets(0,nullptr,id.Get());imm->OMSetDepthStencilState(zs.Get(),0);imm->VSSetShader(vs.Get(),nullptr,0);imm->PSSetShader(ps.Get(),nullptr,0);imm->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
 edvr_layer_seed::Seeder s;s.init(d);check(s.ensure(d,ow,oh,dsvf),"ensure");ComPtr<ID3D11DeviceContext>def;check(SUCCEEDED(d->CreateDeferredContext(0,&def)),"deferred context");
 D3D11_TEXTURE2D_DESC sd{};sd.Width=ow;sd.Height=oh;sd.MipLevels=sd.ArraySize=1;sd.Format=resourcef;sd.SampleDesc.Count=1;sd.Usage=D3D11_USAGE_STAGING;sd.CPUAccessFlags=D3D11_CPU_ACCESS_READ;ComPtr<ID3D11Texture2D>stage;check(SUCCEEDED(d->CreateTexture2D(&sd,nullptr,&stage)),"staging");ID3D11Resource*oraw=nullptr;s.view()->GetResource(&oraw);ComPtr<ID3D11Resource>out;out.Attach(oraw);
 const UINT vals[]={0,1,5,11,15,128,255};for(UINT wanted:vals){imm->ClearDepthStencilView(id.Get(),D3D11_CLEAR_DEPTH|(stencil?D3D11_CLEAR_STENCIL:0),1,wanted);imm->Draw(3,0);check(s.record(def.Get(),ds.Get(),ss.Get(),iw,ih,0.25f,-0.25f),"record");ComPtr<ID3D11CommandList>list;check(SUCCEEDED(def->FinishCommandList(FALSE,&list)),"FinishCommandList");imm->ExecuteCommandList(list.Get(),TRUE);imm->CopyResource(stage.Get(),out.Get());D3D11_MAPPED_SUBRESOURCE m{};check(SUCCEEDED(imm->Map(stage.Get(),0,D3D11_MAP_READ,0,&m)),"Map");for(UINT y=0;y<oh;y++)for(UINT x=0;x<ow;x++){auto row=(const unsigned char*)m.pData+y*m.RowPitch;size_t off=x*(resourcef==DXGI_FORMAT_R24G8_TYPELESS?4:(resourcef==DXGI_FORMAT_R32G8X24_TYPELESS?8:4));if(stencil&&row[off+(resourcef==DXGI_FORMAT_R24G8_TYPELESS?3:4)]!=wanted){imm->Unmap(stage.Get(),0);throw std::runtime_error("stencil readback mismatch");}float f=0;if(resourcef==DXGI_FORMAT_R24G8_TYPELESS){UINT packed=row[off]|(row[off+1]<<8)|(row[off+2]<<16);f=packed/16777215.0f;}else memcpy(&f,row+off,4);int sx=(int)floor(((x+0.5f)*iw/ow)+0.25f),sy=(int)floor(((y+0.5f)*ih/oh)-0.25f);sx=(sx<0?0:sx>=int(iw)?int(iw)-1:sx);sy=(sy<0?0:sy>=int(ih)?int(ih)-1:sy);float expected=0.1f+0.8f*(0.6f*((sx+0.5f)/iw)+0.4f*((sy+0.5f)/ih));if(fabs(f-expected)>0.0002f){imm->Unmap(stage.Get(),0);throw std::runtime_error("depth address readback mismatch");}}imm->Unmap(stage.Get(),0);}
 imm->ClearDepthStencilView(id.Get(),D3D11_CLEAR_DEPTH|(stencil?D3D11_CLEAR_STENCIL:0),1,0);imm->Draw(3,0);check(s.record(def.Get(),ds.Get(),ss.Get(),iw,ih,0,0),"reuse record");ComPtr<ID3D11CommandList>reuse;check(SUCCEEDED(def->FinishCommandList(FALSE,&reuse)),"reuse Finish");imm->ExecuteCommandList(reuse.Get(),TRUE);imm->CopyResource(stage.Get(),out.Get());D3D11_MAPPED_SUBRESOURCE rm{};check(SUCCEEDED(imm->Map(stage.Get(),0,D3D11_MAP_READ,0,&rm)),"reuse Map");for(UINT y=0;y<oh;y++)for(UINT x=0;x<ow;x++){auto row=(const unsigned char*)rm.pData+y*rm.RowPitch;size_t off=x*(resourcef==DXGI_FORMAT_R24G8_TYPELESS?4:(resourcef==DXGI_FORMAT_R32G8X24_TYPELESS?8:4));if(stencil&&row[off+(resourcef==DXGI_FORMAT_R24G8_TYPELESS?3:4)]!=0){imm->Unmap(stage.Get(),0);throw std::runtime_error("reuse zero stencil mismatch");}}imm->Unmap(stage.Get(),0);
 std::printf("case dsv=%d stencil=%d specifiedStencil=%d PASS values=0,1,5,11,15,128,255 reuse-zero scale=%.3f/%.3f jitter=+0.25/-0.25\n",(int)dsvf,stencil?1:0,s.usesSpecifiedStencilRef()?1:0,(double)ow/iw,(double)oh/ih);
}
int main(int argc,char**argv){try{ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>imm;D3D_FEATURE_LEVEL fl;check(SUCCEEDED(D3D11CreateDevice(nullptr,argc>1&&strcmp(argv[1],"--hardware")==0?D3D_DRIVER_TYPE_HARDWARE:D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,&fl,&imm)),"WARP");runCase(d.Get(),imm.Get(),DXGI_FORMAT_D24_UNORM_S8_UINT,DXGI_FORMAT_R24G8_TYPELESS,DXGI_FORMAT_R24_UNORM_X8_TYPELESS,DXGI_FORMAT_X24_TYPELESS_G8_UINT,true,13,9);runCase(d.Get(),imm.Get(),DXGI_FORMAT_D24_UNORM_S8_UINT,DXGI_FORMAT_R24G8_TYPELESS,DXGI_FORMAT_R24_UNORM_X8_TYPELESS,DXGI_FORMAT_X24_TYPELESS_G8_UINT,true,7,5);runCase(d.Get(),imm.Get(),DXGI_FORMAT_D32_FLOAT_S8X24_UINT,DXGI_FORMAT_R32G8X24_TYPELESS,DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS,DXGI_FORMAT_X32_TYPELESS_G8X24_UINT,true,13,9);runCase(d.Get(),imm.Get(),DXGI_FORMAT_D32_FLOAT,DXGI_FORMAT_R32_TYPELESS,DXGI_FORMAT_R32_FLOAT,DXGI_FORMAT_UNKNOWN,false,13,9);std::puts("seed_test PASS");return 0;}catch(const std::exception&e){std::fprintf(stderr,"seed_test FAIL: %s\n",e.what());return 1;}}
