// Making a replacement shader: from the build's bytecode, and (for two callers) by compiling at runtime -- and the lessons that cost.
//
// The sun-glare fix paved this: when a draw's own vertex shader is what is
// wrong -- geometry emitted flat in screen space, a billboard basis taken
// from the camera -- no constant substitution reaches it, and the only
// honest fix is to hand that one draw a different shader. The machinery is
// small but every part of it is scar tissue:
//
//   * D3DCompile takes ELEVEN parameters. The first field build declared
//     ten, omitting ppErrorMsgs, so the compiler wrote its error-blob
//     pointer through whatever sat in the eleventh slot and the game
//     crashed at the first matched draw -- the project's first crash,
//     bought by an FFI signature nobody proof-read.
//   * The HLSL is desk-compiled before it ever ships (the scratchpad's
//     compile_variants.py). The game is never the compiler's first
//     audience.
//   * Every failure stands the swap down and lets the game draw stock. A
//     missing d3dcompiler_47.dll, a compile error, a failed CreateShader:
//     all of them mean "draw what the game would have drawn".
//   * The whole build runs inside a fault budget, because it runs on the
//     render thread at a matched draw.
//   * Fixed HLSL belongs in the build, not here: compiling in the first
//     Present delayed the intro by 18 seconds. tools/temporal_shader_build
//     compiles every fixed shader into the generated bytecode header and
//     the proxy creates them with the shaderSwapCreate* forms below.
#pragma once

#include <cstddef>

struct ID3D11DeviceContext;
struct ID3D11VertexShader;
struct ID3D11PixelShader;
struct ID3D11ComputeShader;
struct ID3D11GeometryShader;

namespace edvr {

// One preprocessor define for a compile: a name and its value, the shape
// D3DCompile's macro array wants. A zeroed entry terminates the list.
struct SwapMacro {
    const char* name;
    const char* value;
};

// Create a shader compiled into the DLL at build time (tools/temporal_shader_build,
// the generated bytecode header): the way every fixed shader of the proxy is made.
// Guarded and budgeted: a fault, a refusal or a failed create returns null, and
// the caller's contract is always "null means draw stock" (or stand down). No HLSL
// compiler is touched, on the render thread or anywhere. Every call logs one line,
// "<who>: precompiled <stage> shader <name> created (0x%08X, <ms> ms)." (or the
// refusal that stood it down), so a log says which shaders were made and how long
// each took.
ID3D11VertexShader* shaderSwapCreateVs(ID3D11DeviceContext* ctx,
                                      const void* bytecode, size_t bytecodeLen,
                                      const char* name, const char* who);
ID3D11ComputeShader* shaderSwapCreateCs(ID3D11DeviceContext* ctx,
                                      const void* bytecode, size_t bytecodeLen,
                                      const char* name, const char* who);
ID3D11PixelShader* shaderSwapCreatePs(ID3D11DeviceContext* ctx,
                                    const void* bytecode, size_t bytecodeLen,
                                    const char* name, const char* who);
// The geometry form (2026-10-07: the supercruise bars' strip shader, the first geometry shader the proxy makes): the same
// contract and the same log line, "<who>: precompiled geometry shader <name> created ...".
ID3D11GeometryShader* shaderSwapCreateGs(ID3D11DeviceContext* ctx,
                                       const void* bytecode, size_t bytecodeLen,
                                       const char* name, const char* who);

// THE RUNTIME COMPILE, vertex and pixel forms, for exactly two callers whose
// HLSL macros are the USER'S SETTINGS and so cannot be known at build time:
//   * fss_panel.cpp: EDVR_FSS_DIST, from experimental.fss_panel_distance (any
//     float from 0.2 to 3.0; the fix is off at 1.0, the default);
//   * target_sharp.cpp: EDVR_RCAS_SHARP, from the indicator's fixed RCAS
//     sharpness (experimental.target_indicator is stock, off, by default).
// These two are the only things in the proxy that load d3dcompiler_47.dll, and
// only in those opt-in configurations (LoadLibraryW on demand: the proxy has no
// static import of it, which the build's PE gate holds). The compute form was
// removed on 2026-10-01: nothing called it -- the FSS series reducer, its last
// user, has been a precompiled shader (kFssSeriesBytecode) for some time.
//
// Compile HLSL and create a vertex shader from it, or return null having
// said why in the log. `who` names the caller in those messages ("sun
// glare world", "particle billboard") so a log line is attributable
// without a stack trace. `macros` may be null; when given it must end
// with a zeroed entry.
//
// Guarded and budgeted internally: a fault here returns null rather than
// propagating, and the caller's contract is always "null means draw
// stock".
ID3D11VertexShader* shaderSwapCompileVs(ID3D11DeviceContext* ctx,
                                        const char* hlsl, size_t hlslLen,
                                        const char* entry, const char* name,
                                        const SwapMacro* macros,
                                        const char* who);

// The pixel form: ps_5_0, CreatePixelShader, the same contract -- null
// means draw stock, every failure named in the log.
ID3D11PixelShader* shaderSwapCompilePs(ID3D11DeviceContext* ctx,
                                       const char* hlsl, size_t hlslLen,
                                       const char* entry, const char* name,
                                       const SwapMacro* macros,
                                       const char* who);

}  // namespace edvr
