#pragma once

// The temporal reprojection shader. Its arithmetic mirrors
// src/common/temporal_math.h. Compiled by temporal_shader_build during the
// build; the graphics DLL consumes only its generated bytecode.
//
// Two things happen in gamma space on purpose. The blend: bright hairlines
// in linear light would dominate their neighbours' average, and a
// perceptual space is where every shipped TAA does its accumulation. And
// the history: stored as the output is, so a frame with no history to
// blend is bit-for-bit the game's own.
namespace edvr {

constexpr char kTemporalCsHlsl[] = R"HLSL(
#ifndef EDVR_TEMPORAL_DIAGNOSTICS
#define EDVR_TEMPORAL_DIAGNOSTICS 1
#endif
Texture2D<float4> S : register(t0);      // this frame, the game's own texture (or the region copied out of it)
Texture2D<float4> H : register(t1);      // the history, region-sized, on the unjittered grid
Texture2D<float> Z : register(t2);       // the scene's depth, the game's own, when the pass has it
SamplerState L : register(s0);           // bilinear, clamp
RWTexture2D<float4> O : register(u0);    // the output: region-sized in the game's format for main, and for mv's debug views the trained runtime's OUTPUT texture, which is LARGER under DLSS -- paintDebug, not O[id.xy]
RWTexture2D<float4> N : register(u1);    // the new history
RWStructuredBuffer<uint> Stats : register(u2);   // 0 rejected, 1 clipped, 2 the clips' size (luma/255, summed); then the same three per candidate, four of them; 15 pixels on the world path, 16 bright pixels, 17 bright pixels with no depth; 18-20 the registration probes on the world path (sum dx*100, sum dy*100, count) and 21-23 on the ship; 24-27 world pixels, world clipped, ship pixels, ship clipped; 28-29 unused (the depth layers, retired 2026-09-04); 30-32 the registration probes on the sky (the far plane: sum dx*100, sum dy*100, count); 33-34 the probes' sum resid.mv*100 and sum mv.mv*100 on the sky, 35-36 on the world with a depth, 37-38 on the ship; 39 pixels on a moving ship's path (tier 2, 2026-09-09); 40-45 the ships' claim by reason: 40 in a ship's footprint with a depth and not claimed, 41 of those outside the box at their depth, 42 behind the tail, 43 beyond the parts' reach, 44 the sum over 41 of (the pixel's depth less the box centre's) in decimetres (signed), 45 in a footprint with no depth
RWTexture2D<float2> MV : register(u3);   // for a trained pass: motion vectors, pixels, current -> previous
RWTexture2D<float>  ZC : register(u4);   // and the depth, copied as it is (both entries, when the mover mask wants last frame's)
Texture2D<float> ZP : register(t3);      // LAST frame's ZC, when the mover mask is on (movers.x)
Texture2D<float> UM : register(t4);      // the interface's reactive mask (ui_depth.h), folded into MK when probe.z says it is bound
Texture3D<float> BG : register(t5);      // the dominant body's occupancy grid over box0..box1 (tier 2), when tvSt.w says the body's path is on
Texture2D<float> ZS : register(t6);      // the drives' smoke's own depth (ui_depth.h, uiDepthSmokeDepth), the scene depth's size; unbound = none this frame, and reads as the far value
Texture2D<float> ZUI : register(t7);     // private UI depth; never used by game draws
Texture2D<float4> UP : register(t8);     // previous raw-raster UI colour; alpha is coverage, not opacity
Texture2D<uint> TI : register(t9);      // terrain patch index, zero outside rasterised coverage
Texture2D<float> TZ : register(t10);    // terrain depth, compared against final scene/UI depth
struct TerrainRecord { uint4 key[12]; float4 q; float4 t; float4 r[3]; };
Texture2D<float2> HC : register(t12);
struct HoloRecord { uint4 key[8]; float4 clip[3]; float4 map[3]; float4 meta; };
StructuredBuffer<HoloRecord> HR : register(t13);
Texture2D<float4> Screen : register(t14);
StructuredBuffer<TerrainRecord> TR : register(t11);
RWTexture2D<float4> UN : register(u6);   // this frame's UI evidence, separate from accumulated colour
RWTexture2D<float> MK : register(u5);    // for a trained pass: the mover mask, NVIDIA's bias-current-colour input (ONE texture: the interface's mask is folded in)
cbuffer P : register(b0) {
    int4   region;      // x0 y0 x1 y1: this eye's pixels in S (x1, y1 exclusive)
    int2   size;        // the region's size = the output's
    int2   texSize;     // S's size, for the sampler's uv
    float4 tanNow;      // l r t b this frame, jitter excluded
    float4 tanPrev;     // l r t b for the frame the history holds
    float4 jit;         // xy this frame's jitter in pixels; z 1 = filter the current sample; w the history kernel's C
    float4 dR0;         // rows of the rotation taking this frame's view
    float4 dR1;         // directions to last frame's (xyz; w unused)
    float4 dR2;
    float4 c0R0;        // the registration instrument's candidates, same
    float4 c0R1;        // shape: 0 the head's rotation alone, 1 the eyes swapped,
    float4 c0R2;        // 2 the world path's delta from the rows, 3 the
    float4 c1R0;        // head with depth as used
    float4 c1R1;
    float4 c1R2;
    float4 c2R0;
    float4 c2R1;
    float4 c2R2;
    float4 c3R0;
    float4 c3R1;
    float4 c3R2;
    float  blend;       // history weight
    float  gamma;       // clip half-width, in standard deviations
    int    haveHistory; // 0: nothing to blend, this frame goes out as it is
    int    candMask;    // bit c: candidate c has a delta this frame
    float4 knobs;       // x, z: the depth's encoding, written = x + z / metres (reversed-Z; x = 0 with no far plane); y 1 = depth bound; w the runtime's far, unused
    float4 tvUsed;      // xyz the translation term for the used delta (depth motion), w unused
    float4 tvCand;      // xyz the same for the instrument's swapped-eyes candidate
    float4 tvCam;       // xyz the translation term for the camera rows (the world path); w 1 = the world path is on
    float4 split;       // x the ship's radius in metres (nearer: the head's delta; farther and the far plane: the camera's); y the debug view (1 motion, 2 error, 3 depth); z a depth in metres for depthless pixels in a menu-like scene (0 off); w 1 = menu-like scene
    float4 fovea0;      // xy the fovea centre in output pixels, z the inner radius (px) where the periphery calming starts, w 1/(the ramp width in px)
    float4 fovea1;      // x the periphery calm strength (0..1), w 1 = the fovea is on (else no modulation)
    float4 movers;      // x 1 = the mover mask is on (ZP holds last frame's depth for this frustum); y the depth tolerance, a fraction; z the strength, how much history a masked pixel loses (0..1); w 1 = main writes ZC
    float4 probe;       // x history scale, y registration probes, z coverage bound; w bits: 1 fixed bias, 2 prior UI valid, 4 adaptive UI, 8 terrain, 16 holo, 32 screen
    float4 stR0;        // the body's path (tier 2, docs/per-object-motion.md): the composite delta's rows,
    float4 stR1;        // the camera's with the dominant body's own turn -- a station's -- in it
    float4 stR2;
    float4 tvSt;        // xyz its translation term; w 1 = the body's path is on this frame
    float4 st2R0;       // the second body's path (object_probe.h, 2026-09-09): its composite delta's rows
    float4 st2R1;
    float4 st2R2;
    float4 tv2St;       // xyz its translation term; w 1 = on this frame (its grid cells hold 128)
    float4 st3R[36];    // the stepped parts' paths (object_probe.h, 2026-09-09): twelve composite deltas, one per
    float4 tv3[12];     // multiple of the body's turn from kSteppedMin (-3) to kSteppedMax (8); w 1 = filled this frame
    float4 objects;     // x the reach in metres (for the record; the grid already carries it); y the body's near floor, metres; z a moving ship's reach around each of its parts, squared
    float4 wR0;         // the camera rows this frame, view -> world: xyz the row, w the position's component,
    float4 wR1;         // so a view-space point v (the game's, z forward) sits at R v + c in the body's frame
    float4 wR2;
    float4 box0;        // xyz the body's box, low corner (world)
    float4 box1;        // xyz ...high corner; the grid BG spans it
    float4 ships;       // x the moving ships in hand this frame, 0..8 (object_probe.h, 2026-09-09): each on the body's path with its own motion, its box its claim, no grid
    float4 shR[24];     // per ship, three rows of its composite delta (stR0..2's shape)
    float4 shTv[8];     // xyz its translation term
    float4 shBox0[8];   // xyz its box, low corner (world)
    float4 shBox1[8];   // xyz ...high corner; w unused
    float4 shDir[8];    // xyz the way the ship flies (unit, world; zero when unknown), w its tail plane: a point whose dot with xyz is under w is behind the ship -- its plume, which is not the ship's
    float4 shParts[256];   // per ship kObjectShipParts of its parts' positions (xyz, this frame's frame), shBox0[i].w of them: the ship's claim is the space within objects.z (a reach, squared) of one
    float4 shRect[8];   // per ship, its box's footprint on the image in pixels (x0 y0 x1 y1; empty when a corner is behind the eye), for the claim's counters
    float4 holoJitter; // current minus previous raster jitter; z = consecutive treated frames
};
float3 rgbToYcocg(float3 c) {
    return float3(0.25 * c.r + 0.5 * c.g + 0.25 * c.b,
                  0.5 * c.r - 0.5 * c.b,
                  -0.25 * c.r + 0.5 * c.g - 0.25 * c.b);
}
float3 ycocgToRgb(float3 y) {
    return float3(y.x + y.y - y.z, y.x + y.z, y.x - y.y - y.z);
}
// Pull q into the box along the ray from the box's centre: the standard
// AABB clip, which keeps the history's hue while bounding its distance.
float3 clipToBox(float3 mn, float3 mx, float3 q) {
    float3 c = 0.5 * (mx + mn);
    float3 e = 0.5 * (mx - mn) + 1e-5;
    float3 v = q - c;
    float3 a = abs(v / e);
    float ma = max(a.x, max(a.y, a.z));
    return ma > 1.0 ? c + v / ma : q;
}
// The history's resampling kernel through nine bilinear fetches: a
// bicubic of the B = 0 family with C from the parameters -- C = 0.5 is
// Catmull-Rom, larger C is sharper with more ringing (0.75 is a common
// "sharp bicubic"). Every frame the history is fetched at a sub-pixel
// offset, since a tracked head is never quite still, and each fetch is a
// low-pass whose losses compound through the exponential average: at a
// third of a cycle per pixel Catmull-Rom keeps about half of the
// contrast after that compounding at a 0.9 blend, and a sharper kernel
// keeps more. advanced.temporal_aa_history_sharp sets C, live.
float4 catmullRom(float2 uv, float2 tsize) {
    float C = jit.w;
    float2 sp = uv * tsize;
    float2 t1 = floor(sp - 0.5) + 0.5;
    float2 f = sp - t1;
    float2 g0 = 1.0 + f;
    float2 g3 = 2.0 - f;
    float2 w0 = C * (-g0 * g0 * g0 + 5.0 * g0 * g0 - 8.0 * g0 + 4.0);
    float2 w1 = (2.0 - C) * f * f * f + (C - 3.0) * f * f + 1.0;
    float2 h = 1.0 - f;
    float2 w2 = (2.0 - C) * h * h * h + (C - 3.0) * h * h + 1.0;
    float2 w3 = C * (-g3 * g3 * g3 + 5.0 * g3 * g3 - 8.0 * g3 + 4.0);
    float2 w12 = w1 + w2;
    float2 o12 = w2 / w12;
    float2 t0 = (t1 - 1.0) / tsize;
    float2 t3 = (t1 + 2.0) / tsize;
    float2 t12 = (t1 + o12) / tsize;
    float4 r = 0.0;
    r += H.SampleLevel(L, float2(t0.x, t0.y), 0) * w0.x * w0.y;
    r += H.SampleLevel(L, float2(t12.x, t0.y), 0) * w12.x * w0.y;
    r += H.SampleLevel(L, float2(t3.x, t0.y), 0) * w3.x * w0.y;
    r += H.SampleLevel(L, float2(t0.x, t12.y), 0) * w0.x * w12.y;
    r += H.SampleLevel(L, float2(t12.x, t12.y), 0) * w12.x * w12.y;
    r += H.SampleLevel(L, float2(t3.x, t12.y), 0) * w3.x * w12.y;
    r += H.SampleLevel(L, float2(t0.x, t3.y), 0) * w0.x * w3.y;
    r += H.SampleLevel(L, float2(t12.x, t3.y), 0) * w12.x * w3.y;
    r += H.SampleLevel(L, float2(t3.x, t3.y), 0) * w3.x * w3.y;
    return r;
}
// temporalReproject, transcribed: the pixel's direction now, rotated into
// last frame's view by the rows given, projected through last frame's
// frustum, the history fetched there. False off the image or behind the
// eye. One function, so the instrument can ask it of every candidate.
// With a translation and depth, the pixel is a POINT, not a direction:
// P = z * d (d.z = -1, so z is the view depth in metres), moved to last
// frame's eye space by delta * P + tv, then projected. Without depth (the
// far plane, or none bound) the direction alone is rotated, which is the
// rotation-only path: exact at infinity, and what v1 was everywhere.
)HLSL"
// (adjacent literals: MSVC caps one at 16 KB)
R"HLSL(
// Merge current scene depth with private smoke and UI coverage. The UI
// copy is seeded once per eye/frame; reading the latest scene here also
// lets later nearer geometry win. The game's live depth is never modified
// by these coverage passes. Reversed-Z; unbound layer SRVs read far (zero).
float zSceneAt(int2 q) {
    if((uint(probe.w+.5)&32u)!=0u) { float4 s=Screen.Load(int3(q,0));if(s.w>0)return s.z; }
    return max(max(Z.Load(int3(q, 0)), ZS.Load(int3(q, 0))), ZUI.Load(int3(q, 0)));
}
float zAt(int2 q) { return zSceneAt(q); }
// Tier 1 of docs/per-object-motion.md: the mover mask from depth
// consistency (2026-09-08). The reprojection says where this pixel's
// surface WAS if it moved with the camera alone -- at pp, at view depth
// zPred metres -- and last frame's depth copy says what actually was at
// pp. Where the two disagree the surface is either a mover (something the
// camera's vectors cannot follow: a station's rim, a ship crossing the
// view) or a disocclusion (the history at pp shows what was in front a
// frame ago), and both deserve less history: a moving edge stops trailing
// a ghost, and the far side of a pillar you move past stops showing the
// pillar. It compares against the RANGE of last frame's 3x3 around pp,
// not one texel: the jitter shifts the sample grid half a pixel between
// frames, and at a depth edge a single-texel compare fires on every
// silhouette every frame whether anything moved or not (the same reason
// the reprojection dilates). The far plane is consistent only with the
// far plane, so a pixel that is sky now where a hull was last frame -- a
// mover's trail -- is masked too. What it cannot see is a mover's
// INTERIOR at constant depth, which passes; that is the later tiers'
// work, and this is the floor under them. temporalMoverTest in
// temporal_math.h is the reference the test pins; this transcribes it.
// zPred <= 0 means the pixel has no depth now (the far plane, or none).
// `thick`: at least six of the nine texels around the pixel have a depth
// NOW. The "surface where only sky was" rule is for a hull's leading edge
// arriving over empty space; a THIN feature -- a text stroke the interface
// wrote depth under, a wire, a railing -- reprojects onto texels that had
// no depth last frame on every frame the head moves, and the rule called
// every one of them a mover (2026-09-08: the interface's text swam again
// with the mask on, the very thing ui_depth had fixed). A thin feature
// gets the range test alone.
float moverAt(float2 pp, float zPred, bool thick) {
    int2 pq = int2(round(pp));
    float zmin = 1e30;
    float zmax = 0.0;
    bool anyFar = false;
    [unroll] for (int oy = -1; oy <= 1; ++oy) {
        [unroll] for (int ox = -1; ox <= 1; ++ox) {
            int2 q = clamp(pq + int2(ox, oy), int2(0, 0), size - 1);
            float zr = ZP.Load(int3(q, 0));
            float den = zr - knobs.x;   // depth = A + B / z: z = B / (depth - A)
            if (zr <= 0.0 || den <= 0.0) {
                anyFar = true;
            } else {
                float z = knobs.z / den;
                zmin = min(zmin, z);
                zmax = max(zmax, z);
            }
        }
    }
    if (zPred <= 0.0) return anyFar ? 0.0 : 1.0;   // sky now: consistent only with sky then
    if (zmax <= 0.0) return thick ? 1.0 : 0.0;     // a surface now where only sky was: a hull's edge, not a stroke's
    float tol = movers.y;
    return (zPred < zmin * (1.0 - tol) || zPred > zmax * (1.0 + tol)) ? 1.0 : 0.0;
}
// Tier 2 of docs/per-object-motion.md (2026-09-08): the dominant rigid
// body's own motion -- a station's turn, read from the game's instance
// pool by object_probe.cpp in the world frame the camera rows share -- as
// a SECOND reprojection for the world path's pixels, taken by the pixels
// that are the body's. Which pixels those are is a question of GEOMETRY,
// not of matching: the first build chose per pixel by a 3x3 match against
// last frame's image, and took under one pixel in a hundred, because the
// history it matched against was accumulated at the camera's landing --
// its smear is centred exactly there, and a comparison against it
// confirms the camera every time; and a station ten kilometres off turns
// its parts a tenth of a pixel a frame, under any test's reach. So the
// pixel's own depth places it in the world, and the body's occupancy grid
// (its parts' positions, each marking the cells within a reach of it) says
// whether that place is the body's. No tag and no draw classification,
// and no comparison; the pool's slots are re-ordered every frame (its
// fourth flight), so nothing per instance can be trusted from one frame to
// the next, but a turn shared by a thousand parts and the space they fill
// can, and this is all it needs.
int insideBody(float3 d, float z) {
)HLSL"
R"HLSL(
    // The view-space point, the game's way round (z forward), into the
    // world by this frame's camera rows, into the grid by the box.
    float3 vg = float3(d.x * z, d.y * z, -d.z * z);
    float3 w = float3(dot(wR0.xyz, vg), dot(wR1.xyz, vg), dot(wR2.xyz, vg)) +
               float3(wR0.w, wR1.w, wR2.w);
    float3 u = (w - box0.xyz) / max(box1.xyz - box0.xyz, 1e-3);
    if (any(u < 0.0) || any(u >= 1.0)) return 0;
    // kObjectGrid cells a side (object_probe.h): 255 the body's, 128 the
    // second body's (ObjectMotion::body2), 64..75 a stepped part's multiple
    // of the body's turn plus 67 (kSteppedCellBase), 0 the space between.
    return int(BG.Load(int4(int3(u * 128.0), 0)) * 255.0 + 0.5);
}
)HLSL"
R"HLSL(
// The moving ships (object_probe.h, 2026-09-09): compact bodies with a box
// each and no grid. The nearest whose box holds the pixel's world point
// claims it, and the boxes are tested BEFORE the dominant body's grid: a
// ship crossing the slot sits inside the station's cells too, and took the
// station's turn there until the ships had paths of their own.
int insideShip(float3 d, float z) {
    float3 vg = float3(d.x * z, d.y * z, -d.z * z);
    float3 w = float3(dot(wR0.xyz, vg), dot(wR1.xyz, vg), dot(wR2.xyz, vg)) +
               float3(wR0.w, wR1.w, wR2.w);
    int n = int(ships.x);
    for (int i = 0; i < n; ++i) {
        if (any(w < shBox0[i].xyz) || any(w > shBox1[i].xyz)) continue;
        // Behind the tail (shDir says): the plume, which is particles
        // left in space and not the ship's -- "rectangular artifacts in
        // the smoke trail", the ships' second flight, 2026-09-09.
        if (dot(w, shDir[i].xyz) < shDir[i].w) continue;
        // ...and within the reach of one of its parts: the hull, not the
        // box's empty corners nor a wall the ship skims.
        int np = int(shBox0[i].w);
        int base = i * 32;   // kObjectShipParts
        bool hit = false;
        for (int j = 0; j < np && !hit; ++j) {
            float3 e = w - shParts[base + j].xyz;
            if (dot(e, e) < objects.z) hit = true;
        }
        if (hit) return i;
    }
    return -1;
}
// For the objects view: the ship, if any, whose box this pixel's ray
// passes through at some depth -- the ship's footprint on the image, so
// a pixel in it that was not claimed can say why.
int shipFootprint(float3 d) {
    float3 o = float3(wR0.w, wR1.w, wR2.w);
    float3 vg = float3(d.x, d.y, -d.z);
    float3 r = float3(dot(wR0.xyz, vg), dot(wR1.xyz, vg), dot(wR2.xyz, vg));
    int n = int(ships.x);
    for (int i = 0; i < n; ++i) {
        // A box the eye sits in -- a ship within thirty metres, or the
        // player's own parts taken as one -- is nobody's footprint: every
        // ray hits it, and the fourth flight's sky read teal whole.
        if (all(o >= shBox0[i].xyz) && all(o <= shBox1[i].xyz)) continue;
        float3 inv = 1.0 / (abs(r) > 1e-9 ? r : 1e-9);
        float3 t1 = (shBox0[i].xyz - o) * inv;
        float3 t2 = (shBox1[i].xyz - o) * inv;
        float3 tlo = min(t1, t2);
        float3 thi = max(t1, t2);
        float tmin = max(max(tlo.x, tlo.y), tlo.z);
        float tmax = min(min(thi.x, thi.y), thi.z);
        if (tmax >= max(tmin, 0.0)) return i;
    }
    return -1;
}
// For the claim's counters (the registration line says): the ship whose
// footprint rectangle holds this pixel, and why that ship refused the
// pixel's world point -- 1 outside its box at this depth, 2 behind its
// tail, 3 beyond its parts' reach -- and the view depth of its box centre.
int shipRect(float2 p) {
    int n = int(ships.x);
    for (int i = 0; i < n; ++i) {
        if (p.x >= shRect[i].x && p.y >= shRect[i].y && p.x <= shRect[i].z && p.y <= shRect[i].w) return i;
    }
    return -1;
}
int shipRefusal(float3 d, float z, int i) {
    float3 vg = float3(d.x * z, d.y * z, -d.z * z);
    float3 w = float3(dot(wR0.xyz, vg), dot(wR1.xyz, vg), dot(wR2.xyz, vg)) +
               float3(wR0.w, wR1.w, wR2.w);
    if (any(w < shBox0[i].xyz) || any(w > shBox1[i].xyz)) return 1;
    if (dot(w, shDir[i].xyz) < shDir[i].w) return 2;
    return 3;
}
float shipCentreZ(int i) {
    float3 c = 0.5 * (shBox0[i].xyz + shBox1[i].xyz) - float3(wR0.w, wR1.w, wR2.w);
    return dot(float3(wR0.z, wR1.z, wR2.z), c);
}
// bodyPixel's twin for ship i.
bool shipPixel(int i, float3 d, float z, out float2 pp, out float zp) {
    float3 dp = float3(dot(shR[i * 3].xyz, d), dot(shR[i * 3 + 1].xyz, d), dot(shR[i * 3 + 2].xyz, d)) * z +
                shTv[i].xyz;
    zp = -dp.z;
    pp = 0.0;
    if (dp.z >= -1e-6) return false;
    float xt = dp.x / -dp.z;
    float yt = dp.y / -dp.z;
    pp.x = (xt - tanPrev.x) / (tanPrev.y - tanPrev.x) * float(size.x) - 0.5;
    pp.y = (tanPrev.w - yt) / (tanPrev.w - tanPrev.z) * float(size.y) - 0.5;
    return pp.x >= 0.0 && pp.y >= 0.0 && pp.x <= float(size.x) - 1.0 && pp.y <= float(size.y) - 1.0;
}
// The interface's pixel, by ui_depth's coverage mask when it is bound
// (probe.z), as far as the body's path is concerned. The mask's value is
// NVIDIA's reactive strength, and its QUANTUM'S PARITY is ui_depth's word
// on the path (floorBuffer there): even rides a turning body's path where
// the pixel sits on it -- a stroke drawn AT the surface, the docking
// hologram over the hub's drum -- and odd keeps the camera's path at the
// pixel's depth: the interface proper, the holo material's target markers,
// the target-time sprite, and a flight HUD stroke's core that floats over
// the scene at the scene's depth. The station's target brackets are the
// last kind: they track the station's centre and do not turn with it, and
// before 2026-09-09 (when a band of values said which, and every stroke
// fell in the riding band) they rode the station's spin where they
// crossed its silhouette and kept the camera's path over the sky beside
// it -- "shimmering on just one side".
// UI history decisions compare UI evidence, independently of fixed bias.
// Flags in probe.w: 1 fixed bias, 2 previous evidence valid, 4 capture/adapt.
// A one-pixel neighbourhood tolerates raster jitter and subpixel movement.
float4 uiEvidence(int2 q) {
    q = clamp(q, int2(0,0), size - 1);
    uint kind = uint(UM.Load(int3(q,0))*255.0+0.5) & 3u;
    float marked = probe.z != 0.0 && (kind == 1u || kind == 2u) ? 1.0 : 0.0;
    // Evidence lives on the raw raster grid, just like its coverage. Adding
    // jitter only to colour paired a glyph's mask with a neighbouring pixel.
    return marked != 0.0 ? float4(S.Load(int3(region.xy + q, 0)).rgb, 1.0) : 0.0;
}
float adaptiveUiReactive(int2 q, float2 previous) {
    uint flags = uint(probe.w + 0.5);
    if ((flags & 4u) == 0u) return 0.0;
    float4 current = uiEvidence(q);
    if ((flags & 2u) == 0u) return current.a;
    if (any(previous < 0) || any(previous > size-1)) return current.a;
    float4 old = UP.SampleLevel(L, (previous + .5) / float2(size), 0);
    if (current.a == 0.0 && old.a == 0.0) return 0.0;
    float3 lo = 1e10, hi = -1e10;
    float nowCount = 0.0;
    [unroll] for (int y=-1; y<=1; ++y) [unroll] for (int x=-1; x<=1; ++x) {
        float4 c = uiEvidence(q + int2(x,y));
        if (c.a != 0.0) { lo = min(lo,c.rgb); hi = max(hi,c.rgb); nowCount += 1.0; }
    }
    if (nowCount == 0.0 || old.a == 0.0) return 1.0;
    // Test the history actually reprojected here. Taking the best of nine
    // old colours let a black neighbour excuse stale white text on a dark
    // marked panel. Alpha is validity, so normalize the bilinear footprint
    // before comparing; unmarked background is not UI colour evidence.
    float3 e = max(max(lo-old.rgb/old.a,old.rgb/old.a-hi),0.0);
    float error = max(e.x,max(e.y,e.z));
    return saturate((error - 0.03) / 0.17);
}
bool uiCovered(int2 q) {
    if (probe.z == 0.0) return false;
    uint v = uint(UM.Load(int3(q, 0)) * 255.0 + 0.5);
    return (v & 1u) != 0u;
}
// Follow the actual nearby panel transform, including pool quantization
// and animation. Exact coverage depth rejects later foreground geometry.
// Offset is jitter for native TAA's output grid, zero for DLSS's input grid.
bool holoPixel(float2 p, float2 offset, out float2 pp, out float zp) {
    pp=0; zp=0;
    if((uint(probe.w+.5)&16u)==0u || holoJitter.z==0) return false;
    int2 q=region.xy+int2(round(p+offset));
    float2 cov=HC.Load(int3(q,0)); uint index=uint(cov.x+.5);
    if(index==0 || index>128) return false;
    if(cov.y<=knobs.x || abs(zSceneAt(q)-cov.y)>abs(cov.y)*1e-6) return false;
    HoloRecord r=HR[index-1]; if(r.meta.w!=1) return false;
    if(r.key[3].w==1 ? uiCovered(q) : !uiCovered(q)) return false;
    float z=knobs.z/(cov.y-knobs.x);
    float2 ndc=(p+offset+region.xy+.5)/r.meta.yz*float2(2,-2)+float2(-1,1);
    if(r.key[3].w==3) {
        // Sprites intentionally draw over nearer geometry. Coverage stores
        // the selected scene depth for visibility validation, while motion
        // must use the sprite's actual plane (captured local Y=0), not that
        // foreground depth or the VS's forced Z=W.
        float3 normal=cross(r.clip[2].xyz,r.clip[0].xyz);
        float den=dot(normal,float3(ndc,1));
        if(den==0) return false;
        z=dot(normal,float3(r.clip[0].w,r.clip[1].w,r.clip[2].w))/den;
        if(z<=0 || !isfinite(z)) return false;
    }
    float4 current=float4(ndc*z,z,1);
    float3 before=float3(dot(r.map[0],current),dot(r.map[1],current),dot(r.map[2],current));
    if(before.z<=0 || !all(isfinite(before))) return false;
    pp=(before.xy/before.z*float2(.5,-.5)+.5)*r.meta.yz-.5-region.xy+holoJitter.xy-offset;
    zp=before.z;
    return all(isfinite(pp));
}
// Exact terrain coverage only. The patch transform is in DirectX view
// space (+Z forward); the pass's rays use the runtime's -Z convention.
bool terrainPixel(float2 p, float3 d, out float2 pp, out float zp) {
    pp=0; zp=0;
    if ((uint(probe.w+0.5)&8u)==0u) return false;
    int2 q=region.xy+int2(p);
    uint index=TI.Load(int3(q,0));
    if (knobs.y==0 || index==0 || index>512 || uiCovered(q)) return false;
    float zraw=TZ.Load(int3(q,0)), scene=zSceneAt(q);
    if (zraw<=knobs.x || abs(scene-zraw)>abs(zraw)*0.00001) return false;
    TerrainRecord rec=TR[index-1];
    if (rec.t.w!=1) return false;
    float z=knobs.z/(zraw-knobs.x);
    float4 here=float4(d.xy*z,z,1);
    float3 before=float3(dot(rec.r[0],here),dot(rec.r[1],here),dot(rec.r[2],here));
    if (before.z<=0 || !all(isfinite(before))) return false;
    zp=before.z;
    pp.x=(before.x/zp-tanPrev.x)/(tanPrev.y-tanPrev.x)*size.x-0.5;
    pp.y=(tanPrev.w-before.y/zp)/(tanPrev.w-tanPrev.z)*size.y-0.5;
    return true;
}
// Where this pixel's surface was last frame if it moved with the body:
// the camera's path composed with the body's turn. False when it lands
// behind the eye or off the image.
bool bodyPixelRows(float3 r0, float3 r1, float3 r2, float3 tv, float3 d, float z, out float2 pp, out float zp) {
    float3 dp = float3(dot(r0, d), dot(r1, d), dot(r2, d)) * z + tv;
    zp = -dp.z;
    pp = 0.0;
    if (dp.z >= -1e-6) return false;
    float xt = dp.x / -dp.z;
    float yt = dp.y / -dp.z;
    pp.x = (xt - tanPrev.x) / (tanPrev.y - tanPrev.x) * float(size.x) - 0.5;
    pp.y = (tanPrev.w - yt) / (tanPrev.w - tanPrev.z) * float(size.y) - 0.5;
    return pp.x >= 0.0 && pp.y >= 0.0 && pp.x <= float(size.x) - 1.0 && pp.y <= float(size.y) - 1.0;
}
bool bodyPixel(float3 d, float z, out float2 pp, out float zp) {
    return bodyPixelRows(stR0.xyz, stR1.xyz, stR2.xyz, tvSt.xyz, d, z, pp, zp);
}
// The second body's (object_probe.h, 2026-09-09): its own rows.
bool bodyPixel2(float3 d, float z, out float2 pp, out float zp) {
    return bodyPixelRows(st2R0.xyz, st2R1.xyz, st2R2.xyz, tv2St.xyz, d, z, pp, zp);
}
// A stepped part's (object_probe.h): the composite delta for its cell's
// multiple of the body's turn, v the cell's byte (64..75).
bool steppedPixel(int v, float3 d, float z, out float2 pp, out float zp) {
    int e = v - 64;
    return bodyPixelRows(st3R[e * 3].xyz, st3R[e * 3 + 1].xyz, st3R[e * 3 + 2].xyz, tv3[e].xyz, d, z, pp, zp);
}
)HLSL"
R"HLSL(
// zPred: the predicted view depth of this pixel's surface in last frame's
// eye space, metres, for the mover mask -- 0 when the pixel took no real
// depth (the far plane, the menu's assumed depth, no depth bound).
// depthN: how many of the 3x3 around the pixel have a depth now, for the
// mask's thick-or-thin verdict (moverAt says); 0 when no depth was read.
bool fetchHistoryT(float2 p, float3 r0, float3 r1, float3 r2, float3 tv,
                   bool useDepth, bool allowWorld, out uint world, out float2 mvOut,
                   out float zPred, out uint depthN, out float3 hy) {
    float3 d;
    d.x = tanNow.x + (p.x + 0.5) / float(size.x) * (tanNow.y - tanNow.x);
    d.y = tanNow.w - (p.y + 0.5) / float(size.y) * (tanNow.w - tanNow.z);
    d.z = -1.0;
    float3 dp = float3(dot(r0, d), dot(r1, d), dot(r2, d));
    world = 0;
    mvOut = 0.0;
    zPred = 0.0;
    depthN = 0;
    hy=0;
    if(allowWorld && (uint(probe.w+.5)&32u)!=0u) {
        float4 s=Screen.Load(int3(region.xy+int2(round(p+jit.xy)),0));
        if(s.w>1)return false;
        if(s.w==1) {
            float2 previous=p+s.xy+holoJitter.xy;
            if(any(previous<0) || any(previous>float2(size)-1))return false;
            mvOut=previous-p;
            hy=rgbToYcocg(catmullRom((previous+.5)/float2(size),float2(size)).rgb);
            return true;
        }
    }
    float zBody = 0.0;   // the depth the body's path would take; 0 = not this pixel's question
    // The world/ship split: the ship's own things (the cockpit, the hull)
    // move with the head's delta; everything farther than split.x metres,
    // and the far plane, moves with the game's CAMERA -- the head and the
    // ship together, the rows the instrument's candidate 2 reads -- which
    // is what a turning ship needs for its skybox and a station (the Pimax
    // flight of 2026-09-04 saw both smear; the review's F6). The split
    // needs a depth to classify by, so it runs only with one bound.
    bool worldOn = allowWorld && tvCam.w != 0.0 && split.x > 0.0 && knobs.y != 0.0;
    if (useDepth || worldOn) {
        // The NEAREST depth of the 3x3, not the pixel's own: at the edge of
        // a near thing against a far one the pixel's own depth is either,
        // and a history fetched by the far one at a text stroke's edge is
        // the "underwater" the second depth flight saw at rest. With the
        // nearest, the edge follows the thing in front, which is the
        // standard dilation every velocity-based filter does.
        float zr = 0.0;
        [unroll] for (int oy = -1; oy <= 1; ++oy) {
            [unroll] for (int ox = -1; ox <= 1; ++ox) {
                int2 q = clamp(int2(p) + int2(ox, oy), int2(0, 0), size - 1);
                float zs = zSceneAt(region.xy + q);
                zr = max(zr, zs);
                if (zs > 0.0) ++depthN;
            }
        }
        float den = zr - knobs.x;   // depth = A + B / z: z = B / (depth - A)
        bool far = zr <= 0.0 || den <= 0.0;
        float z = far ? 0.0 : knobs.z / den;
        if (worldOn && (far || z > split.x)) {
            world = 1;
            dp = float3(dot(c2R0.xyz, d), dot(c2R1.xyz, d), dot(c2R2.xyz, d));
            if (!far) {
                dp = dp * z + tvCam.xyz;
                zPred = -dp.z;
                zBody = (tvSt.w != 0.0 || ships.x != 0.0) ? z : 0.0;
            }
        } else if (useDepth && !far) {
            dp = dp * z + tv;
            zPred = -dp.z;
            // Inside the ship split but past the body's own floor
            // (objects.y): a hangar's walls and floor turn with the station
            // until the ship is latched to the pad, while the ship's own
            // hull, within the floor as seen from the seat, does not
            // (2026-09-09). The claim below decides by the grid as usual.
            zBody = ((tvSt.w != 0.0 || ships.x != 0.0) && z > objects.y) ? z : 0.0;
        } else if (useDepth && far && split.w != 0.0 && split.z > 0.0) {
            // A menu-like scene's depthless pixels (the main menu's hangar
            // wall reads no depth and reprojected as the far plane, so it
            // detached under head translation): an assumed depth, the
            // player's choice, better than infinity for a wall a few metres
            // off. advanced.temporal_aa_menu_metres.
            dp = dp * split.z + tv;
        }
    }
    hy = 0.0;
    if (dp.z >= -1e-6) return false;
    float xt = dp.x / -dp.z;
    float yt = dp.y / -dp.z;
    float2 pp;
    pp.x = (xt - tanPrev.x) / (tanPrev.y - tanPrev.x) * float(size.x) - 0.5;
    pp.y = (tanPrev.w - yt) / (tanPrev.w - tanPrev.z) * float(size.y) - 0.5;
    if (pp.x < 0.0 || pp.y < 0.0 || pp.x > float(size.x) - 1.0 ||
        pp.y > float(size.y) - 1.0) {
        return false;
    }
    // (A per-pixel "rest snap" once sat here, fetching the history at its
    // own texel under a fraction of a pixel of motion. Gone since
    // 2026-09-04: each frame re-registers by the frame's delta, not by the
    // accumulated error, so the motion it suppressed accumulated into a lag
    // of blend / (1 - blend) times that motion, about 0.7 px on slowly
    // drifting distant content, and differed across the image. The rest
    // lock, experimental.shimmer_rest, holds the pose at rest instead.)
    // The body's path, where this pixel took the world path with a depth
    // and that depth places it in the body (insideBody says). world = 2
    // marks it for the counters and the debug view; the fetch below is
    // the same either way.
    if (zBody > 0.0 && !uiCovered(region.xy + int2(p))) {
        // A moving ship's box first (insideShip says why), the body's
        // grid after; world = 3 marks a ship's pixel.
        int si = ships.x != 0.0 ? insideShip(d, zBody) : -1;
        bool taken = false;
        if (si >= 0) {
            float2 ppS;
            float zpS;
            if (shipPixel(si, d, zBody, ppS, zpS)) {
                pp = ppS;
                zPred = zpS;
                world = 3;
                taken = true;
            }
        }
        // A ship's pixel whose prediction fell off the image is offered to
        // the body's grid as before the ships (the review of 2026-09-09).
        if (!taken && tvSt.w != 0.0) {
            // 1 the body's cells, 2 the second body's: its own path when
            // one is in hand, else the camera's (the body's would be wrong
            // there by twice the turn). world = 4 marks the second body's.
            int inb = insideBody(d, zBody);
            float2 ppB;
            float zpB;
            if (inb == 128) {
                if (tv2St.w != 0.0 && bodyPixel2(d, zBody, ppB, zpB)) {
                    pp = ppB;
                    zPred = zpB;
                    world = 4;
                }
            } else if (inb >= 64 && inb < 76) {
                // A stepped part's cell (object_probe.h): its own multiple
                // of the body's turn this frame. world = 5 marks it. Counted
                // straight into Stats (48 the cell hit, 49 the path refused):
                // the flight of 18:00 stamped cells on every frame and no
                // pixel took the path, and the counts say which half failed.
#if EDVR_TEMPORAL_DIAGNOSTICS
                InterlockedAdd(Stats[48], 1u);
#endif
                if (tv3[0].w != 0.0 && steppedPixel(inb, d, zBody, ppB, zpB)) {
                    pp = ppB;
                    zPred = zpB;
                    world = 5;
                } else {
#if EDVR_TEMPORAL_DIAGNOSTICS
                    InterlockedAdd(Stats[49], 1u);
#endif
                }
            } else if (inb == 255 && bodyPixel(d, zBody, ppB, zpB)) {
                pp = ppB;
                zPred = zpB;
                world = 2;
            }
        }
    }
    float2 terrainP; float terrainZ;
    if (allowWorld && terrainPixel(p,d,terrainP,terrainZ)) {
        pp=terrainP; zPred=terrainZ; world=1;
        if (any(pp<0) || any(pp>float2(size)-1)) return false;
    }
    float2 holoP; float holoZ;
    if (allowWorld && holoPixel(p,jit.xy,holoP,holoZ)) {
        pp=holoP; zPred=holoZ; world=0;
        if(any(pp<0) || any(pp>float2(size)-1)) return false;
    }
    mvOut = pp - p;
    hy = rgbToYcocg(catmullRom((pp + 0.5) / float2(size), float2(size)).rgb);
    return true;
}
bool fetchHistory(float2 p, float3 r0, float3 r1, float3 r2, out float3 hy) {
    uint wd = 0;
    float2 mvd = 0.0;
    float zd = 0.0;
    uint dn = 0;
    return fetchHistoryT(p, r0, r1, r2, float3(0.0, 0.0, 0.0), false, false, wd, mvd, zd, dn, hy);
}
// How far a clip moved the history, in luma, as a count of 1/255ths: a
// nudge on a text edge is a few, a history that landed somewhere else
// entirely is tens. Summed per reading, it separates the two where a
// count of clipped pixels cannot.
uint clipSize(float3 hc, float3 hy) {
    return uint(saturate(abs(hc.x - hy.x)) * 255.0 + 0.5);
}
)HLSL"
// (adjacent literals: MSVC caps one at 16 KB)
R"HLSL(
#if EDVR_TEMPORAL_DIAGNOSTICS
groupshared uint gCount[48];
#endif
// A debug view's pixel, painted into the OUTPUT rather than at this
// thread's own index.
//
// The mv entry is dispatched over the RENDER size, because that is what it
// computes; its debug views are painted into O, which on this path is the
// trained runtime's OUTPUT texture. Those two are the same size under DLAA
// and are not under DLSS, and writing O[id.xy] put the whole frame in the
// top-left corner -- the view "skewed up and left" at 2x, and every debug
// view under DLSS wrong since the trained path was written (Sean,
// 2026-09-08). So each render pixel paints the block of output pixels that
// belongs to it: [ceil(id*s), ceil((id+1)*s)), which is exactly the set of
// output pixels that map back to this one, so the block tiles the output
// with no seam and no overlap. Four each way covers every ratio a trained
// runtime offers (ultra performance is three); at 1:1 it is one write, as
// before.
void paintDebug(uint2 idx, int2 sz, float3 c) {
    uint ow = 0, oh = 0;
    O.GetDimensions(ow, oh);
    if (ow == 0 || oh == 0 || sz.x <= 0 || sz.y <= 0) return;
    float2 s = float2(float(ow) / float(sz.x), float(oh) / float(sz.y));
    int2 lo = int2(ceil(float2(idx) * s));
    int2 hi = int2(ceil((float2(idx) + 1.0) * s));
    [unroll] for (int dy = 0; dy < 4; ++dy) {
        [unroll] for (int dx = 0; dx < 4; ++dx) {
            int2 q = lo + int2(dx, dy);
            if (q.x < hi.x && q.y < hi.y && q.x < int(ow) && q.y < int(oh)) {
                O[q] = float4(c, 1.0);
            }
        }
    }
}
// The motion vectors for a trained pass (DLAA): the same reprojection
// the history fetch does, written out instead of used -- the pixel's
// position last frame minus its position now, in render pixels, which
// is DLSS's convention with a scale of one (pinned on the desk by the
// conventions rig in tools/smoke, 2026-09-04). Off the image or behind
// the eye: no motion. The depth goes beside it, copied as the game wrote
// it (reversed-Z, told to the runtime as such). The world/ship split is
// the history fetch's, transcribed, and the counts feed the registration
// line the way main's do.
groupshared float mvDepthTile[100];
[numthreads(8, 8, 1)]
void mv(uint3 id : SV_DispatchThreadID, uint gi : SV_GroupIndex) {
    int2 local = int2(gi & 7u, gi >> 3u);
    int2 origin = int2(id.xy) - local;
    for (uint k = gi; k < 100; k += 64) {
        int2 q = clamp(origin + int2(k % 10, k / 10) - 1, int2(0,0), size - 1);
        mvDepthTile[k] = zSceneAt(region.xy + q);
    }
    GroupMemoryBarrierWithGroupSync();
#if EDVR_TEMPORAL_DIAGNOSTICS
    if (gi < 48) gCount[gi] = 0;
    GroupMemoryBarrierWithGroupSync();
#endif
    // Three counters, not forty. This pass writes 15, 16 and 17 and no
    // others, and a forty-element local array costs forty registers of
    // occupancy on a dispatch that covers the whole eye.
    uint count15 = 0, count16 = 0, count17 = 0, count28 = 0, count29 = 0, count39 = 0, count46 = 0, count47 = 0;
    uint count40 = 0, count41 = 0, count42 = 0, count43 = 0, count45 = 0;
    int count44 = 0;
    if (id.x < (uint)size.x && id.y < (uint)size.y) {
        float2 p = float2(id.xy);
        float3 d;
        if ((uint(probe.w + 0.5) & 4u) != 0u) UN[id.xy] = uiEvidence(int2(id.xy));
        d.x = tanNow.x + (p.x + 0.5) / float(size.x) * (tanNow.y - tanNow.x);
        d.y = tanNow.w - (p.y + 0.5) / float(size.y) * (tanNow.w - tanNow.z);
        d.z = -1.0;
        float3 dp = float3(dot(dR0.xyz, d), dot(dR1.xyz, d), dot(dR2.xyz, d));
        float zraw = mvDepthTile[(local.y + 1) * 10 + local.x + 1];
        float zPred = 0.0;   // for the mover mask: the surface's predicted depth last frame, 0 = none
        uint depthN = 0;     // ...and how many of the 3x3 have a depth now (thick or thin)
        float zBody = 0.0;   // the depth the body's path would take; 0 = not this pixel's question
        bool farPx = true;   // the objects view's reasons: no depth here...
        float zPx = 0.0;     // ...and the depth otherwise
        if (knobs.y != 0.0) {
            float zr = 0.0;
            [unroll] for (int oy = -1; oy <= 1; ++oy) {
                [unroll] for (int ox = -1; ox <= 1; ++ox) {
                    float zs = mvDepthTile[(local.y + 1 + oy) * 10 + local.x + 1 + ox];
                    zr = max(zr, zs);
                    if (zs > 0.0) ++depthN;
                }
            }
            float den = zr - knobs.x;   // depth = A + B / z: z = B / (depth - A)
            bool far = zr <= 0.0 || den <= 0.0;
            float z = far ? 0.0 : knobs.z / den;
            farPx = far;
            zPx = z;
            bool worldOn = tvCam.w != 0.0 && split.x > 0.0;
            if (worldOn && (far || z > split.x)) {
                count15 = 1;
                dp = float3(dot(c2R0.xyz, d), dot(c2R1.xyz, d), dot(c2R2.xyz, d));
                if (!far) {
                    dp = dp * z + tvCam.xyz;
                    zPred = -dp.z;
                    zBody = (tvSt.w != 0.0 || ships.x != 0.0) ? z : 0.0;
                }
            } else if (!far) {
                dp = dp * z + tvUsed.xyz;
                zPred = -dp.z;
                zBody = ((tvSt.w != 0.0 || ships.x != 0.0) && z > objects.y) ? z : 0.0;   // past the body's floor (fetchHistoryT says)
            } else if (split.w != 0.0 && split.z > 0.0) {
                dp = dp * split.z + tvUsed.xyz;   // the menu's assumed depth (fetchHistoryT says)
            }
            float luma = rgbToYcocg(S.Load(int3(region.xy + int2(p), 0)).rgb).x;
            if (luma > 0.6) {
                count16 = 1;
                if (zraw <= 0.0) count17 = 1;
            }
        }
        float2 motion = 0.0;
        float mover = 0.0;
        if (dp.z < -1e-6) {
            float xt = dp.x / -dp.z;
            float yt = dp.y / -dp.z;
            float2 pp;
            pp.x = (xt - tanPrev.x) / (tanPrev.y - tanPrev.x) * float(size.x) - 0.5;
            pp.y = (tanPrev.w - yt) / (tanPrev.w - tanPrev.z) * float(size.y) - 0.5;
            motion = pp - p;
            // The body's path for the pixels the body's grid claims, the
            // interface's excepted.
            if (zBody > 0.0 && !uiCovered(region.xy + int2(p))) {
                int si = ships.x != 0.0 ? insideShip(d, zBody) : -1;
                bool taken = false;
                if (si >= 0) {
                    float2 ppS;
                    float zpS;
                    if (shipPixel(si, d, zBody, ppS, zpS)) {
                        pp = ppS;
                        motion = pp - p;
                        zPred = zpS;
                        count39 = 1;
                        taken = true;
                    }
                }
                if (!taken && tvSt.w != 0.0) {
                    int inb = insideBody(d, zBody);   // 128 = the second body's cells, 64..75 a stepped part's
                    float2 ppB;
                    float zpB;
                    if (inb == 128) {
                        if (tv2St.w != 0.0 && bodyPixel2(d, zBody, ppB, zpB)) {
                            pp = ppB;
                            motion = pp - p;
                            zPred = zpB;
                            count46 = 1;
                        }
                    } else if (inb >= 64 && inb < 76) {
                        if (tv3[0].w != 0.0 && steppedPixel(inb, d, zBody, ppB, zpB)) {
                            pp = ppB;
                            motion = pp - p;
                            zPred = zpB;
                            count47 = 1;
                        }
                    } else if (inb == 255 && bodyPixel(d, zBody, ppB, zpB)) {
                        pp = ppB;
                        motion = pp - p;
                        zPred = zpB;
                        count29 = 1;
                    }
                }
            }
            float2 terrainP; float terrainZ;
            if (terrainPixel(p,d,terrainP,terrainZ)) {
                pp=terrainP; motion=pp-p; zPred=terrainZ;
            }
            float2 holoP; float holoZ;
            if(holoPixel(p,0,holoP,holoZ)) {
                pp=holoP; motion=pp-p; zPred=holoZ;
            }
            // The ships' claim, counted (Stats 40-45, the registration
            // line): a pixel in a ship's footprint the ship did not claim,
            // and why.
            if (ships.x != 0.0 && count39 == 0) {
                int fr = shipRect(p);
                if (fr >= 0) {
                    if (farPx) {
                        count45 = 1;
                    } else if (zBody > 0.0 && !uiCovered(region.xy + int2(p))) {
                        count40 = 1;
                        int why = shipRefusal(d, zBody, fr);
                        if (why == 1) {
                            count41 = 1;
                            // Clamped to a hundred metres either way: a footprint over a
                            // station two kilometres behind the ship summed past 2^31 in
                            // one frame (the review of 2026-09-09).
                            count44 = int(round(clamp((zBody - shipCentreZ(fr)) * 10.0, -1000.0, 1000.0)));
                        } else if (why == 2) {
                            count42 = 1;
                        } else {
                            count43 = 1;
                        }
                    }
                }
            }
            // The mover mask, where the prediction lands on last frame's
            // image (off it NVIDIA has no history to bias against anyway).
            if (movers.x != 0.0 && pp.x >= 0.0 && pp.y >= 0.0 &&
                pp.x <= float(size.x) - 1.0 && pp.y <= float(size.y) - 1.0) {
                mover = moverAt(pp, zPred, depthN >= 6);
                if (mover != 0.0) count28 = 1;
            }
        }
        if((uint(probe.w+.5)&32u)!=0u) {
            float4 s=Screen.Load(int3(region.xy+int2(p),0));
            if(s.w>0) {
                motion=s.w!=2?s.xy+holoJitter.xy:float2(size)*2;zraw=s.z;
                // The eye-space prediction above is not source-scene depth.
                // Do not apply its mover rejection to screen pixels.
                mover=0;
            }
        }
        MV[id.xy] = motion;
        // Combine detected UI changes and the optional fixed UI bias.
        // World-mover rejection must not override stable marked UI.
        uint mark = probe.z != 0.0 ? uint(UM.Load(int3(id.xy,0))*255.0+0.5) : 0u;
        uint kind = mark & 3u;
        float ui = (kind == 3u || (uint(probe.w + 0.5) & 1u) != 0u) ? float(mark >> 2u)/63.0 : 0.0;
        float adaptive = adaptiveUiReactive(int2(id.xy), p + motion - holoJitter.xy);
        bool uiHere = kind == 1u || kind == 2u;
        MK[id.xy] = max(adaptive, uiHere ? ui : max(ui, mover * movers.z));
        // The registration probes on the trained path (2026-09-08): main's
        // 5x5 luma SAD search, transcribed, against NVIDIA's PREVIOUS output
        // -- the history as the runtime accumulated it, bound at t1 in place
        // of the pass's own and probe.x times the render size (1 under DLAA,
        // 2 under DLSS at half), so the window steps probe.x texels to span
        // the same render pixels. Until this ran, no line in the log had
        // measured the vectors NVIDIA is handed against what it kept: the
        // probes lived in the own pass and the flown path was NVIDIA's, so a
        // station approach that "looked soft on every moving surface" had no
        // number behind it. Same classes and slots as main's, so the
        // registration line reads the same either way.
#if EDVR_TEMPORAL_DIAGNOSTICS
        if (probe.y != 0.0 && dp.z < -1e-6 && (id.x & 63) == 16 && (id.y & 63) == 16 &&
            id.x >= 8 && id.y >= 8 && id.x + 8 < (uint)size.x && id.y + 8 < (uint)size.y) {
            int2 ci = int2(id.xy);
            float curL[25];
            float meanL = 0.0;
            int kk = 0;
            [unroll] for (int wy = -2; wy <= 2; ++wy) {
                [unroll] for (int wx = -2; wx <= 2; ++wx) {
                    curL[kk] = rgbToYcocg(S.Load(int3(region.xy + ci + int2(wx, wy), 0)).rgb).x;
                    meanL += curL[kk];
                    ++kk;
                }
            }
            meanL /= 25.0;
            float varL = 0.0;
            [unroll] for (int jj = 0; jj < 25; ++jj) varL += (curL[jj] - meanL) * (curL[jj] - meanL);
            const bool sky = count15 != 0 && knobs.y != 0.0 && zraw <= 0.0;
            if (varL > (sky ? 0.0025 : 0.0225)) {
                float2 pp2 = p + motion;
                int2 pq = int2(round(pp2));
                float bestSad = 1e9;
                int2 best = int2(0, 0);
                for (int sy = -4; sy <= 4; ++sy) {
                    for (int sx = -4; sx <= 4; ++sx) {
                        float sad = 0.0;
                        int mm = 0;
                        [unroll] for (int wy2 = -2; wy2 <= 2; ++wy2) {
                            [unroll] for (int wx2 = -2; wx2 <= 2; ++wx2) {
                                int2 q = clamp(pq + int2(sx + wx2, sy + wy2), int2(0, 0), size - 1);
                                // The history at this render pixel's CENTRE, bilinear:
                                // H is probe.x times the render size, so the uv is the
                                // render pixel's own, and at 2x that is the mean of the
                                // four output texels the pixel covers. Picking one
                                // texel put every reading a quarter of a render pixel
                                // to the right and down (the first DLSS flight of the
                                // probe, 2026-09-08: +0.2 px on every class at rest).
                                float2 huv = (float2(q) + 0.5) / float2(size);
                                sad += abs(curL[mm] - rgbToYcocg(H.SampleLevel(L, huv, 0).rgb).x);
                                ++mm;
                            }
                        }
                        if (sad < bestSad) {
                            bestSad = sad;
                            best = int2(sx, sy);
                        }
                    }
                }
                float2 resid = float2(best) + (float2(pq) - pp2);
                uint base = sky ? 30u : (count15 != 0 ? 18u : 21u);
#if EDVR_TEMPORAL_DIAGNOSTICS
                InterlockedAdd(Stats[base], asuint(int(round(resid.x * 100.0))));
                InterlockedAdd(Stats[base + 1], asuint(int(round(resid.y * 100.0))));
                InterlockedAdd(Stats[base + 2], 1u);
#endif
                uint base2 = sky ? 33u : (count15 != 0 ? 35u : 37u);
#if EDVR_TEMPORAL_DIAGNOSTICS
                InterlockedAdd(Stats[base2], asuint(int(round(dot(resid, motion) * 100.0))));
                InterlockedAdd(Stats[base2 + 1], uint(round(dot(motion, motion) * 100.0)));
#endif
            }
        }
#endif
)HLSL"
R"HLSL(
        // The motion view on the trained path: painted into the output in
        // NVIDIA's place (the pass skips its evaluation that frame).
        if (split.y == 1.0) {
            paintDebug(id.xy, size,
                       float3(saturate(0.5 + motion.x / 16.0), saturate(0.5 + motion.y / 16.0),
                              count15 != 0 ? 1.0 : 0.0));
        } else if (split.y == 4.0) {
            // The mover view: the mask white over the frame dimmed, so a
            // screenshot in the slot shows the rim's edges and nothing else.
            // Painted the way main's views are, into the output's own size.
            float3 dim = S.Load(int3(region.xy + int2(p), 0)).rgb * 0.25;
            paintDebug(id.xy, size, mover != 0.0 ? float3(1.0, 1.0, 1.0) : dim);
        } else if (split.y == 5.0) {
            // The objects view, by reason (2026-09-09, for reading an eye
            // dump off the desk): white where the body's path was taken;
            // where the world path had it and the body's path is on, blue
            // for no depth (the far plane), green for the interface's mask,
            // red for a depth that lands outside the body's cells, yellow
            // for one inside them whose prediction fell off the image; the
            // frame dimmed elsewhere (the ship's path, or the body off).
            float3 dim = S.Load(int3(region.xy + int2(p), 0)).rgb * 0.25;
            float3 o5 = dim;
            if (count39 != 0) {
                o5 = float3(0.0, 1.0, 1.0);   // cyan: a moving ship's path
            } else if (count29 != 0) {
                o5 = float3(1.0, 1.0, 1.0);
            } else if (count46 != 0) {
                o5 = float3(0.7, 0.7, 0.7);   // grey: the second body's path (object_probe.h)
            } else if (count47 != 0) {
                o5 = float3(1.0, 0.55, 0.0);   // orange: a stepped part on its own multiple of the turn (object_probe.h)
            } else if (count15 != 0 && (tvSt.w != 0.0 || ships.x != 0.0)) {
                // In a moving ship's footprint but not the ship's: teal with
                // no depth at all, magenta with a depth the claim refused
                // (outside the box at that depth, behind the tail, or beyond
                // its parts' reach).
                int fs = ships.x != 0.0 ? shipFootprint(d) : -1;
                if (farPx) o5 = fs >= 0 ? float3(0.0, 0.5, 0.5) : float3(0.0, 0.3, 1.0);
                else if (uiCovered(region.xy + int2(p))) o5 = float3(0.0, 1.0, 0.0);
                else if (fs >= 0) o5 = float3(1.0, 0.0, 1.0);
                else if (insideBody(d, zPx) == 0) o5 = float3(1.0, 0.0, 0.0);
                else o5 = float3(1.0, 1.0, 0.0);
            }
            paintDebug(id.xy, size, o5);
        } else if (split.y == 3.0) {
            float zs3 = zSceneAt(region.xy + int2(p));
            float3 o3;
            if (knobs.y == 0.0) {
                o3 = float3(0.25, 0.0, 0.25);
            } else if (zs3 > 0.0) {
                float m3 = knobs.z / (zs3 - knobs.x);
                float g3 = saturate(1.0 - log2(max(m3, 0.5)) / 8.0);
                o3 = g3.xxx;
            } else {
                o3 = float3(1.0, 0.0, 1.0);
            }
            paintDebug(id.xy, size, o3);
        }
        ZC[id.xy] = knobs.y != 0.0 ? zraw : 0.0;
    }
#if EDVR_TEMPORAL_DIAGNOSTICS
    if (count15 != 0) InterlockedAdd(gCount[15], count15);
    if (count16 != 0) InterlockedAdd(gCount[16], count16);
    if (count17 != 0) InterlockedAdd(gCount[17], count17);
    if (count28 != 0) InterlockedAdd(gCount[28], count28);
    if (count29 != 0) InterlockedAdd(gCount[29], count29);
    if (count46 != 0) InterlockedAdd(gCount[46], count46);
    if (count47 != 0) InterlockedAdd(gCount[47], count47);
    if (count39 != 0) InterlockedAdd(gCount[39], count39);
    if (count40 != 0) InterlockedAdd(gCount[40], count40);
    if (count41 != 0) InterlockedAdd(gCount[41], count41);
    if (count42 != 0) InterlockedAdd(gCount[42], count42);
    if (count43 != 0) InterlockedAdd(gCount[43], count43);
    if (count44 != 0) InterlockedAdd(gCount[44], asuint(count44));
    if (count45 != 0) InterlockedAdd(gCount[45], count45);
    GroupMemoryBarrierWithGroupSync();
#endif
    // Only the counters that moved. A group whose counters are all zero --
    // which is nearly every group, since these count rare classes of pixel
    // -- used to pay forty global atomics onto forty contended addresses
    // regardless. At the Crystal Super's size that is 290,512 groups an
    // eye, so 11.6 million atomic adds an eye and 23 million a frame, for
    // a set of numbers that only a log line reads.
#if EDVR_TEMPORAL_DIAGNOSTICS
    if (gi < 48 && gCount[gi] != 0) InterlockedAdd(Stats[gi], gCount[gi]);
#endif
}
)HLSL"
// (adjacent literals: MSVC caps one at 16 KB)
R"HLSL(
[numthreads(8, 8, 1)]
void main(uint3 id : SV_DispatchThreadID, uint gi : SV_GroupIndex) {
#if EDVR_TEMPORAL_DIAGNOSTICS
    if (gi < 48) gCount[gi] = 0;
    GroupMemoryBarrierWithGroupSync();
#endif
    uint count[48] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    if (id.x < (uint)size.x && id.y < (uint)size.y) {
        float2 p = float2(id.xy);
        int2 ci = int2(id.xy);
        if ((uint(probe.w + 0.5) & 4u) != 0u) UN[id.xy] = uiEvidence(ci);
        // Foveation-aware periphery (docs/performance.md feature 6, the
        // sharp periphery only): toward the frame's edge the history's
        // WEIGHT is eased down and the fallback sample is blurred a little
        // more. A lighter history cuts the motion smear (a heavier one
        // smears -- the 2026-09-05 field lesson); the wider Gaussian holds
        // the flicker down spatially without the lag a heavier history
        // adds. Mild, because with a fixed centre the player looks straight
        // at the periphery whenever the eyes move; the ramp starts at the
        // fovea's edge (outside the blend band) and reaches full strength at
        // the farthest frame corner. ecc is exactly 0 when the fovea is off
        // (fovea1.w == 0), so the full-frame pass is unchanged (blend >= 0.5
        // never reaches the 0.40 floor at ecc 0).
        float ecc = 0.0;
        if (fovea1.w != 0.0) {
            float dist = length(p - fovea0.xy);
            ecc = saturate((dist - fovea0.z) * fovea0.w) * fovea1.x;
        }
        float blEff = blend - ecc * 0.30;                // history: LIGHTER toward the edge
        if (blEff < 0.40) blEff = 0.40;
        float gEff = gamma;                              // clamp unchanged
        float curK = 2.29 / (1.0 + ecc * 1.5);           // the fallback Gaussian widens (spatial low-pass), mildly
        // This frame's sample and its neighbourhood, in one pass over the
        // 3x3 around the pixel. The sample the game rendered at q sits at
        // q - jit on the unjittered grid, so each is weighted by its
        // distance from THIS pixel's centre there: exp(-2.29 d^2), a
        // Gaussian of sigma 0.47 px, UE4's filter for the same job. Two
        // The blend uses the filtered value, so a pixel whose history is
        // rejected shows a spatially settled sample rather than the raw
        // one hopping by the jitter. The neighbourhood's moments are NOT
        // weighted the same way: the sixth build tried that, the box
        // narrowed to the filter's width, the clip fired on a third of
        // the pixels at rest by hair-widths, and the picture shimmered
        // faintly everywhere (measured 2026-09-03: 35% clipped by 0.3/255
        // with the head still, against 11% by 0.5 before). The plain 3x3
        // it is. At 3096 wide before a 1.5x resolve the filter's
        // softening is a third of an output pixel; the sharpen recovers
        // the rest. advanced.temporal_aa_current = raw gives the point
        // sample back for an A/B.
        float4 cur = 0.0;
        float wsum = 0.0;
        float3 m1 = 0.0;
        float3 m2 = 0.0;
        float msum = 0.0;
        [unroll] for (int dy = -1; dy <= 1; ++dy) {
            [unroll] for (int dx = -1; dx <= 1; ++dx) {
                int2 q = clamp(ci + int2(dx, dy), int2(0, 0), size - 1);
                float4 sq = S.Load(int3(region.xy + q, 0));
                float2 dpos = float2(dx, dy) - jit.xy;
                float w = jit.z != 0.0 ? exp(-curK * dot(dpos, dpos))
                                       : ((dx == 0 && dy == 0) ? 1.0 : 0.0);
                float wm = 1.0;
                cur += sq * w;
                wsum += w;
                float3 s = rgbToYcocg(sq.rgb);
                m1 += s * wm;
                m2 += s * s * wm;
                msum += wm;
            }
        }
        cur /= max(wsum, 1e-6);
        // The bright pixels, and the bright pixels with no depth behind
        // them: HUD text the game draws without a depth write takes the
        // rotation-only path and cannot register under head translation
        // (the review of 2026-09-04, H5, believed; this counts it).
        {
            float lumaC = rgbToYcocg(S.Load(int3(region.xy + ci, 0)).rgb).x;
            if (lumaC > 0.6) {
                count[16] = 1;
                if (knobs.y != 0.0 && zAt(region.xy + ci) <= 0.0) count[17] = 1;
            }
        }
        m1 /= msum;
        m2 /= msum;
        float3 sigma = sqrt(max(m2 - m1 * m1, 0.0));
        float3 boxMin = m1 - gEff * sigma;
        float3 boxMax = m1 + gEff * sigma;
        float3 outc = cur.rgb;
        bool used = false;
        uint worldTaken = 0;
        float2 mvUsed = 0.0;
        float errUsed = 0.0;
        float mover = 0.0;
        if (haveHistory != 0) {
            float3 hy;
            float zPred = 0.0;
            uint depthN = 0;
            if (fetchHistoryT(p, dR0.xyz, dR1.xyz, dR2.xyz, tvUsed.xyz,
                              knobs.y != 0.0 && tvUsed.w != 0.0, true, worldTaken, mvUsed, zPred,
                              depthN, hy)) {
                if (worldTaken != 0) count[15] = 1;
                if (worldTaken == 2) count[29] = 1;   // the body's path taken
                if (worldTaken == 4) count[46] = 1;   // the second body's
                if (worldTaken == 5) count[47] = 1;   // a stepped part's
                if (worldTaken == 3) count[39] = 1;   // a moving ship's
                // The mover mask (moverAt says): a masked pixel keeps less
                // of its history, by the strength -- at 1 it is the fresh
)HLSL"
R"HLSL(
                // frame alone, spatially settled by the filter above.
                uint uiKind = probe.z != 0.0 ? uint(UM.Load(int3(ci,0))*255.0+0.5)&3u : 0u;
                if (movers.x != 0.0 && uiKind != 1u && uiKind != 2u) {
                    mover = moverAt(p + mvUsed, zPred, depthN >= 6);
                    if (mover != 0.0) {
                        count[28] = 1;
                        blEff *= 1.0 - movers.z;
                    }
                }
                errUsed = saturate(abs(hy.x - rgbToYcocg(cur.rgb).x) * 4.0);
                blEff *= 1.0 - adaptiveUiReactive(int2(round(p+jit.xy)), p + mvUsed + jit.xy - holoJitter.xy);
                float3 hc = clipToBox(boxMin, boxMax, hy);
                if (any(abs(hc - hy) > 1e-4)) {
                    count[1] = 1;
                    count[2] = clipSize(hc, hy);
                }
                // The used delta's clip share per class: the world path's
                // pixels and the ship's, since the two are registered by
                // different deltas and one number hid the other.
                if (worldTaken != 0) {
                    count[24] = 1;
                    if (count[1] != 0) count[25] = 1;
                } else {
                    count[26] = 1;
                    if (count[1] != 0) count[27] = 1;
                }
                outc = lerp(cur.rgb, ycocgToRgb(hc), blEff);
                used = true;
            }
            // The registration instrument: what each candidate would have
            // fetched, judged by the same clip, counted and not used. The
            // candidates: 0 the head's rotation alone, 2 the world path's
            // delta from the game's view rows, 3 the head with depth as
            // used, 1 the same with the other eye's translation. Up to four
            // pixel while it runs.
            [unroll] for (int c = 0; c < 4; ++c) {
                if ((candMask & (1 << c)) == 0) continue;
                float3 r0 = c == 0 ? c0R0.xyz : (c == 1 ? c1R0.xyz : (c == 2 ? c2R0.xyz : c3R0.xyz));
                float3 r1 = c == 0 ? c0R1.xyz : (c == 1 ? c1R1.xyz : (c == 2 ? c2R1.xyz : c3R1.xyz));
                float3 r2 = c == 0 ? c0R2.xyz : (c == 1 ? c1R2.xyz : (c == 2 ? c2R2.xyz : c3R2.xyz));
                // Candidate 2 is the world path's delta from the game's view
                // rows, judged rotation-only; 3 is the head with depth as
                // used for the ship's own pixels; 1 is 3 again with the
                // OTHER eye's translation, which is the whole test of
                // whether the depth textures are assigned to the right
                // eyes -- so it must reproject with depth exactly as 3
                // does, or it collapses into a copy of candidate 0 and
                // measures nothing.
                float3 tvc = c == 1 ? tvCand.xyz : tvUsed.xyz;
                bool depthC = knobs.y != 0.0 && (c == 3 || c == 1);
                float3 h;
                uint wc = 0;
                float2 mvc = 0.0;
                float zc = 0.0;
                uint dnc = 0;
                if (!fetchHistoryT(p, r0, r1, r2, tvc, depthC, false, wc, mvc, zc, dnc, h)) {
                    count[3 + c * 3] = 1;
                } else {
                    float3 hc2 = clipToBox(boxMin, boxMax, h);
                    if (any(abs(hc2 - h) > 1e-4)) {
                        count[4 + c * 3] = 1;
                        count[5 + c * 3] = clipSize(hc2, h);
                    }
                }
            }
        }
        // The registration probes: on a 64-pixel grid, where the frame has
        // texture, the history's best match within 4 px of the predicted
        // position by a 5x5 luma SAD. The mean offset per class -- the
        // world path, the ship -- is the used reprojection's systematic
        // error in pixels, which no clip share can give: a steady offset
        // that follows the motion is a lag or a scale, noise averages to
        // zero, and the jitter's sub-pixel offset is in every probe and
        // averages out too. Signed: (+2, 0) means the content sat two
        // pixels further right in the history than the prediction said.
        if (used && (id.x & 63) == 16 && (id.y & 63) == 16 && id.x >= 8 && id.y >= 8 &&
            id.x + 8 < (uint)size.x && id.y + 8 < (uint)size.y) {
            float curL[25];
            float meanL = 0.0;
            int kk = 0;
            [unroll] for (int wy = -2; wy <= 2; ++wy) {
                [unroll] for (int wx = -2; wx <= 2; ++wx) {
                    curL[kk] = rgbToYcocg(S.Load(int3(region.xy + ci + int2(wx, wy), 0)).rgb).x;
                    meanL += curL[kk];
                    ++kk;
                }
            }
            meanL /= 25.0;
            float varL = 0.0;
            [unroll] for (int jj = 0; jj < 25; ++jj) varL += (curL[jj] - meanL) * (curL[jj] - meanL);
            // Three classes: the sky (the far plane, whose Milky Way is soft,
            // so its texture bar is lower), the world with a depth (a station,
            // whose own rotation is in no vector and shows here), the ship.
            const bool sky = worldTaken != 0 && knobs.y != 0.0 && zAt(region.xy + ci) <= 0.0;
            if (varL > (sky ? 0.0025 : 0.0225)) {
                float2 pp = p + mvUsed;
                int2 pq = int2(round(pp));
                float bestSad = 1e9;
                int2 best = int2(0, 0);
                for (int sy = -4; sy <= 4; ++sy) {
                    for (int sx = -4; sx <= 4; ++sx) {
                        float sad = 0.0;
                        int mm = 0;
                        [unroll] for (int wy2 = -2; wy2 <= 2; ++wy2) {
                            [unroll] for (int wx2 = -2; wx2 <= 2; ++wx2) {
                                int2 q = clamp(pq + int2(sx + wx2, sy + wy2), int2(0, 0), size - 1);
                                sad += abs(curL[mm] - rgbToYcocg(H.Load(int3(q, 0)).rgb).x);
                                ++mm;
                            }
                        }
                        if (sad < bestSad) {
                            bestSad = sad;
                            best = int2(sx, sy);
                        }
                    }
                }
                float2 resid = float2(best) + (float2(pq) - pp);
                uint base = sky ? 30u : (worldTaken != 0 ? 18u : 21u);
#if EDVR_TEMPORAL_DIAGNOSTICS
                InterlockedAdd(Stats[base], asuint(int(round(resid.x * 100.0))));
                InterlockedAdd(Stats[base + 1], asuint(int(round(resid.y * 100.0))));
                InterlockedAdd(Stats[base + 2], 1u);
#endif
                // The match against the prediction's own motion, for a
                // least-squares scale: with resid = k * mv the true motion
                // was (1 + k) times the vector, k = sum(resid.mv) /
                // sum(mv.mv) over the class. A signed mean cancels over a
                // head that turns both ways; this does not.
                uint base2 = sky ? 33u : (worldTaken != 0 ? 35u : 37u);
#if EDVR_TEMPORAL_DIAGNOSTICS
                InterlockedAdd(Stats[base2], asuint(int(round(dot(resid, mvUsed) * 100.0))));
                InterlockedAdd(Stats[base2 + 1], uint(round(dot(mvUsed, mvUsed) * 100.0)));
#endif
            }
        }
        if (!used) count[0] = 1;
        float3 o = saturate(outc);
        N[id.xy] = float4(o, 1.0);
        // This frame's depth, kept for next frame's mover mask (movers.w):
        // the trained path's mv entry writes the same copy for NVIDIA.
        if (movers.w != 0.0) ZC[id.xy] = zAt(region.xy + ci);
        // The debug views (advanced.temporal_aa_debug): the history keeps
        // accumulating as normal, only what leaves changes. motion paints
        // the used reprojection -- +x red, +y green, around mid-grey with
        // 16 px to the rail -- and the world path in blue; error paints
        // how far the fetched history sat from this frame's sample, in
        // luma, four times over. A skybox that leads or trails its true
        // motion shows as a colour that disagrees with the ship's turn.
        if (split.y == 1.0) {
            o = float3(saturate(0.5 + mvUsed.x / 16.0), saturate(0.5 + mvUsed.y / 16.0),
                       worldTaken != 0 ? 1.0 : 0.0);
        } else if (split.y == 2.0) {
            o = errUsed.xxx;
        } else if (split.y == 4.0) {
            // The mover view: the mask white over the frame dimmed.
            o = mover != 0.0 ? float3(1.0, 1.0, 1.0) : cur.rgb * 0.25;
        } else if (split.y == 5.0) {
            // The objects view: the pixels that took the body's path.
            o = worldTaken == 2 ? float3(1.0, 1.0, 1.0)
              : worldTaken == 4 ? float3(0.7, 0.7, 0.7)   // the second body's path grey
              : worldTaken == 5 ? float3(1.0, 0.55, 0.0)  // a stepped part's path orange
              : worldTaken == 3 ? float3(0.0, 1.0, 1.0) : cur.rgb * 0.25;   // a moving ship's path cyan
        } else if (split.y == 3.0) {
            // The depth view: where each pixel's depth comes from -- the
            // scene's in grey by distance (near bright, log scale to
            // 256 m), none in magenta, no depth bound at all in dark
            // purple. HUD text shows magenta: it has no depth of its own
            // and reprojects by what is behind it.
            float zs3 = zSceneAt(region.xy + ci);
            if (knobs.y == 0.0) {
                o = float3(0.25, 0.0, 0.25);
            } else if (zs3 > 0.0) {
                float m3 = knobs.z / (zs3 - knobs.x);
                float g3 = saturate(1.0 - log2(max(m3, 0.5)) / 8.0);
                o = g3.xxx;
            } else {
                o = float3(1.0, 0.0, 1.0);
            }
        }
        O[id.xy] = float4(o, cur.a);
    }
    // One atomic per group per counter, not per pixel -- and none at all
    // for a counter that did not move, which is most of them in most
    // groups.
    [unroll] for (int k = 0; k < 48; ++k) {
#if EDVR_TEMPORAL_DIAGNOSTICS
        if (count[k] != 0) InterlockedAdd(gCount[k], count[k]);
#endif
    }
#if EDVR_TEMPORAL_DIAGNOSTICS
    GroupMemoryBarrierWithGroupSync();
    if (gi < 48 && gCount[gi] != 0) InterlockedAdd(Stats[gi], gCount[gi]);
#endif
}
)HLSL";

}  // namespace edvr
