// Fixed core shaders: former runtime call contracts remain independently checked below.
#pragma once
static std::vector<Variant> coreVariants(const std::string& core) {
    static const std::string screen = edvr::screenMotionPsSource(core.c_str());
    static const std::string corona = "#define CORONA_MOTION 1\n" + std::string(edvr::kSmokeDepthHlsl);
    return {
        {"kUiLayerCompositeBytecode", "ui_layer_composite_cs", "main", nullptr, {}, false, edvr::kUiLayerCompositeHlsl, "cs_5_0"},
        {"kUiLayerCoverageVsBytecode", "ui_layer_coverage_vs", "main", nullptr, {}, false, edvr::kUiLayerCoverageVsHlsl, "vs_5_0"},
        {"kUiLayerCoveragePsBytecode", "ui_layer_coverage_ps", "main", nullptr, {}, false, edvr::kUiLayerCoveragePsHlsl, "ps_5_0"},
        {"kUiSeedVsBytecode", "ui_layer_seed", "main", nullptr, {}, false, edvr::kUiSeedVs, "vs_5_0"},
        {"kUiSeedDepthStencilBytecode", "ui_layer_seed", "main", nullptr, {}, false, edvr::kUiSeedPsDepthStencil, "ps_5_0"},
        {"kUiSeedDepthOnlyBytecode", "ui_layer_seed", "main", nullptr, {}, false, edvr::kUiSeedPsDepthOnly, "ps_5_0"},
        {"kUiSeedDepthNoStencilBytecode", "ui_layer_seed", "main", nullptr, {}, false, edvr::kUiSeedPsDepthNoStencil, "ps_5_0"},
        {"kUiDepthPanelBytecode", "ui_depth_panel_ps", "main", nullptr, {}, false, edvr::kPanelDepthHlsl, "ps_5_0"},
        {"kUiDepthHudBytecode", "ui_depth_hud_ps", "main", nullptr, {}, false, edvr::kHudDepthHlsl, "ps_5_0"},
        {"kUiDepthScreenBytecode", "ui_depth_screen_ps", "main", nullptr, {}, false, edvr::kScreenDepthHlsl, "ps_5_0"},
        {"kUiDepthHoloBytecode", "ui_depth_holo_ps", "main", nullptr, {}, false, edvr::kHoloDepthHlsl.c_str(), "ps_5_0"},
        {"kUiDepthSmokeBytecode", "ui_depth_smoke_ps", "main", nullptr, {}, false, edvr::kSmokeDepthHlsl, "ps_5_0"},
        {"kUiDepthSpriteBytecode", "ui_depth_sprite_ps", "main", nullptr, {}, false, edvr::kSpriteDepthHlsl, "ps_5_0"},
        {"kUiDepthRingBytecode", "ring_coverage_ps", "main", nullptr, {}, false, edvr::kRingCoverage, "ps_5_0"},
        {"kUiDepthOrbitalBytecode", "orbital_coverage_ps", "main", nullptr, {}, false, edvr::kOrbitalCoveragePs, "ps_5_0"},
        {"kUiDepthHoloUnlitBytecode", "ui_depth_holo_unlit_ps", "main", nullptr, {}, false, edvr::kHoloUnlitDepthHlsl.c_str(), "ps_5_0"},
        {"kUiHoloResolveVsBytecode", "ui_depth_holo_resolve_vs", "main", nullptr, {}, false, edvr::kHoloResolveVsHlsl, "vs_5_0"},
        {"kUiHoloResolvePsBytecode", "ui_depth_holo_resolve_ps", "main", nullptr, {}, false, edvr::kHoloResolvePsHlsl, "ps_5_0"},
        {"kUiHoloNearLightBytecode", "ui_depth_holo_near_light_cs", "main", nullptr, {}, false, edvr::kHoloNearLightCsHlsl, "cs_5_0"},
        {"kUiHoloMarkerReticleBytecode", "ui_depth_holo_marker_reticle_ps", "main", nullptr, {}, false, edvr::kHoloMarkerReticleDepthPsHlsl, "ps_5_0"},
        {"kUiOrbitalCoverageVsBytecode", "orbital coverage", "main", nullptr, {}, false, edvr::kOrbitalCoverageVs, "vs_5_0"},
        {"kUiSmokeCoronaBytecode", "ui_depth_corona_ps", "main", nullptr, {}, false, corona.c_str(), "ps_5_0"},
        {"kNightExteriorBytecode", "night exterior", "main", nullptr, {}, false, edvr::kNightExteriorCs, "cs_5_0"},
        {"kScreenMotionBytecode", "screen motion", "main", nullptr, {}, false, screen.c_str(), "ps_5_0"},
        {"kWeaponMotionVsBytecode", "weapon motion", "main", nullptr, {}, false, edvr::kWeaponMotionVs, "vs_5_0"},
        {"kWeaponMotionPsBytecode", "weapon motion", "main", nullptr, {}, false, edvr::kWeaponMotionPs, "ps_5_0"},
        {"kWeaponIdentityBytecode", "weapon identity", "main", nullptr, {}, false, edvr::kWeaponIdentityCs, "cs_5_0"},
        {"kPlanetCoverageBytecode", "planet coverage", "main", nullptr, {}, false, edvr::kPlanetCoverageHlsl, "ps_5_0"},
        {"kTemporalFoveaBytecode", "temporal_fovea_cs", "fovea", nullptr, {}, false, edvr::kFoveaCsHlsl, "cs_5_0"},
        {"kTemporalDownBytecode", "temporal_down_cs", "down", nullptr, {}, false, edvr::kDownCsHlsl, "cs_5_0"},
    };
}

static std::vector<LegacyContract> coreLegacyContracts() {
    return {
        {"ui_layer_composite_cs", "main", "cs_5_0", nullptr, 0x237EEBB920BC9015ull},
        {"ui_layer_coverage_vs", "main", "vs_5_0", nullptr, 0xC0A9BDF65E71A8DCull},
        {"ui_layer_coverage_ps", "main", "ps_5_0", nullptr, 0xA12E6D166D50BDA1ull},
        {"ui_layer_seed", "main", "vs_5_0", nullptr, 0xCC059AB4FCFA26BCull},
        {"ui_layer_seed", "main", "ps_5_0", nullptr, 0x6204DC7B89FEB995ull},
        {"ui_layer_seed", "main", "ps_5_0", nullptr, 0xB4E15991FFB22394ull},
        {"ui_layer_seed", "main", "ps_5_0", nullptr, 0xD5CC09085C1E6153ull},
        {"ui_depth_panel_ps", "main", "ps_5_0", nullptr, 0x1D917A3C0D1713B4ull},
        {"ui_depth_hud_ps", "main", "ps_5_0", nullptr, 0xBF9B75865E9F9E09ull},
        {"ui_depth_screen_ps", "main", "ps_5_0", nullptr, 0xF5002C2A63664430ull},
        {"ui_depth_holo_ps", "main", "ps_5_0", nullptr, 0x5F77A92009D3B66Cull},
        {"ui_depth_smoke_ps", "main", "ps_5_0", nullptr, 0xC85041994740A190ull},
        {"ui_depth_sprite_ps", "main", "ps_5_0", nullptr, 0x6C9C1A2DEE91E117ull},
        {"ring_coverage_ps", "main", "ps_5_0", nullptr, 0xF5BF48ECBB489351ull},
        {"orbital_coverage_ps", "main", "ps_5_0", nullptr, 0x8BF4DF22F42F0472ull},
        {"ui_depth_holo_unlit_ps", "main", "ps_5_0", nullptr, 0xBF9BF9DF94D733DBull},
        {"ui_depth_holo_resolve_vs", "main", "vs_5_0", nullptr, 0x20645D8AD5F63813ull},
        {"ui_depth_holo_resolve_ps", "main", "ps_5_0", nullptr, 0xA0BA9F47CC37A5BAull},
        {"ui_depth_holo_near_light_cs", "main", "cs_5_0", nullptr, 0xB1BF8BF2F8942B44ull},
        {"ui_depth_holo_marker_reticle_ps", "main", "ps_5_0", nullptr, 0x6EE982850EC312BBull},
        {"orbital coverage", "main", "vs_5_0", nullptr, 0xF436926B85A7DA3Full},
        {"ui_depth_corona_ps", "main", "ps_5_0", nullptr, 0x0372DA1389F36CE0ull},
        {"night exterior", "main", "cs_5_0", nullptr, 0x28453D6A0BAB0138ull},
        {"screen motion", "main", "ps_5_0", nullptr, 0x422615E32B4FE096ull},
        {"weapon motion", "main", "vs_5_0", nullptr, 0x7232767DAC4ADBD4ull},
        {"weapon motion", "main", "ps_5_0", nullptr, 0xF948E51A2E036952ull},
        {"weapon identity", "main", "cs_5_0", nullptr, 0x10E05DE79500471Dull},
        {"planet coverage", "main", "ps_5_0", nullptr, 0xAC1BF855670403D4ull},
        {"temporal_fovea_cs", "fovea", "cs_5_0", nullptr, 0xE05D6C08CF233167ull},
        {"temporal_down_cs", "down", "cs_5_0", nullptr, 0x446A3A4BBB585FFAull},
    };
}
