#pragma once
#include <filesystem>
#include <fstream>
#include <iterator>
#include <map>
#include "../../src/d3d11/device_hook.h"
namespace edvr {
// The rig has no hooked device. Its layout fixture supplies the same owned POD
// metadata that the production CreateInputLayout hook retains.
inline bool flatPacketInputLayout(ID3D11InputLayout*,std::vector<FlatPacketInputElement>& out) {out.clear();return false;}
inline bool flatPacketGeometryShaderData(ID3D11GeometryShader*,std::vector<uint8_t>& out){out.clear();return false;}
}
#include "../../src/d3d11/flat_draw_packet_capture.h"
namespace flatPacketTest {
inline std::map<void*,uint64_t> hashes;
inline std::map<std::pair<char,uint64_t>,std::vector<uint8_t>> shaders;
inline uint64_t hash(void* object){const auto it=hashes.find(object);return it==hashes.end()?0:it->second;}
inline bool lookup(char stage,uint64_t hash,const uint8_t** data,size_t* size){const auto it=shaders.find({stage,hash});if(it==shaders.end())return false;*data=it->second.data();*size=it->second.size();return true;}
inline std::vector<BYTE> file(const std::filesystem::path& path){std::ifstream in(path,std::ios::binary);return {std::istreambuf_iterator<char>(in),std::istreambuf_iterator<char>()};}
}
inline int flatDrawPacketGpuTests(ID3D11Device* device,ID3D11DeviceContext* ctx) {
    using Microsoft::WRL::ComPtr;using edvr::FlatDrawPacketCapture;using namespace flatPacketTest;
    ctx->ClearState();int failed=0;auto expect=[&](bool ok,const char* why){if(!ok){std::printf("FAIL: flat draw packet %s\n",why);++failed;}};
    auto compile=[&](const char* source,const char* profile){ComPtr<ID3DBlob> b,e;expect(SUCCEEDED(D3DCompile(source,strlen(source),nullptr,nullptr,nullptr,"main",profile,0,0,&b,&e)),"fixture compiles");return b;};
    auto vsCode=compile("float4 main(uint i:SV_VertexID):SV_Position{float2 p[3]={float2(-1,-1),float2(3,-1),float2(-1,3)};return float4(p[i%3],.5,1);}","vs_5_0");
    auto psCode=compile("Texture2D<float4> t:register(t5);SamplerState s:register(s3);cbuffer C:register(b4){float4 color;}struct O{float4 c:SV_Target0;float4 b:SV_Target1;};O main(float4 p:SV_Position){if(p.x<4)discard;O o;o.c=color*t.SampleLevel(s,p.xy/16,0);o.b=float4(.5,.5,.5,.5);return o;}","ps_5_0");
    if(!vsCode||!psCode)return failed;ComPtr<ID3D11VertexShader> vs;ComPtr<ID3D11PixelShader> ps;
    expect(SUCCEEDED(device->CreateVertexShader(vsCode->GetBufferPointer(),vsCode->GetBufferSize(),nullptr,&vs))&&SUCCEEDED(device->CreatePixelShader(psCode->GetBufferPointer(),psCode->GetBufferSize(),nullptr,&ps)),"dual-source fixture creates");if(!vs||!ps)return failed;
    auto fnv=[](ID3DBlob* b){uint64_t h=1469598103934665603ull;auto* p=static_cast<const BYTE*>(b->GetBufferPointer());for(size_t i=0;i<b->GetBufferSize();++i){h^=p[i];h*=1099511628211ull;}return h;};const uint64_t vsHash=fnv(vsCode.Get()),psHash=fnv(psCode.Get());hashes[vs.Get()]=vsHash;hashes[ps.Get()]=psHash;shaders[{'v',vsHash}]={static_cast<BYTE*>(vsCode->GetBufferPointer()),static_cast<BYTE*>(vsCode->GetBufferPointer())+vsCode->GetBufferSize()};shaders[{'p',psHash}]={static_cast<BYTE*>(psCode->GetBufferPointer()),static_cast<BYTE*>(psCode->GetBufferPointer())+psCode->GetBufferSize()};
    D3D11_TEXTURE2D_DESC td{};td.Width=td.Height=16;td.MipLevels=td.ArraySize=td.SampleDesc.Count=1;td.Format=DXGI_FORMAT_R8G8B8A8_UNORM;td.BindFlags=D3D11_BIND_RENDER_TARGET|D3D11_BIND_SHADER_RESOURCE;
    ComPtr<ID3D11Texture2D> color,baseline,texture;ComPtr<ID3D11RenderTargetView> rtv,baseRtv;ComPtr<ID3D11ShaderResourceView> srv;
    BYTE texels[16*16*4];std::fill(std::begin(texels),std::end(texels),BYTE(255));D3D11_SUBRESOURCE_DATA init{texels,64,1024};
    expect(SUCCEEDED(device->CreateTexture2D(&td,nullptr,&color))&&SUCCEEDED(device->CreateTexture2D(&td,nullptr,&baseline))&&SUCCEEDED(device->CreateTexture2D(&td,&init,&texture))&&SUCCEEDED(device->CreateRenderTargetView(color.Get(),nullptr,&rtv))&&SUCCEEDED(device->CreateRenderTargetView(baseline.Get(),nullptr,&baseRtv))&&SUCCEEDED(device->CreateShaderResourceView(texture.Get(),nullptr,&srv)),"color and sampled texture create");
    td.Format=DXGI_FORMAT_R24G8_TYPELESS;td.BindFlags=D3D11_BIND_DEPTH_STENCIL;ComPtr<ID3D11Texture2D> depth,baseDepth;ComPtr<ID3D11DepthStencilView> dsv,baseDsv;D3D11_DEPTH_STENCIL_VIEW_DESC vd{};vd.Format=DXGI_FORMAT_D24_UNORM_S8_UINT;vd.ViewDimension=D3D11_DSV_DIMENSION_TEXTURE2D;
    expect(SUCCEEDED(device->CreateTexture2D(&td,nullptr,&depth))&&SUCCEEDED(device->CreateTexture2D(&td,nullptr,&baseDepth))&&SUCCEEDED(device->CreateDepthStencilView(depth.Get(),&vd,&dsv))&&SUCCEEDED(device->CreateDepthStencilView(baseDepth.Get(),&vd,&baseDsv)),"depth stencil create");
    D3D11_BLEND_DESC bd{};auto& bt=bd.RenderTarget[0];bt.BlendEnable=TRUE;bt.SrcBlend=bt.SrcBlendAlpha=D3D11_BLEND_ONE;bt.DestBlend=D3D11_BLEND_SRC1_COLOR;bt.DestBlendAlpha=D3D11_BLEND_SRC1_ALPHA;bt.BlendOp=bt.BlendOpAlpha=D3D11_BLEND_OP_ADD;bt.RenderTargetWriteMask=15;ComPtr<ID3D11BlendState> blend;device->CreateBlendState(&bd,&blend);
    D3D11_DEPTH_STENCIL_DESC ds{};ds.DepthEnable=TRUE;ds.DepthWriteMask=D3D11_DEPTH_WRITE_MASK_ZERO;ds.DepthFunc=D3D11_COMPARISON_LESS;ds.StencilEnable=TRUE;ds.StencilReadMask=1;ds.StencilWriteMask=4;ds.FrontFace.StencilFunc=D3D11_COMPARISON_EQUAL;ds.FrontFace.StencilFailOp=ds.FrontFace.StencilDepthFailOp=D3D11_STENCIL_OP_KEEP;ds.FrontFace.StencilPassOp=D3D11_STENCIL_OP_REPLACE;ds.BackFace=ds.FrontFace;ComPtr<ID3D11DepthStencilState> depthState;device->CreateDepthStencilState(&ds,&depthState);
    D3D11_SAMPLER_DESC sd{};sd.Filter=D3D11_FILTER_MIN_MAG_MIP_POINT;sd.AddressU=sd.AddressV=sd.AddressW=D3D11_TEXTURE_ADDRESS_CLAMP;sd.MaxLOD=D3D11_FLOAT32_MAX;ComPtr<ID3D11SamplerState> sampler;device->CreateSamplerState(&sd,&sampler);
    D3D11_BUFFER_DESC buffer{};buffer.ByteWidth=64;buffer.BindFlags=D3D11_BIND_CONSTANT_BUFFER;float oldValues[16]{.25f,.5f,.75f,1},newValues[16]{.5f,.25f,.125f,1};D3D11_SUBRESOURCE_DATA cbInit{oldValues,0,0};ComPtr<ID3D11Buffer> cb;device->CreateBuffer(&buffer,&cbInit,&cb);
    buffer.ByteWidth=32;buffer.BindFlags=D3D11_BIND_VERTEX_BUFFER;BYTE vertices[32];for(unsigned i=0;i<32;++i)vertices[i]=BYTE(i+1);D3D11_SUBRESOURCE_DATA vbInit{vertices,0,0};ComPtr<ID3D11Buffer> vb;device->CreateBuffer(&buffer,&vbInit,&vb);
    if(!rtv||!baseRtv||!dsv||!baseDsv||!srv||!blend||!depthState||!sampler||!cb||!vb){expect(false,"all fixture resources create");return failed;}
    D3D11_RASTERIZER_DESC rd{};rd.FillMode=D3D11_FILL_SOLID;rd.CullMode=D3D11_CULL_NONE;rd.DepthClipEnable=TRUE;ComPtr<ID3D11RasterizerState> raster;device->CreateRasterizerState(&rd,&raster);
    auto bind=[&](ID3D11RenderTargetView* r,ID3D11DepthStencilView* d){ctx->OMSetRenderTargets(1,&r,d);ctx->VSSetShader(vs.Get(),nullptr,0);ctx->PSSetShader(ps.Get(),nullptr,0);ctx->IASetInputLayout(nullptr);ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);ctx->PSSetConstantBuffers(4,1,cb.GetAddressOf());ctx->PSSetShaderResources(5,1,srv.GetAddressOf());ctx->PSSetSamplers(3,1,sampler.GetAddressOf());UINT stride=8,offset=0;ctx->IASetVertexBuffers(31,1,vb.GetAddressOf(),&stride,&offset);ctx->OMSetBlendState(blend.Get(),nullptr,~0u);ctx->OMSetDepthStencilState(depthState.Get(),1);D3D11_VIEWPORT vp{0,0,16,16,0,1};ctx->RSSetViewports(1,&vp);ctx->RSSetState(raster.Get());};
    const float clear[4]{};ctx->ClearRenderTargetView(rtv.Get(),clear);ctx->ClearRenderTargetView(baseRtv.Get(),clear);ctx->ClearDepthStencilView(dsv.Get(),D3D11_CLEAR_DEPTH|D3D11_CLEAR_STENCIL,.8f,5);ctx->ClearDepthStencilView(baseDsv.Get(),D3D11_CLEAR_DEPTH|D3D11_CLEAR_STENCIL,.8f,5);
    ctx->UpdateSubresource(cb.Get(),0,nullptr,newValues,0,0);bind(baseRtv.Get(),baseDsv.Get());ctx->Draw(3,7);ctx->UpdateSubresource(cb.Get(),0,nullptr,oldValues,0,0);bind(rtv.Get(),dsv.Get());
    const auto root=std::filesystem::path(L"build/supporter-0182/packet_gpu_fixture");std::filesystem::create_directories(root);FlatDrawPacketCapture packets;packets.arm(root.wstring(),100,&hash,&lookup);
    FlatDrawPacketCapture::Args args{'D',3,7,1,0,0};
    for(unsigned i=0;i<40;++i)expect(!packets.before(ctx,100,i,100+i,200+i,args,false,true),"ordinary draws do not consume refused-pair quota");
    void* token=packets.before(ctx,100,42,vsHash,psHash,args,true,true);expect(token!=nullptr,"late non-qualified refused pair admitted independently");
    ctx->UpdateSubresource(cb.Get(),0,nullptr,newValues,0,0);packets.execution(ctx,token,nullptr,0,"replay-PS-bytecode-not-retained: fixture");
    ComPtr<ID3D11PixelShader> live;ctx->PSGetShader(&live,nullptr,nullptr);expect(live.Get()==ps.Get(),"capture leaves live original PS unchanged");ctx->Draw(3,7);packets.after(ctx,token);ctx->Flush();
    auto ring=std::make_unique<edvr::FlatTraceRing>();edvr::flatTraceBeginFrame(*ring,100,color.Get(),16,16,DXGI_FORMAT_R8G8B8A8_UNORM);
    edvr::FlatRuntimeDraw traced{};traced.key.sequence=42;traced.key.vs=vsHash;traced.key.ps=psHash;traced.instances=1;edvr::flatTraceRecord(*ring,traced,false);edvr::flatTraceSeal(*ring,false,0);packets.trace(100,*ring,true);
    for(unsigned i=0;i<200&&packets.finished()==0;++i){packets.present(ctx,101+i);if(!packets.finished())Sleep(1);}expect(packets.finished()==1&&packets.incomplete()==0,"complete packet retained with no HDR qualification or accepted phase");
    const auto jsonBytes=file(root/L"packet_100_42_1.json");const std::string json(jsonBytes.begin(),jsonBytes.end());expect(json.find("\"complete\":true")!=std::string::npos&&json.find("\"name\":\"PS.SRV5.view\"")!=std::string::npos&&json.find("\"name\":\"IA.VB31\"")!=std::string::npos&&json.find("\"name\":\"OM.depthStencil\"")!=std::string::npos,"packet exposes full stencil/SRV/high-slot IA metadata");
    auto gpuBytes=[&](ID3D11Texture2D* source){D3D11_TEXTURE2D_DESC d{};source->GetDesc(&d);d.Usage=D3D11_USAGE_STAGING;d.BindFlags=d.MiscFlags=0;d.CPUAccessFlags=D3D11_CPU_ACCESS_READ;ComPtr<ID3D11Texture2D> stage;device->CreateTexture2D(&d,nullptr,&stage);ctx->CopyResource(stage.Get(),source);D3D11_MAPPED_SUBRESOURCE map{};std::vector<BYTE> out;if(SUCCEEDED(ctx->Map(stage.Get(),0,D3D11_MAP_READ,0,&map))){for(unsigned y=0;y<16;++y){auto* row=static_cast<BYTE*>(map.pData)+y*map.RowPitch;out.insert(out.end(),row,row+64);}ctx->Unmap(stage.Get(),0);}return out;};
    expect(gpuBytes(color.Get())==gpuBytes(baseline.Get())&&gpuBytes(depth.Get())==gpuBytes(baseDepth.Get()),"original SRC1 color and stencil04 results byte-identical to baseline");
    const auto actualColor=gpuBytes(color.Get()),actualDepth=gpuBytes(depth.Get());
    expect(std::any_of(actualColor.begin(),actualColor.end(),[](BYTE b){return b!=0;})&&actualDepth[3]==5&&actualDepth[4*8+3]==1,
        "fixture executes actual color writes while discard preserves stencil and passing fragments clear bit04");
    expect(file(root/L"packet_100_42_1_resource_1_sub_0_0.bin")==gpuBytes(color.Get())&&file(root/L"packet_100_42_1_resource_3_sub_0_0.bin")==gpuBytes(depth.Get()),"saved full after color and depth/stencil equal actual original draw");
    bool oldCb=false,newCb=false,vbSaved=false,srvSaved=false;for(const auto& entry:std::filesystem::directory_iterator(root)){if(entry.path().extension()!=L".bin")continue;const auto b=file(entry.path());oldCb|=b.size()==64&&memcmp(b.data(),oldValues,64)==0;newCb|=b.size()==64&&memcmp(b.data(),newValues,64)==0;vbSaved|=b.size()==32&&memcmp(b.data(),vertices,32)==0;srvSaved|=b.size()==1024&&memcmp(b.data(),texels,1024)==0;expect(b.size()<=(64ull<<20),"all binary chunks obey bundler limit");}
    expect(oldCb&&newCb&&vbSaved&&srvSaved,"original and executed mutable CB, all-slot IA and sampled texture bytes captured");
    expect(file(root/L"packet_100_42_1_shader_PS_0.bin")==shaders[{'p',psHash}],"original qualifier-rejected-capable PS bytes saved exactly");
    const auto traceBytes=file(root/L"trace_100.bin");bool traceJoined=false;const auto traceStatus=edvr::flatTraceParse(traceBytes.data(),traceBytes.size(),[&](const edvr::FlatTraceFrameHeader& h){traceJoined=h.frame==100;},[&](const edvr::FlatTraceEvent& e){traceJoined=traceJoined&&e.key.sequence==42&&e.key.vs==vsHash&&e.key.ps==psHash;});
    expect(traceStatus&&traceJoined,"selected original frame/q joins its complete same-frame chronology");
    expect(json.find("\"start\":7,\"base\":0")!=std::string::npos,"non-indexed StartVertexLocation is serialized as start, not signed base vertex");
    FlatDrawPacketCapture::Args instanced{'N',3,7,2,9,0};auto* second=packets.before(ctx,101,43,vsHash,psHash,instanced,true,true);expect(second!=nullptr,"same refused pair captured in a second distinct frame");
    packets.execution(ctx,second,nullptr,0,"generic-projection-refusal");ctx->DrawInstanced(3,2,7,9);packets.after(ctx,second);edvr::flatTraceBeginFrame(*ring,101,color.Get(),16,16,DXGI_FORMAT_R8G8B8A8_UNORM);traced.key.sequence=43;edvr::flatTraceRecord(*ring,traced,false);packets.trace(101,*ring,true);ctx->Flush();
    for(unsigned i=0;i<200&&packets.finished()<2;++i){packets.present(ctx,102+i);if(packets.finished()<2)Sleep(1);}
    const auto secondJsonBytes=file(root/L"packet_101_43_2.json");const std::string secondJson(secondJsonBytes.begin(),secondJsonBytes.end());
    expect(secondJson.find("\"kind\":\"N\",\"count\":3,\"start\":7,\"base\":0,\"instances\":2,\"start_instance\":9")!=std::string::npos,"DrawInstanced count/start vertex/start instance arguments are exact");
    expect(!packets.before(ctx,102,44,vsHash,psHash,args,true,true),"priority pair is bounded to two distinct frames");
    const auto fallback=root/L"fallback";std::filesystem::create_directories(fallback);FlatDrawPacketCapture representative;representative.arm(fallback.wstring(),200,&hash,&lookup);auto* rep=representative.before(ctx,200,1,vsHash,psHash,args,false,true,1);expect(rep!=nullptr,"representative fallback works without previous refusal");representative.execution(ctx,rep,nullptr,0,"representative");ctx->Draw(3,7);representative.after(ctx,rep);expect(!representative.before(ctx,201,2,vsHash,psHash,args,false,true,1),"representative category sampled only once");representative.cancel();
    const auto cap=root/L"cap";std::filesystem::create_directories(cap);FlatDrawPacketCapture capped;capped.arm(cap.wstring(),300,&hash,&lookup,1);auto* limited=capped.before(ctx,300,9,vsHash,psHash,args,true,true);capped.execution(ctx,limited,nullptr,0,"cap");ctx->Draw(3,7);capped.after(ctx,limited);capped.present(ctx,301);expect(capped.finished()==1&&capped.incomplete()==1,"resource and file caps cannot report complete");
    const auto automatic=root/L"auto";std::filesystem::create_directories(automatic);FlatDrawPacketCapture autoPacket;autoPacket.arm(automatic.wstring(),400,&hash,&lookup);args.kind='A';auto* a=autoPacket.before(ctx,400,1,vsHash,psHash,args,true,true);autoPacket.execution(ctx,a,nullptr,0,"DrawAuto fixture");autoPacket.abandoned(a);autoPacket.cancel();const auto autoJson=file(automatic/L"packet_400_1_1.json");expect(std::string(autoJson.begin(),autoJson.end()).find("unsupported-DrawAuto-count")!=std::string::npos,"DrawAuto implicit count is explicitly unavailable");
    args.kind='D';
    const auto off=root/L"off";std::filesystem::create_directories(off);FlatDrawPacketCapture offPacket;offPacket.arm(off.wstring(),500,&hash,&lookup);auto* offToken=offPacket.before(ctx,500,1,vsHash,psHash,args,false,true,1);
    offPacket.missing(offToken,"chronology.resource_mutations","unsupported-AA-off-or-paused-mutation-observation");offPacket.execution(ctx,offToken,nullptr,0,"capture-only-AA-off-or-paused");ctx->Draw(3,7);offPacket.after(ctx,offToken);offPacket.cancel();
    const auto offJson=file(off/L"packet_500_1_1.json");expect(std::string(offJson.begin(),offJson.end()).find("unsupported-AA-off-or-paused-mutation-observation")!=std::string::npos,"AA-off native draw evidence explicitly describes missing mutation chronology");
    const auto timeout=root/L"timeout";std::filesystem::create_directories(timeout);FlatDrawPacketCapture timed;timed.arm(timeout.wstring(),600,&hash,&lookup);auto* t=timed.before(ctx,600,1,vsHash,psHash,args,true,true);timed.execution(ctx,t,nullptr,0,"readback-timeout");ctx->Draw(3,7);timed.after(ctx,t);timed.present(ctx,901);
    const auto timeoutJson=file(timeout/L"packet_600_1_1.json");expect(timed.incomplete()==1&&std::string(timeoutJson.begin(),timeoutJson.end()).find("\"status\":\"timeout\"")!=std::string::npos,"timed-out readback releases resources and cannot report complete");
    const auto overflow=root/L"overflow";std::filesystem::create_directories(overflow);FlatDrawPacketCapture truncated;truncated.arm(overflow.wstring(),700,&hash,&lookup);auto* ov=truncated.before(ctx,700,1,vsHash,psHash,args,true,true);truncated.execution(ctx,ov,nullptr,0,"trace-overflow");ctx->Draw(3,7);truncated.after(ctx,ov);edvr::flatTraceBeginFrame(*ring,700,color.Get(),16,16,DXGI_FORMAT_R8G8B8A8_UNORM);edvr::flatTraceRecord(*ring,traced,false);ring->headers[ring->slot].truncated=1;truncated.trace(700,*ring,true);truncated.cancel();
    const auto overflowJson=file(overflow/L"packet_700_1_1.json");expect(std::string(overflowJson.begin(),overflowJson.end()).find("\"trace_status\":\"overflow\"")!=std::string::npos,"overflow chronology remains explicitly incomplete");
    const auto failedMap=root/L"map_failure";std::filesystem::create_directories(failedMap);FlatDrawPacketCapture mapFailure;mapFailure.arm(failedMap.wstring(),800,&hash,&lookup);auto* m=mapFailure.before(ctx,800,1,vsHash,psHash,args,true,true);mapFailure.execution(ctx,m,nullptr,0,"readback-error");ctx->Draw(3,7);mapFailure.after(ctx,m);ComPtr<ID3D11DeviceContext> deferred;device->CreateDeferredContext(0,&deferred);if(deferred){mapFailure.present(deferred.Get(),801);const auto mapJson=file(failedMap/L"packet_800_1_1.json");expect(mapFailure.incomplete()==1&&std::string(mapJson.begin(),mapJson.end()).find("map-failed")!=std::string::npos,"actual invalid read Map HRESULT is recorded, never complete");}
    packets.cancel();ctx->ClearState();hashes.clear();shaders.clear();return failed;
}
