// Exercises the production controller. Only game classification and shader
// creation/logging are supplied by this standalone D3D11 harness.
#include "../../src/d3d11/ui_deferred.cpp"
#include "../../third_party/dxbc_hash/DxilHash.cpp"
#include <cstdio>
#include <cstdlib>
#include <cstdarg>
#include <chrono>
#include <cmath>
#include <algorithm>
#include <fstream>
#include <unordered_map>
using Microsoft::WRL::ComPtr;
static unsigned checks=0;
static uint64_t vsHash=0,psHash=0;
static void* bindings[static_cast<unsigned>(edvr::BindSlot::Count)]{};
static uint32_t bindingGens[static_cast<unsigned>(edvr::BindSlot::Count)]{};
static std::unordered_map<void*,uint64_t> shaderHashes;
static void check(bool x,const char* why){++checks;if(!x){fprintf(stderr,"FAIL: %s\n",why);exit(1);}}
static void hr(HRESULT h){if(FAILED(h))fprintf(stderr,"HRESULT %08x\n",unsigned(h));check(SUCCEEDED(h),"D3D operation");}
static ComPtr<ID3DBlob> compile(const char*s,size_t n,const char*entry,const char*profile){ComPtr<ID3DBlob>b,e;auto h=D3DCompile(s,n,nullptr,nullptr,nullptr,entry,profile,D3DCOMPILE_ENABLE_STRICTNESS,0,&b,&e);if(FAILED(h)&&e)fprintf(stderr,"%s",(char*)e->GetBufferPointer());hr(h);return b;}
namespace edvr {
Log& Log::get(){static Log l;return l;} Log::~Log()=default;
void Log::note(const char*,...){}
std::string Config::getString(const char*,const char*)const{return "dlss";}
 float Config::getFloat(const char*,float def)const{return def;}
 uint64_t bindingShaderHash(BindSlot s){return s==BindSlot::Vs?vsHash:psHash;}
 void* bindingGet(BindSlot s){return bindings[static_cast<unsigned>(s)];}
 uint32_t bindingGeneration(BindSlot s){return bindingGens[static_cast<unsigned>(s)];}
 bool bindingResolve(void* view,ResourceInfo*out){if(!view||!out)return false;*out={};ComPtr<ID3D11Resource>r;static_cast<ID3D11View*>(view)->GetResource(&r);ComPtr<ID3D11Texture2D>t;if(FAILED(r.As(&t)))return false;D3D11_TEXTURE2D_DESC d{};t->GetDesc(&d);out->isTexture2D=true;out->a=d.Width;out->b=d.Height;out->fmt=d.Format;out->resource=r.Get();return true;}
 bool vScreenIsEyeSized(uint32_t w,uint32_t h){return w==h && w>=8;}
 uint64_t lookupShaderHash(void* shader){auto i=shaderHashes.find(shader);return i==shaderHashes.end()?0:i->second;}
void vScreenExecuteCommandListRaw(ID3D11DeviceContext*c,ID3D11CommandList*l,int r){c->ExecuteCommandList(l,r);}
void vScreenSetRenderTargetsRaw(ID3D11DeviceContext*c,uint32_t n,ID3D11RenderTargetView*const*r,ID3D11DepthStencilView*d){c->OMSetRenderTargets(n,r,d);}
ID3D11VertexShader* shaderSwapCompileVs(ID3D11DeviceContext*c,const char*s,size_t n,const char*e,const char*,const SwapMacro*,const char*){auto b=compile(s,n,e,"vs_5_0");ComPtr<ID3D11Device>d;c->GetDevice(&d);ID3D11VertexShader*v=nullptr;hr(d->CreateVertexShader(b->GetBufferPointer(),b->GetBufferSize(),nullptr,&v));return v;}
ID3D11PixelShader* shaderSwapCompilePs(ID3D11DeviceContext*c,const char*s,size_t n,const char*e,const char*,const SwapMacro*,const char*){auto b=compile(s,n,e,"ps_5_0");ComPtr<ID3D11Device>d;c->GetDevice(&d);ID3D11PixelShader*v=nullptr;hr(d->CreatePixelShader(b->GetBufferPointer(),b->GetBufferSize(),nullptr,&v));return v;}
ID3D11ComputeShader* shaderSwapCompileCs(ID3D11DeviceContext*c,const char*s,size_t n,const char*e,const char*,const SwapMacro*,const char*){auto b=compile(s,n,e,"cs_5_0");ComPtr<ID3D11Device>d;c->GetDevice(&d);ID3D11ComputeShader*v=nullptr;hr(d->CreateComputeShader(b->GetBufferPointer(),b->GetBufferSize(),nullptr,&v));return v;}
}
static std::vector<BYTE> read(ID3D11Device*d,ID3D11DeviceContext*c,ID3D11Texture2D*t){D3D11_TEXTURE2D_DESC td{};t->GetDesc(&td);td.Usage=D3D11_USAGE_STAGING;td.BindFlags=td.MiscFlags=0;td.CPUAccessFlags=D3D11_CPU_ACCESS_READ;ComPtr<ID3D11Texture2D>s;hr(d->CreateTexture2D(&td,nullptr,&s));c->CopyResource(s.Get(),t);D3D11_MAPPED_SUBRESOURCE m{};hr(c->Map(s.Get(),0,D3D11_MAP_READ,0,&m));std::vector<BYTE> b(size_t(td.Width)*td.Height*4);for(UINT y=0;y<td.Height;++y)memcpy(b.data()+size_t(y)*td.Width*4,(BYTE*)m.pData+y*m.RowPitch,td.Width*4);c->Unmap(s.Get(),0);return b;}
static std::vector<BYTE> readRgba32(ID3D11Device*d,ID3D11DeviceContext*c,ID3D11Texture2D*t){D3D11_TEXTURE2D_DESC td{};t->GetDesc(&td);check(td.Format==DXGI_FORMAT_R32G32B32A32_FLOAT,"RGBA32 readback format");td.Usage=D3D11_USAGE_STAGING;td.BindFlags=td.MiscFlags=0;td.CPUAccessFlags=D3D11_CPU_ACCESS_READ;ComPtr<ID3D11Texture2D>s;hr(d->CreateTexture2D(&td,nullptr,&s));c->CopyResource(s.Get(),t);D3D11_MAPPED_SUBRESOURCE m{};hr(c->Map(s.Get(),0,D3D11_MAP_READ,0,&m));std::vector<BYTE>b(size_t(td.Width)*td.Height*16);for(UINT y=0;y<td.Height;++y)memcpy(b.data()+size_t(y)*td.Width*16,(BYTE*)m.pData+y*m.RowPitch,td.Width*16);c->Unmap(s.Get(),0);return b;}
static std::vector<BYTE> readBuffer(ID3D11Device*d,ID3D11DeviceContext*c,ID3D11Buffer*b){D3D11_BUFFER_DESC bd{};b->GetDesc(&bd);auto staging=bd;staging.Usage=D3D11_USAGE_STAGING;staging.BindFlags=staging.MiscFlags=0;staging.CPUAccessFlags=D3D11_CPU_ACCESS_READ;staging.StructureByteStride=0;ComPtr<ID3D11Buffer>s;hr(d->CreateBuffer(&staging,nullptr,&s));c->CopyResource(s.Get(),b);D3D11_MAPPED_SUBRESOURCE m{};hr(c->Map(s.Get(),0,D3D11_MAP_READ,0,&m));std::vector<BYTE> data(bd.ByteWidth);memcpy(data.data(),m.pData,data.size());c->Unmap(s.Get(),0);return data;}
static std::vector<BYTE> readFile(const wchar_t*path){FILE*f=nullptr;if(_wfopen_s(&f,path,L"rb")||!f)return {};fseek(f,0,SEEK_END);const long n=ftell(f);fseek(f,0,SEEK_SET);std::vector<BYTE>b(n>0?size_t(n):0);if(!b.empty()&&fread(b.data(),1,b.size(),f)!=b.size())b.clear();fclose(f);return b;}
static edvr::Surface surf(ID3D11Device*d,UINT w,UINT h,DXGI_FORMAT f){edvr::Surface s;check(s.ensure(d,w,h,f),"surface created");return s;}
static std::vector<BYTE> programContainer(ID3DBlob* shell,std::vector<UINT> program){using namespace edvr::dxbc_fanout_detail;program[1]=UINT(program.size());const auto*p=static_cast<const BYTE*>(shell->GetBufferPointer());std::vector<BYTE>in(p,p+shell->GetBufferSize());std::vector<std::pair<UINT,std::vector<BYTE>>>chunks;bool replaced=false;for(UINT i=0,n=word(in,28);i<n;++i){UINT off=word(in,32+4*i),tag=word(in,off),size=word(in,off+4);std::vector<BYTE>b(in.begin()+off+8,in.begin()+off+8+size);if(tag==0x58454853||tag==0x52444853){b.resize(program.size()*4);memcpy(b.data(),program.data(),b.size());replaced=true;}chunks.push_back({tag,std::move(b)});}check(replaced,"compiled shader shell has a token program");std::vector<BYTE>out(in.begin(),in.begin()+32);out.resize(32+chunks.size()*4);UINT i=0;for(auto&chunk:chunks){UINT off=UINT(out.size());memcpy(out.data()+32+4*i++,&off,4);put(out,chunk.first);put(out,UINT(chunk.second.size()));out.insert(out.end(),chunk.second.begin(),chunk.second.end());}UINT size=UINT(out.size());memcpy(out.data()+24,&size,4);ComputeHashRetail(out.data()+20,size-20,out.data()+4);return out;}
static std::vector<BYTE> stripRdef(ID3DBlob* shell){using namespace edvr::dxbc_fanout_detail;const auto*p=static_cast<const BYTE*>(shell->GetBufferPointer());std::vector<BYTE>in(p,p+shell->GetBufferSize());std::vector<std::pair<UINT,std::vector<BYTE>>>chunks;bool removed=false;for(UINT i=0,n=word(in,28);i<n;++i){UINT off=word(in,32+4*i),tag=word(in,off),size=word(in,off+4);if(tag==0x46454452u){removed=true;continue;}chunks.push_back({tag,std::vector<BYTE>(in.begin()+off+8,in.begin()+off+8+size)});}check(removed,"compiled fixture contains RDEF");std::vector<BYTE>out(in.begin(),in.begin()+32);out.resize(32+chunks.size()*4);UINT count=UINT(chunks.size());memcpy(out.data()+28,&count,4);UINT i=0;for(auto&chunk:chunks){UINT off=UINT(out.size());memcpy(out.data()+32+4*i++,&off,4);put(out,chunk.first);put(out,UINT(chunk.second.size()));out.insert(out.end(),chunk.second.begin(),chunk.second.end());}UINT size=UINT(out.size());memcpy(out.data()+24,&size,4);ComputeHashRetail(out.data()+20,size-20,out.data()+4);return out;}
static std::vector<BYTE> duplicateProgramChunk(const std::vector<BYTE>&in){using namespace edvr::dxbc_fanout_detail;std::vector<std::pair<UINT,std::vector<BYTE>>>chunks;bool duplicated=false;for(UINT i=0,n=word(in,28);i<n;++i){UINT off=word(in,32+4*i),tag=word(in,off),size=word(in,off+4);std::vector<BYTE>body(in.begin()+off+8,in.begin()+off+8+size);chunks.push_back({tag,body});if(!duplicated&&(tag==0x58454853u||tag==0x52444853u)){chunks.push_back({tag,body});duplicated=true;}}check(duplicated,"duplicate fixture found a program chunk");std::vector<BYTE>out(in.begin(),in.begin()+32);out.resize(32+chunks.size()*4);UINT count=UINT(chunks.size());memcpy(out.data()+28,&count,4);UINT i=0;for(auto&chunk:chunks){UINT off=UINT(out.size());memcpy(out.data()+32+4*i++,&off,4);put(out,chunk.first);put(out,UINT(chunk.second.size()));out.insert(out.end(),chunk.second.begin(),chunk.second.end());}UINT size=UINT(out.size());memcpy(out.data()+24,&size,4);ComputeHashRetail(out.data()+20,size-20,out.data()+4);return out;}
static void fanoutDestinationTests(){using namespace edvr::dxbc_fanout_detail;
 auto unchanged=[](std::vector<UINT> inst,UINT op){auto original=inst;UINT mask=0;rewriteDestinations(inst,op,9,mask);check(inst==original&&mask==0,"multi-destination temp/null instruction remains unchanged");};
 unchanged({0x0600004D,0x00100042,2,0x0000D000,0x0010002A,2},77);
 unchanged({0x0600004D,0x0000D000,0x00100042,2,0x0010002A,2},77);
 unchanged({0x08000026,0x0000D000,0x00100022,3,0x0010003A,2,0x00004001,0x30},38);
 unchanged({0x0800004E,0x0000D000,0x00100082,8,0x0010003A,8,0x00004001,12},78);
 unchanged({0x0B00008E,0x00100072,5,0x00100072,6,0x00100FF6,5,0x00100246,5,0x00100386,4},142);
 {std::vector<UINT> inst{0x0600004D,0x00102042,0,0x0000D000,0x0010002A,2};UINT mask=0;rewriteDestinations(inst,77,9,mask);check(mask==4&&inst[1]==0x00100042&&inst[2]==9,"first sincos output destination is redirected");}
 {std::vector<UINT> inst{0x08000026,0x0000D000,0x00102032,0,0x00100046,0,0x00100AA6,0};UINT mask=0;rewriteDestinations(inst,38,9,mask);check(mask==3&&inst[2]==0x00100032&&inst[3]==9,"second imul output destination is redirected");}
 for(UINT op:{81u,132u,133u}){std::vector<UINT> inst{0x05000000u|op,0x0000D000,0x00100012,1,0};UINT mask=0;rewriteDestinations(inst,op,9,mask);check(mask==0,"remaining SDK two-destination opcode advances both destinations");}
 for(UINT op:{18u,21u,22u,57u}){std::vector<UINT> inst{0x01000000u|op};UINT mask=0;rewriteDestinations(inst,op,9,mask);check(mask==0&&inst.size()==1,"operand-free control instruction remains unchanged");}
 for(UINT token:{0x80500022u,0x00500022u}){bool declined=false;try{std::vector<UINT> inst{0x08000026,0x0000D000,token,3,0,0,0,0};UINT mask=0;rewriteDestinations(inst,38,9,mask);}catch(const std::exception&){declined=true;}check(declined,"extended or relative multi-destination operand declines closed");}
}
static std::vector<UINT> twoDestinationProgram(UINT op,bool outputFirst,UINT sourceCount){std::vector<UINT>p{0x50,0,0x03000065,0x001020f2,0};const UINT length=1+3+5*sourceCount;p.push_back((length<<24)|op);if(outputFirst){p.push_back(0x00102032);p.push_back(0);p.push_back(0x0000d000);}else{p.push_back(0x0000d000);p.push_back(0x00102032);p.push_back(0);}UINT values[3][4]={{1,1,0,0},{0x3f000000,0x3e800000,0,0},{1,1,1,1}};if(op==77){values[0][0]=0x3f000000;values[0][1]=0x3f800000;}if(op==78){values[0][0]=0x3f000000;values[0][1]=0x3e800000;values[1][0]=values[1][1]=1;}for(UINT s=0;s<sourceCount;++s){p.push_back(0x00004002);p.insert(p.end(),values[s],values[s]+4);}const UINT mov[]={0x08000036,0x001020c2,0,0x00004002,0,0,0x3f400000,0x3f800000};p.insert(p.end(),mov,mov+8);p.push_back(0x0100003e);return p;}
static void fanoutGpuDifferential(bool hardware){
 const char* shellSource="float4 main():SV_Target{return float4(0,0,0,0);}";auto shell=compile(shellSource,strlen(shellSource),"main","ps_5_0");
 ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>c;D3D_FEATURE_LEVEL level{};hr(D3D11CreateDevice(nullptr,hardware?D3D_DRIVER_TYPE_HARDWARE:D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,&level,&c));
 const char* vsSource="float4 main(uint i:SV_VertexID):SV_Position{float2 p=float2(i==2?3:-1,i==1?3:-1);return float4(p,0,1);}";auto vsCode=compile(vsSource,strlen(vsSource),"main","vs_5_0");ComPtr<ID3D11VertexShader>vs;hr(d->CreateVertexShader(vsCode->GetBufferPointer(),vsCode->GetBufferSize(),nullptr,&vs));
 const struct{UINT op;bool outputFirst;UINT sources;}cases[]={{38,false,2},{77,true,1},{77,false,1},{78,true,2},{81,false,2},{132,true,2},{133,true,2},{142,true,3}};
 for(const auto&fixture:cases){auto original=programContainer(shell.Get(),twoDestinationProgram(fixture.op,fixture.outputFirst,fixture.sources));std::vector<BYTE>patched;std::string why;const bool fanoutOk=edvr::uiColourFanout(original.data(),original.size(),patched,why);check(fanoutOk,why.c_str());ComPtr<ID3D11PixelShader>a,b;hr(d->CreatePixelShader(original.data(),original.size(),nullptr,&a));hr(d->CreatePixelShader(patched.data(),patched.size(),nullptr,&b));auto expected=surf(d.Get(),4,4,DXGI_FORMAT_R32G32B32A32_FLOAT),actual=surf(d.Get(),4,4,DXGI_FORMAT_R32G32B32A32_FLOAT),clean=surf(d.Get(),4,4,DXGI_FORMAT_R32G32B32A32_FLOAT),influence=surf(d.Get(),4,4,DXGI_FORMAT_R32G32B32A32_FLOAT);D3D11_VIEWPORT vp{0,0,4,4,0,1};c->ClearState();c->RSSetViewports(1,&vp);c->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);c->VSSetShader(vs.Get(),nullptr,0);c->OMSetRenderTargets(1,expected.rtv.GetAddressOf(),nullptr);c->PSSetShader(a.Get(),nullptr,0);c->Draw(3,0);ID3D11RenderTargetView*rt[3]={actual.rtv.Get(),clean.rtv.Get(),influence.rtv.Get()};c->OMSetRenderTargets(3,rt,nullptr);c->PSSetShader(b.Get(),nullptr,0);c->Draw(3,0);auto x=readRgba32(d.Get(),c.Get(),expected.tex.Get()),y=readRgba32(d.Get(),c.Get(),actual.tex.Get()),z=readRgba32(d.Get(),c.Get(),clean.tex.Get()),w=readRgba32(d.Get(),c.Get(),influence.tex.Get());check(x==y&&x==z,"GPU fanout preserves full colour and exports clean colour for two-destination opcode");bool alpha=true;for(size_t i=0;i<w.size();i+=16)for(size_t component=0;component<4;++component)alpha&=!memcmp(w.data()+i+component*4,x.data()+i+12,4);check(alpha,"GPU fanout exports original alpha as scalar influence");}
 c->ClearState();
}
static void strippedDeclarationTests(bool hardware){
 const char*vsSource="Texture2D<float> E:register(t0);cbuffer V:register(b0){float4 shift;}struct O{float4 p:SV_Position;float e:TEXCOORD0;};O main(uint i:SV_VertexID){O o;float2 p=float2(i==2?3:-1,i==1?3:-1);o.p=float4(p+shift.xy,0,1);o.e=E.Load(int3(0,0,0));return o;}";
 const char*psSource="Texture2D<float4> L:register(t0);cbuffer P:register(b2){float4 factor;}float4 main(float4 p:SV_Position,float e:TEXCOORD0):SV_Target{return L.Load(int3(0,0,0))*factor*e;}";
 auto vsBlob=compile(vsSource,strlen(vsSource),"main","vs_5_0"),psBlob=compile(psSource,strlen(psSource),"main","ps_5_0");auto vsBytes=stripRdef(vsBlob.Get()),psBytes=stripRdef(psBlob.Get());
 ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>c;D3D_FEATURE_LEVEL level{};hr(D3D11CreateDevice(nullptr,hardware?D3D_DRIVER_TYPE_HARDWARE:D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,&level,&c));ComPtr<ID3D11VertexShader>vs;ComPtr<ID3D11PixelShader>ps;hr(d->CreateVertexShader(vsBytes.data(),vsBytes.size(),nullptr,&vs));hr(d->CreatePixelShader(psBytes.data(),psBytes.size(),nullptr,&ps));hr(vs->SetPrivateData(edvr::kDeferredBytes,UINT(vsBytes.size()),vsBytes.data()));hr(ps->SetPrivateData(edvr::kDeferredBytes,UINT(psBytes.size()),psBytes.data()));
 ComPtr<ID3D11ShaderReflection>strippedReflection;hr(D3DReflect(psBytes.data(),psBytes.size(),IID_PPV_ARGS(&strippedReflection)));D3D11_SHADER_DESC strippedDesc{};hr(strippedReflection->GetDesc(&strippedDesc));check(strippedDesc.BoundResources==0,"stripped D3DReflect succeeds while reporting zero dependencies");
 edvr::UiDeferredCaptureMask mask;check(edvr::uiDeferredReflect(vs.Get(),mask.cbVs,mask.srvVs)&&edvr::uiDeferredReflect(ps.Get(),mask.cbPs,mask.srvPs),"stripped SM5 declarations are readable");check(mask.cbVs==1 && mask.cbPs==4 && mask.srvVs[0] && mask.srvPs[0],"stripped SM5 declarations retain exact CB/SRV slots");
 float exposure=2,colour[4]={.2f,.3f,.4f,1},vconst[4]={},pconst[4]={.5f,.5f,.5f,.5f};D3D11_TEXTURE2D_DESC td{};td.Width=td.Height=td.MipLevels=td.ArraySize=1;td.SampleDesc.Count=1;td.Usage=D3D11_USAGE_DEFAULT;td.BindFlags=D3D11_BIND_SHADER_RESOURCE;td.Format=DXGI_FORMAT_R32_FLOAT;D3D11_SUBRESOURCE_DATA initial{&exposure,4,0};ComPtr<ID3D11Texture2D>exposureTex;hr(d->CreateTexture2D(&td,&initial,&exposureTex));ComPtr<ID3D11ShaderResourceView>exposureSrv;hr(d->CreateShaderResourceView(exposureTex.Get(),nullptr,&exposureSrv));td.Format=DXGI_FORMAT_R32G32B32A32_FLOAT;initial={colour,16,0};ComPtr<ID3D11Texture2D>colourTex;hr(d->CreateTexture2D(&td,&initial,&colourTex));ComPtr<ID3D11ShaderResourceView>colourSrv;hr(d->CreateShaderResourceView(colourTex.Get(),nullptr,&colourSrv));
 D3D11_BUFFER_DESC bd{};bd.ByteWidth=16;bd.BindFlags=D3D11_BIND_CONSTANT_BUFFER;initial={vconst,0,0};ComPtr<ID3D11Buffer>vcb;hr(d->CreateBuffer(&bd,&initial,&vcb));initial={pconst,0,0};ComPtr<ID3D11Buffer>pcb;hr(d->CreateBuffer(&bd,&initial,&pcb));D3D11_RASTERIZER_DESC rd{};rd.FillMode=D3D11_FILL_SOLID;rd.CullMode=D3D11_CULL_NONE;ComPtr<ID3D11RasterizerState>rs;hr(d->CreateRasterizerState(&rd,&rs));D3D11_DEPTH_STENCIL_DESC dd{};dd.DepthEnable=FALSE;ComPtr<ID3D11DepthStencilState>ds;hr(d->CreateDepthStencilState(&dd,&ds));
 auto output=surf(d.Get(),4,4,DXGI_FORMAT_R32G32B32A32_FLOAT);D3D11_VIEWPORT vp{0,0,4,4,0,1};c->RSSetState(rs.Get());c->RSSetViewports(1,&vp);c->OMSetDepthStencilState(ds.Get(),0);c->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);c->VSSetShader(vs.Get(),nullptr,0);c->PSSetShader(ps.Get(),nullptr,0);c->VSSetConstantBuffers(0,1,vcb.GetAddressOf());c->PSSetConstantBuffers(2,1,pcb.GetAddressOf());c->VSSetShaderResources(0,1,exposureSrv.GetAddressOf());c->PSSetShaderResources(0,1,colourSrv.GetAddressOf());edvr::UiDeferredSnapshots pool;edvr::UiDeferredDraw packet;check(packet.capture(c.Get(),pool,'D',3,1,0,0,0,mask),packet.failureReason());check(packet.vsResource(0)&&packet.psResource(0)&&packet.psBuffer(2),"stripped declaration packet snapshots every declared input");
 float zeros[4]{};c->UpdateSubresource(exposureTex.Get(),0,nullptr,zeros,4,0);c->UpdateSubresource(colourTex.Get(),0,nullptr,zeros,16,0);c->UpdateSubresource(pcb.Get(),0,nullptr,zeros,0,0);ComPtr<ID3D11DeviceContext>dc;hr(d->CreateDeferredContext(0,&dc));check(packet.bind(dc.Get(),packet.originalPixelShader(),output.rtv.Get(),nullptr,nullptr,vp),"stripped declaration packet binds");packet.draw(dc.Get());ComPtr<ID3D11CommandList>list;hr(dc->FinishCommandList(FALSE,&list));c->ExecuteCommandList(list.Get(),TRUE);auto pixels=readRgba32(d.Get(),c.Get(),output.tex.Get());float actual[4]{};memcpy(actual,pixels.data()+((2*4+2)*16),sizeof(actual));check(fabs(actual[0]-.2f)<.001f&&fabs(actual[1]-.3f)<.001f&&fabs(actual[2]-.4f)<.001f&&fabs(actual[3]-1)<.001f,"stripped declaration packet replays immutable captured inputs after source mutation");
 const char*resourceSource="ByteAddressBuffer R:register(t4);StructuredBuffer<float4> S:register(t38);float4 main():SV_Target{return asfloat(R.Load4(0))+S[0];}";auto resourceBlob=compile(resourceSource,strlen(resourceSource),"main","ps_5_0");auto resourceBytes=stripRdef(resourceBlob.Get());uint32_t cb=0;std::array<bool,128>srv{};check(edvr::uiDeferredDeclaredInputs(resourceBytes,cb,srv)&&!cb&&srv[4]&&srv[38],"raw and structured stripped declarations retain bounded slots");
 const char*dynamicSource="cbuffer D:register(b1){float4 values[64];}float4 main(float4 p:SV_Position):SV_Target{return values[(uint)p.x&63];}";auto dynamicBlob=compile(dynamicSource,strlen(dynamicSource),"main","ps_5_0");auto dynamicBytes=stripRdef(dynamicBlob.Get());bool dynamicFound=false;for(size_t i=0;i+16<=dynamicBytes.size();i+=4){uint32_t w=0,next=0;memcpy(&w,dynamicBytes.data()+i,4);memcpy(&next,dynamicBytes.data()+i+4,4);if((w&0x7ffu)==89&&next==0x00208e46u)dynamicFound|=(w&0x800u)!=0;}cb=0;srv={};check(dynamicFound&&edvr::uiDeferredDeclaredInputs(dynamicBytes,cb,srv)&&cb==2,"dynamic-indexed fixed CB declaration retains its bounded slot");
 auto unknownSize=psBytes;bool changed=false;for(size_t i=0;i+16<=unknownSize.size();i+=4){uint32_t w=0,next=0;memcpy(&w,unknownSize.data()+i,4);memcpy(&next,unknownSize.data()+i+4,4);if((w&0x7ffu)==89&&next==0x00208e46u){uint32_t zero=0;memcpy(unknownSize.data()+i+12,&zero,4);changed=true;break;}}cb=0;srv={};check(changed&&edvr::uiDeferredDeclaredInputs(unknownSize,cb,srv)&&cb==4,"unknown-size fixed CB declaration retains its bounded slot");
 auto malformed=resourceBytes;changed=false;for(size_t i=0;i+8<=malformed.size();i+=4){uint32_t w=0,next=0;memcpy(&w,malformed.data()+i,4);memcpy(&next,malformed.data()+i+4,4);if((w&0x7ffu)==162&&next==0x00107000u){w=(w&~0x7ffu)|156u;memcpy(malformed.data()+i,&w,4);changed=true;break;}}cb=0;srv={};check(changed&&!edvr::uiDeferredDeclaredInputs(malformed,cb,srv),"UAV declaration declines closed");
 malformed=psBytes;changed=false;for(size_t i=0;i+4<=malformed.size();i+=4){uint32_t w=0;memcpy(&w,malformed.data()+i,4);if(w==0x00208e46u){w|=0x80000000u;memcpy(malformed.data()+i,&w,4);changed=true;break;}}cb=0;srv={};check(changed&&!edvr::uiDeferredDeclaredInputs(malformed,cb,srv),"extended declaration operand declines closed");
 const char*emptySource="float4 main():SV_Target{return float4(1,0,0,1);}";auto emptyBlob=compile(emptySource,strlen(emptySource),"main","ps_5_0");auto emptyBytes=stripRdef(emptyBlob.Get());cb=0;srv={};check(edvr::uiDeferredDeclaredInputs(emptyBytes,cb,srv)&&!cb&&std::none_of(srv.begin(),srv.end(),[](bool x){return x;}),"resource-free stripped shader remains valid");
 cb=0;srv={};check(!edvr::uiDeferredDeclaredInputs(duplicateProgramChunk(psBytes),cb,srv),"duplicate executable program declines closed");
 malformed=psBytes;changed=false;for(size_t i=0;i+16<=malformed.size();i+=4){uint32_t w=0,next=0;memcpy(&w,malformed.data()+i,4);memcpy(&next,malformed.data()+i+4,4);if((w&0x7ffu)==89&&next==0x00208e46u){w&=0x00ffffffu;memcpy(malformed.data()+i,&w,4);changed=true;break;}}cb=0;srv={};check(changed&&!edvr::uiDeferredDeclaredInputs(malformed,cb,srv),"zero-length declaration declines closed");
 malformed=psBytes;changed=false;for(size_t i=0;i+16<=malformed.size();i+=4){uint32_t w=0,next=0;memcpy(&w,malformed.data()+i,4);memcpy(&next,malformed.data()+i+4,4);if((w&0x7ffu)==89&&next==0x00208e46u){uint32_t slot=14;memcpy(malformed.data()+i+8,&slot,4);changed=true;break;}}cb=0;srv={};check(changed&&!edvr::uiDeferredDeclaredInputs(malformed,cb,srv),"out-of-range declaration register declines closed");
 malformed=resourceBytes;changed=false;for(size_t i=0;i+8<=malformed.size();i+=4){uint32_t w=0,next=0;memcpy(&w,malformed.data()+i,4);memcpy(&next,malformed.data()+i+4,4);if((w&0x7ffu)==162&&next==0x00107000u){w=(w&~0x7ffu)|144u;memcpy(malformed.data()+i,&w,4);changed=true;break;}}cb=0;srv={};check(changed&&!edvr::uiDeferredDeclaredInputs(malformed,cb,srv),"interface declaration declines closed");
}
struct Harness {
 ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>c;
 ComPtr<ID3D11VertexShader>vs,postVs,tailVs,glassVs;ComPtr<ID3D11PixelShader>ui,tone,postTone,glass;
 ComPtr<ID3D11DepthStencilState>noDepth,uiDepth,tailDepth,glassDepth;
 ComPtr<ID3D11BlendState>over,add,destAlpha,unsupported,tailBlend,glassBlend;
 ComPtr<ID3D11RasterizerState>rs;ComPtr<ID3D11SamplerState>sampler;
 ComPtr<ID3D11Buffer>cb,tailIb,tailStructured;
 ComPtr<ID3D11ShaderResourceView>tailStructuredSrv;ComPtr<ID3D11UnorderedAccessView>tailStructuredUav;
 edvr::Surface hdr,ldr,output,expected,expectedHdr;
 ComPtr<ID3D11Texture2D>z,tailZ;ComPtr<ID3D11DepthStencilView>dsv,tailDsv;
 ComPtr<ID3D11ShaderResourceView>zSrv;
 UINT inW=8,inH=8,outW=8,outH=8;
 float bg[4]={.25,.5,.75,1};
 Harness(bool hardware,UINT input=8,UINT out=8,UINT inputHeight=0,UINT outputHeight=0):inW(input),inH(inputHeight?inputHeight:input),outW(out),outH(outputHeight?outputHeight:out){
  D3D_FEATURE_LEVEL level{};hr(D3D11CreateDevice(nullptr,hardware?D3D_DRIVER_TYPE_HARDWARE:D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,&level,&c));
  const char*v="cbuffer C:register(b0){float4 colour;float2 jitter;float2 cut;}struct O{float4 p:SV_Position;float2 uv:TEXCOORD0;};O main(uint i:SV_VertexID){O o;float2 p=float2(i==2?3:-1,i==1?3:-1);o.p=float4(p+float2(2*jitter.x,-2*jitter.y),.5,1);o.uv=p*float2(.5,-.5)+.5;return o;}";
   auto b=compile(v,strlen(v),"main","vs_5_0");hr(d->CreateVertexShader(b->GetBufferPointer(),b->GetBufferSize(),nullptr,&vs));edvr::uiDeferredRemember(vs.Get(),b->GetBufferPointer(),b->GetBufferSize(),false);
   const char*pv="struct O{float4 p:SV_Position;float2 uv:TEXCOORD0;};O main(uint i:SV_VertexID){float2 q=float2((i&1)?1:-1,(i&2)?1:-1);O o;o.p=float4(q,.5,1);float2 uv=q*float2(.5,-.5)+.5;o.uv=uv*.75+float2(.2,.1);return o;}";
   b=compile(pv,strlen(pv),"main","vs_5_0");hr(d->CreateVertexShader(b->GetBufferPointer(),b->GetBufferSize(),nullptr,&postVs));edvr::uiDeferredRemember(postVs.Get(),b->GetBufferPointer(),b->GetBufferSize(),false);
   const char*tv="cbuffer C:register(b0){float4 colour;float2 jitter;float2 cut;}struct T{float4 value;float4 pad0;float4 pad1;};StructuredBuffer<T> Dynamic:register(t38);struct O{float4 p:SV_Position;float2 uv:TEXCOORD0;};O main(uint i:SV_VertexID){float2 q=float2((i&1)?1:-1,(i&2)?1:-1);O o;o.p=float4(q*.75+float2(2*jitter.x,-2*jitter.y)+float2(Dynamic[0].value.x*.05,0),.5,1);o.uv=q*float2(.5,-.5)+.5;return o;}";
   b=compile(tv,strlen(tv),"main","vs_5_0");hr(d->CreateVertexShader(b->GetBufferPointer(),b->GetBufferSize(),nullptr,&tailVs));edvr::uiDeferredRemember(tailVs.Get(),b->GetBufferPointer(),b->GetBufferSize(),false);
  const char*p="cbuffer C:register(b0){float4 colour;float2 jitter;float2 cut;}float4 main(float4 p:SV_Position,float2 uv:TEXCOORD0):SV_Target{if(uv.x<cut.x || uv.x>cut.y || uv.y<.2 || uv.y>.8)discard;return colour;}";
  b=compile(p,strlen(p),"main","ps_5_0");hr(d->CreatePixelShader(b->GetBufferPointer(),b->GetBufferSize(),nullptr,&ui));edvr::uiDeferredRemember(ui.Get(),b->GetBufferPointer(),b->GetBufferSize(),false);
  const char*t="Texture2D<float3> H:register(t1);SamplerState S:register(s0);float4 main(float4 p:SV_Position,float2 uv:TEXCOORD0):SV_Target{float3 h=H.SampleLevel(S,uv,0);return float4(h/(1+h),1);}";
  b=compile(t,strlen(t),"main","ps_5_0");hr(d->CreatePixelShader(b->GetBufferPointer(),b->GetBufferSize(),nullptr,&tone));edvr::uiDeferredRemember(tone.Get(),b->GetBufferPointer(),b->GetBufferSize(),false);
  const char*post="Texture2D<float4> T:register(t0);SamplerState S:register(s0);float4 main(float4 p:SV_Position,float2 uv:TEXCOORD0):SV_Target{return T.Sample(S,uv);}";
  b=compile(post,strlen(post),"main","ps_5_0");hr(d->CreatePixelShader(b->GetBufferPointer(),b->GetBufferSize(),nullptr,&postTone));edvr::uiDeferredRemember(postTone.Get(),b->GetBufferPointer(),b->GetBufferSize(),false);shaderHashes[vs.Get()]=0x111;shaderHashes[ui.Get()]=0x222;shaderHashes[tone.Get()]=0x333;shaderHashes[postTone.Get()]=0x444;
  const char*glassSource="struct O{float4 colour:SV_Target0;float4 transmission:SV_Target1;};O main(){O o;o.colour=float4(.07,.19,.41,.6);o.transmission=float4(.23,.47,.71,.8);return o;}";
  b=compile(glassSource,strlen(glassSource),"main","ps_5_0");hr(d->CreatePixelShader(b->GetBufferPointer(),b->GetBufferSize(),nullptr,&glass));edvr::uiDeferredRemember(glass.Get(),b->GetBufferPointer(),b->GetBufferSize(),false);
  const char*glassVertex="float4 main(uint i:SV_VertexID):SV_Position{float2 p=float2(i==2?3:-1,i==1?3:-1);return float4(p,i?0.8:0.2,1);}";
  b=compile(glassVertex,strlen(glassVertex),"main","vs_5_0");hr(d->CreateVertexShader(b->GetBufferPointer(),b->GetBufferSize(),nullptr,&glassVs));edvr::uiDeferredRemember(glassVs.Get(),b->GetBufferPointer(),b->GetBufferSize(),false);
   D3D11_BUFFER_DESC bd{};bd.ByteWidth=32;bd.BindFlags=D3D11_BIND_CONSTANT_BUFFER;hr(d->CreateBuffer(&bd,nullptr,&cb));UINT indices[6]={0,1,2,2,1,3};bd={};bd.ByteWidth=sizeof(indices);bd.BindFlags=D3D11_BIND_INDEX_BUFFER;D3D11_SUBRESOURCE_DATA initial{indices,0,0};hr(d->CreateBuffer(&bd,&initial,&tailIb));bd={};bd.ByteWidth=8388624;bd.BindFlags=D3D11_BIND_SHADER_RESOURCE|D3D11_BIND_UNORDERED_ACCESS;bd.MiscFlags=D3D11_RESOURCE_MISC_BUFFER_STRUCTURED;bd.StructureByteStride=48;hr(d->CreateBuffer(&bd,nullptr,&tailStructured));D3D11_SHADER_RESOURCE_VIEW_DESC structuredView{};structuredView.Format=DXGI_FORMAT_UNKNOWN;structuredView.ViewDimension=D3D11_SRV_DIMENSION_BUFFER;structuredView.Buffer.NumElements=174763;hr(d->CreateShaderResourceView(tailStructured.Get(),&structuredView,&tailStructuredSrv));D3D11_UNORDERED_ACCESS_VIEW_DESC structuredUav{};structuredUav.Format=DXGI_FORMAT_UNKNOWN;structuredUav.ViewDimension=D3D11_UAV_DIMENSION_BUFFER;structuredUav.Buffer.NumElements=174763;hr(d->CreateUnorderedAccessView(tailStructured.Get(),&structuredUav,&tailStructuredUav));UINT zero[4]{};c->ClearUnorderedAccessViewUint(tailStructuredUav.Get(),zero);
   D3D11_DEPTH_STENCIL_DESC dd{};dd.DepthFunc=D3D11_COMPARISON_ALWAYS;hr(d->CreateDepthStencilState(&dd,&noDepth));dd.StencilEnable=TRUE;dd.StencilReadMask=1;dd.StencilWriteMask=5;dd.FrontFace=dd.BackFace={D3D11_STENCIL_OP_KEEP,D3D11_STENCIL_OP_KEEP,D3D11_STENCIL_OP_REPLACE,D3D11_COMPARISON_EQUAL};hr(d->CreateDepthStencilState(&dd,&uiDepth));
   dd={};dd.DepthEnable=FALSE;dd.StencilEnable=TRUE;dd.StencilReadMask=0;dd.StencilWriteMask=4;dd.FrontFace=dd.BackFace={D3D11_STENCIL_OP_KEEP,D3D11_STENCIL_OP_KEEP,D3D11_STENCIL_OP_REPLACE,D3D11_COMPARISON_ALWAYS};hr(d->CreateDepthStencilState(&dd,&tailDepth));
   dd={};dd.DepthEnable=TRUE;dd.DepthWriteMask=D3D11_DEPTH_WRITE_MASK_ZERO;dd.DepthFunc=D3D11_COMPARISON_GREATER_EQUAL;dd.StencilEnable=TRUE;dd.StencilReadMask=0;dd.StencilWriteMask=4;dd.FrontFace={D3D11_STENCIL_OP_KEEP,D3D11_STENCIL_OP_KEEP,D3D11_STENCIL_OP_REPLACE,D3D11_COMPARISON_ALWAYS};dd.BackFace={D3D11_STENCIL_OP_KEEP,D3D11_STENCIL_OP_KEEP,D3D11_STENCIL_OP_KEEP,D3D11_COMPARISON_ALWAYS};hr(d->CreateDepthStencilState(&dd,&glassDepth));
   D3D11_BLEND_DESC blend{};auto&r=blend.RenderTarget[0];r.BlendEnable=TRUE;r.SrcBlend=r.SrcBlendAlpha=D3D11_BLEND_ONE;r.DestBlend=r.DestBlendAlpha=D3D11_BLEND_INV_SRC_ALPHA;r.BlendOp=r.BlendOpAlpha=D3D11_BLEND_OP_ADD;r.RenderTargetWriteMask=15;hr(d->CreateBlendState(&blend,&over));r.DestBlend=r.DestBlendAlpha=D3D11_BLEND_ONE;hr(d->CreateBlendState(&blend,&add));r.DestBlend=r.DestBlendAlpha=D3D11_BLEND_DEST_ALPHA;hr(d->CreateBlendState(&blend,&destAlpha));r.SrcBlend=D3D11_BLEND_DEST_COLOR;hr(d->CreateBlendState(&blend,&unsupported));
   r.SrcBlend=r.SrcBlendAlpha=D3D11_BLEND_ONE;r.DestBlend=r.DestBlendAlpha=D3D11_BLEND_INV_SRC_ALPHA;r.RenderTargetWriteMask=7;hr(d->CreateBlendState(&blend,&tailBlend));
   blend={};auto&g=blend.RenderTarget[0];g.BlendEnable=TRUE;g.SrcBlend=g.SrcBlendAlpha=D3D11_BLEND_ONE;g.DestBlend=D3D11_BLEND_SRC1_COLOR;g.DestBlendAlpha=D3D11_BLEND_SRC1_ALPHA;g.BlendOp=g.BlendOpAlpha=D3D11_BLEND_OP_ADD;g.RenderTargetWriteMask=15;hr(d->CreateBlendState(&blend,&glassBlend));
  D3D11_RASTERIZER_DESC rd{};rd.FillMode=D3D11_FILL_SOLID;rd.CullMode=D3D11_CULL_NONE;rd.DepthClipEnable=TRUE;hr(d->CreateRasterizerState(&rd,&rs));
  D3D11_SAMPLER_DESC sd{};sd.Filter=D3D11_FILTER_MIN_MAG_MIP_LINEAR;sd.AddressU=sd.AddressV=sd.AddressW=D3D11_TEXTURE_ADDRESS_CLAMP;sd.MaxLOD=D3D11_FLOAT32_MAX;hr(d->CreateSamplerState(&sd,&sampler));
   hdr=surf(d.Get(),inW,inH,DXGI_FORMAT_R11G11B10_FLOAT);ldr=surf(d.Get(),inW,inH,DXGI_FORMAT_R8G8B8A8_UNORM);output=surf(d.Get(),outW,outH,DXGI_FORMAT_R8G8B8A8_UNORM);expected=surf(d.Get(),outW,outH,DXGI_FORMAT_R8G8B8A8_UNORM);expectedHdr=surf(d.Get(),outW,outH,DXGI_FORMAT_R11G11B10_FLOAT);
   D3D11_TEXTURE2D_DESC zd{};zd.Width=inW;zd.Height=inH;zd.MipLevels=zd.ArraySize=zd.SampleDesc.Count=1;zd.Format=DXGI_FORMAT_R24G8_TYPELESS;zd.BindFlags=D3D11_BIND_DEPTH_STENCIL|D3D11_BIND_SHADER_RESOURCE;hr(d->CreateTexture2D(&zd,nullptr,&z));D3D11_DEPTH_STENCIL_VIEW_DESC dv{};dv.Format=DXGI_FORMAT_D24_UNORM_S8_UINT;dv.ViewDimension=D3D11_DSV_DIMENSION_TEXTURE2D;hr(d->CreateDepthStencilView(z.Get(),&dv,&dsv));D3D11_SHADER_RESOURCE_VIEW_DESC sv{};sv.Format=DXGI_FORMAT_R24_UNORM_X8_TYPELESS;sv.ViewDimension=D3D11_SRV_DIMENSION_TEXTURE2D;sv.Texture2D.MipLevels=1;hr(d->CreateShaderResourceView(z.Get(),&sv,&zSrv));edvr::enabled=true;
   zd.Format=DXGI_FORMAT_R32G8X24_TYPELESS;hr(d->CreateTexture2D(&zd,nullptr,&tailZ));dv.Format=DXGI_FORMAT_D32_FLOAT_S8X24_UINT;hr(d->CreateDepthStencilView(tailZ.Get(),&dv,&tailDsv));
 }
 void constants(float jx,float jy,float alpha=.5){float values[8]={.3f,.12f,.03f,alpha,jx/inW,jy/inH,.25f,.75f};edvr::uiDeferredResourceWrite(c.Get(),cb.Get());c->UpdateSubresource(cb.Get(),0,nullptr,values,0,0);}
 void setup(edvr::Surface&s,UINT w,UINT h,ID3D11PixelShader*p,ID3D11BlendState*b,ID3D11DepthStencilView*depth){c->ClearState();c->RSSetState(rs.Get());D3D11_VIEWPORT vp{0,0,float(w),float(h),0,1};c->RSSetViewports(1,&vp);c->OMSetRenderTargets(1,s.rtv.GetAddressOf(),depth);bindings[unsigned(edvr::BindSlot::Rtv0)]=s.rtv.Get();bindings[unsigned(edvr::BindSlot::Dsv0)]=depth;++bindingGens[unsigned(edvr::BindSlot::Rtv0)];++bindingGens[unsigned(edvr::BindSlot::Dsv0)];c->OMSetBlendState(b,nullptr,~0u);c->OMSetDepthStencilState(depth?uiDepth.Get():noDepth.Get(),15);c->VSSetShader(vs.Get(),nullptr,0);c->PSSetShader(p,nullptr,0);c->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);c->VSSetConstantBuffers(0,1,cb.GetAddressOf());c->PSSetConstantBuffers(0,1,cb.GetAddressOf());c->PSSetSamplers(0,1,sampler.GetAddressOf());}
 void start(){edvr::uiDeferredFrameBoundary(c.Get());edvr::enabled=true;edvr::failed=edvr::routeNoted=false;edvr::resetPending[0]=edvr::resetPending[1]=false;vsHash=psHash=0;c->ClearState();c->ClearRenderTargetView(hdr.rtv.Get(),bg);c->ClearDepthStencilView(dsv.Get(),D3D11_CLEAR_DEPTH|D3D11_CLEAR_STENCIL,.6f,1);}
 void uiDraw(float jx,float jy,ID3D11BlendState*blend,bool defer){constants(jx,jy);setup(hdr,inW,inH,ui.Get(),blend,dsv.Get());edvr::uiDeferredTraceDrawEnter(c.Get(),true,'N',3,1,0,vsHash,psHash);edvr::uiDeferredBeforeDraw(c.Get(),'N',3,1,0,0,0,0);bool captured=defer&&edvr::uiDeferredBegin(c.Get(),0,'N',3,1,0,0,0);check(!defer||captured,"recognized UI captured");c->DrawInstanced(3,1,0,0);edvr::uiDeferredTraceOriginalIssued();if(captured)edvr::uiDeferredEnd(c.Get());}
 void toneDraw(bool defer,uint64_t variant=edvr::EyeTonemapSnapshot::kVs){constants(0,0);setup(ldr,inW,inH,tone.Get(),nullptr,nullptr);c->PSSetShaderResources(1,1,hdr.srv.GetAddressOf());vsHash=variant;psHash=edvr::EyeTonemapSnapshot::kPs;edvr::uiDeferredTraceDrawEnter(c.Get(),true,'N',3,1,0,vsHash,psHash);edvr::uiDeferredBeforeDraw(c.Get(),'N',3,1,0,0,0,0);if(defer){edvr::uiDeferredTraceBeforeTone(c.Get());edvr::uiDeferredBeforeTone(c.Get(),'N',3,1,0,0,0);check(!edvr::uiDeferredBegin(c.Get(),-1,'N',3,1,0,0,0),"full wrapper tone has no later world mirror");}c->DrawInstanced(3,1,0,0);edvr::uiDeferredTraceOriginalIssued();if(defer)edvr::uiDeferredEnd(c.Get());}
 void candidateDraw(edvr::Surface&target,ID3D11ShaderResourceView*source,uint64_t vh,uint64_t ph){constants(0,0);setup(target,inW,inH,postTone.Get(),nullptr,nullptr);c->PSSetShaderResources(0,1,&source);vsHash=vh;psHash=ph;edvr::uiDeferredTraceDrawEnter(c.Get(),true,'N',3,1,0,vh,ph);edvr::uiDeferredBeforeDraw(c.Get(),'N',3,1,0,0,0,0);edvr::uiDeferredTraceBeforeTone(c.Get());c->DrawInstanced(3,1,0,0);edvr::uiDeferredTraceOriginalIssued();edvr::uiDeferredEnd(c.Get());}
 void postToneDraw(edvr::Surface&target,ID3D11ShaderResourceView*source,bool allow=true){constants(0,0);setup(target,inW,inH,postTone.Get(),nullptr,nullptr);c->VSSetShader(postVs.Get(),nullptr,0);c->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP);c->PSSetShaderResources(0,1,&source);vsHash=edvr::kPostToneVs;psHash=edvr::kPostTonePs;edvr::uiDeferredTraceDrawEnter(c.Get(),true,'N',4,1,0,vsHash,psHash);edvr::uiDeferredBeforeDraw(c.Get(),'N',4,1,0,0,0,allow?0:7);edvr::uiDeferredTraceBeforeTone(c.Get());edvr::uiDeferredBegin(c.Get(),-1,'N',4,1,0,0,0);c->DrawInstanced(4,1,0,0);edvr::uiDeferredTraceOriginalIssued();edvr::uiDeferredEnd(c.Get());}
 bool tailDraw(edvr::Surface&target,ID3D11ShaderResourceView*source,float jx,float jy,uint32_t verdict=0){constants(jx,jy);setup(target,inW,inH,postTone.Get(),tailBlend.Get(),tailDsv.Get());c->OMSetDepthStencilState(tailDepth.Get(),4);c->VSSetShader(tailVs.Get(),nullptr,0);c->VSSetShaderResources(38,1,tailStructuredSrv.GetAddressOf());c->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);c->IASetIndexBuffer(tailIb.Get(),DXGI_FORMAT_R32_UINT,0);c->PSSetShaderResources(0,1,&source);vsHash=edvr::kTailVs;psHash=edvr::kTailPs;edvr::uiDeferredTraceDrawEnter(c.Get(),true,'X',6,1,verdict,vsHash,psHash);edvr::uiDeferredBeforeDraw(c.Get(),'X',6,1,0,0,0,verdict);edvr::uiDeferredTraceBeforeTone(c.Get());const bool handled=edvr::uiDeferredBegin(c.Get(),0,'X',6,1,0,0,0);c->DrawIndexedInstanced(6,1,0,0,0);edvr::uiDeferredTraceOriginalIssued();edvr::uiDeferredEnd(c.Get());return handled;}
 void baselineNative(ID3D11BlendState*b){constants(0,0);c->ClearRenderTargetView(expectedHdr.rtv.Get(),bg);setup(expectedHdr,outW,outH,ui.Get(),b,nullptr);c->DrawInstanced(3,1,0,0);setup(expected,outW,outH,tone.Get(),nullptr,nullptr);c->PSSetShaderResources(1,1,expectedHdr.srv.GetAddressOf());c->DrawInstanced(3,1,0,0);}
 ~Harness(){edvr::uiDeferredShutdown();c->ClearState();}
};
static void setupGlass(Harness& h,UINT sampleMask=~0u) {
 h.constants(0,0);h.setup(h.hdr,h.inW,h.inH,h.glass.Get(),h.glassBlend.Get(),h.dsv.Get());
 h.c->OMSetBlendState(h.glassBlend.Get(),nullptr,sampleMask);h.c->OMSetDepthStencilState(h.glassDepth.Get(),4);
 h.c->VSSetShader(h.glassVs.Get(),nullptr,0);h.c->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);h.c->IASetIndexBuffer(h.tailIb.Get(),DXGI_FORMAT_R32_UINT,0);
 vsHash=edvr::kUiDeferredGlassVs;psHash=edvr::kUiDeferredGlassPs;shaderHashes[h.glassVs.Get()]=edvr::kUiDeferredGlassVs;shaderHashes[h.glass.Get()]=edvr::kUiDeferredGlassPs;
}
static void glassReplayTests(Harness& h) {
 auto*d=h.d.Get();auto*c=h.c.Get();
 const auto replayCount=edvr::glassReplays;
 h.start();c->ClearDepthStencilView(h.dsv.Get(),D3D11_CLEAR_DEPTH|D3D11_CLEAR_STENCIL,.4f,1);h.uiDraw(0,0,h.over.Get(),true);const auto cleanInitial=read(d,c,edvr::eyes[0].cleanHdr.tex.Get());setupGlass(h);
 check(!edvr::uiDeferredBegin(c,-1,'X',3,1,0,0,0,0,false),"exact dual-source glass schedules a direct world replay");
 c->DrawIndexedInstanced(3,1,0,0,0);const auto originalColour=read(d,c,h.hdr.tex.Get()),originalDepth=read(d,c,h.z.Get());
 check(edvr::uiDeferredWorldReplayBegin(c),"issued glass draw binds the private clean target");c->DrawIndexedInstanced(3,1,0,0,0);edvr::uiDeferredEnd(c);
 check(read(d,c,h.hdr.tex.Get())==originalColour,"glass replay leaves original HDR colour unchanged");
 check(read(d,c,h.z.Get())==originalDepth,"glass replay leaves original depth and stencil unchanged");
 ID3D11RenderTargetView* restoredTarget=nullptr;ID3D11DepthStencilView* restoredDepth=nullptr;c->OMGetRenderTargets(1,&restoredTarget,&restoredDepth);ComPtr<ID3D11RenderTargetView> retainedTarget;ComPtr<ID3D11DepthStencilView> retainedDepth;retainedTarget.Attach(restoredTarget);retainedDepth.Attach(restoredDepth);
 ComPtr<ID3D11VertexShader> restoredVs;c->VSGetShader(&restoredVs,nullptr,nullptr);ComPtr<ID3D11PixelShader> restoredPs;c->PSGetShader(&restoredPs,nullptr,nullptr);ComPtr<ID3D11BlendState> restoredBlend;UINT restoredMask=0;c->OMGetBlendState(&restoredBlend,nullptr,&restoredMask);ComPtr<ID3D11DepthStencilState> restoredState;UINT restoredRef=0;c->OMGetDepthStencilState(&restoredState,&restoredRef);
 check(retainedTarget.Get()==h.hdr.rtv.Get() && retainedDepth.Get()==h.dsv.Get() && restoredVs.Get()==h.glassVs.Get() && restoredPs.Get()==h.glass.Get() && restoredBlend.Get()==h.glassBlend.Get() && restoredMask==~0u && restoredState.Get()==h.glassDepth.Get() && restoredRef==4,"glass replay restores render, shaders, blend and depth/stencil state exactly");
 check(!edvr::uiDeferredWorldReplayBegin(c),"completed glass replay cannot issue twice");
 check(edvr::glassReplays==replayCount+1,"successful glass replay increments the bounded runtime counter");
 auto expected=surf(d,h.inW,h.inH,DXGI_FORMAT_R11G11B10_FLOAT);c->ClearRenderTargetView(expected.rtv.Get(),h.bg);ID3D11RenderTargetView* expectedTarget=expected.rtv.Get();c->OMSetRenderTargets(1,&expectedTarget,h.dsv.Get());c->OMSetBlendState(h.glassBlend.Get(),nullptr,~0u);c->OMSetDepthStencilState(h.glassDepth.Get(),4);c->VSSetShader(h.glassVs.Get(),nullptr,0);c->PSSetShader(h.glass.Get(),nullptr,0);c->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);c->IASetIndexBuffer(h.tailIb.Get(),DXGI_FORMAT_R32_UINT,0);c->DrawIndexedInstanced(3,1,0,0,0);
 const auto cleanFinal=read(d,c,edvr::eyes[0].cleanHdr.tex.Get()),expectedFinal=read(d,c,expected.tex.Get());check(cleanFinal==expectedFinal,"private clean HDR receives the exact nontrivial dual-source glass equation");size_t changed=0,unchanged=0;for(size_t i=0;i<cleanFinal.size();i+=4)(memcmp(cleanFinal.data()+i,cleanInitial.data()+i,4)?changed:unchanged)++;check(changed && unchanged,"glass fixture covers both depth-pass and depth-fail pixels");

 h.start();c->ClearDepthStencilView(h.dsv.Get(),D3D11_CLEAR_DEPTH|D3D11_CLEAR_STENCIL,.4f,1);h.uiDraw(0,0,h.over.Get(),true);const auto cleanBefore=read(d,c,edvr::eyes[0].cleanHdr.tex.Get());setupGlass(h);const auto issuedReplayCount=edvr::glassReplays;check(!edvr::uiDeferredBegin(c,-1,'X',3,1,0,0,0,0,false),"exact glass can be pending before an unissued original");edvr::uiDeferredEnd(c);check(!edvr::uiDeferredWorldReplayBegin(c) && read(d,c,edvr::eyes[0].cleanHdr.tex.Get())==cleanBefore,"unissued original is ended without a private replay");check(edvr::glassReplays==issuedReplayCount,"abandoned glass draw does not record a successful replay");
 auto guarded=[&](UINT verdict,bool query,UINT mask,const char* reason){h.start();c->ClearDepthStencilView(h.dsv.Get(),D3D11_CLEAR_DEPTH|D3D11_CLEAR_STENCIL,.4f,1);h.uiDraw(0,0,h.over.Get(),true);setupGlass(h,mask);check(!edvr::uiDeferredBegin(c,-1,'X',3,1,0,0,0,verdict,query) && edvr::failed && !edvr::uiDeferredWorldReplayBegin(c),reason);edvr::uiDeferredEnd(c);};
 guarded(0,true,~0u,"counting query blocks glass replay and retains fallback");
 guarded(7,false,~0u,"non-kNone wrapper verdict blocks glass replay and retains fallback");
 guarded(0,false,0x7fffffffu,"non-full sample mask blocks glass replay and retains fallback");
 shaderHashes.erase(h.glassVs.Get());shaderHashes.erase(h.glass.Get());vsHash=psHash=0;
}
int main(int argc,char**argv){
 if(argc==3 && strcmp(argv[1],"--fanout")==0){
  std::ifstream input(argv[2],std::ios::binary);check(bool(input),"captured shader opened");
  std::vector<BYTE> code((std::istreambuf_iterator<char>(input)),{}),patched;std::string why;
  const bool ok=edvr::uiColourFanout(code.data(),code.size(),patched,why);check(ok,why.c_str());
  ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>c;D3D_FEATURE_LEVEL level{};hr(D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,&level,&c));
  ComPtr<ID3D11PixelShader>ps;hr(d->CreatePixelShader(patched.data(),patched.size(),nullptr,&ps));
  printf("Captured shader fanout: %zu -> %zu bytes, %u checks passed.\n",code.size(),patched.size(),checks);return 0;
 }
 if(argc>1 && strcmp(argv[1],"--benchmark")==0){
  Harness h(true,2644,4068,2610,4016);auto*c=h.c.Get();auto*d=h.d.Get();auto post=surf(d,2644,2610,DXGI_FORMAT_R8G8B8A8_UNORM),tailSource=surf(d,512,512,DXGI_FORMAT_R8G8B8A8_UNORM);
  ComPtr<IDXGIDevice> gd;ComPtr<IDXGIAdapter> adapter;DXGI_ADAPTER_DESC adapterDesc{};hr(d->QueryInterface(IID_PPV_ARGS(&gd)));hr(gd->GetAdapter(&adapter));hr(adapter->GetDesc(&adapterDesc));wprintf(L"GPU: %s\n",adapterDesc.Description);
  D3D11_QUERY_DESC qd{D3D11_QUERY_TIMESTAMP_DISJOINT,0};ComPtr<ID3D11Query> freq,a,b;hr(d->CreateQuery(&qd,&freq));qd.Query=D3D11_QUERY_TIMESTAMP;hr(d->CreateQuery(&qd,&a));hr(d->CreateQuery(&qd,&b));double gpu=0,cpu=0;unsigned samples=0;
  for(unsigned frame=0;frame<24;++frame){h.start();h.uiDraw(.25f,-.25f,h.over.Get(),true);h.toneDraw(true);h.postToneDraw(post,h.ldr.srv.Get());check(h.tailDraw(post,tailSource.srv.Get(),.25f,-.25f),"benchmark terminal capture");auto begin=std::chrono::steady_clock::now();check(edvr::uiDeferredPrepare(c,post.tex.Get(),h.zSrv.Get(),h.output.tex.Get(),0,h.inW,h.inH,.25f,-.25f)!=nullptr,"benchmark prepare");auto end=std::chrono::steady_clock::now();c->Begin(freq.Get());c->End(a.Get());edvr::uiDeferredApply(c,0);c->End(b.Get());c->End(freq.Get());D3D11_QUERY_DATA_TIMESTAMP_DISJOINT f{};HRESULT result;do{result=c->GetData(freq.Get(),&f,sizeof(f),0);}while(result==S_FALSE);hr(result);UINT64 ta=0,tb=0;hr(c->GetData(a.Get(),&ta,sizeof(ta),0));hr(c->GetData(b.Get(),&tb,sizeof(tb),0));check(!f.Disjoint,"stable timestamps");if(frame>=4){gpu+=double(tb-ta)*1000/f.Frequency;cpu+=std::chrono::duration<double,std::milli>(end-begin).count();++samples;}}
  printf("Native sampled/tail replay 2644x2610 -> 4068x4016: GPU %.4f ms/eye, prepare CPU %.4f ms/eye, snapshots %.2f MiB, stencil-in-PS=%d (%u samples). Synthetic one HDR UI draw, retained sampled map and one terminal canvas; excludes DLSS, game rendering, pre-tone work and full game materials.\n",gpu/samples,cpu/samples,edvr::snapshots.allocatedBytes()/1048576.,edvr::renderer.depth.usesSpecifiedStencilRef(),samples);return 0;
 }
 bool hardware=argc>1&&strcmp(argv[1],"--hardware")==0;
 fanoutDestinationTests();fanoutGpuDifferential(hardware);strippedDeclarationTests(hardware);
 for(UINT scale:{1u,2u})for(float j:{0.f,.25f,-.25f}){
  Harness h(hardware,8,8*scale);auto*d=h.d.Get();auto*c=h.c.Get();
  if(scale==1 && j==0){
   glassReplayTests(h);
   UINT first[4]={1,2,3,4},second[4]={5,6,7,8};D3D11_BUFFER_DESC bd{};bd.ByteWidth=sizeof(first);bd.BindFlags=D3D11_BIND_SHADER_RESOURCE|D3D11_BIND_UNORDERED_ACCESS;bd.MiscFlags=D3D11_RESOURCE_MISC_BUFFER_STRUCTURED;bd.StructureByteStride=sizeof(UINT);D3D11_SUBRESOURCE_DATA initial{first,0,0};ComPtr<ID3D11Buffer>source;hr(d->CreateBuffer(&bd,&initial,&source));ComPtr<ID3D11Resource>before,after;check(!edvr::snapshots.capture(c,source.Get(),before,true),"ordinary reflected capture still rejects UAV-capable buffers");check(edvr::snapshots.capture(c,source.Get(),before,true,true),"terminal opt-in supports UAV-capable reflected structured buffer snapshot");c->UpdateSubresource(source.Get(),0,nullptr,second,0,0);check(edvr::snapshots.capture(c,source.Get(),after,true,true),"opted-in reflected buffer can be captured again without write-hook evidence");ComPtr<ID3D11Buffer>beforeBuffer,afterBuffer;hr(before.As(&beforeBuffer));hr(after.As(&afterBuffer));D3D11_BUFFER_DESC copyDesc{};beforeBuffer->GetDesc(&copyDesc);check(before.Get()!=after.Get() && copyDesc.ByteWidth==sizeof(first) && copyDesc.StructureByteStride==sizeof(UINT) && copyDesc.MiscFlags==D3D11_RESOURCE_MISC_BUFFER_STRUCTURED && copyDesc.BindFlags==D3D11_BIND_SHADER_RESOURCE,"volatile reflected UAV buffer uses fresh SRV-only structured clones");check(readBuffer(d,c,beforeBuffer.Get())==std::vector<BYTE>((BYTE*)first,(BYTE*)first+sizeof(first)) && readBuffer(d,c,afterBuffer.Get())==std::vector<BYTE>((BYTE*)second,(BYTE*)second+sizeof(second)),"fresh reflected UAV snapshots preserve each captured buffer version");
    h.start();h.uiDraw(0,0,h.over.Get(),true);ComPtr<ID3D11Resource>tracked0,trackedSame,trackedCs,trackedOm;check(edvr::snapshots.capture(c,h.tailStructured.Get(),tracked0,true,false,true),"tracked panel t38 first snapshot");check(edvr::snapshots.capture(c,h.tailStructured.Get(),trackedSame,true,false,true) && trackedSame==tracked0,"tracked panel t38 reuses an unchanged version");ID3D11UnorderedAccessView*uav=h.tailStructuredUav.Get();c->CSSetUnorderedAccessViews(0,1,&uav,nullptr);edvr::uiDeferredBeforeDispatch(c);UINT csValue[4]={1,2,3,4};c->ClearUnorderedAccessViewUint(uav,csValue);ID3D11UnorderedAccessView*nullUav=nullptr;c->CSSetUnorderedAccessViews(0,1,&nullUav,nullptr);check(edvr::snapshots.capture(c,h.tailStructured.Get(),trackedCs,true,false,true) && trackedCs!=tracked0,"CS UAV callback advances tracked panel t38 version");c->OMSetRenderTargetsAndUnorderedAccessViews(0,nullptr,nullptr,0,1,&uav,nullptr);edvr::uiDeferredBeforeDraw(c,'N',3,1,0,0,0,0);UINT omValue[4]={5,6,7,8};c->ClearUnorderedAccessViewUint(uav,omValue);c->OMSetRenderTargetsAndUnorderedAccessViews(0,nullptr,nullptr,0,1,&nullUav,nullptr);check(edvr::snapshots.capture(c,h.tailStructured.Get(),trackedOm,true,false,true) && trackedOm!=trackedCs,"OM UAV draw callback advances tracked panel t38 version");ComPtr<ID3D11Buffer>tracked0Buffer,trackedCsBuffer,trackedOmBuffer;hr(tracked0.As(&tracked0Buffer));hr(trackedCs.As(&trackedCsBuffer));hr(trackedOm.As(&trackedOmBuffer));const auto initialBytes=readBuffer(d,c,tracked0Buffer.Get()),csBytes=readBuffer(d,c,trackedCsBuffer.Get()),omBytes=readBuffer(d,c,trackedOmBuffer.Get());UINT iv[4]{},cv[4]{},ov[4]{};memcpy(iv,initialBytes.data(),sizeof(iv));memcpy(cv,csBytes.data(),sizeof(cv));memcpy(ov,omBytes.data(),sizeof(ov));const bool versions=initialBytes!=csBytes && csBytes!=omBytes;if(!versions)fprintf(stderr,"tracked t38 first words initial=%u,%u,%u,%u cs=%u,%u,%u,%u om=%u,%u,%u,%u\n",iv[0],iv[1],iv[2],iv[3],cv[0],cv[1],cv[2],cv[3],ov[0],ov[1],ov[2],ov[3]);check(versions,"tracked panel t38 retains each CS/OM-written payload version");
   }
  {
   wchar_t scratch[MAX_PATH],shaderPath[MAX_PATH],missingPath[MAX_PATH];_snwprintf_s(scratch,_TRUNCATE,L"build\\obj\\uideferredtest\\producer_shader_%lu",GetCurrentProcessId());CreateDirectoryW(scratch,nullptr);edvr::writerShaderDir=scratch;edvr::writerShaderKeys={};edvr::writerShaderCount=edvr::writerShaderReports=0;
   UINT shaderBytes=0;h.vs->GetPrivateData(edvr::kDeferredBytes,&shaderBytes,nullptr);std::vector<BYTE> expectedShader(shaderBytes);hr(h.vs->GetPrivateData(edvr::kDeferredBytes,&shaderBytes,expectedShader.data()));
   edvr::writeProducerShader(L"vs",0x1234,h.vs.Get());_snwprintf_s(shaderPath,_TRUNCATE,L"%s\\vs_%016llX.dxbc",scratch,0x1234ull);check(readFile(shaderPath)==expectedShader && edvr::writerShaderCount==1,"retained producer shader is exported byte for byte");
   {HANDLE f=CreateFileW(shaderPath,GENERIC_WRITE,0,nullptr,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,nullptr);check(f!=INVALID_HANDLE_VALUE,"shader repeat sentinel opened");BYTE sentinel=0x5a;DWORD written=0;check(WriteFile(f,&sentinel,1,&written,nullptr)&&written==1,"shader repeat sentinel written");CloseHandle(f);}edvr::writeProducerShader(L"vs",0x1234,h.vs.Get());check(readFile(shaderPath)==std::vector<BYTE>{0x5a} && edvr::writerShaderCount==1,"repeat stage/hash is neither rewritten nor recounted");
   const char*rawSource="float4 main():SV_Target{return 1;}";auto rawBytes=compile(rawSource,strlen(rawSource),"main","ps_5_0");ComPtr<ID3D11PixelShader>rawShader;hr(d->CreatePixelShader(rawBytes->GetBufferPointer(),rawBytes->GetBufferSize(),nullptr,&rawShader));const auto reports=edvr::writerShaderReports;edvr::writeProducerShader(L"ps",0x2345,rawShader.Get());_snwprintf_s(missingPath,_TRUNCATE,L"%s\\ps_%016llX.dxbc",scratch,0x2345ull);check(GetFileAttributesW(missingPath)==INVALID_FILE_ATTRIBUTES && edvr::writerShaderCount==2 && edvr::writerShaderReports==reports+1,"missing producer bytecode is explicit and creates no file");
   for(unsigned i=0;i<6;++i)edvr::writeProducerShader(L"vs",0x3000+i,h.vs.Get());const auto cappedReports=edvr::writerShaderReports;edvr::writeProducerShader(L"vs",0x4000,h.vs.Get());check(edvr::writerShaderCount==8 && edvr::writerShaderReports==cappedReports+1,"producer shader export cap is explicit");
   WIN32_FIND_DATAW fd{};wchar_t pattern[MAX_PATH];_snwprintf_s(pattern,_TRUNCATE,L"%s\\*",scratch);HANDLE find=FindFirstFileW(pattern,&fd);if(find!=INVALID_HANDLE_VALUE){do{if(wcscmp(fd.cFileName,L".")&&wcscmp(fd.cFileName,L"..")){wchar_t file[MAX_PATH];_snwprintf_s(file,_TRUNCATE,L"%s\\%s",scratch,fd.cFileName);DeleteFileW(file);}}while(FindNextFileW(find,&fd));FindClose(find);}RemoveDirectoryW(scratch);edvr::writerShaderDir.clear();edvr::writerShaderKeys={};edvr::writerShaderCount=edvr::writerShaderReports=0;
  }
  {
   edvr::clearWriterTrace();h.start();h.toneDraw(true);h.uiDraw(j,-j,h.over.Get(),true);auto post=surf(d,8,8,DXGI_FORMAT_R8G8B8A8_UNORM);h.postToneDraw(post,h.ldr.srv.Get());
   check(edvr::lastProducer.target.Get()==h.ldr.tex.Get() && edvr::lastProducer.entryVs==edvr::EyeTonemapSnapshot::kVs && edvr::lastProducer.entryPs==edvr::EyeTonemapSnapshot::kPs,"early pre-capture tone is retained as sampled-blit writer");
   check(edvr::lastProducer.reachedBeforeTone && edvr::lastProducer.originalIssued && edvr::lastIssuedProducer.serial==edvr::lastProducer.serial,"tone wrapper entry, pre-tone reach and original issue are connected");
   check(edvr::lastProducer.actualEntryVs==0x111 && edvr::lastProducer.actualEntryPs==0x333 && edvr::lastProducer.actualBeforeVs==0x111 && edvr::lastProducer.actualBeforePs==0x333,"actual entry and pre-tone shader hashes are retained");
   edvr::clearWriterTrace();h.setup(h.ldr,8,8,h.postTone.Get(),nullptr,nullptr);vsHash=0xabc;psHash=0xdef;edvr::uiDeferredTraceDrawEnter(c,true,'X',6,2,7,vsHash,psHash);edvr::uiDeferredTraceBeforeTone(c);edvr::reportProducer(h.ldr.tex.Get());
   check(edvr::lastProducer.entryVs==0xabc && edvr::lastProducer.entryPs==0xdef && !edvr::lastProducer.originalIssued && !edvr::lastIssuedProducer.target,"alternate skipped attempt is reported without being called a producer");
   check(edvr::lastProducer.actualEntryVs==0x111 && edvr::lastProducer.actualEntryPs==0x444 && edvr::lastProducer.actualBeforeVs==0x111 && edvr::lastProducer.actualBeforePs==0x444,"actual hashes expose shadow divergence at entry and pre-tone");
   c->DrawInstanced(3,1,0,0);edvr::uiDeferredTraceOriginalIssued();edvr::reportProducer(h.ldr.tex.Get());
   check(edvr::lastIssuedProducer.serial==edvr::lastProducer.serial,"issued alternative producer is distinguished from skipped attempt");
   edvr::uiDeferredResourceWrite(c,h.ldr.tex.Get());check(!edvr::producerFor(h.ldr.tex.Get()),"known resource write invalidates older observed draws");
   edvr::clearWriterTrace();std::vector<edvr::Surface> history;history.reserve(edvr::kWriterTraceCount+1);
   for(size_t i=0;i<=edvr::kWriterTraceCount;++i){history.push_back(surf(d,8,8,DXGI_FORMAT_R8G8B8A8_UNORM));h.candidateDraw(history.back(),h.hdr.srv.Get(),0x500+i,0x600+i);}
   check(!edvr::producerFor(history.front().tex.Get()) && edvr::producerFor(history.back().tex.Get()),"24-slot history evicts oldest resource identity without stale match");
   D3D11_TEXTURE2D_DESC td{};td.Width=td.Height=8;td.MipLevels=td.ArraySize=td.SampleDesc.Count=1;td.Format=DXGI_FORMAT_R8G8B8A8_TYPELESS;td.BindFlags=D3D11_BIND_RENDER_TARGET|D3D11_BIND_SHADER_RESOURCE;edvr::Surface typeless;hr(d->CreateTexture2D(&td,nullptr,&typeless.tex));D3D11_RENDER_TARGET_VIEW_DESC rd{};rd.Format=DXGI_FORMAT_R8G8B8A8_UNORM;rd.ViewDimension=D3D11_RTV_DIMENSION_TEXTURE2D;hr(d->CreateRenderTargetView(typeless.tex.Get(),&rd,&typeless.rtv));D3D11_SHADER_RESOURCE_VIEW_DESC sd{};sd.Format=DXGI_FORMAT_R8G8B8A8_UNORM;sd.ViewDimension=D3D11_SRV_DIMENSION_TEXTURE2D;sd.Texture2D.MipLevels=1;hr(d->CreateShaderResourceView(typeless.tex.Get(),&sd,&typeless.srv));
   h.candidateDraw(typeless,h.hdr.srv.Get(),0x777,0x888);check(edvr::producerFor(typeless.tex.Get())!=nullptr,"typeless eye resource with UNORM RTV is retained");
   const auto tq=edvr::writerTargetQueries,sq=edvr::writerShaderQueries;edvr::enabled=false;edvr::diagnosticUntilGeneration=0;h.setup(h.ldr,8,8,h.tone.Get(),nullptr,nullptr);edvr::uiDeferredTraceDrawEnter(c,true,'N',3,1,0,1,2);edvr::uiDeferredTraceBeforeTone(c);check(edvr::writerTargetQueries==tq && edvr::writerShaderQueries==sq,"expired diagnostic performs no target or shader queries");edvr::enabled=true;
  }
  {
   const auto before=edvr::diagnostic;h.start();h.uiDraw(j,-j,h.over.Get(),true);auto submitted=surf(d,8,8,DXGI_FORMAT_R8G8B8A8_UNORM);
   check(!edvr::uiDeferredPrepare(c,submitted.tex.Get(),h.zSrv.Get(),h.output.tex.Get(),0,8,8,j,-j),"prepare before tone reproduces route failure");
   check(edvr::diagnostic.captures==before.captures+1 && edvr::diagnostic.prepares==before.prepares+1,"early route diagnostic sees capture and prepare");
   check(edvr::diagnostic.toneObservations==before.toneObservations && edvr::diagnostic.toneAliases==before.toneAliases,"early route diagnostic proves no tone observation or alias");
   const auto failed=edvr::diagnostic;const auto toneLogs=edvr::toneReports,postLogs=edvr::postToneReports,lateLogs=edvr::lateCompositeReports,boundaryLogs=edvr::boundaryReports;
   h.toneDraw(true);auto post=surf(d,8,8,DXGI_FORMAT_R8G8B8A8_UNORM);h.postToneDraw(post,h.ldr.srv.Get());h.candidateDraw(submitted,h.ldr.srv.Get(),0xA888D51024D9798Eull,0x015EF9349EC097E8ull);
   check(!edvr::enabled && edvr::diagnostic.toneObservations==failed.toneObservations+1 && edvr::diagnostic.toneAliases==failed.toneAliases,"post-failure tone is observed without replay or state reactivation");
   check(edvr::diagnostic.postToneCandidates==failed.postToneCandidates+1 && edvr::diagnostic.lateCompositeCandidates==failed.lateCompositeCandidates+1,"post-failure route candidates remain observable");
   check(edvr::toneReports==toneLogs+1 && edvr::postToneReports==postLogs+1 && edvr::lateCompositeReports==lateLogs+1,"post-failure observations emit bounded trace messages");
   const auto boundary=edvr::diagnostic.boundaries;edvr::uiDeferredFrameBoundary(c);check(edvr::diagnostic.boundaries==boundary+1 && edvr::boundaryReports==boundaryLogs+1,"failed capture is reported before its first boundary clear");
   const auto next=edvr::diagnostic;h.toneDraw(true);h.postToneDraw(post,h.ldr.srv.Get());
   check(edvr::diagnostic.toneObservations==next.toneObservations+1 && edvr::diagnostic.postToneCandidates==next.postToneCandidates+1,"diagnostic window observes the frame following failure");
   edvr::uiDeferredFrameBoundary(c);check(edvr::diagnostic.boundaries==boundary+2,"diagnostic window reports two boundaries");
   const auto expired=edvr::diagnostic;h.toneDraw(true);h.postToneDraw(post,h.ldr.srv.Get());
   check(edvr::diagnostic.toneObservations==expired.toneObservations && edvr::diagnostic.postToneCandidates==expired.postToneCandidates,"post-failure diagnostic window expires after two boundaries");
  }
  {
    h.start();h.uiDraw(j,-j,h.over.Get(),true);const auto before=edvr::diagnostic;h.toneDraw(true);
   check(edvr::diagnostic.toneObservations==before.toneObservations+1 && edvr::diagnostic.toneAliases==before.toneAliases+1,"full wrapper tone wires observation and alias diagnostics");
   check(edvr::eyes[0].complete && edvr::eyes[0].aliases.size()==1,"full wrapper tone leaves a complete route");
   auto post=surf(d,8,8,DXGI_FORMAT_R8G8B8A8_UNORM);const auto afterTone=edvr::diagnostic;h.postToneDraw(post,h.ldr.srv.Get());
   check(edvr::diagnostic.postToneCandidates==afterTone.postToneCandidates+1,"post-tone sampled blit diagnostic is wired");
    check(edvr::eyes[0].complete && edvr::eyes[0].postTone.ready() && edvr::eyes[0].aliases.front().Get()==post.tex.Get(),"sampled blit advances the alias to its exact destination");
    auto*sampledClean=edvr::uiDeferredPrepare(c,post.tex.Get(),h.zSrv.Get(),h.output.tex.Get(),0,8,8,j,-j);check(sampledClean,"sampled blit destination prepares through retained route");ComPtr<ID3D11Resource>sampledResource;sampledClean->GetResource(&sampledResource);check(sampledResource.Get()==edvr::eyes[0].cleanFinal.tex.Get(),"sampled route publishes clean final rather than pre-blit tone");
  }
  {
   h.start();h.uiDraw(j,-j,h.over.Get(),true);h.toneDraw(true,edvr::kToneVsConstantExposure);check(edvr::eyes[0].complete && edvr::eyes[0].tone.originalVertexShader()==h.vs.Get(),"constant-exposure tone variant captures its live vertex shader");
   h.start();h.uiDraw(j,-j,h.over.Get(),true);const auto observations=edvr::diagnostic.toneObservations;h.toneDraw(true,0x123456789ABCDEF0ull);check(!edvr::eyes[0].complete && !edvr::failed && edvr::diagnostic.toneObservations==observations,"unknown tone vertex variant is ignored without weakening fallback");h.toneDraw(true);check(edvr::eyes[0].complete,"known sampled-exposure tone remains accepted after unknown variant");
  }
  {
   h.start();h.uiDraw(j,-j,h.over.Get(),true);h.toneDraw(true);auto post=surf(d,8,8,DXGI_FORMAT_R8G8B8A8_UNORM);h.postToneDraw(post,h.ldr.srv.Get(),false);
   check(edvr::eyes[0].complete && !edvr::eyes[0].postTone.ready() && edvr::eyes[0].aliases.front().Get()==h.ldr.tex.Get(),"nonzero-verdict sampled draw cannot advance route alias or retain packet");
  }
  {
   h.start();h.uiDraw(j,-j,h.over.Get(),true);h.toneDraw(true);auto post=surf(d,8,8,DXGI_FORMAT_R8G8B8A8_UNORM),tailSource=surf(d,8,8,DXGI_FORMAT_R8G8B8A8_UNORM),tailOriginal=surf(d,8,8,DXGI_FORMAT_R8G8B8A8_UNORM),mappedExpected=surf(d,h.outW,h.outH,DXGI_FORMAT_R8G8B8A8_UNORM),mappedTransmission=surf(d,h.outW,h.outH,DXGI_FORMAT_R32_FLOAT);
   h.postToneDraw(post,h.ldr.srv.Get());const float tailColour[4]={.8f,.1f,.05f,.5f};c->ClearRenderTargetView(tailSource.rtv.Get(),tailColour);c->CopyResource(tailOriginal.tex.Get(),tailSource.tex.Get());check(h.tailDraw(post,tailSource.srv.Get(),j,-j),"exact terminal canvas consumes handled token and suppresses legacy decline");
   check(edvr::eyes[0].tails.size()==1 && edvr::diagnostic.tailCaptures,"terminal canvas packet is retained once");ComPtr<ID3D11Resource>capturedStructured;edvr::eyes[0].tails[0]->vsResource(38)->GetResource(&capturedStructured);ComPtr<ID3D11Buffer>capturedStructuredBuffer;hr(capturedStructured.As(&capturedStructuredBuffer));D3D11_BUFFER_DESC capturedDesc{};capturedStructuredBuffer->GetDesc(&capturedDesc);check(capturedDesc.ByteWidth==8388624 && capturedDesc.StructureByteStride==48 && capturedDesc.MiscFlags==D3D11_RESOURCE_MISC_BUFFER_STRUCTURED && capturedDesc.BindFlags==D3D11_BIND_SHADER_RESOURCE,"terminal packet captures exact-size UAV-capable t38 as an SRV-only structured snapshot");auto originalGame=read(d,c,post.tex.Get());
   edvr::uiDeferredResourceWrite(c,tailSource.tex.Get());const float changed[4]={.05f,.9f,.2f,.9f};c->ClearRenderTargetView(tailSource.rtv.Get(),changed);UINT changedStructured[4]={0x41200000u,0x41200000u,0x41200000u,0x41200000u};c->ClearUnorderedAccessViewUint(h.tailStructuredUav.Get(),changedStructured);h.constants(-j,j,.9f);
   auto*clean=edvr::uiDeferredPrepare(c,post.tex.Get(),h.zSrv.Get(),h.output.tex.Get(),0,8,8,j,-j);check(clean,"sampled route with terminal canvas prepares");float world[4]={h.bg[0]/(1+h.bg[0]),h.bg[1]/(1+h.bg[1]),h.bg[2]/(1+h.bg[2]),1};c->ClearRenderTargetView(h.output.rtv.Get(),world);edvr::uiDeferredApply(c,0);check(read(d,c,post.tex.Get())==originalGame,"native tail replay leaves original game canvas unchanged");
   h.baselineNative(h.over.Get());h.constants(0,0);h.setup(mappedExpected,h.outW,h.outH,h.postTone.Get(),nullptr,nullptr);c->VSSetShader(h.postVs.Get(),nullptr,0);c->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP);c->PSSetShaderResources(0,1,h.expected.srv.GetAddressOf());c->DrawInstanced(4,1,0,0);
   h.constants(0,0);h.setup(mappedExpected,h.outW,h.outH,h.postTone.Get(),h.tailBlend.Get(),nullptr);c->VSSetShader(h.tailVs.Get(),nullptr,0);c->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);c->IASetIndexBuffer(h.tailIb.Get(),DXGI_FORMAT_R32_UINT,0);c->PSSetShaderResources(0,1,tailOriginal.srv.GetAddressOf());c->DrawIndexedInstanced(6,1,0,0,0);
   auto routed=read(d,c,h.output.tex.Get()),anchored=read(d,c,mappedExpected.tex.Get());size_t routeDifferences=0;int routeMax=0;for(size_t i=0;i<routed.size();++i){const int delta=abs(int(routed[i])-int(anchored[i]));if(delta>1)++routeDifferences;routeMax=(std::max)(routeMax,delta);}if(routeDifferences){fprintf(stderr,"sampled/tail route scale=%u jitter=%g differences=%zu max=%d\n",scale,j,routeDifferences,routeMax);for(size_t p=0;p<routed.size()/4;++p)if(memcmp(routed.data()+p*4,anchored.data()+p*4,4))fprintf(stderr," p%zu (%u,%u,%u,%u)/(%u,%u,%u,%u)\n",p,routed[p*4],routed[p*4+1],routed[p*4+2],routed[p*4+3],anchored[p*4],anchored[p*4+1],anchored[p*4+2],anchored[p*4+3]);}check(!routeDifferences,"native sampled mapping and captured tail match anchored zero-jitter baseline after source/CB mutation");
   h.setup(mappedTransmission,h.outW,h.outH,h.postTone.Get(),nullptr,nullptr);c->VSSetShader(h.postVs.Get(),nullptr,0);c->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP);c->PSSetShaderResources(0,1,edvr::renderer.transmission.srv.GetAddressOf());c->DrawInstanced(4,1,0,0);
   const auto mappedMask=read(d,c,edvr::renderer.mappedTransmission.tex.Get()),rawMask=read(d,c,edvr::renderer.transmission.tex.Get());check(mappedMask!=rawMask && mappedMask==read(d,c,mappedTransmission.tex.Get()),"nonidentity sampled draw maps transmission coverage with the same UV and sampler as colour");
  }
  {
   h.start();h.uiDraw(0,0,h.over.Get(),true);h.toneDraw(true);auto post=surf(d,8,8,DXGI_FORMAT_R8G8B8A8_UNORM),tailSource=surf(d,8,8,DXGI_FORMAT_R8G8B8A8_UNORM);h.postToneDraw(post,h.ldr.srv.Get());
   for(size_t i=0;i<edvr::kTailDrawLimit;++i)check(h.tailDraw(post,tailSource.srv.Get(),0,0),"bounded terminal packet accepted");check(edvr::eyes[0].tails.size()==edvr::kTailDrawLimit,"terminal packet count reaches exact bound");check(!h.tailDraw(post,tailSource.srv.Get(),0,0) && edvr::failed,"terminal packet beyond bound declines to original game colour");
  }
  {
   h.start();h.uiDraw(j,-j,h.over.Get(),true);h.toneDraw(true);auto source=surf(d,8,8,DXGI_FORMAT_R8G8B8A8_UNORM);const auto before=edvr::diagnostic;
   h.postToneDraw(h.ldr,source.srv.Get());
   check(edvr::diagnostic.aliasRemovals==before.aliasRemovals+1 && !edvr::eyes[0].complete,"in-place post-tone write records first alias removal");
   h.start();h.uiDraw(j,-j,h.over.Get(),true);const auto late=edvr::diagnostic;
   h.candidateDraw(source,h.ldr.srv.Get(),0xA888D51024D9798Eull,0x015EF9349EC097E8ull);
   check(edvr::diagnostic.lateCompositeCandidates==late.lateCompositeCandidates+1,"late composite source/target diagnostic is wired");
  }
  for(auto*b:{h.over.Get(),h.add.Get()}){
   h.start();h.uiDraw(j,-j,b,false);h.toneDraw(false);auto fallback=read(d,c,h.ldr.tex.Get());
   h.start();h.uiDraw(j,-j,b,true);h.toneDraw(true);check(read(d,c,h.ldr.tex.Get())==fallback,"fallback retains original UI and stencil");check(edvr::eyes[0].complete,"tone recognized");
   auto alias=surf(d,8,8,DXGI_FORMAT_R8G8B8A8_UNORM);edvr::uiDeferredResourceWrite(c,alias.tex.Get());edvr::uiDeferredCopy(alias.tex.Get(),h.ldr.tex.Get(),true);c->CopyResource(alias.tex.Get(),h.ldr.tex.Get());
   auto*clean=edvr::uiDeferredPrepare(c,alias.tex.Get(),h.zSrv.Get(),h.output.tex.Get(),0,8,8,j,-j);check(clean!=nullptr,"copied submit route matched");ComPtr<ID3D11Resource> cr;clean->GetResource(&cr);ComPtr<ID3D11Texture2D> ct;hr(cr.As(&ct));auto input=read(d,c,ct.Get());if(input==fallback){fprintf(stderr,"identical input/fallback center %u %u hdr %u\n",input[4*(4*8+4)],fallback[4*(4*8+4)],read(d,c,h.hdr.tex.Get())[4*(4*8+4)]);}check(input!=fallback,"DLSS input contains no UI");
   // A stationary world reconstruction is the exact nonlinear tone of the
   // constant background. The UI itself must rasterize at output resolution.
   float world[4]={h.bg[0]/(1+h.bg[0]),h.bg[1]/(1+h.bg[1]),h.bg[2]/(1+h.bg[2]),1};c->ClearRenderTargetView(h.output.rtv.Get(),world);edvr::uiDeferredApply(c,0);auto actual=read(d,c,h.output.tex.Get());h.baselineNative(b);auto expected=read(d,c,h.expected.tex.Get());
   size_t different=0;for(size_t i=0;i<actual.size();++i)if(abs(int(actual[i])-int(expected[i]))>1)++different;if(different){fprintf(stderr,"scale=%u jitter=%g differences=%zu\n",scale,j,different);for(size_t i=0;i<actual.size();i+=4)if(actual[i]!=expected[i]){auto bt=read(d,c,edvr::renderer.base.tex.Get()),ut=read(d,c,edvr::renderer.ui.tex.Get()),trans=read(d,c,edvr::renderer.transmission.tex.Get());float tv;memcpy(&tv,trans.data()+i,4);fprintf(stderr,"(%zu,%zu) %u vs %u base%u ui%u t%g\n",i/4%(8*scale),i/4/(8*scale),actual[i],expected[i],bt[i],ut[i],tv);}}check(!different,"native UI matches original shader without jitter");
   edvr::uiDeferredResourceWrite(c,alias.tex.Get());check(!edvr::uiDeferredPrepare(c,alias.tex.Get(),h.zSrv.Get(),h.output.tex.Get(),0,8,8,j,-j),"modified submit is rejected");
  }
  h.start();h.uiDraw(0,0,h.over.Get(),true);h.constants(0,0);h.setup(h.hdr,8,8,h.ui.Get(),h.unsupported.Get(),h.dsv.Get());check(!edvr::uiDeferredBegin(c,0,'N',3,1,0,0,0),"unsupported UI flushes sequence");check(edvr::eyes[0].aborted&&edvr::eyes[0].restored,"decline retains prior UI");check(!edvr::enabled&&edvr::failed,"late failure latches off");check(edvr::uiDeferredFallbackReset(0)&&!edvr::uiDeferredFallbackReset(0)&&edvr::uiDeferredFallbackReset(1)&&!edvr::uiDeferredFallbackReset(1),"one reset per eye after fallback");check(!edvr::uiDeferredBegin(c,0,'N',3,1,0,0,0),"disabled controller leaves subsequent UI to existing path");
  h.start();h.uiDraw(0,0,h.over.Get(),true);h.constants(0,0);h.setup(h.hdr,8,8,h.ui.Get(),h.destAlpha.Get(),h.dsv.Get());check(!edvr::uiDeferredBegin(c,0,'N',3,1,0,0,0),"destination-alpha blend remains unsupported for UI");check(edvr::eyes[0].aborted&&edvr::failed,"destination-alpha UI declines the sequence");
  for(auto* blend:{static_cast<ID3D11BlendState*>(nullptr),h.add.Get(),h.over.Get(),h.destAlpha.Get()}){
   auto world=[&](bool mirror){h.constants(0,0,.25);h.setup(h.hdr,8,8,h.ui.Get(),blend,h.dsv.Get());edvr::uiDeferredBeforeDraw(c,'N',3,1,0,0,0,0);if(mirror)check(!edvr::uiDeferredBegin(c,-1,'N',3,1,0,0,0),"world is mirrored without UI classification");c->DrawInstanced(3,1,0,0);edvr::uiDeferredEnd(c);};
   h.start();world(false);h.toneDraw(false);auto cleanExpected=read(d,c,h.ldr.tex.Get());
   h.start();h.uiDraw(0,0,h.over.Get(),false);world(false);h.uiDraw(0,0,h.add.Get(),false);auto originalHdr=read(d,c,h.hdr.tex.Get());h.toneDraw(false);auto original=read(d,c,h.ldr.tex.Get());
   h.start();h.uiDraw(0,0,h.over.Get(),true);world(true);h.uiDraw(0,0,h.add.Get(),true);check(read(d,c,h.hdr.tex.Get())==originalHdr,"interleaved world/UI preserves original HDR bit for bit");h.toneDraw(true);check(read(d,c,h.ldr.tex.Get())==original,"interleaved world/UI preserves original LDR bit for bit");
   auto*clean=edvr::uiDeferredPrepare(c,h.ldr.tex.Get(),h.zSrv.Get(),h.output.tex.Get(),0,8,8,0,0);check(clean,"interleaved world path prepares");ComPtr<ID3D11Resource>r;clean->GetResource(&r);ComPtr<ID3D11Texture2D>t;hr(r.As(&t));check(read(d,c,t.Get())==cleanExpected,"clean image preserves interleaved world and removes both UI groups");
  }
  h.start();h.uiDraw(0,0,h.over.Get(),true);h.toneDraw(true);
  check(edvr::uiDeferredPrepare(c,h.ldr.tex.Get(),h.zSrv.Get(),h.output.tex.Get(),0,8,8,0,0),"prepare before later failure");
  edvr::decline(edvr::eyes[1],"injected later failure");
  float world[4]={.2f,1.f/3.f,3.f/7.f,1};c->ClearRenderTargetView(h.output.rtv.Get(),world);edvr::uiDeferredApply(c,0);h.baselineNative(h.over.Get());
  check(read(d,c,h.output.tex.Get())==read(d,c,h.expected.tex.Get()),"published command still applies after controller is disabled");
  h.start();h.uiDraw(0,0,h.over.Get(),true);
  D3D11_DEPTH_STENCIL_DESC stencil{};h.uiDepth->GetDesc(&stencil);stencil.StencilReadMask=4;ComPtr<ID3D11DepthStencilState> dependent;hr(d->CreateDepthStencilState(&stencil,&dependent));c->OMSetDepthStencilState(dependent.Get(),5);
  check(!edvr::uiDeferredBegin(c,-1,'N',3,1,0,0,0)&&edvr::failed,"world depending on changed UI stencil declines");
  h.start();h.uiDraw(0,0,h.over.Get(),true);auto other=surf(d,8,8,DXGI_FORMAT_R8G8B8A8_UNORM),other2=surf(d,8,8,DXGI_FORMAT_R8G8B8A8_UNORM);ID3D11RenderTargetView* mrt[2]={other.rtv.Get(),other2.rtv.Get()};c->OMSetRenderTargets(2,mrt,nullptr);
  check(!edvr::uiDeferredBegin(c,-1,'N',3,1,0,0,0)&&!edvr::failed,"unrelated MRT draws do not invalidate clean world");
 }
 printf("Deferred UI controller: %u checks passed (%s).\n",checks,hardware?"hardware":"WARP");
 return 0;
}
