#include "../../src/d3d11/ui_deferred_draw.h"
#include <d3dcompiler.h>
#include <wrl/client.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <algorithm>
#include <chrono>
#include <vector>
using Microsoft::WRL::ComPtr;
static void ck(HRESULT h,const char*s){if(FAILED(h)){std::fprintf(stderr,"%s 0x%08lx\n",s,(unsigned long)h);std::exit(1);}}
static void yes(bool v,const char*s){if(!v){std::fprintf(stderr,"FAIL %s\n",s);std::exit(1);}}
static ComPtr<ID3DBlob> compile(const char*x,const char*e,const char*p){ComPtr<ID3DBlob>b,z;ck(D3DCompile(x,std::strlen(x),"deferred",nullptr,nullptr,e,p,0,0,&b,&z),e);return b;}
static void waitGpu(ID3D11Device*d,ID3D11DeviceContext*c){D3D11_QUERY_DESC qd{D3D11_QUERY_EVENT,0};ComPtr<ID3D11Query>q;ck(d->CreateQuery(&qd,&q),"query");c->End(q.Get());c->Flush();HRESULT h=S_FALSE;for(int i=0;i<10000&&h==S_FALSE;++i)h=c->GetData(q.Get(),nullptr,0,0);ck(h,"wait");}
static unsigned center(ID3D11Device*d,ID3D11DeviceContext*c,ID3D11Texture2D*t){D3D11_TEXTURE2D_DESC x{};t->GetDesc(&x);x.Usage=D3D11_USAGE_STAGING;x.BindFlags=0;x.CPUAccessFlags=D3D11_CPU_ACCESS_READ;ComPtr<ID3D11Texture2D>r;ck(d->CreateTexture2D(&x,nullptr,&r),"staging");c->CopyResource(r.Get(),t);waitGpu(d,c);D3D11_MAPPED_SUBRESOURCE m{};ck(c->Map(r.Get(),0,D3D11_MAP_READ,0,&m),"map");auto*p=(const unsigned char*)m.pData+32*m.RowPitch+128;unsigned v=p[0];c->Unmap(r.Get(),0);return v;}
static std::vector<unsigned char> pixels(ID3D11Device*d,ID3D11DeviceContext*c,ID3D11Texture2D*t){D3D11_TEXTURE2D_DESC x{};t->GetDesc(&x);x.Usage=D3D11_USAGE_STAGING;x.BindFlags=0;x.CPUAccessFlags=D3D11_CPU_ACCESS_READ;ComPtr<ID3D11Texture2D>r;ck(d->CreateTexture2D(&x,nullptr,&r),"pixel staging");c->CopyResource(r.Get(),t);waitGpu(d,c);D3D11_MAPPED_SUBRESOURCE m{};ck(c->Map(r.Get(),0,D3D11_MAP_READ,0,&m),"pixel map");std::vector<unsigned char> out(size_t(x.Width)*x.Height*4);for(UINT y=0;y<x.Height;++y)std::memcpy(out.data()+size_t(y)*x.Width*4,static_cast<const unsigned char*>(m.pData)+size_t(y)*m.RowPitch,size_t(x.Width)*4);c->Unmap(r.Get(),0);return out;}
struct SavedPanelLayout{char semantic[64]{};uint32_t index=0,format=0,slot=0,offset=0,classification=0,step=0;};
static const GUID& panelLayoutKey(){static const GUID g={0x0db0ca71,0x6a19,0x4ca8,{0x9b,0x44,0x51,0x22,0x17,0x0e,0x4e,0x91}};return g;}
static void rememberPanelLayout(ID3D11InputLayout*l,UINT step=1){SavedPanelLayout a[4]{};const char*n[]={"INSTANCEANDMODELDATAINDEX","PACKEDVERTEXDATAA","PACKEDVERTEXDATAB","PACKEDVERTEXDATAC"};for(UINT i=0;i<4;++i)strcpy_s(a[i].semantic,n[i]);a[0].format=DXGI_FORMAT_R32G32_UINT;a[0].classification=D3D11_INPUT_PER_INSTANCE_DATA;a[0].step=step;a[1].format=a[2].format=DXGI_FORMAT_R32G32B32A32_UINT;a[3].format=DXGI_FORMAT_R32G32_UINT;for(UINT i=1;i<4;++i){a[i].slot=1;a[i].offset=(i-1)*16;}a[3].offset=32;ck(l->SetPrivateData(panelLayoutKey(),sizeof(a),a),"remember panel layout");}
static void rememberShader(ID3D11DeviceChild*s,ID3DBlob*b){ck(s->SetPrivateData(edvr::kDeferredBytes,UINT(b->GetBufferSize()),b->GetBufferPointer()),"remember shader");}
static ComPtr<ID3D11Buffer> exactBuffer(ID3D11Device*d,UINT bytes,D3D11_USAGE usage,UINT bind,UINT cpu){D3D11_BUFFER_DESC x{bytes,usage,bind,cpu,0,0};ComPtr<ID3D11Buffer>b;ck(d->CreateBuffer(&x,nullptr,&b),"exact panel buffer");return b;}
static void panelRangeTests(bool hardware){
    ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>c;ck(D3D11CreateDevice(nullptr,hardware?D3D_DRIVER_TYPE_HARDWARE:D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,nullptr,&c),"panel device");
    const char* vs="struct V{uint2 i:INSTANCEANDMODELDATAINDEX;uint4 a:PACKEDVERTEXDATAA;uint4 b:PACKEDVERTEXDATAB;uint4 c:PACKEDVERTEXDATAC;};struct O{float4 p:SV_POSITION;float4 c:COLOR;};O main(V v){O o;o.p=float4(asfloat(v.a.xy),0,1);o.c=float4(v.i.x/255.0,v.b.x/255.0,v.c.x/255.0,1);return o;}";
    const char* vsId="struct V{uint2 i:INSTANCEANDMODELDATAINDEX;uint4 a:PACKEDVERTEXDATAA;uint4 b:PACKEDVERTEXDATAB;uint4 c:PACKEDVERTEXDATAC;};struct O{float4 p:SV_POSITION;float4 c:COLOR;};O main(V v,uint id:SV_VertexID){O o;o.p=float4(asfloat(v.a.xy),0,1);o.c=float4(v.i.x/255.0,v.b.x/255.0,v.c.x/255.0,1)+id*0.000001;return o;}";
    const char* ps="struct I{float4 p:SV_POSITION;float4 c:COLOR;};float4 main(I i):SV_TARGET{return i.c;}";
    auto vc=compile(vs,"main","vs_5_0"),vi=compile(vsId,"main","vs_5_0"),pc=compile(ps,"main","ps_5_0");ComPtr<ID3D11VertexShader>vsh,idsh;ComPtr<ID3D11PixelShader>psh;ck(d->CreateVertexShader(vc->GetBufferPointer(),vc->GetBufferSize(),nullptr,&vsh),"panel VS");ck(d->CreateVertexShader(vi->GetBufferPointer(),vi->GetBufferSize(),nullptr,&idsh),"panel ID VS");ck(d->CreatePixelShader(pc->GetBufferPointer(),pc->GetBufferSize(),nullptr,&psh),"panel PS");rememberShader(vsh.Get(),vc.Get());rememberShader(idsh.Get(),vi.Get());rememberShader(psh.Get(),pc.Get());yes(edvr::uiDeferredPanelVertexInputs(vsh.Get()),"panel signature accepted");yes(!edvr::uiDeferredPanelVertexInputs(idsh.Get()),"SV_VertexID panel signature rejected");
    D3D11_INPUT_ELEMENT_DESC desc[]={{"INSTANCEANDMODELDATAINDEX",0,DXGI_FORMAT_R32G32_UINT,0,0,D3D11_INPUT_PER_INSTANCE_DATA,1},{"PACKEDVERTEXDATAA",0,DXGI_FORMAT_R32G32B32A32_UINT,1,0,D3D11_INPUT_PER_VERTEX_DATA,0},{"PACKEDVERTEXDATAB",0,DXGI_FORMAT_R32G32B32A32_UINT,1,16,D3D11_INPUT_PER_VERTEX_DATA,0},{"PACKEDVERTEXDATAC",0,DXGI_FORMAT_R32G32_UINT,1,32,D3D11_INPUT_PER_VERTEX_DATA,0}};ComPtr<ID3D11InputLayout>layout;ck(d->CreateInputLayout(desc,4,vc->GetBufferPointer(),vc->GetBufferSize(),&layout),"panel layout");rememberPanelLayout(layout.Get());
    auto vb0=exactBuffer(d.Get(),32768,D3D11_USAGE_DYNAMIC,D3D11_BIND_VERTEX_BUFFER,D3D11_CPU_ACCESS_WRITE),vb1=exactBuffer(d.Get(),130023424,D3D11_USAGE_DEFAULT,D3D11_BIND_VERTEX_BUFFER,0),ib=exactBuffer(d.Get(),33554432,D3D11_USAGE_DEFAULT,D3D11_BIND_INDEX_BUFFER,0);
    constexpr UINT first=7,base=4,start=10;D3D11_MAPPED_SUBRESOURCE mapped{};ck(c->Map(vb0.Get(),0,D3D11_MAP_WRITE_DISCARD,0,&mapped),"instance map");auto*instance=static_cast<UINT*>(mapped.pData)+first*2;instance[0]=255;instance[1]=0;c->Unmap(vb0.Get(),0);
    struct Vertex{UINT a[4],b[4],c[2];};Vertex vertices[3]{};const float xy[6]={-.8f,-.8f,.8f,-.8f,0,.8f};for(UINT i=0;i<3;++i){std::memcpy(&vertices[i].a[0],&xy[i*2],4);std::memcpy(&vertices[i].a[1],&xy[i*2+1],4);vertices[i].b[0]=64;vertices[i].c[0]=32;}D3D11_BOX box{base*40,0,0,base*40+sizeof(vertices),1,1};c->UpdateSubresource(vb1.Get(),0,&box,vertices,0,0);uint16_t indices[3]={0,1,2};box={start*2,0,0,start*2+sizeof(indices),1,1};c->UpdateSubresource(ib.Get(),0,&box,indices,0,0);
    ID3D11Buffer* buffers[]={vb0.Get(),vb1.Get()};UINT strides[]={8,40},offsets[]={0,0};c->IASetInputLayout(layout.Get());c->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);c->IASetVertexBuffers(0,2,buffers,strides,offsets);c->IASetIndexBuffer(ib.Get(),DXGI_FORMAT_R16_UINT,0);c->VSSetShader(vsh.Get(),nullptr,0);c->PSSetShader(psh.Get(),nullptr,0);
    D3D11_RASTERIZER_DESC rd{};rd.FillMode=D3D11_FILL_SOLID;rd.CullMode=D3D11_CULL_NONE;ComPtr<ID3D11RasterizerState>rs;ck(d->CreateRasterizerState(&rd,&rs),"panel raster");c->RSSetState(rs.Get());D3D11_VIEWPORT vp{0,0,64,64,0,1};c->RSSetViewports(1,&vp);
    D3D11_TEXTURE2D_DESC td{};td.Width=td.Height=64;td.MipLevels=td.ArraySize=1;td.Format=DXGI_FORMAT_R8G8B8A8_UNORM;td.SampleDesc.Count=1;td.BindFlags=D3D11_BIND_RENDER_TARGET;ComPtr<ID3D11Texture2D>target;ComPtr<ID3D11RenderTargetView>rtv;ck(d->CreateTexture2D(&td,nullptr,&target),"panel target");ck(d->CreateRenderTargetView(target.Get(),nullptr,&rtv),"panel RTV");c->OMSetRenderTargets(1,rtv.GetAddressOf(),nullptr);float clear[4]{};c->ClearRenderTargetView(rtv.Get(),clear);c->DrawIndexedInstanced(3,1,start,base,first);auto expected=pixels(d.Get(),c.Get(),target.Get());yes(std::any_of(expected.begin(),expected.end(),[](unsigned char x){return x!=0;}),"original panel fixture covers pixels");
    edvr::UiDeferredCaptureMask mask;mask.compactPanelIa=true;edvr::UiDeferredSnapshots pool;edvr::UiDeferredDraw old;yes(old.capture(c.Get(),pool,'X',3,1,start,base,first,mask),old.failureReason());
    ck(c->Map(vb0.Get(),0,D3D11_MAP_WRITE_DISCARD,0,&mapped),"mutated instance map");instance=static_cast<UINT*>(mapped.pData)+first*2;instance[0]=0;c->Unmap(vb0.Get(),0);pool.written(vb0.Get());Vertex moved[3]{};std::memcpy(moved,vertices,sizeof(moved));float away=3;for(auto&v:moved){std::memcpy(&v.a[0],&away,4);std::memcpy(&v.a[1],&away,4);}box={base*40,0,0,base*40+sizeof(moved),1,1};c->UpdateSubresource(vb1.Get(),0,&box,moved,0,0);pool.written(vb1.Get());
    auto replay=[&](edvr::UiDeferredDraw&draw){c->ClearRenderTargetView(rtv.Get(),clear);ComPtr<ID3D11DeviceContext>dc;ck(d->CreateDeferredContext(0,&dc),"panel deferred");yes(draw.bind(dc.Get(),psh.Get(),rtv.Get(),nullptr,nullptr,vp),"panel bind");draw.draw(dc.Get());ComPtr<ID3D11CommandList>cl;ck(dc->FinishCommandList(FALSE,&cl),"panel finish");c->ExecuteCommandList(cl.Get(),TRUE);return pixels(d.Get(),c.Get(),target.Get());};
    yes(replay(old)==expected,"compact replay preserves exact pixels after source mutation");edvr::UiDeferredDraw changed;yes(changed.capture(c.Get(),pool,'X',3,1,start,base,first,mask),changed.failureReason());yes(replay(changed)!=expected,"source version produces an independent compact snapshot");
    rememberPanelLayout(layout.Get(),2);edvr::UiDeferredDraw badLayout;yes(!badLayout.capture(c.Get(),pool,'X',3,1,start,base,first,mask),"changed panel layout rejected");rememberPanelLayout(layout.Get());
    edvr::UiDeferredSnapshots budget;std::vector<edvr::UiDeferredDraw> stereo(24);const auto t0=std::chrono::steady_clock::now();for(auto&i:stereo){budget.written(vb1.Get());yes(i.capture(c.Get(),budget,'X',3,1,start,base,first,mask),i.failureReason());}waitGpu(d.Get(),c.Get());const double coldMs=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-t0).count();yes(budget.allocatedBytes()<64ull*1024*1024,"stereo panel ranges stay below 64 MiB");const auto stableBytes=budget.allocatedBytes();stereo.clear();budget.frameBoundary();stereo.resize(24);const auto t1=std::chrono::steady_clock::now();for(auto&i:stereo){budget.written(vb1.Get());yes(i.capture(c.Get(),budget,'X',3,1,start,base,first,mask),i.failureReason());}waitGpu(d.Get(),c.Get());const double warmMs=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-t1).count();yes(budget.allocatedBytes()==stableBytes,"steady-state stereo panel ranges reuse allocations");std::printf("Compact panel IA 24 draws: copied %.2f MiB, allocated %.2f MiB, cold %.3f ms, warm %.3f ms (%s).\n",budget.copiedBytes()/1048576.,budget.allocatedBytes()/1048576.,coldMs,warmMs,hardware?"hardware":"WARP");
    stereo.clear();budget.frameBoundary();edvr::UiDeferredDraw six;yes(six.capture(c.Get(),budget,'X',6,1,start,base,first,mask),six.failureReason());const auto afterSix=budget.allocatedBytes();six=edvr::UiDeferredDraw{};budget.frameBoundary();edvr::UiDeferredDraw three;yes(three.capture(c.Get(),budget,'X',3,1,start,base,first,mask),three.failureReason());yes(budget.allocatedBytes()==afterSix,"count-varying range cache reuses prior-frame allocations");
    D3D11_BUFFER_DESC structured{};structured.ByteWidth=8388624;structured.Usage=D3D11_USAGE_DEFAULT;structured.BindFlags=D3D11_BIND_SHADER_RESOURCE|D3D11_BIND_UNORDERED_ACCESS;structured.MiscFlags=D3D11_RESOURCE_MISC_BUFFER_STRUCTURED;structured.StructureByteStride=48;ComPtr<ID3D11Buffer>t38;ck(d->CreateBuffer(&structured,nullptr,&t38),"panel t38");D3D11_SHADER_RESOURCE_VIEW_DESC sd{};sd.Format=DXGI_FORMAT_UNKNOWN;sd.ViewDimension=D3D11_SRV_DIMENSION_BUFFER;sd.Buffer.NumElements=174763;ComPtr<ID3D11ShaderResourceView>t38srv;ck(d->CreateShaderResourceView(t38.Get(),&sd,&t38srv),"panel t38 SRV");D3D11_UNORDERED_ACCESS_VIEW_DESC ud{};ud.Format=DXGI_FORMAT_UNKNOWN;ud.ViewDimension=D3D11_UAV_DIMENSION_BUFFER;ud.Buffer.NumElements=174763;ComPtr<ID3D11UnorderedAccessView>t38uav;ck(d->CreateUnorderedAccessView(t38.Get(),&ud,&t38uav),"panel t38 UAV");UINT zero[4]{},changedValue[4]={1,2,3,4};c->ClearUnorderedAccessViewUint(t38uav.Get(),zero);edvr::UiDeferredSnapshots tracked;ComPtr<ID3D11Resource>a,b,z;yes(tracked.capture(c.Get(),t38.Get(),a,true,false,true),"tracked t38 first snapshot");yes(tracked.capture(c.Get(),t38.Get(),b,true,false,true)&&a==b,"tracked t38 reuses unchanged version");c->ClearUnorderedAccessViewUint(t38uav.Get(),changedValue);tracked.written(t38.Get());yes(tracked.capture(c.Get(),t38.Get(),z,true,false,true)&&z!=a,"tracked t38 mutation creates a new version");D3D11_BUFFER_DESC clone{};static_cast<ID3D11Buffer*>(z.Get())->GetDesc(&clone);yes(clone.BindFlags==D3D11_BIND_SHADER_RESOURCE && clone.MiscFlags==D3D11_RESOURCE_MISC_BUFFER_STRUCTURED && clone.StructureByteStride==48,"tracked t38 clone is exact structured SRV-only storage");
}
int main(int argc,char**argv){const bool hardware=argc>1&&std::strcmp(argv[1],"--hardware")==0;ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>c;ck(D3D11CreateDevice(nullptr,hardware?D3D_DRIVER_TYPE_HARDWARE:D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,nullptr,&c),"device");const char*vs="cbuffer C:register(b0){float4 o;}struct V{float3 p:POSITION;};struct O{float4 p:SV_POSITION;};O main(V v){O z;z.p=float4(v.p+o.xyz,1);return z;}";const char*ps="float4 main():SV_TARGET{return float4(1,0,0,1);}";auto vbcode=compile(vs,"main","vs_5_0"),pbcode=compile(ps,"main","ps_5_0");ComPtr<ID3D11VertexShader>vsh;ComPtr<ID3D11PixelShader>psh;ck(d->CreateVertexShader(vbcode->GetBufferPointer(),vbcode->GetBufferSize(),nullptr,&vsh),"vs");ck(d->CreatePixelShader(pbcode->GetBufferPointer(),pbcode->GetBufferSize(),nullptr,&psh),"ps");D3D11_INPUT_ELEMENT_DESC ie{"POSITION",0,DXGI_FORMAT_R32G32B32_FLOAT,0,0,D3D11_INPUT_PER_VERTEX_DATA,0};ComPtr<ID3D11InputLayout>il;ck(d->CreateInputLayout(&ie,1,vbcode->GetBufferPointer(),vbcode->GetBufferSize(),&il),"layout");float ov[]={-.8f,-.8f,0,.8f,-.8f,0,0,.8f,0},nv[]={3,3,0,3,3,0,3,3,0};D3D11_BUFFER_DESC bd{sizeof(ov),D3D11_USAGE_DEFAULT,D3D11_BIND_VERTEX_BUFFER,0,0,0};D3D11_SUBRESOURCE_DATA sd{ov,0,0};ComPtr<ID3D11Buffer>vb;ck(d->CreateBuffer(&bd,&sd,&vb),"vb");uint16_t oi[]={0,1,2},ni[]={0,0,0};bd={sizeof(oi),D3D11_USAGE_DEFAULT,D3D11_BIND_INDEX_BUFFER,0,0,0};sd={oi,0,0};ComPtr<ID3D11Buffer>ib;ck(d->CreateBuffer(&bd,&sd,&ib),"ib");float oo[]={0,0,0,0};bd={sizeof(oo),D3D11_USAGE_DEFAULT,D3D11_BIND_CONSTANT_BUFFER,0,0,0};sd={oo,0,0};ComPtr<ID3D11Buffer>cb;ck(d->CreateBuffer(&bd,&sd,&cb),"cb");D3D11_RASTERIZER_DESC rd{};rd.FillMode=D3D11_FILL_SOLID;rd.CullMode=D3D11_CULL_NONE;ComPtr<ID3D11RasterizerState>rs;ck(d->CreateRasterizerState(&rd,&rs),"rs");D3D11_TEXTURE2D_DESC td{};td.Width=td.Height=64;td.MipLevels=td.ArraySize=1;td.Format=DXGI_FORMAT_R8G8B8A8_UNORM;td.SampleDesc.Count=1;td.BindFlags=D3D11_BIND_RENDER_TARGET;ComPtr<ID3D11Texture2D>target;ck(d->CreateTexture2D(&td,nullptr,&target),"target");ComPtr<ID3D11RenderTargetView>rtv;ck(d->CreateRenderTargetView(target.Get(),nullptr,&rtv),"rtv");ID3D11Buffer*b=vb.Get(),*cc=cb.Get();UINT stride=12,off=0;c->IASetInputLayout(il.Get());c->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);c->IASetVertexBuffers(0,1,&b,&stride,&off);c->IASetIndexBuffer(ib.Get(),DXGI_FORMAT_R16_UINT,0);c->VSSetShader(vsh.Get(),nullptr,0);c->PSSetShader(psh.Get(),nullptr,0);c->VSSetConstantBuffers(0,1,&cc);c->RSSetState(rs.Get());D3D11_VIEWPORT vp{0,0,64,64,0,1};c->RSSetViewports(1,&vp);D3D11_RECT sc{0,0,64,64};c->RSSetScissorRects(1,&sc);float clear[4]={0,0,0,0};edvr::UiDeferredSnapshots pool;edvr::UiDeferredCaptureMask mask;mask.cbVs=1;edvr::UiDeferredDraw first;yes(first.capture(c.Get(),pool,'I',3,1,0,0,0,mask),"capture first");    auto replay = [&](edvr::UiDeferredDraw& packet)->unsigned {
        c->ClearRenderTargetView(rtv.Get(),clear);
        ComPtr<ID3D11VertexShader> beforeVs, afterVs; ComPtr<ID3D11RenderTargetView> beforeRt, afterRt;
        c->VSGetShader(&beforeVs,nullptr,nullptr); c->OMGetRenderTargets(1,&beforeRt,nullptr);
        ComPtr<ID3D11DeviceContext> local; ck(d->CreateDeferredContext(0,&local),"deferred case"); yes(packet.bind(local.Get(),psh.Get(),rtv.Get(),nullptr,nullptr,vp),"bind case"); packet.draw(local.Get()); ComPtr<ID3D11CommandList> list; ck(local->FinishCommandList(FALSE,&list),"finish case"); c->ExecuteCommandList(list.Get(),TRUE); waitGpu(d.Get(),c.Get());
        c->VSGetShader(&afterVs,nullptr,nullptr); c->OMGetRenderTargets(1,&afterRt,nullptr); yes(beforeVs.Get()==afterVs.Get(),"ExecuteCommandList restored VS"); yes(beforeRt.Get()==afterRt.Get(),"ExecuteCommandList restored RTV"); return center(d.Get(),c.Get(),target.Get());
    };
    float offscreen[]={3,3,0,0}; c->UpdateSubresource(vb.Get(),0,nullptr,nv,0,0); pool.written(vb.Get()); edvr::UiDeferredDraw vbOnly; yes(vbOnly.capture(c.Get(),pool,'I',3,1,0,0,0,mask),"VB-only capture"); yes(replay(vbOnly)<20,"VB snapshot independent"); c->UpdateSubresource(vb.Get(),0,nullptr,ov,0,0); pool.written(vb.Get());
    c->UpdateSubresource(cb.Get(),0,nullptr,offscreen,0,0); pool.written(cb.Get()); edvr::UiDeferredDraw cbOnly; yes(cbOnly.capture(c.Get(),pool,'I',3,1,0,0,0,mask),"CB-only capture"); yes(replay(cbOnly)<20,"CB snapshot independent"); c->UpdateSubresource(cb.Get(),0,nullptr,oo,0,0); pool.written(cb.Get());
    c->UpdateSubresource(ib.Get(),0,nullptr,ni,0,0); pool.written(ib.Get()); edvr::UiDeferredDraw ibOnly; yes(ibOnly.capture(c.Get(),pool,'I',3,1,0,0,0,mask),"IB-only capture"); yes(replay(ibOnly)<20,"IB snapshot independent"); c->UpdateSubresource(ib.Get(),0,nullptr,oi,0,0); pool.written(ib.Get());c->UpdateSubresource(vb.Get(),0,nullptr,nv,0,0);c->UpdateSubresource(ib.Get(),0,nullptr,ni,0,0);float no[]={3,3,0,0};c->UpdateSubresource(cb.Get(),0,nullptr,no,0,0);pool.written(vb.Get());pool.written(ib.Get());pool.written(cb.Get());edvr::UiDeferredDraw second;yes(second.capture(c.Get(),pool,'I',3,1,0,0,0,mask),"capture second");c->ClearRenderTargetView(rtv.Get(),clear);ComPtr<ID3D11DeviceContext>dc;ck(d->CreateDeferredContext(0,&dc),"deferred");yes(first.bind(dc.Get(),psh.Get(),rtv.Get(),nullptr,nullptr,vp),"bind first");first.draw(dc.Get());ComPtr<ID3D11CommandList>cl;ck(dc->FinishCommandList(FALSE,&cl),"finish first");c->ExecuteCommandList(cl.Get(),TRUE);waitGpu(d.Get(),c.Get());yes(center(d.Get(),c.Get(),target.Get())>200,"old snapshot replay");c->ClearRenderTargetView(rtv.Get(),clear);dc.Reset();ck(d->CreateDeferredContext(0,&dc),"deferred2");yes(second.bind(dc.Get(),psh.Get(),rtv.Get(),nullptr,nullptr,vp),"bind second");second.draw(dc.Get());cl.Reset();ck(dc->FinishCommandList(FALSE,&cl),"finish second");c->ExecuteCommandList(cl.Get(),TRUE);waitGpu(d.Get(),c.Get());yes(center(d.Get(),c.Get(),target.Get())<20,"updated snapshot replay");panelRangeTests(hardware);std::puts(hardware?"ui deferred hardware snapshot/replay test passed":"ui deferred WARP snapshot/replay test passed");}
