#include "../../src/d3d11/ui_deferred_draw.h"
#include <d3dcompiler.h>
#include <wrl/client.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
using Microsoft::WRL::ComPtr;
static void ck(HRESULT h,const char*s){if(FAILED(h)){std::fprintf(stderr,"%s 0x%08lx\n",s,(unsigned long)h);std::exit(1);}}
static void yes(bool v,const char*s){if(!v){std::fprintf(stderr,"FAIL %s\n",s);std::exit(1);}}
static ComPtr<ID3DBlob> compile(const char*x,const char*e,const char*p){ComPtr<ID3DBlob>b,z;ck(D3DCompile(x,std::strlen(x),"deferred",nullptr,nullptr,e,p,0,0,&b,&z),e);return b;}
static void waitGpu(ID3D11Device*d,ID3D11DeviceContext*c){D3D11_QUERY_DESC qd{D3D11_QUERY_EVENT,0};ComPtr<ID3D11Query>q;ck(d->CreateQuery(&qd,&q),"query");c->End(q.Get());c->Flush();HRESULT h=S_FALSE;for(int i=0;i<10000&&h==S_FALSE;++i)h=c->GetData(q.Get(),nullptr,0,0);ck(h,"wait");}
static unsigned center(ID3D11Device*d,ID3D11DeviceContext*c,ID3D11Texture2D*t){D3D11_TEXTURE2D_DESC x{};t->GetDesc(&x);x.Usage=D3D11_USAGE_STAGING;x.BindFlags=0;x.CPUAccessFlags=D3D11_CPU_ACCESS_READ;ComPtr<ID3D11Texture2D>r;ck(d->CreateTexture2D(&x,nullptr,&r),"staging");c->CopyResource(r.Get(),t);waitGpu(d,c);D3D11_MAPPED_SUBRESOURCE m{};ck(c->Map(r.Get(),0,D3D11_MAP_READ,0,&m),"map");auto*p=(const unsigned char*)m.pData+32*m.RowPitch+128;unsigned v=p[0];c->Unmap(r.Get(),0);return v;}
int main(){ComPtr<ID3D11Device>d;ComPtr<ID3D11DeviceContext>c;ck(D3D11CreateDevice(nullptr,D3D_DRIVER_TYPE_WARP,nullptr,0,nullptr,0,D3D11_SDK_VERSION,&d,nullptr,&c),"device");const char*vs="cbuffer C:register(b0){float4 o;}struct V{float3 p:POSITION;};struct O{float4 p:SV_POSITION;};O main(V v){O z;z.p=float4(v.p+o.xyz,1);return z;}";const char*ps="float4 main():SV_TARGET{return float4(1,0,0,1);}";auto vbcode=compile(vs,"main","vs_5_0"),pbcode=compile(ps,"main","ps_5_0");ComPtr<ID3D11VertexShader>vsh;ComPtr<ID3D11PixelShader>psh;ck(d->CreateVertexShader(vbcode->GetBufferPointer(),vbcode->GetBufferSize(),nullptr,&vsh),"vs");ck(d->CreatePixelShader(pbcode->GetBufferPointer(),pbcode->GetBufferSize(),nullptr,&psh),"ps");D3D11_INPUT_ELEMENT_DESC ie{"POSITION",0,DXGI_FORMAT_R32G32B32_FLOAT,0,0,D3D11_INPUT_PER_VERTEX_DATA,0};ComPtr<ID3D11InputLayout>il;ck(d->CreateInputLayout(&ie,1,vbcode->GetBufferPointer(),vbcode->GetBufferSize(),&il),"layout");float ov[]={-.8f,-.8f,0,.8f,-.8f,0,0,.8f,0},nv[]={3,3,0,3,3,0,3,3,0};D3D11_BUFFER_DESC bd{sizeof(ov),D3D11_USAGE_DEFAULT,D3D11_BIND_VERTEX_BUFFER,0,0,0};D3D11_SUBRESOURCE_DATA sd{ov,0,0};ComPtr<ID3D11Buffer>vb;ck(d->CreateBuffer(&bd,&sd,&vb),"vb");uint16_t oi[]={0,1,2},ni[]={0,0,0};bd={sizeof(oi),D3D11_USAGE_DEFAULT,D3D11_BIND_INDEX_BUFFER,0,0,0};sd={oi,0,0};ComPtr<ID3D11Buffer>ib;ck(d->CreateBuffer(&bd,&sd,&ib),"ib");float oo[]={0,0,0,0};bd={sizeof(oo),D3D11_USAGE_DEFAULT,D3D11_BIND_CONSTANT_BUFFER,0,0,0};sd={oo,0,0};ComPtr<ID3D11Buffer>cb;ck(d->CreateBuffer(&bd,&sd,&cb),"cb");D3D11_RASTERIZER_DESC rd{};rd.FillMode=D3D11_FILL_SOLID;rd.CullMode=D3D11_CULL_NONE;ComPtr<ID3D11RasterizerState>rs;ck(d->CreateRasterizerState(&rd,&rs),"rs");D3D11_TEXTURE2D_DESC td{};td.Width=td.Height=64;td.MipLevels=td.ArraySize=1;td.Format=DXGI_FORMAT_R8G8B8A8_UNORM;td.SampleDesc.Count=1;td.BindFlags=D3D11_BIND_RENDER_TARGET;ComPtr<ID3D11Texture2D>target;ck(d->CreateTexture2D(&td,nullptr,&target),"target");ComPtr<ID3D11RenderTargetView>rtv;ck(d->CreateRenderTargetView(target.Get(),nullptr,&rtv),"rtv");ID3D11Buffer*b=vb.Get(),*cc=cb.Get();UINT stride=12,off=0;c->IASetInputLayout(il.Get());c->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);c->IASetVertexBuffers(0,1,&b,&stride,&off);c->IASetIndexBuffer(ib.Get(),DXGI_FORMAT_R16_UINT,0);c->VSSetShader(vsh.Get(),nullptr,0);c->PSSetShader(psh.Get(),nullptr,0);c->VSSetConstantBuffers(0,1,&cc);c->RSSetState(rs.Get());D3D11_VIEWPORT vp{0,0,64,64,0,1};c->RSSetViewports(1,&vp);D3D11_RECT sc{0,0,64,64};c->RSSetScissorRects(1,&sc);float clear[4]={0,0,0,0};edvr::UiDeferredSnapshots pool;edvr::UiDeferredCaptureMask mask;mask.cbVs=1;edvr::UiDeferredDraw first;yes(first.capture(c.Get(),pool,'I',3,1,0,0,0,mask),"capture first");    auto replay = [&](edvr::UiDeferredDraw& packet)->unsigned {
        c->ClearRenderTargetView(rtv.Get(),clear);
        ComPtr<ID3D11VertexShader> beforeVs, afterVs; ComPtr<ID3D11RenderTargetView> beforeRt, afterRt;
        c->VSGetShader(&beforeVs,nullptr,nullptr); c->OMGetRenderTargets(1,&beforeRt,nullptr);
        ComPtr<ID3D11DeviceContext> local; ck(d->CreateDeferredContext(0,&local),"deferred case"); yes(packet.bind(local.Get(),psh.Get(),rtv.Get(),nullptr,nullptr,vp),"bind case"); packet.draw(local.Get()); ComPtr<ID3D11CommandList> list; ck(local->FinishCommandList(FALSE,&list),"finish case"); c->ExecuteCommandList(list.Get(),TRUE); waitGpu(d.Get(),c.Get());
        c->VSGetShader(&afterVs,nullptr,nullptr); c->OMGetRenderTargets(1,&afterRt,nullptr); yes(beforeVs.Get()==afterVs.Get(),"ExecuteCommandList restored VS"); yes(beforeRt.Get()==afterRt.Get(),"ExecuteCommandList restored RTV"); return center(d.Get(),c.Get(),target.Get());
    };
    float offscreen[]={3,3,0,0}; c->UpdateSubresource(vb.Get(),0,nullptr,nv,0,0); pool.written(vb.Get()); edvr::UiDeferredDraw vbOnly; yes(vbOnly.capture(c.Get(),pool,'I',3,1,0,0,0,mask),"VB-only capture"); yes(replay(vbOnly)<20,"VB snapshot independent"); c->UpdateSubresource(vb.Get(),0,nullptr,ov,0,0); pool.written(vb.Get());
    c->UpdateSubresource(cb.Get(),0,nullptr,offscreen,0,0); pool.written(cb.Get()); edvr::UiDeferredDraw cbOnly; yes(cbOnly.capture(c.Get(),pool,'I',3,1,0,0,0,mask),"CB-only capture"); yes(replay(cbOnly)<20,"CB snapshot independent"); c->UpdateSubresource(cb.Get(),0,nullptr,oo,0,0); pool.written(cb.Get());
    c->UpdateSubresource(ib.Get(),0,nullptr,ni,0,0); pool.written(ib.Get()); edvr::UiDeferredDraw ibOnly; yes(ibOnly.capture(c.Get(),pool,'I',3,1,0,0,0,mask),"IB-only capture"); yes(replay(ibOnly)<20,"IB snapshot independent"); c->UpdateSubresource(ib.Get(),0,nullptr,oi,0,0); pool.written(ib.Get());c->UpdateSubresource(vb.Get(),0,nullptr,nv,0,0);c->UpdateSubresource(ib.Get(),0,nullptr,ni,0,0);float no[]={3,3,0,0};c->UpdateSubresource(cb.Get(),0,nullptr,no,0,0);pool.written(vb.Get());pool.written(ib.Get());pool.written(cb.Get());edvr::UiDeferredDraw second;yes(second.capture(c.Get(),pool,'I',3,1,0,0,0,mask),"capture second");c->ClearRenderTargetView(rtv.Get(),clear);ComPtr<ID3D11DeviceContext>dc;ck(d->CreateDeferredContext(0,&dc),"deferred");yes(first.bind(dc.Get(),psh.Get(),rtv.Get(),nullptr,nullptr,vp),"bind first");first.draw(dc.Get());ComPtr<ID3D11CommandList>cl;ck(dc->FinishCommandList(FALSE,&cl),"finish first");c->ExecuteCommandList(cl.Get(),TRUE);waitGpu(d.Get(),c.Get());yes(center(d.Get(),c.Get(),target.Get())>200,"old snapshot replay");c->ClearRenderTargetView(rtv.Get(),clear);dc.Reset();ck(d->CreateDeferredContext(0,&dc),"deferred2");yes(second.bind(dc.Get(),psh.Get(),rtv.Get(),nullptr,nullptr,vp),"bind second");second.draw(dc.Get());cl.Reset();ck(dc->FinishCommandList(FALSE,&cl),"finish second");c->ExecuteCommandList(cl.Get(),TRUE);waitGpu(d.Get(),c.Get());yes(center(d.Get(),c.Get(),target.Get())<20,"updated snapshot replay");std::puts("ui deferred WARP snapshot/replay test passed");}
