#!/usr/bin/env python3
"""Turn AMD's vendored FSR headers into HLSL string chunks the DLL can embed.

WHY CHUNKS. MSVC caps a single string literal at 65535 bytes and ffx_a.h is
184 KB, so the text cannot be one literal. Adjacent-literal concatenation does
not help -- the compiler joins them into one literal and the cap still bites.
An array of chunks joined at runtime is the shape that works.

WHY GENERATED RATHER THAN COMMITTED. The vendored headers stay byte-identical
to AMD's, so a newer FSR is a file swap and a rebuild with no local patch to
re-apply (src/d3d11/fsr/README.md). A hand-converted copy would be a second
thing to keep in step, and the first time they drifted nobody would know
which was authoritative.

Usage:  python tools/gen_fsr_hlsl.py --root ROOT --out DIR
Writes: DIR/fsr_hlsl_gen.h
"""

import argparse
import os
import sys

# Comfortably under the 65535-byte literal cap once escaping has had its say:
# a line of dense punctuation can nearly double in length.
CHUNK = 12000


def escape(text):
    out = []
    for ch in text:
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif ch == '\n':
            out.append('\\n')
        elif ch == '\r':
            continue
        elif ch == '\t':
            out.append('\\t')
        elif ch == '?':
            # Trigraphs are long dead, but "??/" in a literal still warns on
            # some settings and the escape costs nothing.
            out.append('\\?')
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            # The headers are ASCII; anything else would be a surprise worth
            # failing on rather than silently mangling.
            raise SystemExit('non-ASCII byte %r in the FSR sources' % ch)
    return ''.join(out)


def emit(name, text, fh):
    chunks = [text[i:i + CHUNK] for i in range(0, len(text), CHUNK)] or ['']
    fh.write('inline const char* const %s[] = {\n' % name)
    for c in chunks:
        fh.write('    "%s",\n' % escape(c))
    fh.write('    nullptr,\n};\n\n')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--root', required=True)
    ap.add_argument('--out', required=True)
    args = ap.parse_args()

    src = os.path.join(args.root, 'src', 'd3d11', 'fsr')
    pairs = [('kFfxAChunks', 'ffx_a.h'), ('kFfxFsr1Chunks', 'ffx_fsr1.h')]
    for _, f in pairs:
        if not os.path.exists(os.path.join(src, f)):
            sys.stderr.write('missing vendored FSR source: %s\n' % f)
            return 1

    os.makedirs(args.out, exist_ok=True)
    path = os.path.join(args.out, 'fsr_hlsl_gen.h')
    with open(path, 'w', encoding='ascii', newline='\n') as fh:
        fh.write('// GENERATED by tools/gen_fsr_hlsl.py -- do not edit.\n')
        fh.write('//\n')
        fh.write('// AMD FidelityFX Super Resolution 1.0, verbatim from\n')
        fh.write('// src/d3d11/fsr/. Copyright (c) 2021 Advanced Micro\n')
        fh.write('// Devices, Inc., MIT licensed; the notice travels with\n')
        fh.write('// the text below, which is the point of embedding it\n')
        fh.write('// whole rather than excerpting it.\n')
        fh.write('#pragma once\n\n')
        fh.write('namespace edvr {\n\n')
        for name, f in pairs:
            with open(os.path.join(src, f), encoding='ascii',
                      errors='strict') as s:
                emit(name, s.read(), fh)
        fh.write('}  // namespace edvr\n')
    print('[edvr] generated %s' % path)
    return 0


if __name__ == '__main__':
    sys.exit(main())
