#!/usr/bin/env python3
"""Turn AMD's vendored FSR headers into HLSL string chunks the DLL can embed.

WHY CHUNKS. MSVC caps a single string literal at 65535 bytes and ffx_a.h is
184 KB, so the text cannot be one literal. Adjacent-literal concatenation does
not help -- the compiler joins them into one literal and the cap still bites.
An array of chunks joined at runtime is the shape that works.

WHY GENERATED RATHER THAN COMMITTED. The vendored headers stay byte-identical
to AMD's, so a newer FSR is a file swap and a rebuild with no local patch to
re-apply (src/d3d11/fsr/README.md). A hand-converted copy would be a second
thing to keep in step, and the first time they drifted nobody would know
which was authoritative.

Usage:  python tools/gen_fsr_hlsl.py --root ROOT --out DIR [--dry-run]
        python tools/gen_fsr_hlsl.py --self-test
Writes: DIR/fsr_hlsl_gen.h

The header is built whole in memory first, so a source that cannot be embedded
fails before anything is written. --dry-run does that and reports the file it
would write, writing nothing (not the directory either). --self-test runs the
escaping, the chunking and a full run over fixtures in the temp folder;
build.bat runs it before it trusts the tool with the vendored sources.
"""

import argparse
import io
import os
import sys

# Comfortably under the 65535-byte literal cap once escaping has had its say:
# a line of dense punctuation can nearly double in length.
CHUNK = 12000

# (the array the DLL reads, the vendored header it is made from)
PAIRS = [('kFfxAChunks', 'ffx_a.h'), ('kFfxFsr1Chunks', 'ffx_fsr1.h')]


def escape(text):
    out = []
    for ch in text:
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif ch == '\n':
            out.append('\\n')
        elif ch == '\r':
            continue
        elif ch == '\t':
            out.append('\\t')
        elif ch == '?':
            # Trigraphs are long dead, but "??/" in a literal still warns on
            # some settings and the escape costs nothing.
            out.append('\\?')
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            # The headers are ASCII; anything else would be a surprise worth
            # failing on rather than silently mangling.
            raise SystemExit('non-ASCII byte %r in the FSR sources' % ch)
    return ''.join(out)


def emit(name, text, fh):
    chunks = [text[i:i + CHUNK] for i in range(0, len(text), CHUNK)] or ['']
    fh.write('inline const char* const %s[] = {\n' % name)
    for c in chunks:
        fh.write('    "%s",\n' % escape(c))
    fh.write('    nullptr,\n};\n\n')


def render(src):
    """The whole generated header, as text. Raises SystemExit on a source that
    cannot be embedded, before anything has been written."""
    fh = io.StringIO()
    fh.write('// GENERATED by tools/gen_fsr_hlsl.py -- do not edit.\n')
    fh.write('//\n')
    fh.write('// AMD FidelityFX Super Resolution 1.0, verbatim from\n')
    fh.write('// src/d3d11/fsr/. Copyright (c) 2021 Advanced Micro\n')
    fh.write('// Devices, Inc., MIT licensed; the notice travels with\n')
    fh.write('// the text below, which is the point of embedding it\n')
    fh.write('// whole rather than excerpting it.\n')
    fh.write('#pragma once\n\n')
    fh.write('namespace edvr {\n\n')
    for name, f in PAIRS:
        with open(os.path.join(src, f), encoding='ascii', errors='strict') as s:
            emit(name, s.read(), fh)
    fh.write('}  // namespace edvr\n')
    return fh.getvalue()


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument('--root')
    ap.add_argument('--out')
    ap.add_argument('--dry-run', action='store_true',
                    help='say what would be written and write nothing')
    ap.add_argument('--self-test', action='store_true',
                    help='check this script against fixtures and exit')
    args = ap.parse_args(argv)
    if args.self_test:
        return self_test()
    if not args.root or not args.out:
        ap.error('--root and --out are required')

    src = os.path.join(args.root, 'src', 'd3d11', 'fsr')
    for _, f in PAIRS:
        if not os.path.exists(os.path.join(src, f)):
            sys.stderr.write('missing vendored FSR source: %s\n' % f)
            return 1

    text = render(src)
    path = os.path.join(args.out, 'fsr_hlsl_gen.h')
    if args.dry_run:
        print('[edvr] dry run: would generate %s (%d bytes); wrote nothing'
              % (path, len(text)))
        return 0
    os.makedirs(args.out, exist_ok=True)
    with open(path, 'w', encoding='ascii', newline='\n') as fh:
        fh.write(text)
    print('[edvr] generated %s' % path)
    return 0


# ---------------------------------------------------------------------------
# --self-test
# ---------------------------------------------------------------------------

def self_test():
    """Escaping, chunking and a full run, against fixtures in the temp folder."""
    import contextlib
    import re
    import shutil
    import tempfile

    failures = []

    def expect(name, condition, what=''):
        if not condition:
            failures.append('%s: %s' % (name, what))

    def unescape(text):
        """The compiler's reading of a literal's body, for the escapes escape() writes."""
        table = {'\\': '\\', '"': '"', 'n': '\n', 't': '\t', '?': '?'}
        out, i = [], 0
        while i < len(text):
            if text[i] == '\\':
                out.append(table[text[i + 1]])
                i += 2
            else:
                out.append(text[i])
                i += 1
        return ''.join(out)

    def chunks_of(header, name):
        """The literal bodies of one generated array, in order."""
        m = re.search(r'inline const char\* const %s\[\] = \{\n(.*?)    nullptr,\n\};' % name,
                      header, re.S)
        if not m:
            return None
        return re.findall(r'^    "(.*)",$', m.group(1), re.M)

    # Every character that needs an escape, the one that is dropped, and a
    # plain one either side.
    name = 'escape'
    expect(name, escape('a\\b"c\nd\re\tf?g') == 'a\\\\b\\"c\\nde\\tf\\?g',
           repr(escape('a\\b"c\nd\re\tf?g')))
    expect(name, escape('') == '', 'empty text')
    for bad in ('caf\u00e9', '\x01', '\x7f'):
        try:
            escape(bad)
            failures.append('%s: %r was not refused' % (name, bad))
        except SystemExit as exc:
            expect(name, 'non-ASCII byte' in str(exc), str(exc))

    # Chunking: a chunk that escaping can double must still fit under MSVC's
    # 65535-byte literal cap; the arrays end in nullptr, an empty source is one
    # empty chunk, and a text several chunks long comes back whole when the
    # literals are joined -- including with an escaped character on every chunk
    # boundary, which is what escaping the chunk (not the text) has to survive.
    name = 'chunking'
    expect(name, 0 < CHUNK and 2 * CHUNK < 65535, 'CHUNK = %d can overrun the literal cap once escaped' % CHUNK)
    fh = io.StringIO()
    emit('kEmpty', '', fh)
    expect(name, chunks_of(fh.getvalue(), 'kEmpty') == [''], repr(fh.getvalue()))
    expect(name, fh.getvalue().endswith('    nullptr,\n};\n\n'), repr(fh.getvalue()))
    text = ''
    while len(text) < 3 * CHUNK + 17:
        text += 'x"\\?\ty\n'
    text = text[:CHUNK - 1] + '"' + text[CHUNK:2 * CHUNK - 1] + '\\' + text[2 * CHUNK:]
    fh = io.StringIO()
    emit('kLong', text, fh)
    got = chunks_of(fh.getvalue(), 'kLong')
    expect(name, got is not None and len(got) == 4, 'chunks: %r' % (got and len(got)))
    expect(name, got is not None and unescape(''.join(got)) == text.replace('\r', ''),
           'the chunks do not join back into the text')

    base = tempfile.mkdtemp(prefix='edvr-fsr-hlsl-')

    def lay(name, files):
        root = os.path.join(base, name)
        src = os.path.join(root, 'src', 'd3d11', 'fsr')
        os.makedirs(src)
        for leaf, data in files.items():
            with open(os.path.join(src, leaf), 'wb') as f:
                f.write(data)
        return root

    def run(*argv):
        """(exit code, stdout, stderr); a run that raises comes back as text."""
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            try:
                code = main(list(argv))
            except (SystemExit, UnicodeDecodeError) as exc:
                code = 'raised %s: %s' % (type(exc).__name__, exc)
        return code, out.getvalue(), err.getvalue()

    def tree(path):
        return sorted(os.path.join(d, n) for d, _, ns in os.walk(path) for n in ns)

    try:
        good = {'ffx_a.h': b'#define A 1\r\nfloat a(float x) { return x ? 1 : 0; }\r\n',
                'ffx_fsr1.h': b'// MIT\n#define B "b"\n'}
        # A full run: both arrays, the guard, the namespace, LF endings, ASCII.
        name = 'run'
        root = lay(name, good)
        out = os.path.join(base, name + '-gen')
        code, said, err = run('--root', root, '--out', out)
        header = os.path.join(out, 'fsr_hlsl_gen.h')
        expect(name, code == 0, 'exit %r: %s%s' % (code, said, err))
        expect(name, os.path.isfile(header), 'no header was written')
        if os.path.isfile(header):
            with open(header, 'rb') as f:
                raw = f.read()
            text = raw.decode('ascii')
            expect(name, b'\r' not in raw, 'CR in the header')
            expect(name, text.startswith('// GENERATED by tools/gen_fsr_hlsl.py -- do not edit.\n'), text[:60])
            expect(name, '#pragma once\n\nnamespace edvr {\n\n' in text and text.endswith('}  // namespace edvr\n'),
                   'guard or namespace')
            expect(name, chunks_of(text, 'kFfxAChunks') ==
                   ['#define A 1\\nfloat a(float x) { return x \\? 1 : 0; }\\n'], repr(chunks_of(text, 'kFfxAChunks')))
            expect(name, chunks_of(text, 'kFfxFsr1Chunks') == ['// MIT\\n#define B \\"b\\"\\n'],
                   repr(chunks_of(text, 'kFfxFsr1Chunks')))
            expect(name, text.index('kFfxAChunks') < text.index('kFfxFsr1Chunks'), 'array order')
            # The same inputs give the same bytes.
            code, _, _ = run('--root', root, '--out', out)
            with open(header, 'rb') as f:
                expect(name, code == 0 and f.read() == raw, 'a second run changed the header')

        # --dry-run writes nothing: not the file, not the directory.
        name = 'dry-run'
        fresh = os.path.join(base, name + '-gen')
        code, said, _ = run('--root', root, '--out', fresh, '--dry-run')
        expect(name, code == 0 and 'dry run: would generate' in said, 'exit %r: %s' % (code, said))
        expect(name, not os.path.exists(fresh), '--dry-run made %s' % fresh)
        existing = os.path.join(base, name + '-existing')
        os.makedirs(existing)
        run('--root', root, '--out', existing, '--dry-run')
        expect(name, tree(existing) == [], '--dry-run wrote %r' % tree(existing))

        # A missing vendored source fails, naming it, and writes nothing.
        name = 'missing-source'
        root = lay(name, {'ffx_a.h': b'x\n'})
        out = os.path.join(base, name + '-gen')
        code, said, err = run('--root', root, '--out', out)
        expect(name, code == 1 and 'missing vendored FSR source: ffx_fsr1.h' in err, 'exit %r: %s' % (code, err))
        expect(name, not os.path.exists(out), 'the out directory was made')

        # A source that cannot be embedded fails before the header is started,
        # so no half-written header can be mistaken for a good one: bytes that
        # are not ASCII, and an ASCII control character escape() has no form for.
        for name, data, why in (('non-ascii-source', b'caf\xc3\xa9\n', 'UnicodeDecodeError'),
                                ('control-char-source', b'a\x01b\n', 'non-ASCII byte')):
            root = lay(name, {'ffx_a.h': b'x\n', 'ffx_fsr1.h': data})
            out = os.path.join(base, name + '-gen')
            code, said, err = run('--root', root, '--out', out)
            expect(name, isinstance(code, str) and why in code, 'exit %r' % (code,))
            expect(name, not os.path.exists(out), 'a header or a directory was written: %r' % tree(out))

        # The arguments the build passes: both are required.
        name = 'arguments'
        code, _, err = run('--root', root)
        expect(name, code != 0 and 'required' in err, 'a missing --out was accepted: %r %r' % (code, err))
    finally:
        shutil.rmtree(base, ignore_errors=True)

    if failures:
        print('gen_fsr_hlsl: self-test FAILED')
        for f in failures:
            print('  ' + f.replace('\n', '\n    '))
        return 1
    print('gen_fsr_hlsl: self-test OK')
    return 0


if __name__ == '__main__':
    sys.exit(main())
