//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// TEXCOORD                 0   xy          1     NONE   float   xy  
// SIZE                     0   xy          2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// __USER_VERTEX_M_TEXCOORD     0   xy          0     NONE   float   xy  
// SV_POSITION              0   xyzw        1      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[12], immediateIndexed
dcl_constantbuffer CB1[274], immediateIndexed
dcl_input v0.xyz
dcl_input v1.xy
dcl_input v2.xy
dcl_output o0.xy
dcl_output_siv o1.xyzw, position
dcl_temps 3
mov o0.xy, v1.xyxx
mul [precise(xy)] r0.xy, v0.xyxx, v2.xyxx
mov [precise(z)] r0.z, v0.z
mov [precise(w)] r0.w, l(1.000000)
dp4 [precise(x)] r1.x, cb0[9].xyzw, r0.xyzw
mul [precise] r1.xyzw, r1.xxxx, cb1[270].xyzw
dp4 [precise(x)] r2.x, cb0[10].xyzw, r0.xyzw
dp4 [precise(x)] r0.x, cb0[11].xyzw, r0.xyzw
mul [precise] r0.xyzw, r0.xxxx, cb1[272].xyzw
mul [precise] r2.xyzw, r2.xxxx, cb1[271].xyzw
add [precise] r1.xyzw, r1.xyzw, r2.xyzw
add [precise] r0.xyzw, r0.xyzw, r1.xyzw
add [precise] o1.xyzw, r0.xyzw, cb1[273].xyzw
ret 
// Approximately 0 instruction slots used
