//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// TEXCOORD                 1   xyz         1     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyz         0   TARGET   float   xyz 
// SV_TARGET                1   x           1   TARGET   float   x   
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[47], immediateIndexed
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_input_ps linear v0.xy
dcl_input_ps linear v1.xyz
dcl_output o0.xyz
dcl_output o1.x
dcl_temps 7
mul r0.xy, v0.xyxx, cb2[1].xyxx
round_ni r0.xy, r0.xyxx
add r0.zw, cb2[1].xxxy, l(0.000000, 0.000000, -1.000000, -1.000000)
ftou r0.xyzw, r0.xyzw
umin r0.xy, r0.zwzz, r0.xyxx
mov r0.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r1.xyzw, r0.xyww, t1.xyzw
mad r1.w, r1.w, l(255.000000), l(0.500000)
ftou r1.w, r1.w
ld_indexable(texture2d)(float,float,float,float) r2.xyz, r0.xyww, t0.xyzw
mad r2.yz, r2.yyzy, l(0.000000, 4.000000, 4.000000, 0.000000), l(0.000000, -2.000000, -2.000000, 0.000000)
dp2 r2.w, r2.yzyy, r2.yzyy
mad r3.x, -r2.w, l(0.250000), l(1.000000)
max r3.x, r3.x, l(0.000000)
sqrt r3.x, r3.x
mul r3.xy, r2.yzyy, r3.xxxx
mad r3.z, r2.w, l(0.500000), l(-1.000000)
dp3 r2.y, r3.xyzx, r3.xyzx
rsq r2.y, r2.y
mul r2.yzw, r2.yyyy, r3.xxyz
mul r3.xyz, r2.zzzz, cb2[3].xyzx
mad r3.xyz, r2.yyyy, cb2[2].xyzx, r3.xyzx
mad r2.yzw, r2.wwww, cb2[4].xxyz, r3.xxyz
max r2.x, r2.x, l(0.050000)
min r2.x, r2.x, l(1.000000)
ld_indexable(texture2d)(float,float,float,float) r3.xyzw, r0.xyww, t2.yzxw
and r4.xyz, r1.wwww, l(128, 4, 32, 0)
if_nz r4.x
  mov r4.xw, l(1.000000,0,0,1.000000)
else 
  and r1.w, r1.w, l(64)
  if_nz r1.w
    mov r3.xy, r3.zzzz
  endif 
  add r1.w, -r3.w, l(1.000000)
  mad r4.xw, -r1.wwww, cb2[46].xxxy, l(1.000000, 0.000000, 0.000000, 1.000000)
endif 
dp3 r1.w, v1.xyzx, v1.xyzx
rsq r1.w, r1.w
mul r5.xyz, r1.wwww, v1.xyzx
movc r3.w, r4.y, l(0), l(1.000000)
ine r4.y, r4.z, l(0)
dp3 r4.z, -cb2[42].xyzx, r2.yzwy
lt r4.z, r4.z, l(0.000000)
and r4.y, r4.z, r4.y
if_nz r4.y
  mov r2.yzw, -r2.yyzw
endif 
mad r6.xyz, -v1.xyzx, r1.wwww, -cb2[42].xyzx
dp3 r1.w, r6.xyzx, r6.xyzx
rsq r1.w, r1.w
mul r6.xyz, r1.wwww, r6.xyzx
dp3_sat r1.w, r2.yzwy, -cb2[42].xyzx
dp3_sat r4.y, r2.yzwy, -r5.xyzx
dp3_sat r2.y, r2.yzwy, r6.xyzx
mul r2.z, r1.w, l(0.318310)
mul r1.xyz, r1.xyzx, r2.zzzz
mul r2.w, r2.x, r2.x
mul r4.z, r2.w, r2.w
mad r5.x, r2.y, r4.z, -r2.y
mad r2.y, r5.x, r2.y, l(1.000001)
min r2.y, r2.y, l(1.000000)
mul r2.y, r2.y, r2.y
mul r2.y, r2.y, l(3.141592)
div r2.y, r4.z, r2.y
dp3 r4.z, -cb2[42].xyzx, r6.xyzx
add r4.z, -|r4.z|, l(1.000000)
mul r5.x, r4.z, r4.z
mul r5.x, r5.x, r5.x
mul r4.z, r4.z, r5.x
add r5.xyz, -r3.zxyz, l(1.000000, 1.000000, 1.000000, 0.000000)
mad r3.xyz, r5.xyzx, r4.zzzz, r3.zxyz
mad r2.x, -r2.x, r2.x, l(2.000000)
mad r4.y, r4.y, r2.x, r2.w
mad r2.x, r1.w, r2.x, r2.w
mul r2.x, r2.x, r4.y
div r2.x, l(1.000000, 1.000000, 1.000000, 1.000000), r2.x
mul r2.x, r2.x, r2.y
mul r2.xyw, r2.xxxx, r3.xyxz
mul r2.xyw, r1.wwww, r2.xyxw
mul r2.xyw, r4.wwww, r2.xyxw
mad r1.xyz, r1.xyzx, r4.xxxx, r2.xywx
mul r1.xyz, r1.xyzx, cb2[40].xyzx
mul r2.xyz, r2.zzzz, cb2[40].xyzx
ld_indexable(texture2d)(float,float,float,float) r0.xyz, r0.xyzw, t3.xyzw
dp3 r0.x, r0.xyzx, cb2[44].xyzx
add r0.y, -r0.x, r3.w
mad r0.x, cb2[36].x, r0.y, r0.x
mul r0.x, r0.x, cb2[36].y
mul r0.yzw, r0.xxxx, r1.xxyz
mul r1.xyz, r0.xxxx, r2.xyzx
mul o0.xyz, r0.yzwy, cb2[0].xxxx
dp3 r0.x, r1.xyzx, l(0.308600, 0.609400, 0.082000, 0.000000)
mul o1.x, r0.x, cb2[0].x
ret 
// Approximately 0 instruction slots used
