//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 1   xyzw        0     NONE    uint   xyzw
// TEXCOORD                 2   xyzw        1     NONE    uint   xyzw
// TEXCOORD                 3   xyz         2     NONE   float   xyz 
// SV_POSITION              0   xyzw        3      POS   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyz         0   TARGET   float   xyz 
// SV_TARGET                1   x           1   TARGET   float   x   
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB2[47], immediateIndexed
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_input_ps constant v0.xyzw
dcl_input_ps constant v1.xyzw
dcl_input_ps linear v2.xyz
dcl_input_ps_siv linear noperspective v3.xy, position
dcl_output o0.xyz
dcl_output o1.x
dcl_temps 9
ftou r0.xy, v3.xyxx
mov r0.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r1.z, r0.xyww, t0.yzxw
div r1.w, r1.z, v2.z
mul r1.xy, r1.wwww, v2.xyxx
add r2.xyz, -r1.xyzx, v0.xyzx
dp3 r1.w, r2.xyzx, r2.xyzx
rsq r2.w, r1.w
mul r3.xyz, r2.wwww, r2.xyzx
mad r3.w, v0.w, r2.w, l(-1.000000)
lt r3.w, r3.w, l(0.000000)
discard_nz r3.w
and r3.w, v1.x, l(1023)
utof r3.w, r3.w
mul r4.x, r3.w, l(0.000978)
ubfe r5.xy, l(10, 10, 0, 0), l(10, 20, 0, 0), v1.xxxx
utof r5.xy, r5.xyxx
mul r4.yz, r5.xxyx, l(0.000000, 0.000978, 0.000978, 0.000000)
mul r3.w, v1.y, cb2[46].z
mul r4.xyz, r3.wwww, r4.xyzx
mul r3.w, v1.z, v1.z
ushr r4.w, v1.w, l(16)
f16tof32 r4.w, r4.w
mul r5.x, v0.w, v0.w
div r5.x, l(1.000000, 1.000000, 1.000000, 1.000000), r5.x
ld_indexable(texture2d)(float,float,float,float) r6.xyzw, r0.xyww, t2.xyzw
mad r5.y, r6.w, l(255.000000), l(0.500000)
ftou r5.y, r5.y
ld_indexable(texture2d)(float,float,float,float) r7.xyz, r0.xyww, t1.xyzw
mad r5.zw, r7.yyyz, l(0.000000, 0.000000, 4.000000, 4.000000), l(0.000000, 0.000000, -2.000000, -2.000000)
dp2 r6.w, r5.zwzz, r5.zwzz
mad r7.y, -r6.w, l(0.250000), l(1.000000)
max r7.y, r7.y, l(0.000000)
sqrt r7.y, r7.y
mul r8.xy, r5.zwzz, r7.yyyy
mad r8.z, r6.w, l(0.500000), l(-1.000000)
dp3 r5.z, r8.xyzx, r8.xyzx
rsq r5.z, r5.z
mul r7.yzw, r5.zzzz, r8.xxyz
max r5.z, r7.x, l(0.050000)
min r5.z, r5.z, l(1.000000)
ld_indexable(texture2d)(float,float,float,float) r0.xyzw, r0.xyzw, t3.yzxw
and r8.xy, r5.yyyy, l(128, 32, 0, 0)
if_nz r8.x
  mov r8.xz, l(1.000000,0,1.000000,0)
else 
  and r5.y, r5.y, l(64)
  if_nz r5.y
    mov r0.xy, r0.zzzz
  endif 
  add r0.w, -r0.w, l(1.000000)
  mad r8.xz, -r0.wwww, cb2[46].xxyx, l(1.000000, 0.000000, 1.000000, 0.000000)
endif 
dp3 r0.w, r1.xyzx, r1.xyzx
rsq r0.w, r0.w
mul r1.xyz, r0.wwww, r1.xyzx
ine r0.w, r8.y, l(0)
dp3 r5.y, r3.xyzx, r7.yzwy
lt r5.y, r5.y, l(0.000000)
and r0.w, r0.w, r5.y
if_nz r0.w
  mov r7.yzw, -r7.yyzw
endif 
mul r0.w, r4.w, r8.z
mad r2.xyz, r2.xyzx, r2.wwww, -r1.xyzx
dp3 r2.w, r2.xyzx, r2.xyzx
rsq r2.w, r2.w
mul r2.xyz, r2.wwww, r2.xyzx
dp3_sat r2.w, r7.yzwy, r3.xyzx
dp3_sat r1.x, r7.yzwy, -r1.xyzx
dp3_sat r1.y, r7.yzwy, r2.xyzx
mul r1.z, r2.w, l(0.318310)
mul r6.xyz, r1.zzzz, r6.xyzx
mul r4.w, r5.z, r5.z
mul r5.y, r4.w, r4.w
mad r5.w, r1.y, r5.y, -r1.y
mad r1.y, r5.w, r1.y, l(1.000001)
min r1.y, r1.y, l(1.000000)
mul r1.y, r1.y, r1.y
mul r1.y, r1.y, l(3.141592)
div r1.y, r5.y, r1.y
dp3 r2.x, r3.xyzx, r2.xyzx
add r2.x, -|r2.x|, l(1.000000)
mul r2.y, r2.x, r2.x
mul r2.y, r2.y, r2.y
mul r2.x, r2.x, r2.y
add r3.xyz, -r0.zxyz, l(1.000000, 1.000000, 1.000000, 0.000000)
mad r0.xyz, r3.xyzx, r2.xxxx, r0.zxyz
mad r2.x, -r5.z, r5.z, l(2.000000)
mad r1.x, r1.x, r2.x, r4.w
mad r2.x, r2.w, r2.x, r4.w
mul r1.x, r1.x, r2.x
div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), r1.x
mul r1.x, r1.x, r1.y
mul r0.xyz, r0.xyzx, r1.xxxx
mul r0.xyz, r2.wwww, r0.xyzx
max r1.x, r1.w, r3.w
div r1.y, l(1.000000, 1.000000, 1.000000, 1.000000), r1.x
mul r1.x, r5.x, r1.x
mad r1.x, -r1.x, r1.x, l(1.000000)
max r1.x, r1.x, l(0.000000)
mul r1.x, r1.x, r1.x
mul r1.x, r1.x, r1.y
mul r1.y, r1.x, r8.x
mul r0.w, r0.w, r1.x
mul r0.xyz, r0.wwww, r0.xyzx
mul r0.w, r1.x, r1.z
mad r0.xyz, r6.xyzx, r1.yyyy, r0.xyzx
mul r0.xyz, r4.xyzx, r0.xyzx
mul r1.xyz, r4.xyzx, r0.wwww
mul o0.xyz, r0.xyzx, cb2[0].xxxx
dp3 r0.x, r1.xyzx, l(0.308600, 0.609400, 0.082000, 0.000000)
mul o1.x, r0.x, cb2[0].x
ret 
// Approximately 0 instruction slots used
