// The FSS body composite's PIXEL shader, ph=A473A867BDDBC342, dumped
// 2026-08-25. The reveal dissolve in full: progress (cb1[119].z/y) vs
// per-cell luminance+noise thresholds, a stage index (cb1[119].w)
// selecting the blending layer pair, cell borders drawn for cells in
// transition, and a radial vignette. Everything derives from the
// quad's own UV -- nothing is per-eye EXCEPT the cb1 contents at each
// eye's draw. See docs/fss-scanner.md, the reveal-sync round.
//
//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB1[333], immediateIndexed
dcl_constantbuffer CB2[2], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_input_ps linear v0.xy
dcl_output o0.xyzw
dcl_temps 7
dcl_indexableTemp x0[3], 4
round_z r0.y, cb1[119].x
div_sat r0.z, cb1[119].z, cb1[119].y
mul r0.z, r0.z, l(0.999900)
frc r0.z, r0.z
mad r1.xyzw, v0.xyxy, l(1.000000, -1.000000, 1.000000, -1.000000), l(0.008000, 1.000000, 0.000000, 1.000000)
div r2.x, cb1[332].x, cb1[332].y
mov r2.yz, l(0,1.000000,2.000000,0)
mul r2.yw, r0.yyyy, r2.xxxy
mul r3.xy, r1.xyxx, r2.ywyy
round_ni r3.zw, r3.xxxy
div r3.zw, r3.zzzw, r2.yyyw
round_pi r4.xy, r3.xyxx
div r2.yw, r4.xxxy, r2.yyyw
add r2.yw, r2.yyyw, r3.zzzw
mul r2.yw, r2.yyyw, l(0.000000, 0.500000, 0.000000, 0.500000)
mul r0.x, r0.y, l(2.000000)
mul r0.xy, r0.xyxx, r2.xzxx
mul r1.xy, r0.xyxx, r1.xyxx
round_ni r2.xz, r1.xxyx
div r2.xz, r2.xxzx, r0.xxyx
round_pi r3.zw, r1.xxxy
div r0.xy, r3.zwzz, r0.xyxx
add r0.xy, r0.xyxx, r2.xzxx
mul r0.xy, r0.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
sample_indexable(texture2d)(float,float,float,float) r4.xyz, r2.ywyy, t1.xyzw, s2
mul r4.xyz, r4.xyzx, cb1[90].zzzz
dp3 r0.w, r4.xyzx, l(0.308600, 0.609400, 0.082000, 0.000000)
sample_indexable(texture2d)(float,float,float,float) r4.xyz, r0.xyxx, t2.xyzw, s2
mul r4.xyz, r4.xyzx, cb1[90].zzzz
dp3 r2.x, r4.xyzx, l(0.308600, 0.609400, 0.082000, 0.000000)
sample_indexable(texture2d)(float,float,float,float) r2.y, r2.ywyy, t4.yxzw, s0
sample_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t4.xyzw, s0
ge r0.y, l(0.001000), r2.x
movc r0.y, r0.y, l(0), l(1.000000)
lt r2.z, r0.w, l(0.500000)
mov_sat r2.w, r0.w
mad r3.z, r2.y, l(0.500000), r2.w
mad r2.y, -r2.y, l(0.500000), r2.w
movc r2.y, r2.z, r3.z, r2.y
lt r2.z, r2.x, l(0.500000)
mov_sat r2.x, r2.x
mad r2.w, r0.x, l(0.500000), r2.x
mad r0.x, -r0.x, l(0.500000), r2.x
movc r0.x, r2.z, r2.w, r0.x
mov x0[0].x, r2.y
mov x0[1].x, r0.x
mov x0[2].x, r0.x
mov r0.x, cb1[119].w
mov r0.x, x0[r0.x + 0].x
add r0.x, -r0.x, r0.z
add_sat r0.x, r0.x, l(1.000000)
sample_indexable(texture2d)(float,float,float,float) r2.xyz, r1.zwzz, t2.xyzw, s2
mul r2.xyz, r2.xyzx, cb1[90].zzzz
sample_indexable(texture2d)(float,float,float,float) r4.xyz, r1.zwzz, t3.xyzw, s1
mul r4.xyz, r4.xyzx, cb1[90].zzzz
ilt r0.z, cb1[119].w, l(1)
if_nz r0.z
  frc r3.xy, r3.xyxx
  ge r0.z, l(0.001000), r0.w
  movc r0.z, r0.z, l(0), l(1.000000)
  add r5.xyzw, r3.xyxy, l(0.100000, 0.100000, 0.050000, 0.050000)
  add r6.xyzw, r3.xyxy, l(-0.100000, -0.100000, -0.050000, -0.050000)
  round_ni r5.xyzw, r5.xyzw
  add r3.zw, r5.yyyw, r5.xxxz
  round_ni r5.xyzw, r6.xyzw
  add r5.xy, r5.ywyy, r5.xzxx
  add r0.w, r3.z, -r5.x
  min r0.w, r0.w, l(1.000000)
  add r0.w, -r3.w, r0.w
  add r0.w, r5.y, r0.w
  add r3.zw, -r3.xxxy, l(0.000000, 0.000000, 1.000000, 1.000000)
  mul r3.xy, r3.zwzz, r3.xyxx
  ge r3.xy, l(0.125000, 0.125000, 0.000000, 0.000000), r3.xyxx
  and r3.xy, r3.xyxx, l(0x3f800000, 0x3f800000, 0, 0)
  mul r2.w, r3.y, r3.x
  mul r0.w, r0.w, r2.w
  sample_indexable(texture2d)(float,float,float,float) r3.xyz, r1.zwzz, t1.xyzw, s2
  mul r3.xyz, r3.xyzx, cb1[90].zzzz
  lt r1.z, r0.x, l(0.990000)
  movc r0.y, r1.z, r0.z, r0.y
  movc r3.xyz, r1.zzzz, r3.xyzx, r2.xyzx
else 
  frc r1.xy, r1.xyxx
  add r5.xyzw, r1.xyxy, l(0.100000, 0.100000, 0.050000, 0.050000)
  add r6.xyzw, r1.xyxy, l(-0.100000, -0.100000, -0.050000, -0.050000)
  round_ni r5.xyzw, r5.xyzw
  add r1.zw, r5.yyyw, r5.xxxz
  round_ni r5.xyzw, r6.xyzw
  add r5.xy, r5.ywyy, r5.xzxx
  add r0.z, r1.z, -r5.x
  min r0.z, r0.z, l(1.000000)
  add r0.z, -r1.w, r0.z
  add r0.z, r5.y, r0.z
  add r1.zw, -r1.xxxy, l(0.000000, 0.000000, 1.000000, 1.000000)
  mul r1.xy, r1.zwzz, r1.xyxx
  ge r1.xy, l(0.125000, 0.125000, 0.000000, 0.000000), r1.xyxx
  and r1.xy, r1.xyxx, l(0x3f800000, 0x3f800000, 0, 0)
  mul r1.x, r1.y, r1.x
  mul r0.w, r0.z, r1.x
  lt r0.z, r0.x, l(0.990000)
  movc r3.xyz, r0.zzzz, r2.xyzx, r4.xyzx
endif 
ilt r0.z, l(1), cb1[119].w
movc r1.xyz, r0.zzzz, r4.xyzx, r3.xyzx
lt r0.z, l(0.890000), r0.x
lt r0.x, r0.x, l(0.990000)
and r0.x, r0.x, r0.z
and r0.x, r0.w, r0.x
mul r0.x, r0.y, r0.x
mul r0.x, r0.x, l(0.500000)
max r0.x, r0.x, l(0.000000)
add r0.yz, v0.xxyx, l(0.000000, -0.500000, -0.500000, 0.000000)
add r0.yz, r0.yyzy, r0.yyzy
dp2 r0.y, r0.yzyy, r0.yzyy
sqrt r0.y, r0.y
add r0.y, r0.y, l(-0.500000)
add_sat r0.y, r0.y, r0.y
add r0.y, -r0.y, l(1.000000)
add r0.xzw, r0.xxxx, r1.xxyz
mul r0.xyz, r0.yyyy, r0.xzwx
mul r0.xyz, r0.xyzx, cb2[0].xxxx
if_nz cb2[1].x
  ieq r0.w, cb2[1].y, l(2)
  if_nz r0.w
    ld_indexable(texture2d)(float,float,float,float) r0.w, l(1, 0, 0, 0), t0.yzwx
    mul r0.w, r0.w, l(0.125000)
  else 
    ieq r1.x, cb2[1].y, l(1)
    if_nz r1.x
      ld_indexable(texture2d)(float,float,float,float) r1.x, l(0, 0, 0, 0), t0.xyzw
      mul r0.w, r1.x, l(0.125000)
    else 
      if_z cb2[1].y
        mov r0.w, cb1[61].z
      else 
        mov r0.w, l(1.000000)
      endif 
    endif 
  endif 
  exp r1.x, cb2[0].w
  mul r0.w, r0.w, r1.x
endif 
if_z cb2[1].x
  mov r0.w, l(1.000000)
endif 
mul r0.xyz, r0.wwww, r0.xyzx
mul o0.xyz, r0.xyzx, cb1[90].yyyy
mov o0.w, l(1.000000)
ret 
// Approximately 0 instruction slots used
