// The config audit's tables, registered into Config at static init.
//
// Compiled into the two DLLs only -- test binaries that compile config.cpp
// without this file run without the audit (and register fixture tables of
// their own when the audit itself is under test). The header is generated by
// tools/check_config_contract.py from the code's own reads and edvr.ini's own
// moved-from annotations, so the runtime fallback, the installer's merge and
// the shipped documentation can never drift apart: one source of truth, three
// consumers, one build gate.
#include "config.h"

#include <cstddef>

#include "config_contract_gen.h"

namespace edvr {
namespace {

struct RegisterAuditTables {
    RegisterAuditTables() {
        Config::get().setAuditTables(
            contractgen::kKnownKeys,
            sizeof(contractgen::kKnownKeys) / sizeof(contractgen::kKnownKeys[0]),
            contractgen::kMovedKeys,
            sizeof(contractgen::kMovedKeys) / sizeof(contractgen::kMovedKeys[0]));
    }
};
RegisterAuditTables g_registerAuditTables;

}  // namespace
}  // namespace edvr
